### ISSUE TITLE
modelsummary(): adjust background or color of add_header_above() rows

### ISSUE THREAD

**Issue by ChrisWaloszek** [vincentarelbundock/modelsummary#102]
Adding additional rows on top of a table can nicely be done with `add_header_above()` to group columns. 
However, how to edit the font face (bold/italics) or font size of the values in these rows?

Also, it seems like the stars settings shown below the table `* p < 0.1, ** p < 0.05, *** p < 0.01` are not adapted to the current font size if is changed generally for the table with `kable_styling(font_size = 8)`.

    library(modelsummary)
    library(kableExtra)
    
    url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
    dat <- read.csv(url)
    
    models <- list()
    models[[1]] <- lm(Crime_prop ~ Literacy, data = dat)
    models[[2]] <- glm(Crime_prop ~ Literacy + Clergy, family = poisson, data = dat)
    models[[3]] <- lm(Crime_pers ~ Literacy, data = dat)
    models[[4]] <- glm(Crime_pers ~ Literacy + Clergy, family = poisson, data = dat)
    names(models) <- c('ols', 'poisson', 'ols', 'poisson')
    
    cm <- c( '(Intercept)' = 'Constant', 'Literacy' = 'Literacy (%)', 'Clergy' = 'Priests/capita')
    cap <- 'A modelsummary table customized with kableExtra'
    
    msummary(models, output = 'kableExtra',
             coef_map = cm, stars = TRUE,
             title = cap, gof_omit = 'IC|Log') %>%
      # column labels
      add_header_above(c(" " = 1, "Crimes (property)" = 2, "Crimes (person)" = 2)) %>% 
      add_header_above(c(" " = 1, "A" = 2, "B" = 2)) %>% 
      # text: make first row in italics (= model specifications)
      row_spec(row = 0, italic = T) %>% 
      row_spec(row = 0, background = "orange") 

![modelsummary](https://user-images.githubusercontent.com/6472717/86115113-c2f22d00-bacb-11ea-8c1e-0396e2d76f8e.png)

**Comment by vincentarelbundock** [comment]
Is this an issue with `modelsummary` specifically, or does it apply to *any* `kableExtra` table with `add_header_above`? For instance, could you achieve the behavior you want from a simple `kableExtra` table built from a very simple dataframe? 

My intuition is that this is a question for `kableExtra`, not for `modelsummary` specifically. If that's the case, then an issue should be opened over there.

**Comment by ChrisWaloszek** [comment]
I found out that it refers to *any* `kableExtra` table. Thus I just added a [post at SO](https://stackoverflow.com/questions/62659009/kableextra-adjust-font-face-and-background-of-add-header-above).

However, I am not sure if the font size of the stars settings shown below the table `* p < 0.1, ** p < 0.05, *** p < 0.01` 
 relate to `kableExtra` directly. How does `modelsummary()` handle its size and alignment settings?

On a similar note: any arguments one would usually directly pass to `kable()`, can they also be passed to `modelsummary()`? And if, how? 
E.g. regarding the recent question I had for naming models, I just found out that [one could actually pass column names directly to kable()](https://stackoverflow.com/questions/58062088/how-to-adjust-labels-in-table-created-with-r-kableextraadd-header-above).
Nevertheless, your solution by padding the model name with " " is much better I believe, as it would work with any output format (`gt`, `huxtable`and `kableExtra`).

**Comment by vincentarelbundock** [comment]
The stars note is treated just like all other notes, with `add_footnote`

https://github.com/vincentarelbundock/modelsummary/blob/master/R/factory_kableExtra.R#L34

At the moment, you cannot pass any argument to `kable`. However, that could be easy to arrange by simply passing through `...` (a 1-minute coding job).

So far, I've been reluctant to do this because it could introduced weird argument conflicts. For this reason, I don't like `...` much. However, I could be convinced otherwise if I see a compelling use-case.

What specifically did you have in mind for this?

**Comment by ChrisWaloszek** [comment]
For future reference, I found the solutions to adjusting font size, font face, and background of `add_header_above()` in `kableExtra`tables and summarized them as an [answer to my SO question](https://stackoverflow.com/questions/62659009/kableextra-adjust-font-face-and-background-of-add-header-above/62660605#62660605).

Regarding `kable()` commands: maybe ...

- `escape = FALSE` to be able to include latex commands in the table, e.g. $1^{st}$
- `longtable = TRUE` for long tables spanning multiple pages.

**Comment by ChrisWaloszek** [comment]
Gently off-topic, but maybe you have a hint for this as well.
`landscape(tab, margin = NULL)` allows printing a table in landscape format on a single page, which is very nice.
As some of my tables are quite large, squeezing them on a single page is rather difficult.
I played around with `statistic_vertical = T/F`, `kable_styling(font_size = XXX)` and `kable_styling(latex_options = c("scale_down"))`, e.g.

    statistic_vertical <- FALSE
    	# estimate & p-value in single line ==> wider table
     font_size_choice <- 6

    statistic_vertical <- TRUE
    	# estimate & p-value below another ==> longer table
     font_size_choice <- 8

However, the result is still not too satisfying. Hence, I tried to [alter the page margins, just for this single landscape page](https://stackoverflow.com/questions/62656467/bookdown-thesisdown-huskydown-change-page-margins-for-a-single-page-within-a-do?noredirect=1#comment110807339_62656467), to gain additional space for the table. Would you have any idea how to fix this or any alternative suggestions?

**Comment by ChrisWaloszek** [comment]
FYI: Changing Rmd chunk options, i.e. setting `out.height='80%', out.width='120%'`, does not make a difference.

**Comment by vincentarelbundock** [comment]
OK, I'm convinced, and I pushed a commit to Github which allows you to pass arbitrary arguments to `kable`.  Could you please try it?

That said, I vaguely remember some bug coming up due to ellipses like this. Unfortunately, I can't find documentation of it at the moment, but you should be aware that this functionality could be rolled-back in the future if I stumble upon the same problem.

More generally, I do believe that `modelsummary` should be as flexible as possible out of the box. That's one of the great strengths! But at the same time, LaTeX code is notoriously finicky and weird, so we can't expect to support *everything*. Moreover, it's trivial to use `modelsummary` to produce a data frame that allows you to create any table you want. Notice that `output='dataframe'`, most of the relevant info (e.g., notes and headers) are stored as attributes, so you can access them and pass them to whatever customized table-making package you want:

``` r
library(modelsummary)
models <- list()
models[[1]] <- lm(hp ~ mpg, mtcars)
models[[2]] <- lm(hp ~ mpg + drat, mtcars)
tab <- msummary(models, 'dataframe', stars = TRUE)
str(tab)
#> tibble [12 × 3] (S3: tbl_df/tbl/data.frame)
#>  $        : chr [1:12] "(Intercept)" "" "mpg" "" ...
#>  $ Model 1: chr [1:12] "324.082***" "(27.433)" "-8.830***" "(1.310)" ...
#>  $ Model 2: chr [1:12] "278.515***" "(55.415)" "-9.985***" "(1.792)" ...
#>  - attr(*, "align")= chr "lll"
#>  - attr(*, "hrule")= int 7
#>  - attr(*, "notes")= chr "* p < 0.1, ** p < 0.05, *** p < 0.01"
#>  - attr(*, "output_format")= chr "dataframe"
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vincentarelbundock** [comment]
I don't know how the `kableExtra::landscape` function works, sorry.

**Comment by ChrisWaloszek** [comment]
Passing arbitrary arguments to `kable`

## Use case 1: include [short captions for TOC](https://stackoverflow.com/questions/50164548/short-caption-in-knitrkable) 

    library(kableExtra)
    df <- data.frame( X = sample(letters, 10), y = runif(10), z = sample(10:20, 10))
    table_caption_title <- "Caption title (used as short caption in TOC)" # (bold)
    table_caption <- "The remainder of the caption appears in main text only." # (normal font)
    
      if (knitr::is_html_output()) {
        table_caption <- paste0("**", table_caption_title,":** ", table_caption) 
      } else if (knitr::is_latex_output()) {
        table_caption <- paste0("\\textbf{", table_caption_title,":} ", table_caption) 
      } else { # e.g. if (is_word_output()) 
        table_caption <- paste0(table_caption_title, ": " , table_caption)
      } 
    
    kable(df,
          booktabs = TRUE,
          caption = table_caption,
          caption.short = table_caption_title,
          escape = FALSE,
          format = 'latex') %>%
      kable_styling(latex_options = c("striped", "hold_position"))

![ShortCaption](https://user-images.githubusercontent.com/6472717/87019643-24ed1980-c1d3-11ea-8c81-dd48316c0940.png)

## Use case 2: include LaTex Code in coefficient names

    library(modelsummary)
    # some data
    df <- data.frame(
      num_protons <- sample(10:100, 10),
      num_neutrons <- sample(10:130, 10),
      alpha = runif(10,0.01,0.15),
      beta = runif(10,0.03,0.2),
      gamma = runif(10,0.1,0.5),
      half_life = sample(10:20000, 10)
    )
    lm_1 <- lm(half_life ~ alpha, df)     
    lm_2 <- lm(half_life ~ alpha + beta, df)     
    lm_3 <- lm(half_life ~ alpha + beta + gamma, df)     
    lm_4 <- lm(half_life ~ alpha + beta + gamma + num_protons, df)     
    lm_5 <- lm(half_life ~ alpha + beta + gamma + num_neutrons, df)     
    l_models <- list(lm_1, lm_2, lm_3, lm_4, lm_5)             
    
    ## coeffficients: create vector of all coeffficients
    # Values of this vector = the “clean” variable name
    # Names of this vector = the “raw” variable name
    # Regression table is sorted in the order of terms presented to coef_map
    cm <- c("$\\alpha$ radiation", "$\\beta$ radiation", "$\\gamma$ radiation", "$N_{+}$", "N_{n}$")
    names(cm) <- c("alpha", "beta", "gamma", "num_protons", "num_neutrons")
    cm <- unlist(cm)
    cm <- c(
      "(Intercept)" = "(Intercept)",
      cm
    )
    
    tab <- msummary(
      l_models,
      output = 'kableExtra',
      coef_map = cm, # use coefficients as defined above
      statistic = 'p.value',
      gof_omit = "AIC|BIC|Log",
      title = table_caption_title,
      # escape = FALSE, # needed to be able to include latex commands
    )
    tab %>%
      kable_styling( 
        latex_options = c(
          "striped",
          "hold_position", # stop table floating
          "scale_down"
        ) 
      )

![LaTex in Table](https://user-images.githubusercontent.com/6472717/87020038-9d53da80-c1d3-11ea-8d5f-a61cb83af52b.png)

**Comment by ChrisWaloszek** [comment]
> The stars note is treated just like all other notes, with `add_footnote`

Just saw that the author of `kableExtra` [now recommends](http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf) to use `footnote` instead of `add_footnote` (see also [here](http://haozhu233.github.io/kableExtra/legacy_features#add_footnote)). Maybe gives more flexibility?

**Comment by vincentarelbundock** [comment]
Thanks for the follow-up. I had closed the issue because `modelsummary` now passes `...` to `kable`, which means you can give it arbitrary arguments. The `caption` argument is already in use by `modelsummary` through `title`, so you would have to do:

```r
msummary(models, output = 'kableExtra', 
                   escape = FALSE, 
                   title = 'Test long caption', 
                   caption.short = 'Test short caption')
```

Does this solve your problem?

**Comment by vincentarelbundock** [comment]
@ChrisWaloszek I opened an issue for `add_footnote` https://github.com/vincentarelbundock/modelsummary/issues/106

Not sure what the benefit is yet, so this is low priority, but I'll probably implement eventually, especially if a compelling use-case comes up.

**Comment by ChrisWaloszek** [comment]
> Does this solve your problem?
Indeed it does :) Just wanted to provide use cases why it is good to be able to pass arbitrary arguments to `kable`.

**Comment by vincentarelbundock** [comment]
Yeah, that really *does* seem useful. Thanks again for the feature suggestion!
