### ISSUE TITLE
msummary(): Error when using   kable_styling(latex_options = c("scale_down"))

### ISSUE THREAD

**Issue by ChrisWaloszek** [vincentarelbundock/modelsummary#103]
If I generate the toy table below and include it in an Rmd file knitted to PDF/LaTex, I receive the following error.

    # ! Missing \endgroup inserted.
    # <inserted text> 
    #                 \endgroup 
    # l.186 \end{tabular}}

Interestingly, if I leave out any one of `coef_map = cm`, `stars = TRUE` or `title = cap`, then the error magically disappears.
(However, I would really like to keep these settings in plus actually a few more). :)

    library(modelsummary)
    library(kableExtra)
    
    url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
    dat <- read.csv(url)
    
    models <- list()
    models[[1]] <- lm(Crime_prop ~ Literacy, data = dat)
    models[[2]] <- glm(Crime_prop ~ Literacy + Clergy, family = poisson, data = dat)
    models[[3]] <- lm(Crime_pers ~ Literacy, data = dat)
    models[[4]] <- glm(Crime_pers ~ Literacy + Clergy, family = poisson, data = dat)
    names(models) <- c('ols', 'poisson', 'ols', 'poisson')
    
    cm <- c( '(Intercept)' = 'Constant', 'Literacy' = 'Literacy (%)', 'Clergy' = 'Priests/capita')
    cap <- 'A modelsummary table customized with kableExtra'

    msummary(models, output = 'kableExtra',
             coef_map = cm, stars = TRUE,
             title = cap
             ) %>%
      kable_styling(latex_options = c("striped", "scale_down"))

**Comment by vincentarelbundock** [comment]
Commit f5af8422b5 should fix this. Can you reinstall and try again?

(Note to self: This is probably related to buggy upstream treatment of `threepartable` in `kableExtra`, but I can't find a MWE at the moment. We just won't use threeparttable for now.)

**Comment by ChrisWaloszek** [comment]
Works well now, thank you very much for fixing!
W.r.t. `threepartable`: I recall kableExtra tables where it was indispensable to use/set `threeparttable = TRUE`. Else longer footnotes would run beyond the table and out of the page.
