### ISSUE TITLE
Get f-statistic or MS error in msummary()?

### ISSUE THREAD

**Issue by acircleda** [vincentarelbundock/modelsummary#105]
Is there any way to add the overall F-test statistic or MS error in the model summary table along with the other stats (r2, AIC, etc)?
I have been doing this as a separate table using `apaTables::apa.aov.table()` but it would be nice to have these summary statistics all in one comparison table.

**Comment by vincentarelbundock** [comment]
Sure! 3 options:

### Option 1: Easiest but may not be possible for all model types.

`modelsummary` automatically extracts all fit statistics produced by the `glance` function of the `broom` package. I don't know what kind of model you are summarizing, so I can't tell you what statistics are available, but you can try this to see the list of available statistics:

```r
library(broom)
glance(model)
```

If the statistic you want is *not* available through `broom::glance`, you have two more options.

### Option 2: Guaranteed success, but some manual editing

Calculate your statistic manually and add a row to your table using the `add_rows` argument. See here for an example: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#add-rows

### Option 3: An automatic and reliable solution which requires you to define a simple function

`modelsummary` offers the `glance_extra` mechanism to add additional information to models. All you need to do is define a new function with a specific name: `glance_modeltype`, where "modeltype" needs to be the class of your model. See here for a complete tutorial: https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html

**Comment by vincentarelbundock** [comment]
To elaborate on Option 1. Let's say you want to extract the F stat from a `lm` model. First, you load the `modelsummary` and `broom` libraries, then you fit your model and use the `glance` function:

```r
library(modelsummary)
library(broom)

mod <- lm(hp ~ mpg, mtcars)
glance(mod)

> glance(mod)
# A tibble: 1 x 12
r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC deviance df.residual  nobs
<dbl>         <dbl> <dbl>     <dbl>       <dbl> <dbl>  <dbl> <dbl> <dbl>    <dbl>       <int> <int>
    1     0.602         0.589  43.9      45.5 0.000000179     1  -165.  337.  341.   57936.          30    32
```

This shows that `glance` allows you to include a value called `statistic`. For a linear model, this turns out to be your `F` stat. 

As you noted, this F stat is omitted by default in `modelsummary`. You can change that by supplying your own `gof_map`, as described here: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#goodness-of-fit-and-other-statistics-1

`gof_map` is a data.frame which includes information about which statistics to omit, and how to rename them. We can extract the default `gof_map` from `modelsummary` and modify it to include the `statistic` and rename it `F`:

```r
gm <- modelsummary::gof_map
gm$omit[gm$raw == 'statistic'] <- FALSE 
gm$clean[gm$raw == 'statistic'] <- 'F'

msummary(mod, gof_map = gm)
```

```
|            |Model 1  |
|:-----------|:--------|
|(Intercept) |324.082  |
|            |(27.433) |
|mpg         |-8.830   |
|            |(1.310)  |
|Num.Obs.    |32       |
|R2          |0.602    |
|R2 Adj.     |0.589    |
|AIC         |336.9    |
|BIC         |341.3    |
|Log.Lik.    |-165.428 |
|F           |45.460   |
```

**Comment by acircleda** [comment]
Thanks! Option one works with *F*. I will need to play around later to get the other statistic because it is not in `glance`.

**Comment by vincentarelbundock** [comment]
Cool. If your familiar enough with R and functions, I'd seriously consider Option 3 for your other stats. The benefit is that you define a simple function once, and then it works for all your models, without the need for manual editing.

Let me know if you run into issues. Happy to help if I can.

**Comment by vincentarelbundock** [comment]
In the next version of `modelsummary` (on CRAN in the next couple weeks), *F* will be displayed by default for `lm` models.
