### ISSUE TITLE
datasummary: position of histogram bars and enhancement with skewness, kurtosis, ...

### ISSUE THREAD

**Issue by ChrisWaloszek** [vincentarelbundock/modelsummary#107]
I very much enjoy the functionality of `datasummary` to get a quick glimpse of the data.  The function's grammar is very nice and easy to use, especially when one wants to get an overview of the data for different levels of a factor, e.g.

     datasummary(All(iris) ~ Species*(Mean + SD) + Median + Histogram, data = iris) 

However, the bars of my histograms are sometimes slightly shifted upwards/downwards in Rstudio's preview function, and with LaTex/PDF output I get `?`s for both of the following tries (see screenshots below):

    datasummary(All(iris) ~ Mean + SD + Median + Histogram, data = iris, output = 'latex')
    datasummary(All(iris) ~ Mean + SD + Median + Histogram, data = iris, output = 'kableExtra')

Any idea what could have gone wrong from my side?
![Screen Shot 2020-07-15 at 15 46 28](https://user-images.githubusercontent.com/6472717/87554514-8110db80-c6b4-11ea-84a4-e6bd0afc6db8.png)
![Screen Shot 2020-07-15 at 16 07 25](https://user-images.githubusercontent.com/6472717/87555403-ae11be00-c6b5-11ea-9ded-33ebfc754c79.png)

Furthermore, would it be possible to enhance the functionality of `datasummary` with further statistics as those available to `RcmdrMisc::numSummary()` or `psych::describe()`?

    library(RcmdrMisc)
    numSummary(iris[1:4],
               # groups = iris$Species, 
               statistics = c("mean", "sd", "se(mean)", 
                              "skewness", "kurtosis", 
                              "IQR", "cv", # coefficient of variation = SD/mean
                              "quantiles"
               ), 
               type=c("2"), 
               quantiles = c(.1,.9))

**Comment by vincentarelbundock** [comment]
The reason why bars are misaligned in RStudio and missing in LaTeX is because the bars are actually Unicode characters, but not every typeface includes support for these characters, and some of them includes *bad* support for them. My advice is to try to play around with different fonts like `DejaVu` fonts which are free and have good support for unicode characters.

FWIW, on the `modelsummary` website, I include this CSS to display histograms properly:

```html
body {
  font-family: 'DejaVu Sans', 'Roboto', 'Georgia', 'Times', 'Roboto', 'DejaVu Serif', serif;
}

caption {
  font-family: 'DejaVu Sans', 'Roboto', 'Georgia', 'Times', 'Roboto', 'DejaVu Serif', serif;
  color: black;
}
```

On your second point, I explain [at this link](https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#datasummary-1), `datasummary` accepts **arbitrary** functions. So you can already define your own or use statistics from any package. For example,

```r
library(modelsummary)

skewness <- function(x) {
    u <- mean(x)
    s <- sd(x)
    mean(((x - u)/s)^3)
}

datasummary(All(iris) ~ Species * (Mean + SD + skewness), data = iris) 
```

**Comment by ChrisWaloszek** [comment]
Thanks a lot for the quick response and info! Will try to find out how to adjust the font within the Rmd file "locally" just for the specific table such that output works for LaTex /PDF.

**Comment by simonheb** [comment]
> Thanks a lot for the quick response and info! Will try to find out how to adjust the font within the Rmd file "locally" just for the specific table such that output works for LaTex /PDF.

Did you find a solution to this?

**Comment by vincentarelbundock** [comment]
For the reasons stated above, it is very difficult to have consistent appropriate display with this feature. I recommend to *not* use it. Instead, I recommend that you should select `output="kableExtra"` or `output="gt"` and use the functionalities of those two packages to add histograms or inline graphs manually.

There are examples on the `modelsummary` website.
