### ISSUE TITLE
Use of conditionals in msummary()

### ISSUE THREAD

**Issue by ChrisWaloszek** [vincentarelbundock/modelsummary#108]
I use a routine to generate a large number of regression tables with differing regressors and regressands. 
Some include controls, others not. If controls are included in the regression it would be nice to add a row with the info "Controls yes	yes	yes ...", as in the abbreviated example below

      CONTROLS <- TRUE # TRUE / FALSE

      l_row_items <- list("term" = "Controls")
      l_row_items[names(l_models)] <- c(rep("yes", length(names(l_models))))
      row_controls <- as.data.frame(l_row_items)
      
      msummary(models, 
               # add_rows = row_controls # works well
               if (CONTROLS == TRUE) add_rows = row_controls # throws error below
      )

    Error in sanity_output(output) : 
      Assertion on 'output' failed: Must be of type 'string', not 'tbl_df/tbl/data.frame'. 

Would it be possible to allow for conditionals within the function call of `msummary()`? Or is there an alternative way to implement the above conditionally on table output settings? Many thanks in advance for your consideration.

**Comment by vincentarelbundock** [comment]
Could you give me a bit more detail about your use-case? Wouldn't this be easy to accomodate with just a `for` loop like this?

```
library(modelsummary)
library(tidyverse)

mod1 <- list(lm(mpg ~ hp + drat, mtcars),
             lm(mpg ~ hp + wt, mtcars))
mod2 <- list(lm(mpg ~ hp, mtcars),
             lm(hp ~ wt, mtcars))

is_control <- function(x) any(sapply(x, function(k) length(coef(k)) > 2))

for (m in list(mod1, mod2)) {
    if (is_control(m)) {
        rows <- cbind('Controls', data.frame(matrix('Yes', ncol = length(m))))
    } else {
        rows <- NULL
    }
    print(msummary(m, add_rows = rows))
}

```

**Comment by vincentarelbundock** [comment]
Or something that looks a lot like your code:

```
m <- list(lm(mpg ~ hp + drat, mtcars),
          lm(mpg ~ hp + wt, mtcars))
is_control <- function(x) {
    rows <- cbind('Controls', data.frame(matrix('Yes', ncol = length(m))))
    if(any(sapply(x, function(k) length(coef(k)) > 2))) {
        return(rows)
    } else {
        return(NULL)
    }
}
msummary(m, add_rows = is_control(m))
```

**Comment by ChrisWaloszek** [comment]
The function approach as in your second example works like charm! Many, many thanks for this!

**Comment by ChrisWaloszek** [comment]
Just FYI, this is how the final version I used looks like:

    ## conditionally add "note on controls" to table
    ## -------------------------------------------------
    ## add additional row with info "Controls	yes	yes	yes ..."
    ## iff controls are included in the regresion, but are not included in the regression table
    is_control <- function(x) {
      rows <- cbind('Controls', data.frame(matrix('Yes', ncol = length(l_lm_RETs))))
    
      multiply_factor <- 1
      if (statistic_vertical) multiply_factor <- 2
      rows_int <- 1 * multiply_factor # for intercept
      
      if (statistic_vertical){
        row_CONT <- (10*multiply_factor)-1  + rows_int
      } else {
        row_CONT <- 10 + rows_int
      }
      
      attr(rows, 'position') <- c(row_CONT)
      
      if(CONTROLS == TRUE & CONTROLSinTABLE == FALSE) {
        return(rows)
      } else {
        return(NULL)
      }
    }

    tab <- msummary(
      l_models, 
      output = 'kableExtra',
      statistic = 'p.value', 
      statistic_vertical = statistic_vertical,
      coef_map = cm, 
      # Conditionally add "note on controls" to table if (CONTROLS == TRUE & CONTROLSinTABLE == FALSE)
      add_rows = is_control(l_lm_RETs),
      stars = c('*' = .05, '**' = .01, '***' = .001),
      gof_omit = "BIC|Log", #'BIC|Log', # DF|Deviance|R2|AIC|BIC|Adj
      title = table_caption, # complete caption for main document
      caption.short = table_caption_title # short caption for LoT
    )
    # customize the table with `kableExtra`
    tab <- tab %>%
      kable_styling( 
        latex_options = c(
          "striped",
          "hold_position", # stop table floating
          "scale_down"
        ) 
      ) %>% 
      footnote(
        general = table_footnote,
        footnote_as_chunk = TRUE, title_format = c("italic", "underline"),
        fixed_small_size = TRUE
      )
    
    # plus lots of grouping of coefficients conditional on regression settings with pack_rows()
    tab <- fun_regr_tab_coeff_grouping(regressiontab = tab)
    tab

Once again, many thanks for providing the R community with your fabulous package! It is very, very useful and helpful!

**Comment by vincentarelbundock** [comment]
cool
