### ISSUE TITLE
modelsummary with fixest

### ISSUE THREAD

**Issue by skhiggins** [vincentarelbundock/modelsummary#109]
The [documentation](https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html) describes how to use `fixest` with `modelsummary` by including the following code in any script using both packages: 

```r
glance_custom.fixest <- function(x) {
    out <- tibble::tibble(.rows = 1)
    for (n in x$fixef_vars) {
        out[[paste('FE: ', n)]] <- 'X'
    }
    return(out)
}
```

Can `modelsummary` incorporate this `glance_custom.fixest` function in the package so that it isn't necessary to define this manually?

**Comment by vincentarelbundock** [comment]
Thanks for this suggestion. I think it makes sense to include this by default.

There are a few detail I need to figure out w.r.t. exports and the ability to override manually, but this shouldn't be a major problem. Will let you know when my laptop is back from repair and I have a minute to look at this.

Thanks!

**Comment by vincentarelbundock** [comment]
Thanks again for the suggestion @skhiggins 

It's on Github now and will be on CRAN in the next few days.
