### ISSUE TITLE
Add first-stage of IV models

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/modelsummary#122]
Hi Vincent,

One feature I've been missing from R table-exporting packages is a way to include the first-stage estimates for IV regression models. At least, for methods that support it.

An example would be `lfe::felm()`, which returns a `mod$stage1` object when applicable. Consider the following toy example.

```r
m = lfe::felm(wt ~ drat | 0 | (disp ~ hp), data = mtcars)

## Second stage
broom::tidy(m)
#> # A tibble: 3 x 5
#>   term        estimate std.error statistic   p.value
#>   <chr>          <dbl>     <dbl>     <dbl>     <dbl>
#> 1 (Intercept)  3.24      1.16         2.80 0.00904  
#> 2 drat        -0.371     0.254       -1.46 0.156    
#> 3 `disp(fit)`  0.00567   0.00124      4.58 0.0000824

# First stage
tidy(m$stage1)
#> # A tibble: 3 x 5
#>   term        estimate std.error statistic    p.value
#>   <chr>          <dbl>     <dbl>     <dbl>      <dbl>
#> 1 (Intercept)   445.      95.5        4.66 0.0000654 
#> 2 drat         -103.      22.4       -4.60 0.0000764 
#> 3 hp              1.07     0.175      6.12 0.00000115
```
<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Your custom methods approach seems an ideal way to add this second stage to the regression table. However, I'm getting blocked by the `gof` sanity check,

```r
library(modelsummary)

glance_custom.felm <- function(x) {
   if (!is.null(x$stage1)) {
      out <- broom::tidy(x$stage1)
       return(out)
    }
 }

 modelsummary(m)
 #> Error in sanity_gof(gof, gof_custom): Assertion on 'gof_custom' failed: Must have exactly 1 rows, but has 3 rows.
```
<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It might require a bit more formatting to make it look nice (related discussion [here](https://twitter.com/andrewheiss/status/1192231221717327873)), but I was wondering if you had any thoughts on the best way to approach this?

**Comment by vincentarelbundock** [comment]
Oh, that's an interesting problem!

I'm not 100% sure `glance_custom` is the right solution for this. The mechanics to produce the top part of the table expects a `broom::tidy` structure, and the mechanics to produce the bottom of the table expects a `broom::glance` one-row tibble. Those are quite different internally. In your case, you want two *top* parts.

I'll have to think about it some more to figure out the best API for this. Right now, the simplest hacky way to do it would be to use `modelsummary` to produce a table with the first stage, and then concatenate the two tables using `add_rows`:

```
library(lfe)
library(modelsummary)
library(tidyverse)

mod <- list(
  lfe::felm(wt ~ drat | 0 | (disp ~ hp), data = mtcars),
  lfe::felm(wt ~ drat + vs | 0 | (disp ~ hp), data = mtcars)
)

stage1 <- mod %>% 
  map(~ .$stage1) %>%
  msummary(output="data.frame", gof_omit=".*") %>%
  select(-group, -statistic) 

msummary(mod, add_rows=stage1)
```

But then the first stage appears at the very bottom of the table, below GOFs, which is almost certainly not what you want. There is already a mechanism to change the position of `add_rows`, based on attributes, but it doesn't work well right. 

```r
attr(new_rows, "position") <- 5
```

It would be trivial to fix it, but it still feels a bit clunky. Let me know if you have a better idea. I'll keep thinking about it in the meantime.

**Comment by vincentarelbundock** [comment]
Output from code above: 

![Screen Shot 2020-09-03 at 14 58 14](https://user-images.githubusercontent.com/987057/92155790-e9975180-edf5-11ea-8991-3bafa216c61f.png)

**Comment by vincentarelbundock** [comment]
Now that I think about it, creating a new `tidy` function with a custom class name might be a cleaner solution:

```
library(lfe)
library(broom)
library(modelsummary)
library(tidyverse)

mod <- list(
  lfe::felm(wt ~ drat | 0 | (disp ~ hp), data = mtcars),
  lfe::felm(wt ~ drat + vs | 0 | (disp ~ hp), data = mtcars)
)

tidy.felm_custom <- function(x, ...) {
  stage1 <- broom:::tidy.felm(x$stage1, ...)
  stage2 <- broom:::tidy.felm(x, ...)
  stage1$term <- paste("Stage 1", stage1$term)
  stage2$term <- paste("Stage 2", stage2$term)
  out <- bind_rows(stage1, stage2)
  out
}
class(mod[[1]]) <- 
  class(mod[[2]]) <- 
  c("felm_custom", class(mod[[1]]))

msummary(mod)
```

![Screen Shot 2020-09-03 at 15 05 05](https://user-images.githubusercontent.com/987057/92156377-dfc21e00-edf6-11ea-8ec8-cde637a0edca.png)

**Comment by grantmcdermott** [comment]
Oh, I like that.

Here's a very slightly modified version, based on what I'd like from a reg table:
- Only include the instrument for the first stage.
- Drop the "Stage 2" prefix. 

```r
tidy.felm_custom <- function(x, ...) {
  stage1 <- broom:::tidy.felm(x$stage1, ...)
  stage2 <- broom:::tidy.felm(x, ...)
  stage1 <- dplyr::filter(stage1, !(term %in% stage2$term))
  stage1$term <- paste("Stage 1", stage1$term)
  out <- bind_rows(stage1, stage2)
  out
}
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model 1</th>
<th style="text-align: left;">Model 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">3.243</td>
<td style="text-align: left;">2.611</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(1.159)</td>
<td style="text-align: left;">(1.543)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>disp(fit)</code></td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.001)</td>
<td style="text-align: left;">(0.002)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drat</td>
<td style="text-align: left;">-0.371</td>
<td style="text-align: left;">-0.293</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.254)</td>
<td style="text-align: left;">(0.289)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stage 1 hp</td>
<td style="text-align: left;">1.069</td>
<td style="text-align: left;">0.844</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.175)</td>
<td style="text-align: left;">(0.226)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">vs</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.237</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.307)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: left;">0.801</td>
<td style="text-align: left;">0.811</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: left;">0.787</td>
<td style="text-align: left;">0.790</td>
</tr>
</tbody>
</table>


One last thing to sort out is printing of *all* the Stage 2 vars before any Stage 1 var. At the moment, the final line ("vs" from the stage 2) is awkwardly positioned.

**Comment by vincentarelbundock** [comment]
Right now, there is no internal sorting of terms going on, unless users specify `coef_map`. IMO, this is a *good* thing, because trying to be smart about row order is a nightmare (I tried), and no sorting basically gives your the terms in the order supplied by users in their model formulas. For now, writing a simple function to sort coefs might be your best bet:

```
sort_coefs <- function(x) {
  out <- map(x, ~tidy(.)$term) %>%
         unlist %>%
         unique
  idx <- grep("Stage 1", out)
  out <- c(out[idx], out[-idx])
  setNames(out, out)
}

mod <- list(
  lfe::felm(wt ~ drat + vs | 0 | (disp ~ hp), data = mtcars),
  lfe::felm(wt ~ drat | 0 | (disp ~ hp), data = mtcars)
)
class(mod[[1]]) <- class(mod[[2]]) <- c("felm_custom", class(mod[[1]]))

msummary(mod, coef_map=sort_coefs(mod))
```

I'll have to think about alternatives, but my hunch is that finding a general solution to this will require significant work. Before starting, I'd need clarity about implementation plan that I don't have now...

**Comment by grantmcdermott** [comment]
Thanks @vincentarelbundock, I think your solution with coef_map is actually very elegant.

(My only minor change would, again, be to switch the order so that the "Stage 1" vars come last... i.e. change line 4 to ` out <- c(out[-idx], out[idx])`.)

One _possible_ general solution if you did end up bundling it with modelsummary is to catch `felm()` models with 1st stages (i.e. `!is.null(x$stage1)` and then pass `sort_coefs()` internally to the coef_map argument by default. Naturally, this would get overridden if users supplied their own coefficient list.

Of course, I could be missing something by thinking it's as easy as that and your decision regardless.

**Comment by grantmcdermott** [comment]
Final thing: This is such a common request in my experience &mdash; whether referees or students &mdash; that I think including a worked example as per the above in your [model customization](https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html) vignette would be widely appreciated.

Feel free to close, but assuming no-one minds I'll tag some folks who I think might be interested in this discussion. @andrewheiss @edrubin @NickCH-K.

P.S. My memory for all this was jogged by the release of the new [**ivreg**](https://john-d-fox.github.io/ivreg/index.html) package; I'm going to request that they also return the 1st stage for `ivreg()` so that a similar workflow would apply. See also https://github.com/DeclareDesign/estimatr/issues/335.

**Comment by andrewheiss** [comment]
Oh man this is awesome! My students have wanted a way to stick the first stage into a table and I've been having them run a manual first-stage with `lm()` just for that (but then using `ivreg()` or `felm()` or `iv_robust()` for the actual IV). This'll be great.

What would be the best approach to extend this to `estimatr::iv_robust()`? Make a custom tidier for it too?

**Comment by grantmcdermott** [comment]
> What would be the best approach to extend this to estimatr::iv_robust()? Make a custom tidier for it too?

Ya, although in doing so you'd have to (re-)run the 1st stage again, because `iv_robust()` doesn't yet return the 1st stage model object. (Open issue linked in my previous comment.)

**Comment by andrewheiss** [comment]
Oof. I'll just switch to 100% `felm()` for my class :)

**Comment by vincentarelbundock** [comment]
I really like your idea @grantmcdermott  and I added a section about this to the docs: [2-stage-instrumental-variable-estimation)](https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html#2-stage-instrumental-variable-estimation)

Also, I don't advertise it broadly, but I keep some unofficial, unexported, unsupported convenience functions for power users like you and @andrewheiss . I added a tweaked version of our code from above. You can now summarize iv models like this:

``` r
library(lfe)
library(modelsummary)

models <- list(
  felm(wt ~ drat | 0 | (disp ~ hp), data = mtcars),
  felm(wt ~ drat + vs | 0 | (disp ~ hp), data = mtcars)
  )
class(models[[1]]) <- class(models[[2]]) <- c('iv', class(models[[1]]))

tidy.iv <- modelsummary:::tidy_felm_iv

cm <- modelsummary:::coef_map_felm_iv(models)

modelsummary(models, coef_map=cm)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model 1</th>
<th style="text-align: left;">Model 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">3.243</td>
<td style="text-align: left;">2.611</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(1.159)</td>
<td style="text-align: left;">(1.543)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drat</td>
<td style="text-align: left;">-0.371</td>
<td style="text-align: left;">-0.293</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.254)</td>
<td style="text-align: left;">(0.289)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>disp(fit)</code></td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.007</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.001)</td>
<td style="text-align: left;">(0.002)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">vs</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.237</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.307)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stage 1 hp</td>
<td style="text-align: left;">1.069</td>
<td style="text-align: left;">0.844</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.175)</td>
<td style="text-align: left;">(0.226)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: left;">0.801</td>
<td style="text-align: left;">0.811</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: left;">0.787</td>
<td style="text-align: left;">0.790</td>
</tr>
</tbody>
</table>

**Comment by grantmcdermott** [comment]
*Chef's kiss*

Amazing Vincent. Think I'll close this in light of your additions. Thanks again.
