### ISSUE TITLE
`coef_rename`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#126]
Is there a case to be made for `coef_rename`?

`coef_map` can already do this, but 

> "Coefficients that are omitted from this vector will be omitted from the table."

Sometimes, it might be convenient to just rename a single term.

Downsides:

* Additional argument to the function (I want to be very aggressive about keeping the API simple)
* Redundancy: Best to have one obvious way of doing things

**Comment by vincentarelbundock** [comment]
Another option would be to "interact" `coef_map` and `coef_omit`, such that `coef_omit=FALSE` ensures that `coef_map` only renames, and neither sorts nor omits.

**Comment by gbekes** [comment]
I like the first one. You have a regression, including dummies. So you work in two steps. 1. drop/keep what you need. 2. rename. I'd like to use two separate options, with rename just renaming what I want.

**Comment by vincentarelbundock** [comment]
I think that use-case is common enough that I'm now leaning toward implementing a `coef_rename`. `coef_map` is great, but maybe too much of a power user feature.

**Comment by vincentarelbundock** [comment]
@gbekes I just implemented the `coef_rename` argument. I'd appreciate it if you could give it a try and let me know if it works as expected. Install from Github and make sure you restart your R session before trying:

```r
library(remotes)
install_github('vincentarelbundock/modelsummary')
```

Restart your R session, and then:

```r
library(modelsummary)

mod <- list()
mod$OLS <- lm(am ~ drat, data = mtcars)
mod$Logit <- glm(am ~ qsec, data = mtcars, family = binomial())

cmap <- c('(Intercept)'='Constant', 'drat'='Rear axle ratio')
msummary(mod, coef_rename=cmap)
```

**Comment by gbekes** [comment]
First thing tomorrow. Cheers, Gabor

**Comment by gbekes** [comment]
Works nicely. 
```
library(estimatr) 
library(lspline)

reg1<-lm(lnw~female,data) 
reg2 <- lm_robust(lnw ~ lspline(age, c(30,40)), data = data, se_type = "HC1")

cm <- c('R2' = 'R-squared (%)',
        'lspline(age, c(30, 40))2' = 'spline(age, c(20,30))',
        '(Intercept)' = 'Constant')

msummary(list(reg1, reg2),
         fmt="%.4f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC',
         stars=c('*' = .05, '**' = .01),
         coef_rename = cm,
         #output = paste(output,"ch09_reg2-R.tex",sep="")
         )
```

My issues
1. I wanna also change R2 to R-squared, Num.Obs to N.  Not sure if gof_clean and gof_omit may work together, and how. 
2. I'd like to change string of gof, eg se type from "HC1" to "Robust", is this possibleM

**Comment by gbekes** [comment]
One more.
say you have a bunch of country dummy vars `+ as.factor(country)` yielding coeffs like as.factor(country)35, and you wanna ommit all. I guess coeff_omit can handle them, but is there a way to have them as all coefficients starting with as.factor or as.factor(country)?

**Comment by vincentarelbundock** [comment]
R2 is not a coefficient, it is a "goodness-of-fit" statistic. The name of those is handled by the `gof_map` argument. This argument expects a data.frame which includes information about the original name, the "clean" name, whether or not you want to omit the GOF statistic, and how you want to round it.

The default formatting data.frame can be found here:

```r
modelsummary::gof_map
```

You can customize this data.frame or prepare a whole new one and then feed it to `gof_map` in order to customize the output.

To customize the output and add new information to the bottom of your table, you can either:

1. Define a new `glance_custom.modelclass` method.
  - https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html
2. Use the `add_rows` argument.
  - https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#add-rows
