### ISSUE TITLE
viewer when output in use

### ISSUE THREAD

**Issue by gbekes** [vincentarelbundock/modelsummary#127]
I love that table is printed to the viewer. 
Can this still happen even when save to tex, using output?

**Comment by vincentarelbundock** [comment]
You can print the raw LaTeX code to the console, but obviously if you want to see the final product you will have to compile your Rmarkdown or your LaTeX document to PDF. The RStudio viewer does not have a built-in LaTeX compiler.

**Comment by gbekes** [comment]
I mean I'd use msummary as my default regression table viewer. This means always looking at at in viewer + sometime saving some versions in tex for paper/talk.

So why can't it do both, show it on the viewer (as it happens when no output device is set) in Rstudio AND save when output is added?.

**Comment by vincentarelbundock** [comment]
What if your script saves 10 tables? We just cycle through?

**Comment by gbekes** [comment]
Yes, sir. Like we do for graphs. I mean say you wanna show three models, with say three different set of sub-samples. Having all three tables in viewer, so that we can cycle thru is super.

**Comment by vincentarelbundock** [comment]
What if someone uses `modelsummary` in a script and wants to look at the logs after running it? Then the whole log will be full of HTML...

**Comment by gbekes** [comment]
I think it's not a huge problem, for some ease while using... 
Not a big deal, may be down to preferences. (People coming from Stata, like me, miss a table when not printed. )

**Comment by vincentarelbundock** [comment]
great, I'll leave this open and think about it.

**Comment by gbekes** [comment]
Okay. I mean, when teaching, it is useful. You have a script that produces output used in slideshow/md. But in class when you go thru script, it's nice if no need to comment out output lines.

**Comment by gbekes** [comment]
One more: just minor suggestions to make error msg more informative


```
 cm <- c('(Intercept)' = 'Constant')
 msummary(list(reg1, reg2),
          coef_rename = cm,
          output = paste(output,"ch20-table-4-wfh-reg1",sep="")
 )
"Error in factory_list[[output_format]] : subscript out of bounds"
```

when in fact I forgot to specify output format type (ie .tex)

**Comment by vincentarelbundock** [comment]
Oh yes, this last one I caught already. If you install from Github you'll see this error message:

> Error in sanity_output(output) :
>   The `output` argument must be default, gt, kableExtra, flextable, huxtable, html, latex, markdown, dataframe, data.frame, or a valid file path with one of these extensions: html, tex, md, txt, docx, pptx, rtf, jpg, png

**Comment by vincentarelbundock** [comment]
Yes!

One of the important design feature of `modelsummary` is that it gives sensible default, and then delegates further customization to external packages (`kableExtra` by default). This makes the package easy to use, but also infinitely customizable. You can read a rundown of the LaTeX customization features here:

https://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf

Note that the `modelsummary(output="file.tex")` is a "quick write" strategy; it writes to file immediately without considering any of the functions you call *after* `modelsummary`. If you want to use `kableExtra` to customize your table, you'll need to save it using `save_kable`. The documentation describes this quite clearly. You can find examples here:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#customizing-the-look-of-your-table-1

**Comment by vincentarelbundock** [comment]
Note that writing to file does not work in this branch. Right now, I'm just worried about histogram displaying correctly on Windows.

**Comment by vincentarelbundock** [comment]
I thought about this, and I think I'm going to stick with the current strategy of having `output` do only one thing.

`output` is already quite overloaded, since it can write a table to file, open a browser, display in the RStudio window. Making it do more than one thing at once runs the risk of confusing users, and I don't have a good idea for default behavior and for overriding that default behavior (what if I want to write to file but *not* see the table?). A good user experience here would require a fair amount of tweaking in the backend, and runs the risk of having to do lots of work just to complicate the user experience.

IMHO, repeating the command with a second time to write to file is not a huge burden, so I think I'll leave things as-is for now.
