### ISSUE TITLE
Add statistic or model characteristic to the table (e.g., Pseudo-R2 or F)

### ISSUE THREAD

**Issue by gbekes** [vincentarelbundock/modelsummary#128]
I wanna have a table with an OLS, a logit coeff, and AME for logit with logitfmx (also for probits)

```

# lpm 
lpm <-lm(stayshealthy ~ smoking + ever_smoked + female + age + lspline(eduyears, c(8,18)) + 
              income10 + lspline(bmi, c(35)) + exerc + as.factor(country), data=share)
# logit coefficients
logit <- glm(stayshealthy ~ smoking + ever_smoked + female + age + lspline(eduyears, c(8,18)) + 
               income10 + lspline(bmi, c(35)) + exerc + as.factor(country), data=share, family='binomial')
# logit marginal differences
logit_marg <- logitmfx(formula = stayshealthy ~ smoking + ever_smoked + female + age + lspline(eduyears, c(8,18)) + 
                          income10 + lspline(bmi, c(35)) + exerc + as.factor(country), data=share, atmean=FALSE)
# probit coefficients
probit <- glm(stayshealthy ~ smoking + ever_smoked + female + age + lspline(eduyears, c(8,18)) + 
               income10 + lspline(bmi, c(35)) + exerc + as.factor(country), data=share, family=binomial(link="probit"))
# probit marginal differences
probit_marg <- probitmfx(formula = stayshealthy ~ smoking + ever_smoked + female + age + eduyears0_8 + eduyears8_18 + 
                       eduyears18 + income10 + bmi16_35 + bmi35 + exerc + as.factor(country), data=share, atmean=FALSE)


library(modelsummary)
cm <- c('(Intercept)' = 'Constant')
msummary(list(lpm, logit, logit_marg, probit, probit_marg),
         fmt="%.3f",
         gof_omit = 'DF|Deviance|Log.Lik.|F|R2 Adj.|AIC|BIC',
         stars=c('*' = .05, '**' = .01),
         coef_rename = cm
)

```
Issues
R2 displayed for OLS only

**Comment by vincentarelbundock** [comment]
`modelsummary` can automatically display all the goodness-of-fit statistics produced by `broom::glance`. You can see what those statistics are by typing:

```r
library(broom)
glance(model)
```

If the GOF statistic you want is *not* retrieved by `glance`, you may still be able to display it. The easiest way to achieve this is probably to write a `glance_custom.logitmfx` method. This is actually super easy; much easier than it sounds. See here for an example:

https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html

BTW, not my business, but it seems quite normal to me that `broom::glance` would *not* produce R2 for logitmfx. Are you looking for "pseudo R2"?

Let's say you have a function called `pseudoR2(model)` which returns a single numeric value with the statistic you want. What you need to do is define this method:

```r
library(tibble)
glance_custom.logitmfx <- function(x)  tibble(`Pseudo R2` = pseudoR2(x))
```

And the pseudo R2 would be added to all the `logitmfx` models in your table.

**Comment by vincentarelbundock** [comment]
Also, when I look at the `summary(model)` for logitmfx, it doesn't show R2 either. So the model package's own summary function does not display it.

**Comment by gbekes** [comment]
Okay I see,  the problem is that indeed, `glm()` does not show Pseudo R2, I forgot that (in stata, it does as default).

So I'd need to make it first, I guess. 
```
logit <- glm(stayshealthy ~ smoking + ever_smoked +...,  family="binomial")
logit0 <- glm(stayshealthy~1, family="binomial")
PseudoR2 <- 1-logLik(logit)/logLik(logit0)
```

**Comment by vincentarelbundock** [comment]
Well, here's a minimal reproducible example, using the `pR2` function from the `pscl` package to retrieve McFadden's version of Pseudo-R2:

```
library(pscl)
glance_custom.glm <- function(x) data.frame(`PseudoR2` = pR2(x)["McFadden"])

mod <- glm(vs ~ drat + mpg, mtcars, family=binomial)
msummary(mod)
```



|            |Model 1 |
|:-----------|:-------|
|(Intercept) |-7.755  |
|            |(4.000) |
|drat        |-0.562  |
|            |(1.333) |
|mpg         |0.477   |
|            |(0.200) |
|Num.Obs.    |32      |
|AIC         |31.4    |
|BIC         |35.7    |
|Log.Lik.    |-12.675 |
|PseudoR2    |0.422   |

**Comment by gbekes** [comment]
Perfect. NB, if a `logitmfx()`  is also run, error msg will let us know that   pR2 does not work with it. 
As you said, the solution is to use `margins()` instead of mfx.

**Comment by vincentarelbundock** [comment]
Cool. I will leave this Issue open because the examples in it might be relevant to other users.
