### ISSUE TITLE
Customize the names or format of goodness-of-fit or model characteristics

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#130]
@gbekes asked these questions in issue https://github.com/vincentarelbundock/modelsummary/issues/126

> My issues
> 
>     I wanna also change R2 to R-squared, Num.Obs to N. Not sure if gof_clean and gof_omit may work together, and how.
>     I'd like to change string of gof, eg se type from "HC1" to "Robust", is this possibleM

**Comment by vincentarelbundock** [comment]
R2 is not a coefficient, it is a "goodness-of-fit" statistic. The name of those is handled by the `gof_map` argument. This argument expects a data.frame which includes information about the original name, the "clean" name, whether or not you want to omit the GOF statistic, and how you want to round it.

The default formatting data.frame can be found here:

```r
modelsummary::gof_map
```

You can customize this data.frame or prepare a whole new one and then feed it to `gof_map` in order to customize the output.

To customize the output and add new information to the bottom of your table, you can either:

1. Define a new `glance_custom.modelclass` method: https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html
2. Use the `add_rows` argument: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#add-rows

**Comment by benzipperer** [comment]
Not sure if this should be a separate issue, but I think I'm having trouble understanding what a custom gof_map should look like.

For example, let's suppose we want a single GOF statistic with the following names
```r
gof_map <- tribble(
    ~raw,         ~clean,  ~fmt,  ~omit,
  "nobs", "Observations",     0,  FALSE
)
```
If we try 
```r
modelsummary(lm(mpg ~ hp, mtcars), gof_map = gof_map)
```
that also brings in the GOF statistics from `glance()` [here](https://github.com/vincentarelbundock/modelsummary/blob/master/R/extract_gof.R#L19-L32). As a result, we have to specify gof_map and also gof_omit to get the desired behavior, something like
```r
modelsummary(lm(mpg ~ hp, mtcars), gof_map = gof_map, gof_omit = "[^Observations]")
```
Am I misunderstanding how you're supposed to use a custom gof_map?

**Comment by vincentarelbundock** [comment]
There is a slight incoherence: (a) `coef_map` omits everything by default unless it is explicitly included, (b) `gof_map` includes everything by default unless it is explicitly excluded.

The problem is that `gof_map` is used *every single time* you call `modelsummary` in order to rename GOF statistics. And since there are hundreds of possible GOF names associated with different models, I can't anticipate all those names and make an informed choice for every possible model supported by `broom`. As a result, I decided to include everything that `glance` produces by default, unless you specifically choose `omit=TRUE`.

Instead of creating your own `gof_map`, I recommend modifying the existing one (`modelsummary:::gof_map`).

**Comment by vincentarelbundock** [comment]
I clarified this in the doc: 6668f27

**Comment by benzipperer** [comment]
That makes sense to me, thank you. 

I really like the flexibility of modifying or creating gof_map. But I wonder if some slight modifications to extract_gof would allow a more common logic for both coef_map and gof_map. What if when gof_map is user provided, modelsummary uses only GOF in gof_map? See for example [here](https://github.com/vincentarelbundock/modelsummary/compare/master...benzipperer:gof_map).

In that case, the user-provided gof_map is prioritized, kind of like coef_map:
```r
gof_map <- tribble(
    ~raw,         ~clean,  ~fmt,  ~omit,
  "nobs", "Observations",     0,  FALSE
)
modelsummary(lm(mpg ~ hp, mtcars))
modelsummary(lm(mpg ~ hp, mtcars), gof_map = gof_map)
```
and of course also you can still do things like 
```r
gof_map <- modelsummary:::gof_map
gof_map$omit <- TRUE
modelsummary(lm(mpg ~ hp, mtcars), gof_map = gof_map)
```

**Comment by vincentarelbundock** [comment]
This makes a lot of sense intuitively. Let me think about it a bit (busy day today), but I currently think that making the default behaviors more consistent is a good idea.

**Comment by vincentarelbundock** [comment]
@benzipperer Thanks for the code example. I used it to make the suggested change. Now, you can do this:

``` r
library(modelsummary)
library(tibble)
gof_map <- tribble(
    ~raw,      ~clean,          ~fmt,  ~omit,
  "nobs",      "Observations",     0,  FALSE,
  "r.squared", "R2",               2,  FALSE
)
modelsummary(lm(mpg ~ hp, mtcars), 
             gof_map=gof_map, 
             output="data.frame")
#> # A tibble: 6 x 4
#>   group     term           statistic    `Model 1`
#>   <chr>     <chr>          <chr>        <chr>    
#> 1 estimates "(Intercept)"  "estimate"   30.099   
#> 2 estimates ""             "statistic1" (1.634)  
#> 3 estimates "hp"           "estimate"   -0.068   
#> 4 estimates ""             "statistic1" (0.010)  
#> 5 gof       "Observations" ""           32       
#> 6 gof       "R2"           ""           0.60
```

I'm not sure when this will be released to CRAN, but you can get it from Github right now.

Thanks again!

**Comment by jacobgellman** [comment]
Thank you for the wonderful package and thread. 

Related question: I have struggled to get the `fmt` column in the `gof_map` to produce number formats where the big mark is a comma, i.e. 12,345 rather than 12345. The [documentation](https://cran.r-project.org/web/packages/modelsummary/modelsummary.pdf) has very helpfully provided this example for rounding:

```
library(modelsummary)
mod <- lm(wt ~ drat, data = mtcars)
gm <- modelsummary::gof_map
gm$omit[gm$raw == 'deviance'] <- FALSE
gm$fmt[gm$raw == 'r.squared'] <- "%.5f"
modelsummary(mod, gof_map = gm)
```

but after much googling I cannot figure out the correct command to change the big mark to a comma. I recognize the answer is probably very simple, but I would wager that some future users would have a similar question. Would it be possible to add a comma example to the documentation? Thanks once again.

**Comment by vincentarelbundock** [comment]
@jacobgellman I don't think this is possible with the version currently on CRAN.

However, I think this is an important feature, so I made a small tweak to allow users to submit lists of lists to the `gof_map` parameter. If you use the new version from Github (make sure to restart R completely after install), you can do things like this:

```r
     f1 <- function(x) format(round(x, 3), big.mark=",")
     f2 <- function(x) format(round(x, 0), big.mark=",")

     gm <- list(
       list("raw" = "nobs", "clean" = "N", "fmt" = f2),
       list("raw" = "AIC", "clean" = "aic", "fmt" = f1))

     modelsummary(models,
       fmt = f1,
       gof_map = gm)
```
