### ISSUE TITLE
Customized SEs for modelplot

### ISSUE THREAD

**Issue by shellmeier** [vincentarelbundock/modelsummary#133]
Hi,

I am using the modelplot function to plot my model estimates. I am using clustered standard errors in my models and would like to use them for the coefficient plots as well. Is there an easy way to include custimized SEs in modelplot similarly to msummary? 

The code below does not work ("Ignoring unknown parameters: statistic_override, statistic"), of course, but this is how I imagined it to work.

Thanks a lot in advance.

```
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list()
models[['OLS 1']] <- lm(Donations ~ Literacy + Clergy, data = dat)
models[['Poisson 1']] <- glm(Donations ~ Literacy + Commerce, family = poisson, data = dat)

modelplot(models, statistic_override = vcovHC, statistic = 'std.error')
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report! This is obviously an important feature. I pushed an update to the package. Could you please install from Github and try it to see if it works as expected?

```r
library(remotes)
install_github('vincentarelbundock/modelsummary')
```

Then restart your R session completely and run something like this:

``` r
library(modelsummary)
library(sandwich)

mod <- list(lm(hp ~ mpg + drat, mtcars),
            lm(hp ~ mpg + drat, mtcars))
so <- list(vcov, vcovHC)
modelplot(mod, statistic_override=so, conf_level=.87)
```

![](https://i.imgur.com/krnPDmz.png)

**Comment by shellmeier** [comment]
Thank you so much, @vincentarelbundock! Works as expected. This (and the whole package in general) is really great.
