### ISSUE TITLE
`datasummary_skim`: misc issues

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#134]
Reported via email:

> #1   
> datasummary_skim(data, type='numeric', histogram = TRUE)
> -->and instead of a histogram, it has "<U+2587>" 
> I changed locale to US, but no change (Windows 10 + R 4.0.2 + RStudio Version 1.3.1073). 
> 
> #2 I wonder if there was a way to include [Date].
> 
> #3 + 1 minor thing.
> when we run datasummary_skim(data, type="categorical") and there is no categorical, it says:
> "Error in datasummary(formula = f, data = dat_new, output = output, title = title,  :   No levels in 'x'!"
> 
> Maybe a better output would just say, maybe you don't have categorical variables. Because, I might have stored year as numeric while i thought it was categorical...
> 
> just as I sent, I tried it on a smaller set, and there I had
> Error in datasummary_skim(data2, type = "categorical") :   datasummary_skim(type="categorical") only works with logical, character, and factor variables. There is such variable in your dataset.
> 
> so the other error, I realized was, when a variable had just NA's as values. I'd consider adding it as a factor value, or maybe allow user deciding whether to allow NA as factor value or not.

**Comment by vincentarelbundock** [comment]
These issues make me think that https://github.com/vincentarelbundock/modelsummary/issues/132 might be a very good idea.

**Comment by gbekes** [comment]
Yes. I'm actually replacing my skimr line with datasummary_skim.... --> as the option to have numeric and categorical separately is great, and output is just neater. This is why I'd add `tyoe=date` as separate type option.

**Comment by vincentarelbundock** [comment]
Oh, I understand what you mean now! Will think about it.

BTW, I'm working on an update to properly support histograms in Windows (through .svg images instead of unicode characters). The problem is I don't have access to a Windows computer at home to test it out (and the office is closed).

If you get a chance, would you mind testing the new version by installing my "histogram" branch with this command:

```r
library(remotes)
install_github('vincentarelbundock/modelsummary@histogram')
```

Then restart R completely and try some code like this:

```r
library(modelsummary)
library(palmerpenguins)

datasummary_skim(penguins)
datasummary_skim(penguins, "categorical")
```

**Comment by vincentarelbundock** [comment]
Note that writing to file does not work in this branch. Right now, I'm just worried about histogram displaying correctly on Windows.

**Comment by vincentarelbundock** [comment]
@gbekes I believe that the two main issues raised in this thread have been resolved by recent commits to github. When `datasummary_skim` cannot handle a particular variable or dataset, informative warnings should generally returned. Obviously, I can't be 100% certain this will *always* work, but I tested `datasummary_skim` with the 1400 datasets of the Rdatasets repository and it worked fine there in all of them, or returned an appropriate error. 

If you want to try it you can install from Github:

```r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

Make sure you restart the R session completely before trying.

I am not certain what to do with date support yet, but I have a opened a specific issue for this.

https://github.com/vincentarelbundock/modelsummary/issues/138

**Comment by gbekes** [comment]
Ok. One more for the road.
Numeric: Instead of p75, p25, it would be better to have p5/p95 or p1/p99. p25 and p75 are not really informative, min and max could harbor extreme values, so p99 or p95 is more informative re shape of distribution.

**Comment by gbekes** [comment]
btw, I'm kinda basing my point on Stata's codebook, which gives stg like. Range, Unique values, missing, type -- all super useful. 
It's kinda close to Hmisc::describe, just better....

---------------------------------------------------------------------------------------------------------------------------------------
total_minutes                                                                                                               (unlabeled)
---------------------------------------------------------------------------------------------------------------------------------------

                  type:  numeric (int)

                 range:  [0,102]                      units:  1
         unique values:  102                      missing .:  0/10,167

                  mean:   70.1268
              std. dev:   28.9993

           percentiles:        10%       25%       50%       75%       90%
                                16        58        86        91        93

**Comment by vincentarelbundock** [comment]
Thanks for these suggestions! A few thoughts:

The main design goal of `datasummary_skim` is to offer a "canned", or "one-size-fits-all" summary function. A secondary design goal is to produce a beautiful output. That means we cannot add a large number of summaries, otherwise the table would become too cluttered.

That said I think there is a case for Missing% and Unique#, so I'm leaning toward including those.

With respect to Min/Max vs. P01/P99, I agree with you on principles that this would be better in cases with extreme values. However, (a) I think the vast majority of users will want to display Min/Max, and (b) I feel like the built-in histogram can guard against the most egregious problems that we can expect in this respect. 

Finally, I recognize that my "one-size-fits-all" will *not* actually fit everyone's needs. For this reason, I also offer a  *super powerful and massively customizable* function called `datasummary`, which allow people to build their own summary tables, and which can accept arbitrary functions. See here for details: https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#datasummary-1

With `datasummary`, it would be trivial to define a function to produce a new column with a "range" string like this "[0, 100]" or any other data summary you like.

For `datasummary_skim`, I'm now leaning towards this look. Given all of the above, what do you think? Would appreciate any comments you may have!

<img width="684" alt="Screen Shot 2020-09-16 at 07 16 14" src="https://user-images.githubusercontent.com/987057/93331860-ee450800-f7ee-11ea-8f3f-122da2c5bfd2.png">

**Comment by gbekes** [comment]
It. Is. Fantastic. Love it. Simple and useful. 
And you are right. The histogram will communicate details, or you can print out more. Indeed. 

(just to be a snobbish nerd, maybe the decimal digits could be set so that if number is above a 999, no digit is used, and if below 10, two digits are used.  or any other more flexible rule. )

btw, thanks so much, an amazing experience for me.

**Comment by vincentarelbundock** [comment]
Fantastic!

Conditional formatting sounds super cool, but I'll have to think about it a bit. Will close this issue for now. Feel free to open new ones with specific requests.
