### ISSUE TITLE
mixed models: lme4, rstanarm, brms, mcmc, nlme, pscl, TMB, GLMMadaptive, etc.

### ISSUE THREAD

**Issue by gorkang** [vincentarelbundock/modelsummary#139]
I tried modelsummary (the CRAN and last github versions) with lme4 (both lmer and glmer models) and in all cases I am getting errors. See a reproducible example below. 

``` r
library(lme4)
data(sleepstudy)
fit <- lmer(Reaction ~ 1|Subject, data=sleepstudy)
modelsummary::msummary(fit)
#> Error: No tidy method for objects of class lmerMod
```

<sup>Created on 2020-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vincentarelbundock** [comment]
Try loading the `broom.mixed` package.

**Comment by gorkang** [comment]
That worked! Thanks!

Shouldn't it be loaded by default when loading modelsummary? :)

Cheers

**Comment by vincentarelbundock** [comment]
Perhaps, but `broom.mixed` has a bunch of dependencies, so it would be a mixed blessing.

I'll think about it. At the very least, this information should be more prominent in the documentation.

**Comment by vincentarelbundock** [comment]
FYI, I just made code contributions to `broom.mixed` which reduced by 4 the number of dependencies (including one particularly heavy and hard to install). When the new lighter version of `broom.mixed` gets to CRAN, I plan import it automatically in `modelsummary`.
