### ISSUE TITLE
data summary_skim() output

### ISSUE THREAD

**Issue by napaxton** [vincentarelbundock/modelsummary#140]
Not sure if this is an issue or not; it's unexpected behavior.

When running your demonstration code from the datasummary page of the documentation in a clean session, instead of the `datasummary()` output shown, I get:

  | Mean | SD | P0 | P25 | P50 | P75 | P100
-- | -- | -- | -- | -- | -- | -- | --
X | 172.5 | 99.4 | 1.0 | 86.8 | 172.5 | 258.2 | 344.0
bill_length_mm | 43.9 | 5.5 | 32.1 | 39.2 | 44.5 | 48.5 | 59.6
bill_depth_mm | 17.2 | 2.0 | 13.1 | 15.6 | 17.3 | 18.7 | 21.5
flipper_length_mm | 200.9 | 14.1 | 172.0 | 190.0 | 197.0 | 213.0 | 231.0
body_mass_g | 4201.8 | 802.0 | 2700.0 | 3550.0 | 4050.0 | 4750.0 | 6300.0
year | 2008.0 | 0.8 | 2007.0 | 2007.0 | 2008.0 | 2009.0 | 2009.0

**Comment by vincentarelbundock** [comment]
Thanks for the report!

I did a serious rewrite of the `datasummary_skim` function, and plan to release it to CRAN in the next couple weeks. The website already shows the development version (sorry for the confusion!). You can try it out by:

```r
library(remotes)
install_github('vincentarelbundock/modelsummary')
```

Then restart your R session completely. Finally:

```r
library(modelsummary)
library(tidyverse)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv'
penguins <- read.csv(url)

datasummary_skim(penguins)
```

Should give you something like this:

<img width="1024" alt="Screen Shot 2020-09-25 at 16 13 26" src="https://user-images.githubusercontent.com/987057/94311954-139de880-ff4a-11ea-8049-72f808a74e85.png">

**Comment by napaxton** [comment]
Boom. Nice.

**Comment by vincentarelbundock** [comment]
on CRAN
