### ISSUE TITLE
Duplicated term names from the `tidy` method with `broom.mixed`

### ISSUE THREAD

**Issue by marklhc** [vincentarelbundock/modelsummary#141]
For mixed-effect models with two or more random effects, the tidy method in `broom.mixed` returns a tibble that has duplicated names in the `term` column, with the effects separated instead by the `group` column, like the following:

    library(lme4)
    #> Loading required package: Matrix
    library(broom.mixed)
    #> Registered S3 method overwritten by 'broom.mixed':
    #>   method      from 
    #>   tidy.gamlss broom
    library(modelsummary)
    fm1 <- lmer(strength ~ (1|batch) + (1|sample), Pastes)
    tidy(fm1)
    #> # A tibble: 4 x 6
    #>   effect   group    term            estimate std.error statistic
    #>   <chr>    <chr>    <chr>              <dbl>     <dbl>     <dbl>
    #> 1 fixed    <NA>     (Intercept)       60.1       0.677      88.7
    #> 2 ran_pars sample   sd__(Intercept)    2.90     NA          NA  
    #> 3 ran_pars batch    sd__(Intercept)    1.29     NA          NA  
    #> 4 ran_pars Residual sd__Observation    0.823    NA          NA
As a result, `msummary()` gives duplicated effect names:

    msummary(fm1, output = "markdown")

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: left;">60.053</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">(0.677)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: left;">2.904</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd__(Intercept)</td>
<td style="text-align: left;">1.287</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">sd__Observation</td>
<td style="text-align: left;">0.823</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: left;">255.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: left;">263.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: left;">-123.495</td>
</tr>
<tr class="even">
<td style="text-align: left;">REMLcrit</td>
<td style="text-align: left;">246.991</td>
</tr>
</tbody>
</table>
And using `coef_map` would not work

    msummary(fm1, output = "markdown", 
             coef_map = c("sd__(Intercept)" = "sd1"))

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Model 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sd1</td>
<td style="text-align: left;">2.904</td>
</tr>
<tr class="even">
<td style="text-align: left;">sd1</td>
<td style="text-align: left;">1.287</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIC</td>
<td style="text-align: left;">255.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">BIC</td>
<td style="text-align: left;">263.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: left;">-123.495</td>
</tr>
<tr class="even">
<td style="text-align: left;">REMLcrit</td>
<td style="text-align: left;">246.991</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-09-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
I'm not sure what the best approach to handle this is. Maybe have `msummary()` detects the existence of a `group` column when there are duplicated `term` names, and add the `group` column to term? I also tried using a `tidy_custom` function to merge the group and term column, but it results in an error
```
Error in sanity_tidy(est, est_custom, estimate, statistic, class(model)[1]) : 
  Assertion on 'all(tidy_output$term == tidy_custom$term)' failed: Must be TRUE.
```
Thanks for your help in advance.

**Comment by vincentarelbundock** [comment]
Interesting!

Should be easy enough to work around, but what's our rule?

1. Paste together `group` and `terms` for *every* row as soon as there is one duplicate.
2. Paste together only for the duplicates (here: `sd_(Intercept)`)
3. Paste together only where `group != NA` and only if there are duplicates
4. Paste together only where `group != NA` always

**Comment by marklhc** [comment]
I think both 3 and 4 make sense to me as I wan to clearly distinguish between the levels (`sample` and `batch` in the example) for all `ran_pars` effects. I will vote for 3 as it does not add in redundant information for simpler models, but I can also see the value of 4 in giving more consistent behaviors. Either one is good for me. Thanks again for the quick response!

**Comment by vincentarelbundock** [comment]
Cool. I pushed a simple implementation of 4 with this condition:

```r
  # broom.mixed sometimes includes a `group` column with duplicate terms
  if ("group" %in% colnames(est) && anyDuplicated(est$term) > 0) {
    est$term <- ifelse(is.na(est$group), est$term, paste(est$group, est$term))
  }
```

If you have a second, I would appreciate if you could take the latest version out for a spin, maybe with some more complicated models.

Install from Github:

```r
library(remotes)
remotes::install_github('vincentarelbundock/modelsumary')
```

Restart R completely, then try it out.

**Comment by marklhc** [comment]
I just tested it in some other models with duplicated terms and it works. Thank you so much for the quick response and fix!

**Comment by marklhc** [comment]
Hi @vincentarelbundock, I'm reopening the issue as I found out that the current version of `msummary()` no longer prints out the group names for mixed models with multiple levels.

``` r
library(lme4)
#> Loading required package: Matrix
library(broom.mixed)
library(modelsummary)
fm1 <- lmer(strength ~ (1|batch) + (1|sample), Pastes)
msummary(fm1, output = "markdown")
#> Warning in msummary(fm1, output = "markdown"): The table includes duplicate
#> term names. This can happen when `coef_map` or `coef_rename` are misused. This
#> can also happen when a model produces "grouped" terms, such as in multinomial
#> logit or gamlss models. You may want to call `get_estimates(model)` to see
#> how estimates are labelled internally, and use the `group` argument of the
#> `modelsummary` function.
```

|                   | Model 1  |
|:------------------|:--------:|
| (Intercept)       |  60.053  |
|                   | (0.677)  |
| sd\_\_(Intercept) |  1.287   |
|                   |  2.904   |
| sd\_\_Observation |  0.823   |
| AIC               |  255.0   |
| BIC               |  263.4   |
| Log.Lik.          | -123.495 |
| REMLcrit          | 246.991  |

<sup>Created on 2021-10-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Previously it shows `sample sd__(Intercept)` and `batch sd__(Intercept)`. Is it an intentional change made in recent updates, and if so, is there a way I can get the old behavior? Thank you very much. 

Mark

**Comment by vincentarelbundock** [comment]
These models should now be supported out of the box *without* loading `broom.mixed`. (Under the hood, we now use `parameters`, which covers more models). In fact, loading `broom.mixed` can introduce conflicts between methods with the same name. 

I recommend starting a new session *without* `broom.mixed`, and trying again. Perhaps you could then call the `get_estimates` function on your model to see the output.

**Comment by marklhc** [comment]
Thank you Vincent. I tried not loading `broom.mixed` but the results are the same. Here's what I get from `get_estimates()`:

``` r
library(lme4)
#> Loading required package: Matrix
library(modelsummary)
fm1 <- lmer(strength ~ (1|batch) + (1|sample), Pastes)
get_estimates(fm1)
#>                term   estimate std.error conf.level conf.low conf.high
#> 1       (Intercept) 60.0533333   0.67687       0.95 58.72669  61.37997
#> 2    SD (Intercept)  2.9040778        NA       0.95       NA        NA
#> 3    SD (Intercept)  1.2873647        NA       0.95       NA        NA
#> 4 SD (Observations)  0.9074181        NA       0.95       NA        NA
#>   statistic df.error p.value effect    group
#> 1   88.7221       56       0  fixed         
#> 2        NA       NA      NA random   sample
#> 3        NA       NA      NA random    batch
#> 4        NA       NA      NA random Residual
```

<sup>Created on 2021-10-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by marklhc** [comment]
Looks this may solve the problem:

``` r
library(lme4)
#> Loading required package: Matrix
library(modelsummary)
fm1 <- lmer(strength ~ (1|batch) + (1|sample), Pastes)
msummary(fm1, output = "markdown", group = group + term ~ model)
#> Registered S3 methods overwritten by 'parameters':
#>   method                           from      
#>   as.double.parameters_kurtosis    datawizard
#>   as.double.parameters_skewness    datawizard
#>   as.double.parameters_smoothness  datawizard
#>   as.numeric.parameters_kurtosis   datawizard
#>   as.numeric.parameters_skewness   datawizard
#>   as.numeric.parameters_smoothness datawizard
#>   print.parameters_distribution    datawizard
#>   print.parameters_kurtosis        datawizard
#>   print.parameters_skewness        datawizard
#>   summary.parameters_kurtosis      datawizard
#>   summary.parameters_skewness      datawizard
```

|          |                   | Model 1 |
|:---------|:------------------|:-------:|
|          | (Intercept)       | 60.053  |
|          |                   | (0.677) |
| sample   | SD (Intercept)    |  2.904  |
| batch    |                   |  1.287  |
| Residual | SD (Observations) |  0.907  |
|          | Num.Obs.          |   60    |
|          | R2 Marg.          |  0.000  |
|          | R2 Cond.          |  0.937  |
|          | AIC               |  255.0  |
|          | BIC               |  263.4  |
|          | ICC               |   0.9   |
|          | RMSE              |  0.59   |

<sup>Created on 2021-10-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Thanks and I'll update this if I ran into further issues.

**Comment by vincentarelbundock** [comment]
Great!

**Comment by vincentarelbundock** [comment]
Also, nice to see that the error message actually diagnosed the problem and gave the correct solution: use `group`
