### ISSUE TITLE
Missing GoF Names

### ISSUE THREAD

**Issue by volkovacodes** [vincentarelbundock/modelsummary#142]
Thank you for the awesome package!

I am following you example but most GoF names are missing in the output. The names are coded as 3/4/5/6 instead of R2, Adj.R2 etc 

```r
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list()
models[['OLS 1']] <- lm(Donations ~ Literacy + Clergy, data = dat)
models[['Poisson 1']] <- glm(Donations ~ Literacy + Commerce, family = poisson, data = dat)
models[['OLS 2']] <- lm(Crime_pers ~ Literacy + Clergy, data = dat)
models[['Poisson 2']] <- glm(Crime_pers ~ Literacy + Commerce, family = poisson, data = dat)
models[['OLS 3']] <- lm(Crime_prop ~ Literacy + Clergy, data = dat)

modelsummary(models)
```

<img width="502" alt="Screen Shot 2020-09-29 at 21 21 04" src="https://user-images.githubusercontent.com/5629785/94552149-c5fee400-0299-11eb-8686-fbc9e2d080f2.png">

**Comment by vincentarelbundock** [comment]
Thanks for the report!

Unfortunately, I can't replicate it on my computer. When I paste your code, I get the correct names for the GOF statistics.

Would you mind updating the package (and its dependencies) and trying again?

```r
install.packages(c("modelsummary", "dplyr", "kableExtra", "broom"))
```

Then, shut down R completely and start a fresh session. Finally,

```r
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list()
models[['OLS 1']] <- lm(Donations ~ Literacy + Clergy, data = dat)
models[['Poisson 1']] <- glm(Donations ~ Literacy + Commerce, family = poisson, data = dat)
models[['OLS 2']] <- lm(Crime_pers ~ Literacy + Clergy, data = dat)
models[['Poisson 2']] <- glm(Crime_pers ~ Literacy + Commerce, family = poisson, data = dat)
models[['OLS 3']] <- lm(Crime_prop ~ Literacy + Clergy, data = dat)

modelsummary(models)
```

And if that doesn't work, please show me the output of this command:

```r
sessionInfo()
```

**Comment by volkovacodes** [comment]
Good suggestion, updating packages did not help but updating R to 4.0.2 version fixed the issue!
