### ISSUE TITLE
Support of broom::tidy Input

### ISSUE THREAD

**Issue by sammo3182** [vincentarelbundock/modelsummary#143]
`modelsummary` has become my "setup" package esp. when it supports `flextable` outputs and I work on Word manuscript a lot. I also appreciate the author's effort in [supporting diverse types of model outputs](https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html). Yet, there are situations where it's easier to get a tidized summary table of the model outcome than setting up customized `tidy` functions. Given such cases, is it doable to allow `modelsummary` to tabulate broom::tidy outcomes directly? For instance, I have a tibble object with `term`, `estimate`, `std.error` and modelsummary can convert that to a printable table?  I'll appreciate this function very much! Thanks

**Comment by vincentarelbundock** [comment]
This is a very good suggestion!

I implemented a way to do this, by creating a list with elements `tidy` and `glance` (the latter is optional), and by changing the class of that list to "modelsummary_list". Then, `modelsummary` will automatically process it correctly.

Install the latest version from github:

```r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

Restart your R session completely. Then,

```r
library(modelsummary)

mod <- list(
  tidy = data.frame(term = c("a", "b"),
                    estimate = 1:2,
                    std.error = 2:3),
  glance = data.frame(test = "abc")
)
class(mod) <- "modelsummary_list"

modelsummary(mod)
```

**Comment by sammo3182** [comment]
Ahh, that looks straightforward! How about multiple models?

**Comment by vincentarelbundock** [comment]
good. then you just need a list of `modelsummary_list` objects. A list of list. Which you can name as usual to label the oclumns.
