### ISSUE TITLE
Presentation of the histogram

### ISSUE THREAD

**Issue by sammo3182** [vincentarelbundock/modelsummary#151]
One striking function of `datasummary` is the histogram and it can be presented in different types of outputs---how amazing is that! However, the histogram seems not always to produce the correct result, esp. when the variable is skewed. See the example following

```r
df_example <- readRDS("example.Rds")
hist(df_example$x)
datasummary(All(df_example) ~ Mean + SD + Min + Max + Histogram, data = df_example)
```

Here's the output of the `hist`

![Rplot](https://user-images.githubusercontent.com/6463211/96356334-76386d80-111f-11eb-8642-8247672412a6.png)

And here's the output of `datasummary`

![Rplot01](https://user-images.githubusercontent.com/6463211/96356337-79cbf480-111f-11eb-80b3-2faa059fd4c1.png)

I tried to alter the number of bins by `Histogram*Arguments(bins = 100)`. Nothing changed. 

Here's the example data.
[example.zip](https://github.com/vincentarelbundock/modelsummary/files/5396914/example.zip)

**Comment by vincentarelbundock** [comment]
Histograms using unicode characters turn out to be extremely unreliable. They depend on the typeface used for display, on the locale, and on the platform (Windows vs. Mac vs. Linux). See for example all the discussions on the `skimr` package github. It is simply a pain to support, and there is never guarantees of correct result.

In the most recent version of `modelsummary`, the `datasummary_skim` function no longer uses the `Histogram` function. Instead, it uses the `spec_hist` function from the `kableExtra` package. This function produces tiny SVG images directly from the `hist` function. In my experience, this is much more reliable, and I recommend you use that instead.

Please see the other issue you opened for an example of how to use that.

**Comment by vincentarelbundock** [comment]
Also, I think that the example you gave is technically correct. The issue is that unicode characters only have 5 or 6 different heights of bars. So if there is a massive difference between your highest bar and your lowest bar, the unicode histogram will basically only show you one bar.

Again, this is not a problem with the SVG histogram of `kableExtra`, because it is not constrained to have only a limited number of heights for the bars.

**Comment by vincentarelbundock** [comment]
I now explain these issues in the documentation for the `Histogram` function: f656dd7

**Comment by sammo3182** [comment]
Thank you for the quick response. I actually noticed the difference between `datasummary` and `datasummary_skim`. My issue is that I need to twist the formula a little bit (e.g., adding a column of `Ncol`). Also, it looks like when the output format is "flextable", the histogram disappeared, correct? I used `flextable` format for a Word output. Your package is the only one (as I know) so far that can produce a decent word output regression table...

**Comment by vincentarelbundock** [comment]
In principle, the unicode histogram should work in Word if you use a font/typeface that supports the unicode characters in question (e.g., Deja Vu). But it won't work with all fonts. Obviously, the `kableExtra` functions won't work in `flextable`.

**Comment by sammo3182** [comment]
Make sense. I'll see if there're other ways around. Meanwhile, I'll appreciate if the unicode version of histogram could remain in the `datasummary` at least as an option. It'll be very impressive to embed such a plot in the descriptive table. Thank you again for the function! The package is AMAZING!
