### ISSUE TITLE
`datasummary_df` fails if columns are not numeric

### ISSUE THREAD

**Issue by eliocamp** [vincentarelbundock/modelsummary#152]
I don't know if this is is how this function is supposed to be used, but when I try to show a table with non-numeric columns, `datasummary_df` fails with error:

``` r
data <- data.frame(group = letters[1:3], 
                   value = c(1:3))

modelsummary::datasummary_df(data)
#> Error in sprintf(fmt, data[[n]]): invalid format '%.2f'; use format %s for character objects
```

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The issue is here, where it applies `format` to all columns.

```r
  for (n in colnames(data)) {
    data[[n]] <- sprintf(fmt, data[[n]])
  }
```

Perhaps it should read something like this?

```r
  for (n in colnames(data)) {
    if (is.numeric(data[[n]]) {
        data[[n]] <- sprintf(fmt, data[[n]])
    }
  }
```

**Comment by vincentarelbundock** [comment]
I think this is related to a different issue I encountered with rounding. Using the development version of `modelsummary`, your example works fine on my computer. Could you install that and try again?

To install the development version of `modelsummary`:

```r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

Then restart your R session completely to make sure that the changes take effect.

**Comment by eliocamp** [comment]
Yes, the dev version works. Thanks.
