### ISSUE TITLE
coef_omit does not support Perl regex

### ISSUE THREAD

**Issue by Asquidy** [vincentarelbundock/modelsummary#154]
Hi, would it be possible to change the grepl function used for coef_omit and gof_omit to have the option grepl(, perl = T)? In general, it is kind of tricky to keep specific coefficients in the current interface. Thanks so much for the great package!

**Comment by vincentarelbundock** [comment]
Happy to consider it. What specific pattern would that allow that we can't use right now? And if I were to change to `perl=TRUE` by default, how likely is it to break people's existing code?

**Comment by Asquidy** [comment]
It would allow for lookahead and lookbacks such as below. I don't know for sure if it would break people's code, but my I think it's unlikely.
` 
coef_names <- c("(Intercept)", "third_party", "any_treatment", "old_job", "third_party:any_treatment", "any_treatment:old_job" )
grepl('^(?!.*treatment).*', coef_names, perl = T)
`

**Comment by vincentarelbundock** [comment]
lookback/ahead definitely sound like useful features. I also can't think of many cases where this would create backward compatibility issues, so I changed the default to `perl=TRUE` in commit 4aad3cb.

Not sure when the next CRAN release will be, but in the meantime you can install the devel version from github: 

```r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

Then restart your R session completely to make sure that the changes take effect. Then, you should be able to omit every coefficient with "vs", *except* those preceded by "mpg":

    library(modelsummary)
    mod <- lm(hp ~ mpg * vs, mtcars)
    modelsummary(mod, 
                 coef_omit="^(?!mpg).*vs",
                 output="data.frame")
    #> # A tibble: 13 x 4
    #>    group     term          statistic    `Model 1`
    #>    <chr>     <chr>         <chr>        <chr>    
    #>  1 estimates "(Intercept)" "estimate"   357.979  
    #>  2 estimates ""            "statistic1" (40.223) 
    #>  3 estimates "mpg"         "estimate"   -10.126  
    #>  4 estimates ""            "statistic1" (2.361)  
    #>  5 estimates "mpg × vs"    "estimate"   6.866    
    #>  6 estimates ""            "statistic1" (3.055)  
    #>  7 gof       "Num.Obs."    ""           32       
    #>  8 gof       "R2"          ""           0.729    
    #>  9 gof       "R2 Adj."     ""           0.699    
    #> 10 gof       "AIC"         ""           328.6    
    #> 11 gof       "BIC"         ""           336.0    
    #> 12 gof       "Log.Lik."    ""           -159.321 
    #> 13 gof       "F"           ""           25.053

**Comment by vincentarelbundock** [comment]
thanks for the suggestion!
