### ISSUE TITLE
Rename variables

### ISSUE THREAD

**Issue by hhsievertsen** [vincentarelbundock/modelsummary#159]
Hi, 
thanks for a great tool! One question/request.

I am running

`
models<-list(
"OLS"<-felm(y~x1+x2+d|0|0|0,data=mydata)
"IV"   <-felm(y~x1+x2|0|(d~z)|0,data=mydata)
)
modelsummary(models)
`

However,  I want the coefficient on _d_ to be shown in the same line. I therefore tried to rename it
`
IV<-felm(y~x1+x2|0|(d~z)|0,data=mydata)
rownames(IV$coefficients)[rownames(IV$coefficients)=='`d(fit)`']<-'d'
rownames(IV$beta)[rownames(IV$beta)=='`d(fit)`']<-'d'
model<-list(
"OLS"<-felm(y~x1+x2+d|0|0|0,data=mydata)
"IV"   <-IV
)
modelsummary(models
`
`

But that leads to "NA"s in the d row. Any suggestions? Sorry if I missed it.
Hans

**Comment by vincentarelbundock** [comment]
You can use `coef_map` to rename your coefficients. For example,

```r
library(modelsummary)

models <- list(
  lm(hp ~ drat, mtcars),
  lm(hp ~ vs, mtcars)
)

modelsummary(models, coef_map=c("drat"="same", "vs"="same"))
```

**Comment by hhsievertsen** [comment]
Hi,
Brilliant. I went for `coef_map`. Works well! I had used it, but didn't realise that I could rename two variables to the same name. Apologies. 

Thanks so much. 
Hans
