### ISSUE TITLE
Support for margins()

### ISSUE THREAD

**Issue by hhsievertsen** [vincentarelbundock/modelsummary#160]
Hi,

apologies if I (also) overlooked this. But is there a way to include marginal effects from `margins()`  in a regression table created with `modelsummary()`?
Thanks

Hans

**Comment by vincentarelbundock** [comment]
The development version of `broom` on github supports margins, so `modelplot` does too if you install devel `broom`.

**Comment by hhsievertsen** [comment]
Brilliant. That works. Thanks!
