### ISSUE TITLE
N should return an integer or be formattable

### ISSUE THREAD

**Issue by willwheels** [vincentarelbundock/modelsummary#162]
I'm very much enjoying this package, but am stuck on something. From the examples:

``` r
library(modelsummary)
url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv'
penguins <- read.csv(url)
datasummary(species * sex + 1 ~ (N = 1) + Percent(),
            data = penguins, 
            output = 'markdown')
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">species</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adelie</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">73.00</td>
<td style="text-align: right;">21.22</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">73.00</td>
<td style="text-align: right;">21.22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chinstrap</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">34.00</td>
<td style="text-align: right;">9.88</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">34.00</td>
<td style="text-align: right;">9.88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gentoo</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">58.00</td>
<td style="text-align: right;">16.86</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">61.00</td>
<td style="text-align: right;">17.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">All</td>
<td style="text-align: right;">344.00</td>
<td style="text-align: right;">100.00</td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Since N is an integer, I'd like to display with no decimals. Could that be the default? I did try to format it with various calls to Format and Arguments, but nothing I tried worked. 

Thanks,

Will

**Comment by vincentarelbundock** [comment]
Does that work for you?

```r
library(modelsummary)
url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv'
penguins <- read.csv(url)
datasummary(species * sex + 1 ~ (N = 1)*Format(digits=0) + Percent(),
            data = penguins, 
            output = 'markdown')
```

**Comment by vincentarelbundock** [comment]
I'll try to think about a more intuitive default, but this is a surprisingly subtle challenge with behind the scenes interactions with the `tables` package.

**Comment by willwheels** [comment]
The fix works great, thank you (and for the quick reply).

I can’t deduce from my history how I mis-used Format before.

And yes, I totally get that working across packages can be hard.

Thanks again,

Will

___________________
Will Wheeler, Economist
U.S. EPA, Office of Policy
National Center for Environmental Economics
202-566-2264

**Comment by vincentarelbundock** [comment]
FYI, the Github version now includes a `N` function which you can just use as follows:

```r
datasummary(species * sex ~ N + Percent(),
            data = penguins, 
            output = 'markdown')
```
