### ISSUE TITLE
datasummary_skim categorical

### ISSUE THREAD

**Issue by gbekes** [vincentarelbundock/modelsummary#164]
This is about how datasummary treats **categorical** variables

I think when we have categorical variable with many levels, say, nationality, it should still offer informative review.

1. It should report N of obs, N unique and N missing just like for numerical. Missing could be NA, or simply "", I guess. 
Thus, it should not report an error when missing 
`  datasummary_skim dropped a categorical variable because it was entirely NA.`

2. It should not drop a variable because it has too many levels. 
 `datasummary_skim dropped a categorical variable because it contained more than 20 levels.`

If N=20 is the cutoff, I'd suggest it to report 19 most frequent values and say Other values (N-19) leves: X X%

**Comment by vincentarelbundock** [comment]
This is a very interesting idea, and I would like to do it eventually. Unfortunately, I looked over my code again, and I think it would be quite a lot of work to implement (because of uninteresting code-related details). I will try to get to it at some point, but my day job keeps me quite busy these days, so I can't promise a quick turnaround.

As always, thanks for the useful suggestions.

**Comment by gbekes** [comment]
Sure. Appreciated. 

I think 2) could be more important in the sense, that if one misses the warnings, they would look for those vars and wonder what happened (they = me this morning...)

**Comment by gbekes** [comment]
Sorry, coming back to this. As R produces tons of warnings, most of them I disregard, it would be useful to display something on the viewer window re factor vars w many values. It even could be a single line at the end. 

birth_country | **20+ values** | - | -|

cheers

**Comment by vincentarelbundock** [comment]
I thought about this some more and considered several options. In the end, the two main options I considered were:

(1) Adding a note to the bottom of the table automatically. Decided not to do this because I couldn't think of a good mechanisms for users to control whether or not this would be added to the notes, and because I don't like automagically changing a user-supplied argument on the fly. They should have control over what they are given control over.

(2) Substituting something in the table itself. I tried this, but for boring code-related reasons, it is actually quite a bit harder than I thought it would be.

With respect to the warnings, I see this as kind of a philosophical point: In principle, I think it is a bad idea to ignore warnings. Moreover, giving warnings using the `warning` function is the idiomatic way to pass those kinds of messages in R. So it makes sense for `modelsummary` to use that standard infrastructure.

That said, in the previous version, `modelsummary` would print one warning per variable it dropped. This resulted in R combining all those warnings, and required the user to call `warnings()` explicitly in order to read them. I made a small tweak to make sure that only a single warning is printed when variables are dropped. That way, the full text should be displayed immediately in your console. That should be easier to read.

Sorry I can't give you all you want here! I may eventually improve this function, but it would require a much bigger refactor than I have time for now.

**Comment by gbekes** [comment]
Yes, okay, thanks!

*Let me do stg uncool, and respond to a closed issue...*

I still think this is a major issue, tbh, no disrespect:-)

I go
```
datasummary_skim(data_with_many_cols, type="categorical")
```
and get
```
Warning messages:
1: In datasummary_skim_categorical(data, output = output, fmt = fmt,  :
  datasummary_skim dropped a categorical variable because it contained more than 20 levels.
2: In datasummary_skim_categorical(data, output = output, fmt = fmt,  :
  datasummary_skim dropped a categorical variable because it was entirely NA.
3: In datasummary_skim_categorical(data, output = output, fmt = fmt,  :
  datasummary_skim dropped a categorical variable because it contained more than 20 levels.
4: In datasummary_skim_categorical(data, output = output, fmt = fmt,  :
  datasummary_skim dropped a categorical variable because it was entirely NA.
```
So I don't even know which is which.
 
I think for a summary, the key bits are count of non-missing, missing, N/A, and unique. They are all available for numeric and categorical or even string and date..

`Hmisc::describe()` can do a quick review, it just looks hard to read. What I like in Stata's `codebook` is that is really flexible in presenting simple stuff in a nice way

-------------------------------------------------------------------------------------------------------------------
owner                                                                                      
-------------------------------------------------------------------------------------------------------------------

                  type:  numeric (byte)
                 label:  owner

                 range:  [1,2]                        units:  1
         unique values:  2                        missing .:  0/3,466

            tabulation:  Freq.   Numeric  Label
                         2,561         1  Domestic
                           905         2  Have foreign

-------------------------------------------------------------------------------------------------------------------
buyer_number_2015                                                 
-------------------------------------------------------------------------------------------------------------------

                  type:  numeric (int)

                 range:  [0,9999]                     units:  1
         unique values:  155                      missing .:  0/3,466

                  mean:   162.315
              std. dev:   546.286

           percentiles:        10%       25%       50%       75%       90%
                               5        10        33       100       300

. 
 -------------------------------------------------------------------------------------------------------------------
country_code                                                                                  
-------------------------------------------------------------------------------------------------------------------

                  type:  string (str2)

         unique values:  3                        missing "":  0/3,466

            tabulation:  Freq.  Value
                         1,203  "HU"
                         1,290  "RO"
                           973  "SK"

. 
-------------------------------------------------------------------------------------------------------------------
b_standard_city_2015                                                                                    
-------------------------------------------------------------------------------------------------------------------

                  type:  string (str40), but longest is str31

         unique values:  1,147                    missing "":  386/3,466

              examples:  "BRATISLAVA"
                         "FONTANAFREDDA"
                         "NEHOIU"
                         "SOPRON"

               warning:  variable has embedded blanks

**Comment by vincentarelbundock** [comment]
@gbekes could you please clarify what you need?

If I improve the warning messages to give a list of variables that were actually omitted, would it help? See this for example:

``` r
library(modelsummary)

dat = data.frame(
  x0 = factor(sample(1:5, 100, replace=TRUE)),
  x1 = sample(letters[1:3], 100, replace=TRUE),
  x2 = sample(letters, 100, replace=TRUE),
  x3 = sample(letters, 100, replace=TRUE),
  x4 = NA,
  x5 = NA)

datasummary_skim(dat, type="categorical", output="markdown")

#> Warning in datasummary_skim_categorical(data, output = output, fmt = fmt, :
#> These variables were omitted because they include more than 20 levels: x2, x3.

#> Warning in datasummary_skim_categorical(data, output = output, fmt = fmt, :
#> These variables were omitted because they are entirely missing: x4, x5.
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th style="text-align: right;">N</th>
<th style="text-align: right;">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">x0</td>
<td style="text-align: left;">1</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">20.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">3</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">19.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">18.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">5</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">18.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: left;">a</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">41.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">b</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">33.0</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">c</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">26.0</td>
</tr>
</tbody>
</table>

**Comment by gbekes** [comment]
Yes, actually, thanks! (and sorry for bother...)

The rest is kinda long term issues. 
I mean when I skim thru data, I wanna see what codebook shows: 
* missing, unique, N/A for *all* variables in some way 
* some key stats for numeric
* list/tabulation when only few values
* examples when string/categorical w many values

And having the small histogram is then the massive bonus. 

But again, maybe me being used to Stata is what's up. 

Cheers!
