### ISSUE TITLE
datasummary_skim data table overview

### ISSUE THREAD

**Issue by gbekes** [vincentarelbundock/modelsummary#165]
Just an idea. 

It would be useful for datasummary_skim to start by producing a small table on the data table. 
* Number of observations (rows)
* Number of variables (columns)
* Coverage = share of missing or empty cells (total missing / rows*columns)
* N of numerical and N of categorical variables

It could be super useful when you restart working with a dataset. Or when a new dataset is created after a bunch of joins.

**Comment by vincentarelbundock** [comment]
Good idea. Try this with the new Github version:

```r
library(palmerpenguins)
library(modelsummary)
datasummary_skim(penguins, 
                 type="dataset", 
                 title="The famous Palmer penguins")
```

**Comment by gbekes** [comment]
Super! Thanks!

two minor points

1. variable type Date is missing (I did not try boolean)
2. % Missing --> % Missing cell -- maybe easier to understand

**Comment by vincentarelbundock** [comment]
What function would you recommend to identify date column? My sense is that there are multiple possible date types, and I'm not sure how to recognize them all.

**Comment by gbekes** [comment]
would not
= col_datetime() - any format
be enough?


Vincent Arel-Bundock <notifications@github.com> ezt írta (időpont: 2020.
nov. 13., Pén 16:55):

**Comment by vincentarelbundock** [comment]
What package is that function from? I don't think `modelsummary` loads it currently.

**Comment by gbekes** [comment]
Sry, I mean read_csv would parse and report like

dateofbirth = col_datetime(format = ""),
  national_name = col_character(),

etc

**Comment by vincentarelbundock** [comment]
OK, but `read_csv` is a text parser, so that doesn't really help me figure out column types for an existing data.frame (i.e., already read from text), because different text readers will convert to different date formats, and there isn't a `is.date` function in R like there is an `is.factor`, because there isn't a single date type (but I'm far from an expert in time series stuff).

Will think about it.

**Comment by gbekes** [comment]
Got it, although I did create some with as.Date. But true, when I check the
raw data, it say POSIXct.

But i am terrible with dates, always have to look up *everything*, both in
Stata (which I have used for a decade) and R....

**Comment by vincentarelbundock** [comment]
I barely know what day it is :)
