### ISSUE TITLE
datasummary: adding N + Tufte style

### ISSUE THREAD

**Issue by gbekes** [vincentarelbundock/modelsummary#167]
Hi, this is regarding making a descriptive table with N.

I think displaying the number of observation should be front and center in most descriptive tables, and hence, it should be somehow easier / more defaultish. 

### Adding N
1a. Adding N of obs should be somehow easier and neater than with the (N=1) trick. .(*)

1b Maybe I'm doing stg wrong, but cannot make N=x without decimals (which should be the default), tried Arguments() but may not well, adapting from the otherwise fab [vignette](https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#rounding-1)

## Tufte Format
2a. It would be nice to have a tufte style table such as(**)  Table 13 in the  [Stata tabout tutorial](https://www.ianwatson.com.au/stata/tabout_tutorial.pdf), where (n=x) would part of the variable label.

2b or even have % instead of n, like in Table 12.

Thanks!!!
_____________________

(*) Maybe it is, already
(**) pls don't hate me for bringing in Stata...

**Comment by vincentarelbundock** [comment]
Stata is great, actually!

You can round the N by:

```r
library(modelsummary)
library(palmerpenguins)
datasummary(species ~ (N=1)*Format() + Mean*flipper_length_mm, penguins)
```
I'll try to think of a cleaner solution and/or document this one better, but for boring reasons having to do with the inner-workings of the `tables` package, this is non-trivial.

Table 13 looks a lot like the `datasummary_balance` output. All you would need to do would be to change the values of your character/factor variable to include (n=???) after the label. Just calculate it separately and paste it on.

**Comment by gbekes** [comment]
Thanks, `*Format()` works, so here just adding a line, and showing this is default would be perfect (i mean N=176.00 is brrrrrr) :-)

**Comment by vincentarelbundock** [comment]
Cool. And what I meant for the labels is something like this:

```r
library(tidyverse)
library(modelsummary)
library(palmerpenguins)

table(penguins$species)

penguins <- penguins %>%
  mutate(species = case_when(species == "Adelie" ~ "Adeline (n=152)",
                             species == "Chinstrap" ~ "Adeline (n=68)",
                             species == "Gentoo" ~ "Gentoo (n=124)"))

datasummary_balance(~island, penguins)
```

![screenshot_20201123-095531](https://user-images.githubusercontent.com/987057/99977006-267a4100-2d72-11eb-9a5d-a8b93167853f.png)

**Comment by gbekes** [comment]
Yes, I will check the _balance bit. 

I mean this is not super practical when you have dozens of types. Like you have hundreds of observation per country, and two dozen countries (like world value survey). So you have two vars, and would have stg like automatically 

| country              | Region        |  mean inc | mean value  |
|-------------------|-------------|-------------| --------------| 
| France (n=500) |  EU              |57 000        | 4.76              |
| Canada (n=720) | N. Am       | 62 000        | 4.96              |

But I am happy having N in a simple way! Thanks

**Comment by vincentarelbundock** [comment]
FYI, I added a `N` function, so you can now do stuff like this:

https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#counts-and-percentages-1
