### ISSUE TITLE
datasummary_balance - adjust for covariate

### ISSUE THREAD

**Issue by akarlinsky** [vincentarelbundock/modelsummary#168]
I want to produce a "Table 1" of my study, but I know that the age distribution differs between control and treatment. I would thus like to see the means of various variables of interest (and the differences), after adjusting for age. 

Manually, I would achieve this by regressing each y on group and age, and then the coefficient of group is the age adjusted difference in means of y.

Unfortunately, the datasummary_balance "only accepts a single right hand side variable of type factor...". so I can't do it easily and automatically for many variables. Can this feature be added somehow? Thank you!

**Comment by vincentarelbundock** [comment]
What if you replaced each column in your dataset by the residuals of the `y~age` regression? The difference in means between residuals in your two groups would be calculated automatically by `datasummary_balance` and should be pretty close to the coefficient you describe, no?

``` r
N = 100000
group = sample(0:1, N, replace=TRUE)
z = rnorm(N)
y = group + 2 * z + rnorm(N)

coef(lm(y ~ group + z))
#> (Intercept)       group           z 
#> 0.001439743 1.001705705 1.999517597

e = resid(lm(y ~ z))
mean(e[group == 1]) - mean(e[group == 0])
#> [1] 1.001705
```

**Comment by akarlinsky** [comment]
Yes, but that means I need to automate the above process as well. I could of course write some function to do it for me, but it is still a bit tedious - and post-covariate adjusted balance tables are pretty common I think.

**Comment by vincentarelbundock** [comment]
Hmmm, I have to admit that I'm not fully convinced. Let's say you want to print a `datasummary_balance` table of the `mtcars` dataset with each variable adjusted by `mpg` and the `vs` as treatment. Then all you would have to do is something like this:

```r
library(modelsummary)

for (n in names(mtcars)) {
  if (!n %in% c("mpg", "vs")) {
    mtcars[[n]] <- residuals(lm(formula(paste(n, "~mpg")), mtcars))
  }
}

datasummary_balance(~vs, mtcars)
```

One of the overriding principles in the design of `modelsummary` is that I want to keep things as simple as possible (I often fail). The main way to do this is to limit the number of arguments to functions. If something is very difficult to implement for end users and also very often used, then I'll be happy to implement. I'm just not sure this is the case here.

Note that *I am not sure* either way. I'll think about it a bit more and leave this issue open. Maybe somebody else will chyme in at some point.;

Thanks for the suggestion and for trying out `modelsummary`. I really appreciate it!

**Comment by akarlinsky** [comment]
Thanks! I had to slightly adjust the code due to NAs, and create a temporary "residualized" dataframe to avoid data loss, and also add back the mean so that the mean in each group would make sense - But this got me very close to what I needed, and I understand not wanting to complicate the core function further.

If you want, the issue can be closed :)
