### ISSUE TITLE
Allow flexible float position

### ISSUE THREAD

**Issue by gregmacfarlane** [vincentarelbundock/modelsummary#169]
The default behavior for LaTeX output is to put the output table in a very strict `H` float environment. This is often not desirable.

``` r
library(modelsummary)
#> Warning: package 'modelsummary' was built under R version 4.0.2
f <- hp + mpg ~ Mean + SD
print(datasummary(f, data = mtcars, output = 'latex'))
#> \begin{table}[H]
#> \centering
#> \begin{tabular}[t]{lrr}
#> \toprule
#>   & Mean & SD\\
#> \midrule
#> hp & 146.69 & 68.56\\
#> mpg & 20.09 & 6.03\\
#> \bottomrule
#> \end{tabular}
#> \end{table}
```

<sup>Created on 2020-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The `datasummary` and related functions do not seem to expose the `"position"` argument to `kableExtra::kable_styling`. Is this correct? Is this recommended behavior?

**Comment by gregmacfarlane** [comment]
I did a bit more investigating. It seems as though the behavior of `kableExtra` and `latex` output changes based on whether you set a table caption / title. By default, it will place the table in the strict `H` float, and further attempts to change it are not possible.  But if you add a title, then you can use the `kable_styling` argument to loosen it up (or just leave it alone!)

``` r
library(modelsummary)
#> Warning: package 'modelsummary' was built under R version 4.0.2
library(kableExtra)
#> Warning: package 'kableExtra' was built under R version 4.0.2
f <- hp + mpg ~ Mean + SD

# why use the "H" environment?
datasummary(f, data = mtcars, output = 'latex') %>%
    print()
#> \begin{table}[H]
#> \centering
#> \begin{tabular}[t]{lrr}
#> \toprule
#>   & Mean & SD\\
#> \midrule
#> hp & 146.69 & 68.56\\
#> mpg & 20.09 & 6.03\\
#> \bottomrule
#> \end{tabular}
#> \end{table}

# adding latex options just wraps a second environment!
datasummary(f, data = mtcars, output = 'latex') %>%
    kable_styling(latex_options = c("hold_position")) %>%
    print()
#> \begin{table}[!h]
#> \centering\begin{table}[H]
#> \centering
#> \begin{tabular}[t]{lrr}
#> \toprule
#>   & Mean & SD\\
#> \midrule
#> hp & 146.69 & 68.56\\
#> mpg & 20.09 & 6.03\\
#> \bottomrule
#> \end{tabular}
#> \end{table}
#> \end{table}

# but adding a caption turns this off: weird!
datasummary(f, data = mtcars, title = "my table", output = "latex") %>%
    kable_styling(latex_options = c("hold_position")) %>%
    print()
#> \begin{table}[!h]
#> 
#> \caption{\label{tab:reprex-body}my table}
#> \centering
#> \begin{tabular}[t]{lrr}
#> \toprule
#>   & Mean & SD\\
#> \midrule
#> hp & 146.69 & 68.56\\
#> mpg & 20.09 & 6.03\\
#> \bottomrule
#> \end{tabular}
#> \end{table}
```

<sup>Created on 2020-11-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Again, this may not be undesired behavior, or something that has to be fixed in the kableExtra package. It was just strange for me to get something out that cannot be further mutated, and that went with the strictest option possible.

**Comment by vincentarelbundock** [comment]
That's interesting, thanks for the report!

It looks like a weird inconsistency upstream in `kableExtra`. I opened an issue on their repo: https://github.com/haozhu233/kableExtra/issues/568

**Comment by vincentarelbundock** [comment]
thanks!
