### ISSUE TITLE
deprecate statistic_vertical

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#178]
statistic_vertical=FALSE is replaced by glue syntax
statistic=NULL omits it completely

**Comment by mplessz** [comment]
Hello
Great package, thanks for developing it.
I am trying to use the option `statistic = NULL` and I get this error. Here is a reproducible example: 
```
data(mpg) 
lm(mpg ~ wt + cyl, data = mtcars ) %>% 
 modelsummary(statistic = NULL)
```
I receive the following error message : 
```
Error in sanity_statistic(statistic, statistic_override, statistic_vertical,  :   Assertion 
on 'statistic' failed: Must be of type 'character', not 'NULL'.
```
Other options (such as `statistic = 'p.value'`) work fine.
`statistic_vertical` still allows me to display a statistic beside the coef.

Thanks again

**Comment by vincentarelbundock** [comment]
Hi, thanks for trying out `modelsummary`.

Could you please reinstall from Github, restart R completely, and try again?

```r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

The fixed version is on its way to CRAN, so it should be available to everyone in the next couple days, but the Github development version should work now (it does on my computer).

**Comment by mplessz** [comment]
Hello
I just tried, and this is what I get : 
```
> library(modelsummary)
> packageVersion("modelsummary")
[1] ‘0.6.3’
> data(mtcars) 
> lm(mpg ~ wt + cyl, data = mtcars ) %>% modelsummary(statistic = NULL)
Error in sanity_statistic(statistic, statistic_override, statistic_vertical,  : 
  Assertion on 'statistic' failed: Must be of type 'character', not 'NULL'.
```
If it means that the fixed version is not available yet, I can wait :-)

**Comment by vincentarelbundock** [comment]
Looks like something went wrong in the installation. The current version on Github is 0.6.4. Are you sure you restarted R completely after installing?

**Comment by vincentarelbundock** [comment]
Make sure you run the `install_github` command I pasted above, and then restart R

**Comment by mplessz** [comment]
Hi,
you are right. This time I closed my current Rproject before running your command lines (in an new R session), and now I do have version 0.6.4 installed. and the option `statistic = NULL` works fine.
Thank you for your patience.

**Comment by vincentarelbundock** [comment]
Excellent news!

**Comment by ChrisWaloszek** [comment]
For anyone else trying to adjust the positioning to have _estimate_, _signif.stars_ & _p-value_ in a single line:

    # Formerly: 
    msummary(mod, 
             statistic_vertical=FALSE,
             statistic = 'p.value',
             stars = TRUE
    )
    
    # Due to the change in syntax it now becomes:
    msummary(mod, 
             estimate = "{estimate} {stars} ({p.value})",
             statistic = NULL,
             stars = TRUE
             )

**Comment by vincentarelbundock** [comment]
Yeah, that new syntax is really powerful. I documented something like what you are suggesting here:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#estimate-1
