### ISSUE TITLE
  object 'N' not found

### ISSUE THREAD

**Issue by bellabuchanan** [vincentarelbundock/modelsummary#179]
object 'N' not found when using datasummary(species * sex + 1 ~ N + Percent(),
            data = penguins)

**Comment by vincentarelbundock** [comment]
Could you please the Github version of the software?

```r
library(remotes)
remotes::install_github("vincentarelbundock/modelsummary")
```

Restart R and try again.

**Comment by bellabuchanan** [comment]
Using (n=1) instead of N solved it but yes will try that!

**Comment by vincentarelbundock** [comment]
Great!

**Comment by bellabuchanan** [comment]
That worked, thank you! While I'm here do you know to embed the "scale_down" latex option with datasummary? Normally for kable I would use kable_styling(latex_options = c("striped", "scale_down")) but struggling to add this to datasummary. Needing to reduce the size of a table :)

**Comment by vincentarelbundock** [comment]
Does this work?

```r
library(modelsummary)
library(kableExtra)
mod <- lm(hp~mpg, mtcars)
modelsummary(mod, "latex") %>%
  kable_styling(latex_options=c("striped", "scale_down"))
```

**Comment by bellabuchanan** [comment]
ah yes, think I had not loaded kableExtra at first. Thank you for your help!
