### ISSUE TITLE
Referencing, labelling, and numbering the tables.

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#18]
Probably needs a `knit_latex` function which will be deprecated once `as_latex` is more feature complete.

**Comment by sammo3182** [comment]
`gtsummary` still can't produce referable table, right? I saw your push in https://github.com/rstudio/gt/pull/143#issuecomment-457834487. It looks great at least for LaTex. Once that gets merged, will `gtsummary` automatically have the function to include labelling, too? 

Also for now, is there any work-around solution other than switching to `texreg` or `huxtable` (esp. for html)? I thought about creating an empty `kable` with a referable title right above the `gtsummary` table, but the output doesn't look good.

**Comment by vincentarelbundock** [comment]
@sammo3182 

Eventually, the best solution will indeed be for this to be improved upstream in the `gt` package.

Until then, you can use the `knit_latex` function for PDF output, as described here: https://github.com/vincentarelbundock/gtsummary#dynamic-documents-with-knitr

I would love to implement a similar workaround for HTML until a better fix is implemented upstream. How does it work with `huxtable` or `texreg`? As far as I can tell, the `texreg::htmlreg` function does not have a `label` argument, so my assumption is that it can't pick up on `bookdown` tags either.

If you give me replicable example of a bookdown with numbered html tables produced by something other than `kable`, I'll implement something very quickly.

Unfortunately, there's a lot of magic underneath `kable`, and I'm not sure the mechnanism that it uses can be transferred to `gtsummary`, so I'd need to find an example elsewhere.

**Comment by sammo3182** [comment]
No, `texreg` does not have an argument of `label`. But it can create citable titble by adding the tab manually, e.g., `caption = "(\\#tab:texreg) Title Created by texreg"`. See an example attached. I tried the same trick with `gtsummary`. Unfortunately, it doesn't work (also see the attached example). 

[table-label-issue.zip](https://github.com/vincentarelbundock/gtsummary/files/2849967/table-label-issue.zip)

Ideally, I hope `gt` and `gtsummary` could help me produce pretty formated and traceble tables for `bookdown::word_document2`. You know, not every journal like AJPS or JOP accepting Latex manuscripts. Especially, some journals in regional studies and interdiscipline journals prefer `docx` file than anything else. But, so far, I haven't find any package enabling producing tracable tables in word-rmarkdown files---except for `knitr::kable`. My current strategy is to produce html and convert it into word, as many online sources suggest. Please let me know if you know any package or a better way to do this. I'll appreciate it so very much.

**Comment by vincentarelbundock** [comment]
I'm sure I could figure out how to hack this, but the truth is the solution is going to be much better if it is purposeful. I'm actively trying to get this sorted in upstream, and we will certainly have a true solution in the short term.

Stay tuned!

**Comment by vincentarelbundock** [comment]
@sammo3182 I just pushed a major update to `modelsummary`. It has now much more robust support for referencing, and tables in LaTeX no longer need to use the hackish `clean_latex` function.

I'd be very grateful if you could try something like this in an `Rmarkdown` document or in a LaTeX document:

```r
library(remotes)
install_github('vincentarelbundock/modelsummary')

library(modelsummary)
models <- list()
models[[1]] <- lm(mpg ~ cyl, mtcars)
models[[2]] <- lm(mpg ~ cyl + drat, mtcars)
msummary(models, output = 'latex', title = 'Title with label \\label{testlabel}')
```

Then, in your main document, you can simply call `\ref{testlabel}` to reference a table.
