### ISSUE TITLE
`statistic_override` -> `vcov`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#184]
Initially suggested here: https://github.com/vincentarelbundock/modelsummary/issues/183

Pros:

* `statistic_override` is long
* `statistic_override` is ugly
* `statistic_override` is unintuitive

Cons:

* backward compatibility (could soften the transition by peeking at `...`)
* makes clear that the argument being modified is `statistic`
* `statistic_override` is a general mechanism. It can be used to include whatever, not just `vcov`-related stuff.

Alternative I don't like: `se_type` (because it is too narrow).

**Comment by NickCH-K** [comment]
Obviously I am for it!

Question about the general-mechanism issue - I can see how `statistic` can do all sorts of non-`vcov` things, but unless I'm missing something in `modelsummary:::extract_statistic_override`, doesn't `statistic_override` just determine how `sandwich` is called? What kind of non-`vcov` things can it be used with?

A name that wouldn't imply `vcov` might be `adjust` but that's probably too vague.

**Comment by vincentarelbundock** [comment]
You're obviously right that the most common use-case is to report some vcov-related uncertainty estimate. This is probably just me being enamored with the generality of the code base. (Like when you write a beautiful paragraph but have to cut it to make the word limit.)

But just to illustrate, let's say you really care about the `drat` coefficient, but not the others. You could add a bunch of !!!! after it using `statistic_override`. It wouldn't be a `vcov`, but I realize that stuff like this is probably unlikely to be of much use.

    library(modelsummary)

    mod <- lm(mpg ~ vs + drat + hp, mtcars)
    so <- c("(Intercept)" = "", 
            "vs" = "",
            "drat" = "!!!!", 
            "hp" = "")

    modelsummary(
      mod,
      estimate="{estimate} {std.error}",
      statistic=NULL,
      statistic_override=so,
      gof_omit=".*",
      output="markdown")

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Model 1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">9.861</td>
</tr>
<tr class="even">
<td style="text-align: left;">vs</td>
<td style="text-align: center;">1.417</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drat</td>
<td style="text-align: center;">4.505 !!!!</td>
</tr>
<tr class="even">
<td style="text-align: left;">hp</td>
<td style="text-align: center;">-0.045</td>
</tr>
</tbody>
</table>

Would be curious to know what other power users like @grantmcdermott and @andrewheiss think about this.

**Comment by vincentarelbundock** [comment]
Edit:

That's a ridiculously convoluted example. With the new `glue` string support, you could just

**Comment by andrewheiss** [comment]
Oh awesome! My only concern from looking at the thread in #183 was if there was a way to have specific vcov options for each model (i.e. showing the same model 3 times but with a bunch of different SEs), and it looks like you can feed it a list for that, so ✅!

I like the `so` idea, since it makes it so you could add something like footnotes (either real with `[^thing]` or fake like a † or some other symbol)

**Comment by vincentarelbundock** [comment]
Thanks everyone for the input, and especially @NickCH-K for the great suggestions. Everything we talked about is now implemented on Github. I plan to dogfood this for a little bit, but should be able to release to CRAN over the holidays.

If you install the devel version (make sure you restart your R session completely), you should be able to do this:

    library(modelsummary)
    library(sandwich)

    models = list(
        "IID 1"       = lm(hp ~ mpg, mtcars),
        "IID 2"       = lm(hp ~ mpg, mtcars),
        "Stata"       = lm(hp ~ mpg, mtcars),
        "Clustered"   = lm(hp ~ mpg, mtcars),
        "Sandwich HC" = lm(hp ~ mpg, mtcars))

    modelsummary(
        models, gof_omit = ".*", output="markdown",
        vcov = list("iid", 
                    stats::vcov, 
                    "stata", 
                    ~cyl, 
                    sandwich::vcovHC))

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">IID 1</th>
<th style="text-align: center;">IID 2</th>
<th style="text-align: center;">Stata</th>
<th style="text-align: center;">Clustered</th>
<th style="text-align: center;">Sandwich HC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">324.082</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(27.433)</td>
<td style="text-align: center;">(27.433)</td>
<td style="text-align: center;">(28.821)</td>
<td style="text-align: center;">(40.775)</td>
<td style="text-align: center;">(30.561)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mpg</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-8.830</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1.310)</td>
<td style="text-align: center;">(1.310)</td>
<td style="text-align: center;">(1.256)</td>
<td style="text-align: center;">(1.488)</td>
<td style="text-align: center;">(1.363)</td>
</tr>
</tbody>
</table>

Of course, simpler calls like this also work:

```r
modelsummary(models, vcov="robust")
```

I also catch calls to `statistic_override` through the ellipses, and I plan to maintain that safety net until about forever to ensure that old code still works.

**Comment by vincentarelbundock** [comment]
<img width="768" alt="Screen Shot 2020-12-17 at 12 44 57" src="https://user-images.githubusercontent.com/987057/102524697-56fa8580-4067-11eb-9372-b43db4989e04.png">

**Comment by NickCH-K** [comment]
This is so awesome and well done! My students will have a much easier time doing robust SEs.

**Comment by grantmcdermott** [comment]
Amazing. Agree that this is a great addition. 

Thanks for the suggestion, Nick and for the implementation, Vincent!

**Comment by grantmcdermott** [comment]
One minor suggestion RE the notes: I assume "classical" and "iid' are the same? If so, then I'd put them together to avoid confusion. Something like:

- string or list of strings: "iid" (alias "classical"), "robust", "HC"...

**Comment by vincentarelbundock** [comment]
> One minor suggestion RE the notes: I assume "classical" and "iid' are the same? If so, then I'd put them together to avoid confusion. Something like:
> 
>     * string or list of strings: "iid" (alias "classical"), "robust", "HC"...

eb25336b59e422

**Comment by vincentarelbundock** [comment]
FYI this feature is on CRAN as v0.6.5. The source is there already, and the binaries should be coming in the next day or so.
