### ISSUE TITLE
in function modelsummary, option exponentiate = TRUE not working

### ISSUE THREAD

**Issue by mplessz** [vincentarelbundock/modelsummary#185]
Hi, I am working with version 0.6.4 of the package, and I have trouble with some options. 
Option `exponentiate = TRUE` is not exponentiating the coefficients (It worked in version 0.6.3, but i need the brand new "statistic = NULL" option).
Here is a reproducible example and my results.

```
library(modelsummary)
packageVersion("modelsummary")
data(mtcars) 
fit <- glm(am  ~ wt + cyl  , data = mtcars , family = binomial ) 
modelsummary(fit,  exponentiate = TRUE)
```
![image](https://user-images.githubusercontent.com/23453716/102502859-68e82280-407f-11eb-93a7-cab3d2bfb79e.png)
```
the coefficients in the image (after modelsummary) are the same as in the results printed below, and one is negative so not an exponential.

summary(fit)

# Call:
# 	glm(formula = am ~ wt + cyl, family = binomial, data = mtcars)
# 
# Deviance Residuals: 
# 	Min        1Q    Median        3Q       Max  
# -1.91155  -0.25974  -0.04161   0.18322   1.95512  
# 
# Coefficients:
# 	       Estimate Std. Error z value Pr(>|z|)   
#(Intercept)   15.749      6.026   2.614  0.00896 **
#wt            -7.864      3.071  -2.561  0.01045 * 
#cyl            1.322      0.789   1.675  0.09390 . 
# ---
# 	Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

am I doing something wrong or is there something to fix?
Beside that I really like working with this package, thanks for developing it.

**Comment by vincentarelbundock** [comment]
I'm really sorry about this. Version 0.6.4 had to be rushed out because CRAN informed me there was an issue with a testing dependency (`vdiffr`). In doing so, I mistakenly introduced a bug.

The version on Github is fixed. So if you reinstall from there, restart R completely, and try again, it should work. 

I plan to release a new version to CRAN sometime during the holidays, but you can use Github development now.

**Comment by mplessz** [comment]
Yes, it works now. Thanks
below, a screenshot of my result.
And do take some holiday ! I will :-) 

![image](https://user-images.githubusercontent.com/23453716/102509566-fa0ec780-4086-11eb-8af4-dd91e5f4d6e6.png)
