### ISSUE TITLE
stars note `<` replaced by `¡` when compiling LaTeX using `pdflatex`

### ISSUE THREAD

**Issue by acoppock** [vincentarelbundock/modelsummary#189]
Just switched to this package for tables -- it's fantastic, thank you.

Small issue with stars:

my call to model summary is
```
modelsummary(
  estimates_dfs,
  coef_map = coef_map,
  coef_omit = "study",
  gof_omit = c("se|Adj"),
  notes = list(
    "HC2 robust standard errors are in parentheses.",
    "All models include study fixed effects."
  ),
  title = "Effects of advertising dosage on post-treatment 7-point party identification",
  stars = c("*" = .05),
  output = "drafts/survey_experiments_paper/tables/pid_7_post_regression_table.tex"
)
```

which produces the following:

```
\begin{table}

\caption{\label{tab:}Effects of advertising dosage on post-treatment 7-point party identification}
\centering
\begin{tabular}[t]{lcccc}
\toprule
  & Immediate & After 10 days & Immediate  & After 10 days \\
\midrule
One video & 0.078* & 0.017 &  & \\
 & (0.039) & (0.038) &  & \\
Two videos & 0.077* & 0.061 &  & \\
 & (0.035) & (0.038) &  & \\
Three videos & 0.125* & 0.063 &  & \\
 & (0.038) & (0.040) &  & \\
Six videos & 0.167* & 0.043 &  & \\
 & (0.075) & (0.081) &  & \\
Number of videos &  &  & 0.032* & 0.013\\
 &  &  & (0.010) & (0.011)\\
Pre-treatment 7-point Party ID & 0.947* & 0.955* & 0.947* & 0.955*\\
 & (0.007) & (0.007) & (0.007) & (0.007)\\
(Intercept) & 0.290* & 0.224* & 0.331* & 0.229*\\
 & (0.055) & (0.052) & (0.045) & (0.041)\\
\midrule
Num.Obs. & 6484 & 6484 & 6484 & 6484\\
R2 & 0.805 & 0.804 & 0.805 & 0.804\\
\bottomrule
\multicolumn{5}{l}{\textsuperscript{} * p < 0.05}\\
\multicolumn{5}{l}{\textsuperscript{} HC2 robust standard errors are in parentheses.}\\
\multicolumn{5}{l}{\textsuperscript{} All models include study fixed effects.}\\
\end{tabular}
\end{table}
```

which renders to

<img width="465" alt="Screen Shot 2020-12-21 at 12 59 44 PM" src="https://user-images.githubusercontent.com/9171009/102807314-67bf3a00-438c-11eb-9cf4-e1868da71d39.png">

to fix, all I need is to add $$'s

`\multicolumn{5}{l}{\textsuperscript{} * $p < 0.05$}\\

Can this be fixed within model summary?

Thank you thank you!

**Comment by vincentarelbundock** [comment]
Seems like an easy fix. If you have a chance to reinstall from github (make sure you restart your R session entirely for the change to take effect), let me know if the new version works for you.

It does here:

![screenshot_20201221-140822](https://user-images.githubusercontent.com/987057/102813059-2a5faa00-4396-11eb-8c06-98ad449be82c.png)

**Comment by vincentarelbundock** [comment]
Hmmm, I just tried with version 0.6.4 and am not getting the problem. So the thing I just pushed might not fix it for you either.

What version are you using?

**Comment by vincentarelbundock** [comment]
@acoppock I dug in a bit more and found out that `pdflatex` does not support the `<` sign natively. Your three options are:

1. Include this in your latex preamble: `\usepackage[T1]{fontenc}`
2. Use `xelatex` or `lualatex` to compile your document instead of `pdflatex`
3. Embed the table in an Rmarkdown document and compile with `knitr`/`rmarkdown`

I have tried all three options with your table and they all seem to work fine.

**Comment by vincentarelbundock** [comment]
Sorry for the multiple notifications, but I just pushed a tiny commit (https://github.com/vincentarelbundock/modelsummary/commit/218977d46180e92e5299a85a642450dc99447baa) which checks if the output is LaTeX, and then surrounds `  <` with dollar signs: ` $<$ `. 

I think this should take care of this.

Will prep a new release early in the new year, but available on Github now.

**Comment by vincentarelbundock** [comment]
Version 0.6.5 source is on CRAN now (binaries coming soon) and fixes this.

Thanks again for the report!
