### ISSUE TITLE
Number of missing observations in datasummary_balance categorical

### ISSUE THREAD

**Issue by gregmacfarlane** [vincentarelbundock/modelsummary#190]
Issue #164 requested more information on categorical variables when there was a high degree of missingness. Is there a way to just print the percent missing from each variable?

```r
mycars <- mtcars %>% mutate(cyl = as_factor(cyl))
mycars$cyl[c(6, 19)] <- NA
datasummary_balance(~am, mycars, output = "markdown")
```

|     |   |0 Mean |0 Std. Dev. |1 Mean |1 Std. Dev. |Diff. in Means |Std. Error |
|:----|:--|:------|:-----------|:------|:-----------|:--------------|:----------|
|mpg  |   |17.1   |3.8         |24.4   |6.2         |7.2            |1.9        |
|disp |   |290.4  |110.2       |143.5  |87.2        |-146.8         |35.0       |
|     |   |N      |%           |N      |%           |               |           |
|cyl  |4  |3      |9.4         |7      |21.9        |               |           |
|     |6  |3      |9.4         |3      |9.4         |               |           |
|     |8  |12     |37.5        |2      |6.2         |               |           |

It would be desirable to have:

|     |   |0 Mean |0 Std. Dev. |1 Mean |1 Std. Dev. |Diff. in Means |Std. Error |
|:----|:--|:------|:-----------|:------|:-----------|:--------------|:----------|
|mpg  |   |17.1   |3.8         |24.4   |6.2         |7.2            |1.9        |
|disp |   |290.4  |110.2       |143.5  |87.2        |-146.8         |35.0       |
|     |   |N      |%           |N      |%           |               |           |
|cyl  |4  |3      |9.4         |7      |21.9        |               |           |
|     |6  |3      |9.4         |3      |9.4         |               |           |
|     |8  |12     |37.5        |2      |6.2         |               |           |
|   | NA | 2 | ? | 0 | 0.0| | |

**Comment by gregmacfarlane** [comment]
I looking at the [tables::tabular()](https://cran.r-project.org/web/packages/tables/vignettes/tables.pdf) vignette, it seems as though this relies on the `exclude` property of the factor. It's amazing how long you can use R and still discover obscure arguments to basic functions! 


```r
mycars$cyl <- factor(mycars$cyl, exclude = NULL)
datasummary_balance(~am, mycars, output = "markdown")
```

|     |   |0 Mean |0 Std. Dev. |1 Mean |1 Std. Dev. |Diff. in Means |Std. Error |
|:----|:--|:------|:-----------|:------|:-----------|:--------------|:----------|
|mpg  |   |17.1   |3.8         |24.4   |6.2         |7.2            |1.9        |
|disp |   |290.4  |110.2       |143.5  |87.2        |-146.8         |35.0       |
|     |   |N      |%           |N      |%           |               |           |
|cyl  |4  |3      |9.4         |7      |21.9        |               |           |
|     |6  |3      |9.4         |3      |9.4         |               |           |
|     |8  |12     |37.5        |2      |6.2         |               |           |
|     |   |1      |3.1         |1      |3.1         |               |           |

Would be nice to print `NA` instead of ` `, but I'll find out that workaround also.

**Comment by vincentarelbundock** [comment]
wow, I had no idea! Very cool!

**Comment by vincentarelbundock** [comment]
BTW, that vignette is pretty amazing.

**Comment by gregmacfarlane** [comment]
So, the [`clean_na`](https://github.com/vincentarelbundock/modelsummary/blob/d2cf7c1155f2bf250344e891aa622da83e655c34/R/datasummary_extract.R#L26-L32) internal function in `datasummary_extract()` is what pulls the `NA` label off the table. This might make sense in the fields of the tables, but probably not in the header / row names, especially since the `tabular` function would not normally pull these off.

```r
  # NA to empty cells
  clean_na <- function(x) {
    out <- trimws(x)
    out[is.na(out)] <- ''
    out <- ifelse(out %in% c('NA', 'NaN'), '', out)
    return(out)
  }
```
But I can understand if this isn't a priority; it probably makes sense for me to code `NA` as a factor level `No Response` for the one display table per paper that requires this kind of thing.

**Comment by vincentarelbundock** [comment]
Thanks for investigating, this is a good find!

I have a faint recollection that there was an important reason why I needed to apply `clean_na` to headers. `tables::tabular` returns some weird output sometimes, and I have to admit that the extraction code is a bit fragile, so I'm wary of making changes without creating a bunch of additional tests.

I'm heading to the kitchen to prep our Finnish Christmas Ham now, so I probably won't be able to look seriously at this for a while. But I will take a close look eventually.

No promises though. Asking users to be explicit about recoding `NA`s might be the best long term solution (or I could do it on the fly, but that seems like the kind of magic that could yield undesirable side effects).

**Comment by gregmacfarlane** [comment]
Hey, I have no need for immediate response on free code two days before Christmas! But thanks for your responsiveness, and I agree this might be a user-side workaround rather than a pile of new tests.

**Comment by gregmacfarlane** [comment]
Actually, the `forcats::fct_explicit_na()` function makes this SUPER EASY.

```r
datasummary_balance(~am, mycars %>% mutate(cyl = fct_explicit_na(cyl)), output = "markdown")
```


|     |          |0 Mean |0 Std. Dev. |1 Mean |1 Std. Dev. |Diff. in Means |Std. Error |
|:----|:---------|:------|:-----------|:------|:-----------|:--------------|:----------|
|mpg  |          |17.1   |3.8         |24.4   |6.2         |7.2            |1.9        |
|disp |          |290.4  |110.2       |143.5  |87.2        |-146.8         |35.0       |
|     |          |N      |%           |N      |%           |               |           |
|cyl  |4         |3      |9.4         |7      |21.9        |               |           |
|     |6         |3      |9.4         |3      |9.4         |               |           |
|     |8         |12     |37.5        |2      |6.2         |               |           |
|     |(Missing) |1      |3.1         |1      |3.1         |               |           |

**Comment by vincentarelbundock** [comment]
Very cool!

We can also get essentially the same result with this:

```r
mycars$cyl <- ifelse(is.na(mycars$cyl), "Missing", mycars$cyl)
datasummary_balance(~am, mycars)
```

So I guess I'm going to close this, since the solution is so easy.

Thanks again for your thoughts on this. And also for the PR on `kableExtra`. Very nice work!
