### ISSUE TITLE
statistic_vertical deprecation breaks my use case - any ideas?

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#195]
I am using the package to make tables like the one below, i.e. showing different uncertainty estimates for different model versions. This used to work well with statistic_vertical and statistic_override ... I can't get it to work yet with the new glue syntax. Am I missing something, or would it be good to add a way to refer to the statistic_override entry within the glue syntax - or do you have a more straightforward solution?

![image](https://user-images.githubusercontent.com/60155545/103356971-fe38dd00-4aa9-11eb-9116-375f10049660.png)

**Comment by vincentarelbundock** [comment]
Oh, that's interesting! Another proof that users will always find a way to use the software in ways you didn't anticipate.

Just to clarify, these are 4 separate models, right? What if I allowed a vector of glue strings in the `estimate` parameter so you could do this:

```r
modelsummary(
  models,
  estimate = c("{estimate} ({std.error}){stars}",
                       "{estimate} [{conf.low}, {conf.high}]",
                       "{estimate} ({std.error}){stars}",
                       "{estimate} [{conf.low}, {conf.high}]"))
```

On my end, this would be relatively easy. It would require allowing `{stars}` and a vector, and I could implement this in the next couple days in time for the holiday release.

Is that syntax too heavy for end users like you? (I was never a big fan of the `statistic_vertical` argument, so I would much rather not going back to it if at all possible.)

**Comment by LukasWallrich** [comment]
That sounds great (and yes, they are 4 models). Composing the `statistic_override` list previously took at least the same amount of coding. Thanks a lot for all the work you are doing on this!

**Comment by vincentarelbundock** [comment]
Commit https://github.com/vincentarelbundock/modelsummary/commit/a20688d1a3d5cfa23aacbf4872048f94bab9584f implements what I suggested above. There's an example in the web docs:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#estimate-1

If you get a chance to try the github version, I'd appreciate it if you could let me know if it works as expected for you. I'm planning to make a CRAN release pretty soon and would like it if someone other than me tried this change.

**Comment by LukasWallrich** [comment]
With the most recent version, I get a strange new error - see at the bottom - but with the commit that you referenced above, it works just as expected. Thanks a lot - that really helps with getting the draft of my PhD done :)

``` r
mod1 <- lm(wt ~ am + mpg, mtcars)
mod2 <- lm(wt ~ am * mpg, mtcars)
library(modelsummary)
msummary(list(mod1, mod2), estimate = c(
"{estimate} ({std.error}){stars}",
"{estimate} [{conf.low}, {conf.high}]"))
#> Error in sanity_factory(factory_dict): Assertion on 'modelsummary_default %in% c("gt", "kableExtra", "flextable", "huxtable", "markdown", "html", "data.frame", "dataframe", "latex")' failed: Must be TRUE.
```

<sup>Created on 2020-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vincentarelbundock** [comment]
ah yeah! looks like I introduced a bug. Should be fixed now.

A PhD is a long, lonely endeavour. You deserve all the help you can get ;-)

**Comment by LukasWallrich** [comment]
Thanks! One more thing: out of curiosity, I tested whether the same would now work for `statistic`, in case I ever want the vertical layout again - of course, it doesn't, given that a vector there does something different, and you probably don't want to add that complexity?  However, there is something else you might want to fix: currently, `statistic = c("({std.error}){stars}"))` results in `FALSE` instead of any stars, unless stars are also included in the `estimate` - for some reason, the code below returns stars for the first model.

```
modelsummary::msummary(list(mod1, mod2), output = "gt", statistic = c("({std.error}){stars}", "[{conf.low}, {conf.high}]"), estimate = c(
    "{estimate} ({std.error}){stars}",
    "{estimate} [{conf.low}, {conf.high}]"))
```


![image](https://user-images.githubusercontent.com/60155545/103386915-d9b82180-4af8-11eb-9fbc-2335938daef1.png)

**Comment by vincentarelbundock** [comment]
Ha! I see what the problem was and just pushed a bug fix.

I really appreciate those reports, especially coming from users who aren't afraid to push the limits of what the software can do.
