### ISSUE TITLE
Possible issue with margins

### ISSUE THREAD

**Issue by clockwoodreynolds** [vincentarelbundock/modelsummary#201]
I know that a prior message said that marginal effects from margins was supported (because broom supports margins).  However, I have been unable to get modelsummary to produce a table of marginal effects from margins.  Margins is in the list of supported packages, and I can confirm with tidy() that estimates and std. errors are produced in a tibble.

My guess is that this is user error on my part.  If so, I apologize for not understanding what to do.  But any assistance would be great.  This package is really wonderful.

Here is the error that I get (model was a logistic regression estimated by glm() and passed through to margins).

Error in get_estimates(model, conf_level = NULL, ...) : 
  Cannot extract the required information from models of class "margins". Consider installing `broom.mixed`, or any other package that includes `tidy` and `glance` methods appropriate for this model type. Alternatively, you can easily define your own methods by following the instructions on the `modelsummary` website: https://vincentarelbundock.github.io/modelsummary/articles/newmodels.html

**Comment by vincentarelbundock** [comment]
Thanks for the report, I really appreciate it!

This seems to be due to a minor quirk in the `broom::tidy.margins` code, where this doesn't work.

```r
mod = glm(vs ~ hp + drat, data = mtcars, family = binomial)
mfx = margins(mod)
broom::tidy(mfx, conf.int = FALSE, conf.level = NULL)
```

I included a workaround in `modelsummary` on Github. Could you try installing the latest version from there, restarting R completely (making sure no leftover objects from the previous section persist), and trying again?

```r
library(remotes)
remotes::install_github("vincentarelbundock/modelsummary")
```

**Comment by clockwoodreynolds** [comment]
That did it, works fine now.  Thank you so much!
