### ISSUE TITLE
why does codecov github action fail?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#211]

**Comment by IndrajeetPatil** [comment]
This happened to me, but only when the tests failed. 

Are you sure all of your tests pass on MacOS for the relevant R-version?

**Comment by vincentarelbundock** [comment]
Interesting.

All the tests seem to pass on Github Actions, except for one on Windows. But even that one should sort itself out on its own (I think it has to do with the new binary `broom` package making its way to CRAN).

See: https://github.com/vincentarelbundock/modelsummary/actions/runs/592540891
