### ISSUE TITLE
Allow coef_map to be used without names

### ISSUE THREAD

**Issue by NickCH-K** [vincentarelbundock/modelsummary#214]
I think it's fairly common, at least in analysis stages before you're ready to publish something, to want to limit the coefficients in a regression table without needing to come up with proper names for each of them (or, they already have the names you want). In `modelsummary`, `coef_omit` can accomplish this, but often what you want to omit is a long list.

A quick fix that wouldn't break anything and I think would improve functionality (and would definitely make it easier on my students) would be to add the lines:

```r
if (is.null(names(coef_map)) {
 names(coef_map) <- coef_map
}
```

to `modelsummary` inside of the `if(!is.null(coef_map)` lines 320-323. This way, you can pass an unnamed vector to `coef_map`, and it will be used to simply limit the table to those coefficients. It would also be straightforward to add a `coef_rename()` call inside this `if()`.

**Comment by vincentarelbundock** [comment]
Excellent suggestion! And thanks for looking into a solution, it was very helpful and worked as-is. I only added a test, an input sanity check, and new docs. Easy peasy.

Version 0.6.6 just came out a few days, and CRAN doesn't like us to submit new versions more than every month or so. I'll release this new feature as part of the next release, as soon as is reasonable.

In the meantime, you can install the Github version and do this:

``` r
library('modelsummary')
data(trees)

models <- list(
  Bivariate = lm(Girth ~ Height, data = trees),
  Multivariate = lm(Girth ~ Height + Volume, data = trees))

modelsummary(models, output = "markdown", 
             coef_map = c('Volume' = 'Large', 'Height' = 'Tall'))
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Bivariate</th>
<th style="text-align: center;">Multivariate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Large</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.195</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tall</td>
<td style="text-align: center;">0.256</td>
<td style="text-align: center;">-0.045</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.078)</td>
<td style="text-align: center;">(0.028)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">31</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.270</td>
<td style="text-align: center;">0.941</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.244</td>
<td style="text-align: center;">0.937</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">154.1</td>
<td style="text-align: center;">78.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">158.4</td>
<td style="text-align: center;">84.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-74.061</td>
<td style="text-align: center;">-35.116</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">10.707</td>
<td style="text-align: center;">222.471</td>
</tr>
</tbody>
</table>

``` r
modelsummary(models, output = "markdown",
             coef_map = c('Volume', 'Height'))
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Bivariate</th>
<th style="text-align: center;">Multivariate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Volume</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.195</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">(0.011)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Height</td>
<td style="text-align: center;">0.256</td>
<td style="text-align: center;">-0.045</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(0.078)</td>
<td style="text-align: center;">(0.028)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">31</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.270</td>
<td style="text-align: center;">0.941</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.244</td>
<td style="text-align: center;">0.937</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">154.1</td>
<td style="text-align: center;">78.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">158.4</td>
<td style="text-align: center;">84.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-74.061</td>
<td style="text-align: center;">-35.116</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">10.707</td>
<td style="text-align: center;">222.471</td>
</tr>
</tbody>
</table>

**Comment by NickCH-K** [comment]
Awesome!
