### ISSUE TITLE
Optional extra rows

### ISSUE THREAD

**Issue by jamarav** [vincentarelbundock/modelsummary#220]
Hi everyone,

I'm starting with this amazing package and I would like to suggest a couple of features to the `modelsummary()` function.

This is really flexible but I detected that there is no option to control the last rows in the summary table (or I don't find in the documentation). These rows are the number of observations, R2, AIC, etc.

The actual format is really good but sometimes I'm interested to obtain only the predictors and AIC. It would be good to control these defaults rows with a boolean vector for example.

An other interesting feature would be to define directly in the function additional rows at the end. For example, calculate the Root Mean Squared Error and include this. Probably with a named numeric vector if we want more than one row or a named character vector if we want more flexibility.

**Comment by vincentarelbundock** [comment]
Please read documentation of gof_omit gof_map and add_rows arguments.

**Comment by jamarav** [comment]
Thanks you very much @vincentarelbundock. Sorry, I had not seen these features.

I usually make my research reports in knitr and this package helps a lot in reproducible research.

Congratulations for the wonderful work you are doing.

**Comment by jamarav** [comment]
I just finished to format the summary table. The only problem that I can't fix is specify the fmt to the extra rows included in `add_rows()`. They take the predefined for the predictors. I have specified two extra columns with the maximum relative error and the rms (I tried to specify the rmse in `gof_map` but in `lm()` models this dosen't works).

Thanks in advance

**Comment by vincentarelbundock** [comment]
round them and convert them to character before
