### ISSUE TITLE
Correlation type used in  datasummary_correlation function?

### ISSUE THREAD

**Issue by DMCottrell** [vincentarelbundock/modelsummary#222]
What is the correlation type used when calling the ```datasummary_correlation()``` function? Additionally, is there a way to change between Pearson, Kendall, or Spearman?

I just discovered this package and am already in love. Thank you!!!!

**Comment by vincentarelbundock** [comment]
Great!

By default, we call: `stats::cor(data, use='pairwise.complete.obs')`, so it uses the default "pearson" method.

What do you think would be the best and most general API to allow specification of the correlation method? Maybe we could do something like this:

```r
datasummary_correlation(
  mtcars,
  fn = function(x) stats::cor(x, use = "pairwise.complete.obs", method = "spearman"))
```

This is verbose, but it would be totally generic and users could specify other measures of distance.

**Comment by vincentarelbundock** [comment]
I just pushed a new commit to Github that includes a new `method` argument:

```
  method: character or function

            • character: "pearson", "kendall", or "spearman"

            • function: takes a data.frame with numeric columns and
              returns a square matrix with unique row.names and
              colnames.
```

Let me know if you have a chance to try it out.

**Comment by DMCottrell** [comment]
Just tried it out and it looks great. Much appreciated! Thank you!!

**Comment by vincentarelbundock** [comment]
Fantastic!

It'll be part of the next CRAN release, but I'm not 100% sure when that will be. Probably a few weeks. Thanks again for the great suggestion.
