### ISSUE TITLE
No native interface to the `ipumsr` package

### ISSUE THREAD

**Issue by tyleransom** [vincentarelbundock/modelsummary#225]
This is more of an FYI, but if I follow the [examples](https://cran.r-project.org/web/packages/ipumsr/vignettes/ipums.html) on the `ipumsr` package, but try to call `datasummary_skim()` etc. on the IPUMS data frames, it won't work.

I believe the reason is because the columns in the IPUMS data sets get read in as "unknown" column types. If I go through and formally convert to a factor or numeric, `datasummary` works just fine. 

More of an FYI, but I thought I'd mention it since the `ipumsr` package is fairly widely used. I'm not sure where in the documentation this could be made known, though.

**Comment by vincentarelbundock** [comment]
Thanks a lot, that's useful!

It's a busy week, but I think there might be a way to at least print out an informative message, or maybe convert `unknown` automatically. Will look into it when I find some time.

**Comment by tyleransom** [comment]
Thanks! As I recall, the error message wasn't terribly helpful, so even just adding an extra print statement would probably be worthwhile. Let me know if you'd like help.

**Comment by vincentarelbundock** [comment]
Looked into this and I think the easiest way to "fix" this is to automatically convert numeric variables to numeric. The problem is that `haven_labelled` data sometimes behave weirdly, so we strip those attributes become computation. So this works now with the latest Github on my computer:

```r
library(modelsummary)
library(ipumsr)

cps_ddi <- read_ipums_ddi(ipums_example("cps_00006.xml"))
cps_data <- read_ipums_micro(cps_ddi, verbose = FALSE)

datasummary_skim(cps_data)
```

Hopefully I didn't break anything with this ;)

**Comment by tyleransom** [comment]
You're awesome! Thank you so much. (And I too hope you didn't break anything with this. 😆)

**Comment by tyleransom** [comment]
Thanks for closing this; I just tested it tonight and it worked for me as well.
