### ISSUE TITLE
Recycle model with multiple vcov args

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/modelsummary#231]
Feel free to close this immediately if you don't like the idea or think it will create unnecessary headaches.

Much as I love the new `vcov` feature, a minor annoyance is that it doesn't permit model recycling. The most obvious case is where I want to demonstrate the effect of different VCOVs on the same underlying model.

```r
m = lm(mpg ~ wt, data = mtcars)

## Doesn't work
msummary(m, vcov = c('iid', 'HC2', 'HC3'))

## Works
m = replicate(3, m, simplify = FALSE)
msummary(m, vcov = c('iid', 'HC2', 'HC3'))
```

What are your thoughts on adding automatic support for model recycling? 

I'm guessing it could be too much of a pain (or too risky on the user side) to allow recycling in cases where the no. of models >= 2. But support for the most likely use case &mdash; i.e. a single model mapping on to multiple vcov args &mdash; seems feasible.

**Comment by vincentarelbundock** [comment]
Oh, that sounds like a neat feature. And yes, I agree that safety restricts us to the many-vcov-one-model case. (Other forms of recycling scare me in general.)

Implementation brainstorm for future use:

The easiest way to implement this would be to add some kind of `rep` call a few lines after this one:

https://github.com/vincentarelbundock/modelsummary/blob/main/R/modelsummary.R#L239

At that stage, `sanitize_models` has already wrapped all models in a list, so in principle if `length(models)==1 && length(vcov)>1`, we should be fine to replicate.

One problem with just replicating models like this is (I think) that we'll use a bunch of memory. A memory efficient strategy would be preferable, but it would require a fair bit of thought.

**Comment by grantmcdermott** [comment]
Strong agree about memory and I was actually thinking about this too.

OTOH, since the model metadata should stay the same (basically the `gof` stuff), could it be something as simple as running an lapply call over `extract_estimates` internally?

```r
## example
m = lm(mpg ~ wt, mtcars)
vcovs = c('iid', 'HC2', 'HC3') 
lapply(vcovs, function(v) modelsummary:::extract_estimates(m, vcov = v))
```

**Comment by vincentarelbundock** [comment]
I think I found a reasonably clean way to implement this. Let me know when you get a change to try the latest github version:

```r
library(modelsummary)
mod = lm(hp ~ mpg, mtcars)
modelsummary(mod, vcov = list("HC0", "stata", ~cyl))
modelsummary(mod, vcov = c("HC0", "stata", "classical"))
```

**Comment by grantmcdermott** [comment]
Just tested and it worked a charm. Awesome!

The only other thing I'm wondering is whether it makes sense to support a vector/list of model names at the same time. So you could do something like:

```r
library(modelsummary)
mod = lm(hp ~ mpg, mtcars)
v = c("HC0", "stata", "classical")
modelsummary(mod, vcov = v, names = v)
modelplot(mod, vcov = v, names = v)
```
Again, please don't feel an obligation. But I'm essentially looking for a line alternative of the approach that I was laying out [here](https://grantmcdermott.com/better-way-adjust-SEs/#example-1-sandwich).

**Comment by vincentarelbundock** [comment]
Cool.

Hmm, I don't think I want to add a whole new argument just for this (trying to be ruthless about argument sprawl).

I don't have a clean alternative in mind right now, but maybe we can think of one?

**Comment by vincentarelbundock** [comment]
one neat feature would be to automatically make the standard error type available in the GOF section. That would probably be easy to implement: if `vcov` is character, then append it to the `gof`/`glance` data.

**Comment by grantmcdermott** [comment]
Oh, I like the GOF idea. Again, though happy with whatever call you decide to make here.

Thanks Vincent! 

(Feel free to close this at your leisure.)

**Comment by grantmcdermott** [comment]
Looks ace!

**Comment by grantmcdermott** [comment]
The only minor issue I can think of is when a user calls a model type that (a) is compatible with sandwich style VCOV estimators, but (b) also provides it's own vcov adjustments that `msummary` already accounts for. 

**fixest** might be the only example that falls in this category:

``` r
library(fixest)
library(modelsummary)

mod = feols(hp ~ mpg + drat, mtcars)
modelsummary(mod,
                         vcov = list("robust", "stata", ~vs, ~vs+am), output = 'markdown')
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Model 1</th>
<th style="text-align: center;">Model 2</th>
<th style="text-align: center;">Model 3</th>
<th style="text-align: center;">Model 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">278.515</td>
<td style="text-align: center;">278.515</td>
<td style="text-align: center;">278.515</td>
<td style="text-align: center;">278.515</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(46.992)</td>
<td style="text-align: center;">(42.037)</td>
<td style="text-align: center;">(19.898)</td>
<td style="text-align: center;">(3.543)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mpg</td>
<td style="text-align: center;">-9.985</td>
<td style="text-align: center;">-9.985</td>
<td style="text-align: center;">-9.985</td>
<td style="text-align: center;">-9.985</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(2.471)</td>
<td style="text-align: center;">(2.209)</td>
<td style="text-align: center;">(3.976)</td>
<td style="text-align: center;">(2.325)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">drat</td>
<td style="text-align: center;">19.126</td>
<td style="text-align: center;">19.126</td>
<td style="text-align: center;">19.126</td>
<td style="text-align: center;">19.126</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(23.133)</td>
<td style="text-align: center;">(20.572)</td>
<td style="text-align: center;">(31.574)</td>
<td style="text-align: center;">(19.238)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.614</td>
<td style="text-align: center;">0.614</td>
<td style="text-align: center;">0.614</td>
<td style="text-align: center;">0.614</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.588</td>
<td style="text-align: center;">0.588</td>
<td style="text-align: center;">0.588</td>
<td style="text-align: center;">0.588</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2 Within</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Pseudo</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">335.9</td>
<td style="text-align: center;">335.9</td>
<td style="text-align: center;">335.9</td>
<td style="text-align: center;">335.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">340.3</td>
<td style="text-align: center;">340.3</td>
<td style="text-align: center;">340.3</td>
<td style="text-align: center;">340.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-164.940</td>
<td style="text-align: center;">-164.940</td>
<td style="text-align: center;">-164.940</td>
<td style="text-align: center;">-164.940</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Std. Errors</td>
<td style="text-align: center;">Robust</td>
<td style="text-align: center;">Stata</td>
<td style="text-align: center;">C: vs</td>
<td style="text-align: center;">C: vs + am</td>
</tr>
<tr class="even">
<td style="text-align: left;">Std. errors</td>
<td style="text-align: center;">Standard</td>
<td style="text-align: center;">Standard</td>
<td style="text-align: center;">Standard</td>
<td style="text-align: center;">Standard</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

As you can see, there are duplicate (conflicting) standard error terms. OTOH, I think that this is a case where the user could be expected to know what they're doing. (You wouldn't normally adjust the fixest object's SEs in this fashion, and can always exclude the "wrong" GOF entry if needed.)

**Comment by vincentarelbundock** [comment]
Good catch! I added an `if` statement to avoid collisions and duplications.

Again, thanks for the great suggestions and for alpha-testing everything!

Feel free to re-open if you run into issues with this feature.

**Comment by grantmcdermott** [comment]
Delighted to see the 0.7.0 release features --- including this one --- generate so much positive feedback. Richly deserved!

I might have missed it, but is there a reason why the HAC sandwich estimators (e.g. HAC, Andrews and NeweyWest) aren't included in the list of supported "vcov" objects? I think the same is true of the bootstrap sandwich estimator (i.e BS), although I can see how that is harder to handle sensibly.

**Motivation:** I was writing a little update to [this post](https://grantmcdermott.com/better-way-adjust-SEs/#example-1-sandwich) and wanted to show off `modelsummary`'s new one-line equivalent to the "manual" code that I used there.

```r
data('PetersenCL', package = 'sandwich')
m = lm(y ~ x, data = PetersenCL)

library(modelsummary)

## Works
msummary(m, vcov = list('iid', ~firm, ~firm+year, 'HC3'))

## Fails if I add NeweyWest (or HAC, etc)
msummary(m, vcov = list('iid', ~firm, ~firm+year, 'HC3', 'NeweyWest'))
```

**Comment by vincentarelbundock** [comment]
> is there a reason why the HAC sandwich estimators (e.g. HAC, Andrews and NeweyWest) aren't included in the list of supported "vcov" objects? 

No good reason. The latest commit should fix this. New docs read:


```r
vcov: robust standard errors and other manual statistics. The
          ‘vcov’ argument accepts five types of input (see the
          'Details' and 'Examples' sections below):

            • string, vector, or list of strings: "robust", "HC",
              "HC0", "HC1", "HC2", "HC3", "HC4", "HC4m", "HC5",
              "stata", "HAC", "NeweyWest", "Andrews",
              "panel-corrected", "outer-product", "weave", or
              "classical" (alias "constant" or "iid"). These
              variance-covariance matrices are computed using functions
              from the ‘sandwich’ package. The behavior of those
              functions can (and sometimes _must_) be altered by
              passing arguments to ‘sandwich’ directly from
              ‘modelsummary’ through the ellipsis (‘...’), but it is
              safer to define your own custom functions as described in
              the next bullet.

            • function or list of functions which return
              variance-covariance matrices with row and column names
              equal to the names of your coefficient estimates (e.g.,
              ‘stats::vcov’, ‘sandwich::vcovHC’, ‘function(x) vcovPC(x,
              cluster="country")’).
```

In principle, this means that you can alter the number of bootstrap replicates by doing:

```r
modelsummary(mod, vcov = "bootstrap", R = 1000, cluster = "firm")
```

I have not tested this extensively, but at first glance it seems to work. However, I'm starting to pass a lot of `...` around to different packages now, so defining a custom `vcov` functions is clearly a safer choice.

**Comment by grantmcdermott** [comment]
Brilliant. 

Everything looks good from my end and I agree that passing on dedicated functions is safer than leaning too hard on `...`

The one minor thing we might want to think about --- or not --- is that passing on a vcov list that contains a function causes us to lose the neat 'Std. Errors' row at the bottom of the table. Compare:

``` r
library(modelsummary)
m = lm(mpg ~ 0 + wt, mtcars)
msummary(m, vcov = list('iid', 'NeweyWest'), gof_omit = 'R2|IC|Log|F')
```

|             | Model 1 |  Model 2   |
|:------------|:-------:|:----------:|
| wt          |  5.292  |   5.292    |
|             | (0.593) |  (1.135)   |
| Num.Obs.    |   32    |     32     |
| Std. Errors |   IID   | Newey-West |

(Now swap `'NeweyWest'` with `sandwich::NeweyWest`:)

``` r
msummary(m, vcov = list('iid', sandwich::NeweyWest), gof_omit = 'R2|IC|Log|F')
```

|          | Model 1 | Model 2 |
|:---------|:-------:|:-------:|
| wt       |  5.292  |  5.292  |
|          | (0.593) | (1.135) |
| Num.Obs. |   32    |   32    |

OTOH it's easy enough to add this in manually, e.g. by naming your vcov list *a priori*.

``` r
vc = list('IID' = 'iid', 'Newey-West' = sandwich::NeweyWest)
rows = data.frame(t(c('Std. Errors', names(vc))))
msummary(m, vcov = vc, add_rows = rows, gof_omit = 'R2|IC|Log|F')
```

|             | Model 1 |  Model 2   |
|:------------|:-------:|:----------:|
| wt          |  5.292  |   5.292    |
|             | (0.593) |  (1.135)   |
| Num.Obs.    |   32    |     32     |
| Std. Errors |   IID   | Newey-West |

**Comment by vincentarelbundock** [comment]
I love it when things are much easier to implement than I anticipate!

@grantmcdermott you should now be able to do this:

``` r
library(modelsummary)

mod <- lm(hp ~ mpg, data = mtcars)

vc <- list("Rob" = "robust",
        "Stata Corp" = "stata",
        "Newey Lewis & the News" = "NeweyWest")

modelsummary(mod, output = "markdown", vcov = vc)
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Model 1</th>
<th style="text-align: center;">Model 2</th>
<th style="text-align: center;">Model 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">324.082</td>
<td style="text-align: center;">324.082</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(30.561)</td>
<td style="text-align: center;">(28.821)</td>
<td style="text-align: center;">(25.881)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">mpg</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-8.830</td>
<td style="text-align: center;">-8.830</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: center;">(1.363)</td>
<td style="text-align: center;">(1.256)</td>
<td style="text-align: center;">(1.108)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Num.Obs.</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">R2</td>
<td style="text-align: center;">0.602</td>
<td style="text-align: center;">0.602</td>
<td style="text-align: center;">0.602</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R2 Adj.</td>
<td style="text-align: center;">0.589</td>
<td style="text-align: center;">0.589</td>
<td style="text-align: center;">0.589</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIC</td>
<td style="text-align: center;">336.9</td>
<td style="text-align: center;">336.9</td>
<td style="text-align: center;">336.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BIC</td>
<td style="text-align: center;">341.3</td>
<td style="text-align: center;">341.3</td>
<td style="text-align: center;">341.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Log.Lik.</td>
<td style="text-align: center;">-165.428</td>
<td style="text-align: center;">-165.428</td>
<td style="text-align: center;">-165.428</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F</td>
<td style="text-align: center;">45.460</td>
<td style="text-align: center;">45.460</td>
<td style="text-align: center;">45.460</td>
</tr>
<tr class="even">
<td style="text-align: left;">Std. Errors</td>
<td style="text-align: center;">Rob</td>
<td style="text-align: center;">Stata Corp</td>
<td style="text-align: center;">Newey Lewis &amp; the News</td>
</tr>
</tbody>
</table>

**Comment by grantmcdermott** [comment]
Dude... you're the man!

Perfect. Thanks for indulging me again and I'm happy to (re)close.
