### ISSUE TITLE
Inconsistent weighted data in modelsummary

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#240]
This is my understanding: 

When using `datasummary_balance` the function will calculate weighted differences in means if a `weights` variable is supplied for continuous variables but _unweighted_ statistics for categorical / binary variables as well as the number of observations. Is this correct? 

Thank you!

**Comment by vincentarelbundock** [comment]
No, the intent is that differences in means should be weighted regardless of the type of outcome variable. Do you have a minimal working example where the function doesn't behave as expected?

Here's an example where it work:

```r
library(modelsummary)
library(estimatr)

dat = mtcars
dat$weights = dat$mpg

datasummary_balance(~vs, dat, fmt = 5)

difference_in_means(
  am~vs, weights = weights, data = dat)

difference_in_means(
  hp~vs, weights = weights, data = dat)
```

**Comment by vincentarelbundock** [comment]
Did you want to say that the means themselves are unweighted? If so, that is correct. The reported means and sd on the left side of the table are unweighted sample statistics. The weights only come in when calculating the differences in means and their associated standard errors.

I'm happy to consider feature requests if this is not the behavior that one would expect.

**Comment by statzhero** [comment]
Please see the example below, I hope it makes sense. I have included the outputs. Yes, I was expecting weighted statistics everywhere.

```
set.seed(123)

d <- dplyr::tibble(a = 1:5,
            b = factor(rbinom(5, 1, 0.5)),
            treatment = c(T,T,F,F,F),
            weights = c(1, 1, 0.5, 1.25, 1.25))

modelsummary::datasummary_balance(~ treatment, d, output = "markdown")
```
|   |   |FALSE (N=3) Mean |FALSE (N=3) Std. Dev. |TRUE (N=2) Mean |TRUE (N=2) Std. Dev. |Diff. in Means |Std. Error |
|:--|:--|:----------------|:---------------------|:---------------|:--------------------|:--------------|:----------|
|a  |   |4.0              |1.0                   |1.5             |0.7                  |-2.7           |0.7        |
|   |   |N                |%                     |N               |%                    |               |           |
|b  |0  |1                |33.3                  |1               |50.0                 |               |           |
|   |1  |2                |66.7                  |1               |50.0                 |               |           |
```
d %>% 
  dplyr::filter(treatment == F) %>% 
  mutate(mean = weighted.mean(x = a, w = weights))

# A tibble: 3 x 5
      a b     treatment weights  mean
<int> <fct> <lgl>       <dbl> <dbl>
1     3 1     FALSE        0.5   4.25
2     4 1     FALSE        1.25  4.25
3     5 1     FALSE        1.25  4.25
    
d %>% 
  dplyr::filter(treatment == F) %>% 
  dplyr::count(b, wt = weights)

# A tibble: 2 x 2
   b         n
<fct> <dbl>
1 0       0.5
2 1       2.5
```

**Comment by vincentarelbundock** [comment]
Thanks for the example, I really appreciate it! I haven't forgotten about this, but I need to think about it a bit more. 

I'm wondering if there's a use-case for reporting weights in one but not the other. And if there is such a use-case, then it probably means I need to add some arguments, which I was kind of hoping to avoid, since I want to keep the user interface simple.

All this to say that I'll need to think about it a bit, but that I do plan to offer a solution in the near future.

**Comment by vincentarelbundock** [comment]
note to self: https://github.com/NickCH-K/vtable

**Comment by vincentarelbundock** [comment]
I'm sure you have moved on by now, but I finally got around to looking into this. Sorry it took so long!

The version on Github should now handle weights correctly for numeric variables.

For uninteresting reasons having to do with the internal structure of the package, supporting categorical variables is very tricky. Unless someone is willing to do a deep dive and help me with this, weights for cateogorical variables are unlikely to be implemented in the near term. At least, `datasummary_balance` will now raise a warning to inform users about this.

Example with manual calculation of the top left number (mean = 17.1):

``` r
library(modelsummary)

dat <- mtcars
dat$weights <- runif(32)
dat$cyl <- factor(dat$cyl)

weighted.mean(dat$mpg[dat$am == 0], dat$weights[dat$am == 0])
# [1] 17.1319

datasummary_balance(~am, data = dat, output = "markdown")
# Warning: When the `data` used in `datasummary_balance` contains a "weights" column, the means, standard deviations, difference in means, and standard errors of numeric variables are adjusted to account for weights. However, the counts and percentages for categorical variables are not adjusted.
# This warning is displayed once per session.
```

|      |   | 0 Mean | 0 Std. Dev. | 1 Mean | 1 Std. Dev. | Diff. in Means | Std. Error |
| :--- | :- | -----: | ----------: | -----: | ----------: | -------------: | ---------: |
| mpg  |   |   17.1 |         3.7 |   22.7 |         6.4 |            5.6 |        2.2 |
| disp |   |  289.1 |       103.9 |  171.2 |       105.0 |        \-117.9 |       46.0 |
| hp   |   |  157.5 |        45.4 |  151.6 |        98.2 |          \-5.8 |       35.6 |
| drat |   |    3.2 |         0.4 |    4.0 |         0.3 |            0.7 |        0.1 |
| wt   |   |    3.7 |         0.7 |    2.6 |         0.6 |          \-1.1 |        0.3 |
| qsec |   |   18.0 |         1.3 |   17.0 |         2.0 |          \-1.0 |        0.7 |
| vs   |   |    0.4 |         0.5 |    0.4 |         0.5 |            0.1 |        0.2 |
| gear |   |    3.1 |         0.4 |    4.4 |         0.5 |            1.3 |        0.2 |
| carb |   |    2.6 |         1.2 |    3.4 |         2.4 |            0.8 |        0.9 |
|      |   |      N |        Pct. |      N |        Pct. |                |            |
| cyl  | 4 |      3 |        15.8 |      8 |        61.5 |                |            |
|      | 6 |      4 |        21.1 |      3 |        23.1 |                |            |
|      | 8 |     12 |        63.2 |      2 |        15.4 |                |            |
