### ISSUE TITLE
Force p.value calculations in modelsummary() for linear mixed models from {lme4}

### ISSUE THREAD

**Issue by svmiller** [vincentarelbundock/modelsummary#248]
Hi Vincent,

I want to pick your brain about what you think of forcing p.value calculations in `{lme4}` models for the purpose of presenting "statistically significant" results from linear mixed models. Here's an abbreviated code as to what's happening.

```r
library(modelsummary)
library(lme4)
library(parameters)
library(tidyverse)

handsome_model <- lmer(Reaction ~ Days + (1 | Subject), sleepstudy)

modelsummary(handsome_model) # no prob, bob

modelsummary(handsome_model, stars = TRUE)
# ^ oh no, modelsummary wants p.value column and lme4 be like "nuh uh, fam, not giving you that"
# for an abbreviated discussion for why: https://stats.stackexchange.com/questions/146988/getting-degrees-of-freedom-from-lmer
```

Basically this is almost entirely a `{broom}` and `{lme4}` issue, but it concerns this package the extent to which `stars = TRUE` will fail here.

I can understand if you're squeamish to do this because it would entail overwriting a default tidier, but the `{parameters}` package gives some intuition to how you can nudge a p-value from a linear mixed model.

```r
parameters::parameters(handsome_model) 
# ^ this will give you p-values, that issue notwithstanding, also indicating the dfs
# Implied, if not stated outright: dfs = nobs - fixed parameters - number of random effects - residual SD

nobs(handsome_model) - 2 - 2 # nobs minus number of fixed effects - the one random effect and residual SD
# alternative shorthand
nobs(handsome_model) - nrow(broom::tidy(handsome_model))
```
On my end, this is my workaround for getting what I want in a profession that's immediately looking for stars with no context to the model. Nature of the beast.

```r
# a workaround on the user's end
# to shoehorn into modelsummary_list or tidy_custom.lmerMod or what have you
# Let's do the tidy_custom approach now that Vincent helpfully clarified how that's probably smarter/more flexible in a previous issue

tidy_custom.lmerMod <- function(x, ...) {
  broom.mixed::tidy(x) %>%
  mutate(df = nobs(x) - nrow(.),
         `p.value` = 2 * pt(abs(statistic), df, lower.tail = FALSE))
}

tidy_custom.lmerMod(handsome_model)

modelsummary(handsome_model, stars = TRUE)
# ^ works, but user really must take it on themselves to remove the random effect stuff to "glance"-level information. p-values make no sense in this context, hence the NA
```
I can understand reticence to incorporate this because it would entail doing additional stuff with tidiers that's 1) likely outside the package's mission and 2) at odds with `{broom}`'s approach to this particular class of model. In the case of the latter, if it were unproblematic to calculate, they'd have included it, but they have their reasons for not doing it.

Alas, I wanted to see what you thought about this. I've no doubt, should you choose to nudge p-values by default from tidied `lmerMod` objects, you'd do so in a more elegant way than I did here.

**Comment by vincentarelbundock** [comment]
Was `broom.mixed` loaded in your session when you ran this? 

When `modelsummary` extracts data from a model, it first tries `broom::tidy`, and then tries `parameters::parameters`. If you load `library(broom.mixed)`, then the first call to `broom::tidy` will actually hook into `broom.mixed` instead of using `parameters`.

This is important because, AFAICT `parameters` *does* support p values for that kind of model. Running this code with the latest Github version of `modelsummary` and **in a fresh R session without** `broom.mixed` produces a table with nice stars on my machine:

```r
library(lme4)
library(modelsummary)

handsome_model <- lmer(Reaction ~ Days + (1 | Subject), sleepstudy)
modelsummary(handsome_model, stars = TRUE)
```

On the more general point though, your intuition is right: I am *super* reluctant to add model-specific configs. `broom` has had *dozens* of contributors, and I just don't have the man power to track the individual math or object features of different models. Pull Requests to `broom` are better for model-specific changes, I think.

**Comment by vincentarelbundock** [comment]
BTW, in the devel version, you can set the order of priorities of extract functions by calling:

```r
options(modelsummary_get = "broom")
options(modelsummary_get = "parameters")
```

**Comment by svmiller** [comment]
> Was broom.mixed loaded in your session when you ran this?

... ... ...goddammit. The *one time* I directly load broom into anything I do and here we are. Sorry about that. You can close this with my apologies for taking up your time.

**Comment by vincentarelbundock** [comment]
No worries at all. I think that by trying to do "too much" magic under the hood, `modelsummary` kind of gets in the way sometimes.

As a general rule, though, I think that `broom.mixed` has been obsoleted by `performance`, so I *never* load it anywhere.

**Comment by vincentarelbundock** [comment]
Another thing to note is that you can get the equivalent of `broom::tidy` by calling `get_estimates`. This will give you some nice magic and try both `broom` and `parameters` without breaking anything else.
