### ISSUE TITLE
Rename GOF

### ISSUE THREAD

**Issue by nithinmkp** [vincentarelbundock/modelsummary#271]
Hello,
I would like to have R2 and Adj. R2 printed as R supercript 2 and adj. R superscript 2 in tables. Is there a way to do this?

**Comment by vincentarelbundock** [comment]
Hi,

Have you tried the `gof_map` argument?

If you export to LaTeX (or PDF), and end up using special commands, you may also consider passing the `escape=FALSE` argument as documented in the ellipsis (`...`) argument.

**Comment by nithinmkp** [comment]
Thanks for the reply. I did . I created a tibble and passed those
arguments. But it just appeared as a special character

gof_map <- tribble(
        ~raw,      ~clean,          ~fmt,  ~omit,
        "nobs",      "Observations",     0,  FALSE,
        "r.squared", "R^2",               3,  FALSE
)

It would be quite helpful if you can provide an example

/Nithin

**Comment by vincentarelbundock** [comment]
With pleasure.

The problem in your code is that "R^2" is neither valid HTML, nor valid LaTeX. In the former you would need `<sup>` tags, in the latter you would need math tags `$$`.

I added a specific example to the end of the `gof_map` section of the website. I hope it helps.

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#gof-map

**Comment by nithinmkp** [comment]
Thats awesome. Thanks a lot

Regards,
Nithin

**Comment by nithinmkp** [comment]
Vincent, just a follow question regarding my earlier problem, the examples
doesn't work for flextable. Any idea why? I tried passing both html and
LaTeX style gof but in vain

Nithin

**Comment by vincentarelbundock** [comment]
What does "not work" mean, exactly?

I'm not exactly sure how `flextable` handles escaping of characters. Do they have a special argument for that? (It's the package I use the least of all supported ones.)

**Comment by vincentarelbundock** [comment]
No bother at all. I love getting feedback!

It looks like the `flextable` author has refused to implement this solution, so html and latex characters will always be escaped automatically. So there is unfortunately nothing I can do about this. See here: https://github.com/davidgohel/flextable/issues/156

**Comment by nithinmkp** [comment]
Ok, thanks for the clarification.
Nithin



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
10/04/21,
08:05:02 PM
