### ISSUE TITLE
`modelsummary()` for `sampleSelection::selection()` includes empty CI-brackets

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#272]
you need to update _insight_, _parameters_ and _performance_ for the latest support of the _sampleSelection_ package.

```r
library(sampleSelection)
library(wooldridge) # for data
data(mroz)

mod1 <- selection(
  inlf ~ educ + kidslt6 + kidsge6, 
  wage ~ educ + exper + expersq,
  method = "2step",
  data = mroz)

mod2 <- selection(
  inlf ~ educ + kidslt6 + kidsge6, 
  wage ~ educ + exper + expersq,
  method = "ml",
  data = mroz)

modelsummary::modelsummary(list(mod1, mod2), group = component + term ~ model)
```

![image](https://user-images.githubusercontent.com/26301769/115671565-f055e300-a34a-11eb-9b0c-d06acafc5a91.png)

**Comment by vincentarelbundock** [comment]
Oh, interesting!

Is this the command you called?

```r
modelsummary::modelsummary(list(mod1, mod2), 
                           estimate = "{estimate} [{conf.low}, {conf.high}]",
                           statistic = NULL,
                           group = component + term ~ model)
```

If so, I'll have to think about this a bit. Internally, I use `glue` to convert this, but since the string is totally free-form and user-generated, I don't have a good way to say: "omit `[{conf.low}, {conf.high}]` if either statistic is missing."

**Comment by strengejacke** [comment]
> Is this the command you called?

Yes, indeed. I copied from the wrong code snippet.

**Comment by strengejacke** [comment]
> If so, I'll have to think about this a bit. 

I think we had some edge cases in _easystats_ as well, and if I remember right, we hard-coded these cases (by checking the final output, and replace "empty" CIs by "").

**Comment by vincentarelbundock** [comment]
I think you're right: I probably don't have a choice but to rely on hackish regular expressions to remove those. 

This commit should fix the issue (it does on my machine, at least): 6969f1a164e5a

**Comment by strengejacke** [comment]
yeah, works!
