### ISSUE TITLE
New argument option vcov = "waive" or similar

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#279]
Say you have a model object where there was already some standard error adjustment, and you want to display this model in a table with both the model-provided standard errors and with adjusted standard errors. For instance, see the tables below: 

``` r
library("modelsummary")
library("fixest")
mod <- feols(hp ~ mpg + drat, mtcars, cluster = "vs")
modelsummary(mod, output = "markdown")
```

|             |    Model 1     |
|:------------|:--------------:|
| (Intercept) |    278.515     |
|             |    (20.573)    |
| mpg         |     -9.985     |
|             |    (4.110)     |
| drat        |     19.126     |
|             |    (32.644)    |
| Std. Errors | Clustered (vs) |

``` r
modelsummary(mod, vcov = list(~vs, ~vs+am), output = "markdown")
```

|             | Model 1  |  Model 2   |
|:------------|:--------:|:----------:|
| (Intercept) | 278.515  |  278.515   |
|             | (19.898) |  (3.543)   |
| mpg         |  -9.985  |   -9.985   |
|             | (3.976)  |  (2.325)   |
| drat        |  19.126  |   19.126   |
|             | (31.574) |  (19.238)  |
| Std. Errors |  C: vs   | C: vs + am |

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

In the second table, I'd like to show the estimates from the first table, including the correct Std. Errors row, but I think it's only possible to supply an adjustment to `vcov`, but not just "give me the standard errors that the model provides". So I'd suggest adding an option to vcov, maybe "waive" or "asis" or something similar, to let modelsummary know to not do any adjustments.

```
modelsummary(mod, vcov = list("waive", ~vs+am))
```

Hope I didn't miss this in the docs!

**Comment by vincentarelbundock** [comment]
We already have "classical" and "iid". In some cases those are not quite *correct*, I guess. Now that you're aware of these options, do you think we should add more aliases?

"waive" is too close to "weave", which we also support.

I like "default" a bit more than "asis".

Perhaps a way to make this clearer in the docs is to set the default value to `vcov="default"` instead of `vcov=NULL`

**Comment by elbersb** [comment]
Sorry, the example wasn't well chosen. Take this: 

``` r
library("modelsummary")
library("fixest")
mod <- feols(hp ~ mpg + drat, mtcars, cluster = "vs")
modelsummary(mod, output = "markdown")
```

|             |    Model 1     |
|:------------|:--------------:|
| (Intercept) |    278.515     |
|             |    (20.573)    |
| mpg         |     -9.985     |
|             |    (4.110)     |
| drat        |     19.126     |
|             |    (32.644)    |
| Std. Errors | Clustered (vs) |

``` r
modelsummary(mod, vcov = list("iid", "classical", ~vs), output = "markdown")
```

|             | Model 1  |  Model 2  | Model 3  |
|:------------|:--------:|:---------:|:--------:|
| (Intercept) | 278.515  |  278.515  | 278.515  |
|             | (20.573) | (20.573)  | (19.898) |
| mpg         |  -9.985  |  -9.985   |  -9.985  |
|             | (4.110)  |  (4.110)  | (3.976)  |
| drat        |  19.126  |  19.126   |  19.126  |
|             | (32.644) | (32.644)  | (31.574) |
| Std. Errors |   IID    | Classical |  C: vs   |

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Note that in the first table, the last row says (correctly) said standard errors are clustered by `vs`. I don't think it's possible currently to get _this exact output_ in the second table. `iid` and `classical` show the same standard errors, but I think this actually confusing (at least to me -- because the SE are actually adjusted for clustering). Clustering by "vs" kind of works, but because of differences in defaults (I think), the SE are not the same, and the last row also differs (`C: vs` compared to `Clustered (vs)` -- there is probably an argument here to standardize this, but I don't care that much). 

So there should be sth like "default" that means: just take the SE that are already in the model.

**Comment by elbersb** [comment]
Instead of `"default"` we could also support `NULL` in the `vcov` list -- this would be consistent with the overall function design, where the default is `NULL`, which means "just show the SE that are in the model".

**Comment by vincentarelbundock** [comment]
Right. I'm fine with including "default".

Under-the-hood, "iid", "classical", and "constant" are just aliases for the same thing: returning whatever is the default output of `vcov(model)`.

When packages like `fixest` hard-code some adjustments, those labels can be incorrect. And then we're back with Issue https://github.com/vincentarelbundock/modelsummary/issues/280 

The question is what we should do in those cases? A warning? Do I have to maintain a list of all supported models that do not return "classical" errors by default? (I would much rather not have to do that.)

**Comment by elbersb** [comment]
> Right. I'm fine with including "default".

Did you see my second comment re `NULL`? This would also avoid another new option. But "default" is good too. 
 
> The question is what we should do in those cases? A warning? Do I have to maintain a list of all supported models that do not return "classical" errors by default? (I would much rather not have to do that.)

Yes, I can see how this can become annoying very quickly. I'll think some more about it and we can keep the discussion about that in #280.

**Comment by vincentarelbundock** [comment]
Sorry, I missed it. Yes, I think that allowing `NULL` and not cluttering the docs with yet another alias is better.

Commit https://github.com/vincentarelbundock/modelsummary/commit/f0df8c89a21a0f7688932b39be13e911bb3ad873 should allow you to do this:

```r
library("modelsummary")
library("fixest")

mod <- feols(hp ~ mpg + drat, mtcars)

vc <- list(
  "NULL" = NULL,
  "Std" = vcov(mod),
  "Clust: vs" = vcov(mod, se = "cluster", cluster = "vs"))

modelsummary(mod, vcov = vc)

```

**Comment by elbersb** [comment]
Wow, that was quick! It _almost_ works, see here the label in the last table that is off:


``` r
library("modelsummary")
library("fixest")
mod <- feols(hp ~ mpg + drat, mtcars, cluster = "vs")
modelsummary(mod, output = "markdown")
```

|             |    Model 1     |
|:------------|:--------------:|
| (Intercept) |    278.515     |
|             |    (20.573)    |
| mpg         |     -9.985     |
|             |    (4.110)     |
| drat        |     19.126     |
|             |    (32.644)    |
| Std. Errors | Clustered (vs) |

``` r
# this works as expected
modelsummary(mod, vcov = list(NULL), output = "markdown")
```

|             |    Model 1     |
|:------------|:--------------:|
| (Intercept) |    278.515     |
|             |    (20.573)    |
| mpg         |     -9.985     |
|             |    (4.110)     |
| drat        |     19.126     |
|             |    (32.644)    |
| Std. Errors | Clustered (vs) |

``` r
# here the label is dropped
modelsummary(mod, vcov = list(NULL, "iid"), output = "markdown")
```

|             | Model 1  | Model 2  |
|:------------|:--------:|:--------:|
| (Intercept) | 278.515  | 278.515  |
|             | (20.573) | (20.573) |
| mpg         |  -9.985  |  -9.985  |
|             | (4.110)  | (4.110)  |
| drat        |  19.126  |  19.126  |
|             | (32.644) | (32.644) |
| Std. Errors |          |   IID    |

<sup>Created on 2021-05-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
So the logic here is that `NULL` and `list(NULL)` are both treated as if user specified nothing for the `vcov` argument. In that case, `glance_custom.fixest` tries to extract information from the model and displays it.

However, when users supply a value for `vcov`, as in the 3rd example, then `modelsummary` takes precedence. This is important because in a lot of cases, the internal `fixest` standard errors will be overwritten by the output of some `sandwich` call.

From the user's perspective, the easy solution is to use named list in your 3rd example:

```r
modelsummary(mod, vcov = list("Std." = NULL, "IID" = "iid"), output = "markdown")
```

We might be able to insert some hardcoded logic that explicitly checks for `fixest` objects, but I think the strong precedence of `modelsummary` over internal object SEs is very important when users feed character labels.
