### ISSUE TITLE
modelsummary_list function or similar

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#295]
What do you think about a function such as the following?

```r
modelsummary_list <- function(tidy, glance) {
    if (inherits(tidy, "parameters_model")) {
        tidy <- parameters::standardize_names(tidy, style = "broom")
    }
    if (inherits(glance, "performance_model")) {
        glance <- parameters::standardize_names(glance, style = "broom")
    }
    mod <- list(tidy = tidy, glance = glance)
    class(mod) <- "modelsummary_list"
    mod
}
```

This would simplify supplying custom objects a lot, such as in this example:

``` r
library("lme4")
library("parameters")
library("modelsummary")

mod <- lmer(mpg ~ (1 | am), data = mtcars)
gof <- performance::model_performance(mod)
mod1 <- modelsummary_list(model_parameters(mod), gof)
mod2 <- modelsummary_list(model_parameters(mod, df = "kenward"), gof)

modelsummary::msummary(list("default" = mod1, "kenward" = mod2), 
    statistic = "{std.error} ({p.value}) {stars}", output = "markdown")
```

|             |       default        |    kenward    |
|:------------|:--------------------:|:-------------:|
| (Intercept) |     20.730\*\*\*     |    20.730     |
|             | 3.622 (0.000) \*\*\* | 3.623 (0.110) |
| R2 Marg.    |        0.000         |     0.000     |
| R2 Cond.    |        0.507         |     0.507     |
| AIC         |        198.8         |     198.8     |
| BIC         |        203.2         |     203.2     |
| ICC         |         0.5          |      0.5      |
| RMSE        |         4.75         |     4.75      |

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

If you like this, I can create a more thorough PR.

**Comment by vincentarelbundock** [comment]
I’m not sure I exactly understand the use-case. How does it compare to this?

``` r
library(modelsummary)

mod <- lm(hp ~ mpg, mtcars)

modelsummary(mod, output = "modelsummary_list")
#> $tidy
#> # A tibble: 2 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)   324.       27.4      11.8  8.25e-13
#> 2 mpg            -8.83      1.31     -6.74 1.79e- 7
#> 
#> $glance
#> # A tibble: 1 x 13
#>   r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC
#>       <dbl>         <dbl> <dbl>     <dbl>       <dbl> <dbl>  <dbl> <dbl> <dbl>
#> 1     0.602         0.589  43.9      45.5 0.000000179     1  -165.  337.  341.
#> # … with 4 more variables: deviance <dbl>, df.residual <int>, nobs <int>,
#> #   F <dbl>
#> 
#> attr(,"class")
#> [1] "modelsummary_list"
```

**Comment by elbersb** [comment]
Wow, you really have thought of _everything_. I thought I knew the package quite well by now, but there is still useful functionality to discover. 

The use case was to show two `lme4` models in one table, but with different degree of freedom adjustments. `parameters::model_parameters` supports this, but standardizing the names and applying the `modelsummary_list` class was quite tedious, so the idea of the function was to make this a bit easier. However, the built-in solution is, of course, much cleaner! (see below)

I do wonder whether it makes sense to include an example such as this in the docs. The ability to use `output = "modelsummary_list"` is only discussed in the "group" section right now, and "Adding new models (part I)" is not quite the same idea. For instance, `texreg` has an option `override.pvalues`, which makes it quite obvious how to achieve this output. Maybe the example below would fit well under "Customizing existing models (part III)"?

``` r
library("lme4")
library("modelsummary")

mod <- lmer(mpg ~ (1 | am), data = mtcars)
options(modelsummary_get = "easystats")
m1 <- modelsummary(mod, output = "modelsummary_list", effects = "fixed")
m2 <- modelsummary(mod, output = "modelsummary_list", df_method = "kenward", effects = "fixed")

modelsummary(list("Standard" = m1, "Kenward" = m2),
    statistic = "{std.error} ({p.value}) {stars}", output = "markdown")
```

|             |       Standard       |    Kenward    |
|:------------|:--------------------:|:-------------:|
| (Intercept) |     20.730\*\*\*     |    20.730     |
|             | 3.622 (0.000) \*\*\* | 3.623 (0.110) |
| Num.Obs.    |          32          |      32       |
| R2 Marg.    |        0.000         |     0.000     |
| R2 Cond.    |        0.507         |     0.507     |
| AIC         |        198.8         |     198.8     |
| BIC         |        203.2         |     203.2     |
| ICC         |         0.5          |      0.5      |
| RMSE        |         4.75         |     4.75      |

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
Yes, I think this would be a great addition to the vignette.

**Comment by elbersb** [comment]
OK, I'll draft something after lunch.

**Comment by vincentarelbundock** [comment]
Sounds great! Make sure you flip back the `modelsummary_get` option after the example so the rest of the vignette doesn't get new defaults.
