### ISSUE TITLE
custom tidy method without ... throws unhelpful error

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#296]
Just ran into this one. When a custom `tidy` function does not have the right signature, modelsummary throws the not-so-helpful error `Error: $ operator is invalid for atomic vectors`. Of course, it works when I add the `...`. This surely is a rare case, so I leave it to you whether it's worth improving the error message. Happy to take a look though.

``` r
library(modelsummary)
x <- structure(1, class = "somemod")
tidy.somemod <- function(mod) data.frame(term = 1)
glance.somemod <- function(mod) data.frame()
tidy(x)
#>   term
#> 1    1

modelsummary::msummary(x)
#> Error: $ operator is invalid for atomic vectors

tidy.somemod <- function(model, ...) data.frame(term = 1)
modelsummary::msummary(x)
#> Error in format_estimates(est = msl[[i]]$tidy, fmt = fmt, estimate = estimate[[i]], : These estimates or statistics do not seem to be available: estimate, std.error. You can use the `get_estimates` function to see which statistics are available.
```

<sup>Created on 2021-05-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
Say I have an `obj` model of unknown class, what you are proposing is:

1. Figure out if a `tidy_custom` method will be triggered by this object
2. Retrieve that method
3. Check the function signature to see if `...` is an argument
4. Raise an error or skip with warning

I'm blanking right now. How do we achieve this?
