### ISSUE TITLE
default stars

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#301]
You're probably aware of this, but the default "stars" are different from the stars printed, e.g., in `summary.lm`: `Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1`

Notably, one star means `p < 0.1` in modelsummary and `p < 0.05` in summary.lm. Maybe it would be worth explicitly mentioning this difference in the docs? Maybe just "Note that these defaults are different from R's summary function for lm objects."

**Comment by vincentarelbundock** [comment]
Oh, I had not even thought of that.

Is this really a problem, though? My guess is people's expectation are probably much more guided by disciplinary norms than by `R`'s defaults. 

The tables include an explicit footnote, and the docs state clearly:

` • TRUE: *=.1, **=.05, ***=.01`

The docs are pretty "heavy" already, so I'm  not 100% convinced this is necessary, but at the same time I don't have a very strong opinion about this, so if you feel it is important, I won't block the merge.

**Comment by elbersb** [comment]
Surely not 100% necessary, but given that (a) the stars are (unfortunately) such an integral part of the output, and (b) the default is different from base R, texreg, esttab (Stata), I think a hint is helpful.

As an aside, one reason I teach this package (and use it myself, of course) are exactly the heavy-handed docs. Especially compared to the Stata docs, this is not an area in which R generally shines, although things are improving, as this package shows. I'm opening a PR right now, feel free to merge or close - wasn't much work ;)

**Comment by vincentarelbundock** [comment]
Sounds good.

But shouldn't we change the `modelsummary` defaults instead? 

Any backward compatibility issue with that?

The dot (`.`) works nicely as a "star" in terminal output, but would it look good in an HTML or LaTeX table?

I assume a lot of the tests would require adjustment, but that's probably not terrible.

**Comment by vincentarelbundock** [comment]
Doesn't look great...

<img width="802" alt="Screen Shot 2021-05-13 at 08 12 33" src="https://user-images.githubusercontent.com/987057/118124012-02172d00-b3c3-11eb-84e0-9eb727308f54.png">

**Comment by vincentarelbundock** [comment]
We could do some kind of unicode character like a middle dot, but it's probably best to stick with standard ascii since unicode isn't displayed well on all plateforms or with all typefaces.

**Comment by elbersb** [comment]
Changing the defaults would work well for me, although some people might've gotten used to the current defaults. But the package is still pre 1.0.0, so I guess it would be fine. The dot does look awkward though, maybe a plus is better?

**Comment by vincentarelbundock** [comment]
The `+` for 0.1 threshold also seems to be default in other packages:

https://www.rdocumentation.org/packages/gtools/versions/3.5.0/topics/stars.pval

If our default needs explaining, then we should probably change the default.

**Comment by elbersb** [comment]
I would be in support of that, and displaying the dot as a plus sign seems to me also a pretty standard solution. I can look into a PR, but knowing you, you might already be on it :)

**Comment by vincentarelbundock** [comment]
ha! No, I've done about as much `modelsummary`-related procrastination as I can afford for the next two weeks and there are lots of deadlines approaching. So my plan is to scale back a bit in the coming days.

**Comment by elbersb** [comment]
Same here! My teaching prep is almost done, so I probably won't open any more issues either. I'll try to tackle this one later today. 

Just to be sure we're on the same page, we will change the new default to `+=0.1, *=.05, **=.01, ***=.001`, right?

**Comment by vincentarelbundock** [comment]
Yep, sounds good. Thanks!
