### ISSUE TITLE
Allow multiple modelsummary columns with the same name

### ISSUE THREAD

**Issue by NickCH-K** [vincentarelbundock/modelsummary#304]
If `modelsummary` is given two models, each with the same name, it will keep only one of them:

```{r}
library(modelsummary)

m1 <- lm(mpg ~ hp, data = mtcars)
m2 <- lm(mpg ~ hp + cyl, data = mtcars)

msummary(list('a'=m1,'a'=m2))
msummary(dvnames(list(m1,m2)))
```

This is easy enough to get around if you're naming models yourself (although likely to be unexpected behavior), but poses a problem for `dvnames()` (oops).

I haven't dug into where exactly these get dropped, but assuming that it's just a step where it uses the model names to pull a model from the list, there are some potential fixes (which I'd be happy to implement):

1. If there are duplicate names in the model list, automatically number them, as Model 1, Model 2, etc., is done for unnamed model lists
2. If there are duplicate names in the model list, add blank characters to distinguish them so they all show up as entered (I've been getting around this myself by adding spaces after the names)
3. Leave as-is for explicitly given names, but change the function of `dvnames()` to add numbers to duplicate names

**Comment by vincentarelbundock** [comment]
Thanks for catching this!

The intention was always to do solution 2: pad column names with white space to allow duplicates. I swear an old version did this, but it must have dropped out in a re-factor.

Commit <https://github.com/vincentarelbundock/modelsummary/commit/682cee756946e39623a1b9697452b635034ccd22> fixes the problem and introduces a test so the feature won’t drop out in the future.

``` r
library(modelsummary)

m1 <- lm(mpg ~ hp, data = mtcars)
m2 <- lm(mpg ~ hp + cyl, data = mtcars)

msummary(list("a" = m1, "a" = m2))
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
a
</th>
<th style="text-align:center;">
a
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
30.099
</td>
<td style="text-align:center;">
36.908
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(1.634)
</td>
<td style="text-align:center;">
(2.191)
</td>
</tr>
<tr>
<td style="text-align:left;">
hp
</td>
<td style="text-align:center;">
-0.068
</td>
<td style="text-align:center;">
-0.019
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.010)
</td>
<td style="text-align:center;">
(0.015)
</td>
</tr>
<tr>
<td style="text-align:left;">
cyl
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
-2.265
</td>
</tr>
<tr>
<td style="text-align:left;box-shadow: 0px 1px">
</td>
<td style="text-align:center;box-shadow: 0px 1px">
</td>
<td style="text-align:center;box-shadow: 0px 1px">
(0.576)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:center;">
0.602
</td>
<td style="text-align:center;">
0.741
</td>
</tr>
<tr>
<td style="text-align:left;">
R2 Adj.
</td>
<td style="text-align:center;">
0.589
</td>
<td style="text-align:center;">
0.723
</td>
</tr>
<tr>
<td style="text-align:left;">
AIC
</td>
<td style="text-align:center;">
181.2
</td>
<td style="text-align:center;">
169.6
</td>
</tr>
<tr>
<td style="text-align:left;">
BIC
</td>
<td style="text-align:center;">
185.6
</td>
<td style="text-align:center;">
175.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Log.Lik.
</td>
<td style="text-align:center;">
-87.619
</td>
<td style="text-align:center;">
-80.781
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;">
45.460
</td>
<td style="text-align:center;">
41.422
</td>
</tr>
</tbody>
</table>

``` r
msummary(dvnames(list(m1, m2)))
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
mpg
</th>
<th style="text-align:center;">
mpg
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
30.099
</td>
<td style="text-align:center;">
36.908
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(1.634)
</td>
<td style="text-align:center;">
(2.191)
</td>
</tr>
<tr>
<td style="text-align:left;">
hp
</td>
<td style="text-align:center;">
-0.068
</td>
<td style="text-align:center;">
-0.019
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.010)
</td>
<td style="text-align:center;">
(0.015)
</td>
</tr>
<tr>
<td style="text-align:left;">
cyl
</td>
<td style="text-align:center;">
</td>
<td style="text-align:center;">
-2.265
</td>
</tr>
<tr>
<td style="text-align:left;box-shadow: 0px 1px">
</td>
<td style="text-align:center;box-shadow: 0px 1px">
</td>
<td style="text-align:center;box-shadow: 0px 1px">
(0.576)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:center;">
32
</td>
<td style="text-align:center;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:center;">
0.602
</td>
<td style="text-align:center;">
0.741
</td>
</tr>
<tr>
<td style="text-align:left;">
R2 Adj.
</td>
<td style="text-align:center;">
0.589
</td>
<td style="text-align:center;">
0.723
</td>
</tr>
<tr>
<td style="text-align:left;">
AIC
</td>
<td style="text-align:center;">
181.2
</td>
<td style="text-align:center;">
169.6
</td>
</tr>
<tr>
<td style="text-align:left;">
BIC
</td>
<td style="text-align:center;">
185.6
</td>
<td style="text-align:center;">
175.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Log.Lik.
</td>
<td style="text-align:center;">
-87.619
</td>
<td style="text-align:center;">
-80.781
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;">
45.460
</td>
<td style="text-align:center;">
41.422
</td>
</tr>
</tbody>
</table>

**Comment by NickCH-K** [comment]
Awesome! Thanks
