### ISSUE TITLE
kable_styling(full_width = FALSE) cannot be undone

### ISSUE THREAD

**Issue by NickCH-K** [vincentarelbundock/modelsummary#305]
I am very likely the *only* person with this use case so it's probably best to leave this one be, and I'll just make a forked version with the change I need. 

When the `modelsummary` output is via **kableExtra**, it applies `kable_styling(full_width = FALSE)`, with the doc note that "# styling can be overriden by user by calling again". However, this is not true.

Compare:

```{r}
library(magrittr)
library(kableExtra)
kbl(mtcars)
kbl(mtcars) %>% kable_styling(full_width = FALSE)
kbl(mtcars) %>% kable_styling(full_width = FALSE) %>% kable_styling(full_width = TRUE)
kbl(mtcars) %>% kable_styling(full_width = FALSE) %>% kable_styling(full_width = NULL)
```

This is causing me a problem as I am using `modelsummary` with **bookdown**/**tufte**. The `full_width = FALSE` setting is causing tables to span both the text and sidenote columns, rather than just the text column. As an example (first table created with `kableExtra::kbl()` and no styling, second and third with `msummary()`. These latter two are piped to `kable_styling(full_width = TRUE)` and `=NULL`, respectively, but the same thing happens with no `kable_styling`.

![image](https://user-images.githubusercontent.com/44816781/118225569-3843c380-b43a-11eb-8400-e6cb96f9a3ae.png)

Again, the problem here is so niche (and the current styling looks better) that it may be better to leave the functionality as it is and I'll just make a modified version of **modelsummary** that does what I want. But thought I'd mention it.

**Comment by vincentarelbundock** [comment]
No, I think this is an important problem, and I've run into something similar myself before (even made some commits to `kableExtra` to achieve something similar). 

Would using `output="latex_tabular"` work for you? Compare these:

```{r}
library(modelsummary)
library(kableExtra)

mod = lm(hp ~ mpg, mtcars)

modelsummary(mod, "latex")

modelsummary(mod, "latex_tabular")

modelsummary(mod, "latex_tabular") %>%
    kable_styling(full_width = TRUE)

modelsummary(mod, "latex_tabular") %>%
    kable_styling(full_width = FALSE)
```

If it does *not* work, let me know what output you expect, and I'm sure we can find a solution. Let's not force you to work with a fork

**Comment by NickCH-K** [comment]
Oh, this is HTML output so `latex_tabular` wouldn't work.

Bookdown does all sorts of its own styling to `kable`s, so any `kable_styling` applied before that tends to mess things up, although usually in ways that don't matter (and I suspect that in standard Bookdown there's no issue here, it's just that I'm using **tufte**). The intended output is the first table shown in my image (cut off at the top), which was created purely with `kableExtra::kbl(mtcars)` and works fine. I've similarly had no problem with `knitr::kable()` or `vtable::sumtable(out = 'kable')`, both of which are unstyled in the code but then Bookdown styles them, e.g.:

![image](https://user-images.githubusercontent.com/44816781/118317965-9493fb00-b4ad-11eb-9343-50d8f1d83eee.png)

I haven't managed to check it within Bookdown yet since that would require the forked version I was talking about, but when I modify `factory_kableExtra` to remove line 104 where `kable_styling()` is applied, I get the intended output. Maybe `...` could accept a `full_width` option, and default it to `FALSE` if `!('full_width' %in% names(list(...)))`? `kableExtra::kbl()` doesn't seem to complain if you pass it a `full_width` option so I don't think including it in the `...` would mess anything else up.

Something like:

```{r}
  full_width <- FALSE
  if ('full_width' %in% names(list(...))) {
    full_width <- list(...)[['full_width']]
  }
  
  if (!output_format %in% c("markdown", "latex_tabular")) {
    out <- kableExtra::kable_styling(out, full_width = full_width)
  }
```

**Comment by vincentarelbundock** [comment]
Ah, I get it now.

For a while, I've been thinking about implementing a global option for backend-specific themes. For `kableExtra`, the default theme would be the current version. But you could define your own themes that would then apply globally. If you don't want anything to be applied and just get the raw `kableExtra` table without any `kable_styling`, you could then do something like:

```r
options(modelsummary_kableExtra_theme = identity)
```

Internally, the table would just be piped to the `identity` function, which wouldn't change anything.

Do you think this would solve the issue for you?

**Comment by NickCH-K** [comment]
Oh that would definitely solve the issue!

**Comment by vincentarelbundock** [comment]
Cool. Will give it a shot. I think it'll be easy to implement, but I might have a to iterate a bit before settling on a "final" user interface.

Will ping you when I have something.

**Comment by NickCH-K** [comment]
Thank you very much!

**Comment by vincentarelbundock** [comment]
I will keep playing with this and might still change some things, but there's a working alpha commit on Github now.

The default theme (for inspiration) is here:

<https://github.com/vincentarelbundock/modelsummary/blob/main/R/themes.R#L1>

But if you just want a barebones table, you can do something like (the `...` are essential):

``` r
library(modelsummary)
options(modelsummary_theme_kableExtra = function(x, ...) x)

mod <- lm(hp ~ mpg, mtcars)
modelsummary(mod)
```

<img width="146" alt="Screen Shot 2021-05-16 at 09 24 06" src="https://user-images.githubusercontent.com/987057/118398888-7e5e7a00-b628-11eb-8167-181620e8bf62.png">

**Comment by NickCH-K** [comment]
It works great! Thank you.

And thank goodness for the issue too, or I likely wouldn't have noticed the significance star level switch. All the `msummary()` examples in the book would have been wrong :P

**Comment by vincentarelbundock** [comment]
Oh wow, yes! I'm sorry for this!

I was worried about backward compatibility, but given that we are version less than 1, I concluded that making the stars consistent with base `R` was a good move.

Do you think this is too dangerous to release in the wild?

I'm glad you saw this!

**Comment by NickCH-K** [comment]
I think being consistent with base R only makes sense, although I'll be bummed - I did really like not having to teach my students about named vectors (might be neat to be able to have stars accept a string as shorthand for different star standards). It would probably be a good idea to add a warning that triggers on stars = TRUE for a few versions. Otherwise it can be easy to miss that anything changed

**Comment by vincentarelbundock** [comment]
The warning makes a lot of sense. @elbersb do you have an idea for best implementation? Ideally, the warning wouldn't be too intrusive, and we wouldn't rely on external packages, but there's a `frenquency` argument in the `rlang::warn` function (e.g., "once per session"), and `broom` imports depends on `rlang`, so we will always have that installed.

**Comment by elbersb** [comment]
`rlang::warn` sounds like a good way to go. Another idea would be a package startup message. Usually not a huge fan of those, but if it's not too intrusive, it might make sense. It could in the future be used to advertise new features (also hard to miss for people who upgrade) or to possibly mention other breaking changes.

**Comment by vincentarelbundock** [comment]
cool, I'll go with `rlang::warn` then. I know it's not rational, but I'm repulsed by startup messages ;)

**Comment by vincentarelbundock** [comment]
stars warning: fd165f3
