### ISSUE TITLE
Super script not working with gt output

### ISSUE THREAD

**Issue by nithinmkp** [vincentarelbundock/modelsummary#306]
The html style superscript works fine with output html. The corresponding latex style also works with kableextra package. But the superscript doesn't work with gt output even after specifying escape=F

**Comment by vincentarelbundock** [comment]
Thanks for opening the issue.

It is much easier for me to diagnose the issue when people supply a [Minimal Working Example.](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)

In this case, since the problem is almost certainly related to the `gt` package rather than `modelsummary`, it would be especially useful if you could show m:

1. The code you have tried in `modelsummary`
2. A super simple example of a raw `gt` table where you sucessfully include a superscript.

If you figure out how to include a superscript in `gt`, we will almost certainly have an easy solution in `modelsummary`.

**Comment by nithinmkp** [comment]
Sure.
Here it goes
library(gt)
library(modelsummary)

gof_map2_html <- tribble(
        ~raw,      ~clean,          ~fmt,  ~omit,
        "nobs",      "Observations",     0,  FALSE,
        "r.squared", "R<sup>2</sup>",               3,  FALSE,
        "adj.r.squared","Adj.R<sup>2</sup>",3,FALSE,
        "AIC","AIC",3,F
)

url <- '
https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list(
        "OLS 1"     = lm(Donations ~ Literacy + Clergy, data = dat),
        "Poisson 1" = glm(Donations ~ Literacy + Commerce, family =
poisson, data = dat),
        "OLS 2"     = lm(Crime_pers ~ Literacy + Clergy, data = dat),
        "Poisson 2" = glm(Crime_pers ~ Literacy + Commerce, family =
poisson, data = dat),
        "OLS 3"     = lm(Crime_prop ~ Literacy + Clergy, data = dat)
)

cm <- c('Literacy'    = 'Literacy (%)',
        'Commerce'    = 'Patents per capita',
        '(Intercept)' = 'Constant')

cap <- 'A modelsummary table customized with gt'

tab<-modelsummary(models,stars = T,
                  gof_map = gof_map2_html,
                  statistic = "statistic",
                  coef_map = cm,
                  output = "gt",
                  escape=F,
                  title = cap)

tab_gt<-tab %>%

        # column labels
        tab_spanner(label = 'Donations', columns = 2:3) %>%
        tab_spanner(label = 'Crimes (persons)', columns = 4:5) %>%
        tab_spanner(label = 'Crimes (property)', columns = 6)

The html output is just fine thanks to an earlier issue I raised . Latex
output works fine too with kableExtra package

Thanks and Regards

**Comment by vincentarelbundock** [comment]
Thanks, but you did not give me the two examples I requested. For example, say you want to display this super simple example of a raw `gt` table:

```r
library(gt)

dat <- data.frame(
    "a" = "2^2",
    "b" = "3^4")

gt(dat)
```

In this example, the superscripts will *not* work well; you will see the `^` symbol instead. My question to you is: How do you make superscripts appear in a simple raw `gt` table?

Once you find a solution to the simple puzzle I posed above, you should have a solution to your whole problem.

Another way of saying the same thing is that this seems like a pure `gt` problem, not one that should be solved by the `modelsummary` developer. If you are able to produce superscripts in a raw `gt` table, but then are unable to transfer the same strategy to `modelsummary`, then that becomes a bug I should handle. In that case, feel free to re-open this issue, and I will be more than happy to address it.

**Comment by nithinmkp** [comment]
Ok, I will do that. There is a solution in gt using fmt_markdown(). We can
pass columns or rows to that. I tried implementing that but the output of
modellsummary is not gt object rather grouped Ribble.. that was the issue

**Comment by vincentarelbundock** [comment]
`gt` seems to work well with HTML, and I strongly advise against using `gt` to produce LaTeX or PDF output. It’s LaTeX output capabilities are not mature at all, as evidence by longstanding bugs reported in their github.

``` r
library(modelsummary)
library(gt)
library(magrittr)
library(tibble)

mod <- lm(hp ~ mpg, mtcars)

gm <- tribble(
  ~raw, ~clean, ~fmt,
  "r.squared", "R<sup>2</sup>", 2
)

modelsummary(mod, output = "gt", gof_map = gm) %>%
    fmt_markdown(columns = 1)
```

![markdown](https://user-images.githubusercontent.com/987057/118277868-47a52a00-b497-11eb-8a82-2c4ede8a3eea.png)

**Comment by nithinmkp** [comment]
Yes sure..I understand that . I was confused whether passing column affects
every rows and was trying to pass rows which was throwing that error .

Thanks a ton for your help

Nithin
