### ISSUE TITLE
cannot use modelsummary via Rscript

### ISSUE THREAD

**Issue by lidinghi** [vincentarelbundock/modelsummary#308]
I find that modelsummary does not work properly with Rscript in linux/ubuntu. For instance, the following R script (modelsummary_test.R) works well in Rstudio. 

```
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)

library(modelsummary)

msummary(
  lm.D9,
  fmt='%.7f',
  stars=T,
  output = "tmp.html" #, ## Optional if saving to MS Word as OP requested
  # se.type = 'robust'     ## Argument being passed to tidy.lfe::felm()
)
```

However, if I run this script using `Rscript modelsummary_test.R >& test.txt` in terminal. The following error is returned,

```
sh: 1: +RTS: not found
Error: pandoc document conversion failed with error 127
In addition: Warning message:
In system(command) : error in running command
Execution halted
```

I tested in two linux servers. Both returned the same error.

**Comment by vincentarelbundock** [comment]
Thanks for the report.

I am UNable to replicate the problem on Mac OS.

Do you have `pandoc` installed on those servers?

Is this a `modelsummary`-specific problem or is it a `kableExtra`-specific problem. Can you create a simple `kableExtra` table and save it to file using `save_kable`?

If this is a `kableExtra` problem, you might want to another export backend. For instance, try `output="gt"` combined with `gt::gtsave` instead. Or try `output="flextable"` (see their website for more info).

**Comment by elbersb** [comment]
Possibly helpful: https://stackoverflow.com/questions/54081994/r-package-exams-not-importing-r-markdown

**Comment by vincentarelbundock** [comment]
feel free to re-open this issue or to open a new one if this is a `modelsummary` specific error rather than a `kableExtra` or `gt` problem.
