### ISSUE TITLE
output allowing a vector

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#310]
Just a quick thought: Would it make sense to allow the `output` argument to `modelsummary` and `datasummary` to be a vector? That could be used to output, say, a tex and html file simultaneously. Of course, the immediate question is what the functions should return when several non-filenames are supplied, or a filename and a non-filename. I would definitely use this if this were implemented, but it might complicate things too much.

**Comment by vincentarelbundock** [comment]
The two ways I can see this being implemented is as a global loop in `modelsummary()` or by creating a new internal function to hold everything that is currently in `modelsummary`, and turning `modelsummary` into a thin wrapper that loops over `output`.

Honestly, I think neither option is very elegant, they add some code complexity (especially approach 2), and the clarity of documentation for the `output` argument will be affected.

My current gut feeling is that this is a little bit of a niche application, and that it is easy enough for users to achieve the same result with a simple loop:

```r
library(modelsummary)

for (f in c("test.html", "test.tex")) {
  modelsummary(mod, output = f)
}
```

**Comment by vincentarelbundock** [comment]
Also, the fact that this would have to be implemented as a kind of "global" loop in the `modelsummary` function kind of suggests that this maybe should be a loop *around* `modelsummary` anyway.

**Comment by elbersb** [comment]
Agree in principle, but the loop would only need to start after the output data frame is constructed, so I don't think it would be quite so inelegant. Anyway, I don't have strong feelings about this, so I'm closing for now.
