### ISSUE TITLE
Glue statistic not working

### ISSUE THREAD

**Issue by ericrgottlieb** [vincentarelbundock/modelsummary#317]
I am finding today that a "glue" string for my statistic argument that previously worked is now giving an error. I have not changed the code.

statistic = "p{ifelse(p.value <0.001, '<', '=')}{ifelse(p.value <0.001, '0.001', p.value)}"

I get the following error:
Error in format_estimates(est = msl[[i]]$tidy, fmt = fmt, estimate = estimate[[i]],  : 
  These estimates or statistics do not seem to be available: ifelse(p.value <0.001, '<', '='), ifelse(p.value <0.001, '0.001', p.value). You can use the `get_estimates` function to see which statistics are available.

I am still able to insert {p.value} by itself, and this works.

Thank you!
-Eric

**Comment by vincentarelbundock** [comment]
Thanks for the bug report. I introduced a test with an informative message when glue string statistics were not available, but I did not take this use case into account. I removed the test in commit 75baaa9. If you install it from github and restart R completely, your example should work.

This will be part of the next 0.8.1 release.
