### ISSUE TITLE
When using coef_rename, colons are replaced by "x"

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#318]
See title. Interestingly, doesn't happen with `coef_map`:

``` r
library("modelsummary")
mod <- lm(mpg ~ disp, data = mtcars)
modelsummary(mod, coef_rename = c("disp" = "a:b"), output = "markdown")
```

|             | Model 1 |
|:------------|:-------:|
| (Intercept) | 29.600  |
|             | (1.230) |
| a × b       | -0.041  |
|             | (0.005) |
| Num.Obs.    |   32    |
| R2          |  0.718  |
| R2 Adj.     |  0.709  |
| AIC         |  170.2  |
| BIC         |  174.6  |
| Log.Lik.    | -82.105 |
| F           | 76.513  |

``` r
modelsummary(mod, coef_map = c("disp" = "a:b"), output = "markdown")
```

|          | Model 1 |
|:---------|:-------:|
| a:b      | -0.041  |
|          | (0.005) |
| Num.Obs. |   32    |
| R2       |  0.718  |
| R2 Adj.  |  0.709  |
| AIC      |  170.2  |
| BIC      |  174.6  |
| Log.Lik. | -82.105 |
| F        | 76.513  |

<sup>Created on 2021-05-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment]
Thanks!

We convert : to x automagically to make interaction terms cleaner, but we should only do it when both `coef_rename` and `coef_map` are `NULL`. 

Commit da9aff7 should fix this.

**Comment by elbersb** [comment]
Great!
