### ISSUE TITLE
coef_map and factor variables

### ISSUE THREAD

**Issue by sergiu-burlacu** [vincentarelbundock/modelsummary#321]
To my understanding, once coef_map is used, you need to explicitly include the names of all the factor levels in coef_map, otherwise, they will be excluded from the regression table.  This seems quite repetitive for me, I imagine most people would not wish to rename their factor levels, only (maybe) renaming the variable name. 

I would propose the following change. Say x is a factor with levels c("A", "B). By including x in coef_map, "x" = "Name X", you would end up with the following rows in a regression table:
Name X A
Name X B 

without having to include the name of all factor levels in coef_map.

PS: thank you for this wonderful package. I was toying around with a similar idea some years back but nothing close to what you achieved.

**Comment by vincentarelbundock** [comment]
Thanks!

This is interesting, but I'm curious about how this would generalize. What about multiple distinct factors? What about interactions between factors? Interactions between non-factors?

I'm sure we could cook up a regex that works in most cases, but would that regex create problems if users' variables are weirdly named?

One first-cut approach would be to try to write a safe and generalizable function to feed to the `coef_rename` function. Notice in the docs that you can feed that argument any arbitrary function that takes a vector of coefficient names and returns a transformed character vector. This allows users to automatically do the kind of modifications you have in mind.

On the one hand, you might find that a simple function does trick for you. On the other, if you are able to design a truly generalizable and safe function, then we will already have code that I can consider adding to `modelsummary`'s base function.

The main issues to keep in mind, I think, are:

1. safety
2. not too much automatic transformation unless requested
3. keep the user interface as simple and consistent as possible

**Comment by vincentarelbundock** [comment]
Circling back to this, it feels to me that the ability of `coef_rename` to accept a function meets this need. You can easily create a custom function using `gsub` to replace factor levels in term names.

Closing now, but feel free to re-open or to open a new issue to explain why the approach is unsatisfactory.

``` r
library(modelsummary)
mod <- lm(mpg ~ factor(cyl), mtcars)

modelsummary(mod, coef_rename = function(x) gsub("factor\\(cyl\\)", "Cylinders: ", x))
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
Model 1
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:center;">
26.664
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(0.972)
</td>
</tr>
<tr>
<td style="text-align:left;">
Cylinders: 6
</td>
<td style="text-align:center;">
-6.921
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(1.558)
</td>
</tr>
<tr>
<td style="text-align:left;">
Cylinders: 8
</td>
<td style="text-align:center;">
-11.564
</td>
</tr>
<tr>
<td style="text-align:left;box-shadow: 0px 1px">
</td>
<td style="text-align:center;box-shadow: 0px 1px">
(1.299)
</td>
</tr>
<tr>
<td style="text-align:left;">
Num.Obs.
</td>
<td style="text-align:center;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
R2
</td>
<td style="text-align:center;">
0.732
</td>
</tr>
<tr>
<td style="text-align:left;">
R2 Adj.
</td>
<td style="text-align:center;">
0.714
</td>
</tr>
<tr>
<td style="text-align:left;">
AIC
</td>
<td style="text-align:center;">
170.6
</td>
</tr>
<tr>
<td style="text-align:left;">
BIC
</td>
<td style="text-align:center;">
176.4
</td>
</tr>
<tr>
<td style="text-align:left;">
Log.Lik.
</td>
<td style="text-align:center;">
-81.282
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;">
39.698
</td>
</tr>
</tbody>
</table>
<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_Canada.1252         
#>  ctype    English_Canada.1252         
#>  tz       America/New_York            
#>  date     2021-07-05                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package      * version date       lib source             
#>  assertthat     0.2.1   2019-03-21 [1] standard (@0.2.1)  
#>  backports      1.2.1   2020-12-09 [1] standard (@1.2.1)  
#>  broom          0.7.6   2021-04-05 [1] standard (@0.7.6)  
#>  checkmate      2.0.0   2020-02-06 [1] standard (@2.0.0)  
#>  cli            2.5.0   2021-04-26 [1] standard (@2.5.0)  
#>  colorspace     2.0-1   2021-05-04 [1] standard (@2.0-1)  
#>  crayon         1.4.1   2021-02-08 [1] standard (@1.4.1)  
#>  DBI            1.1.1   2021-01-15 [1] standard (@1.1.1)  
#>  digest         0.6.27  2020-10-24 [1] standard (@0.6.27) 
#>  dplyr          1.0.6   2021-05-05 [1] standard (@1.0.6)  
#>  ellipsis       0.3.2   2021-04-29 [1] standard (@0.3.2)  
#>  evaluate       0.14    2019-05-28 [1] standard (@0.14)   
#>  fansi          0.4.2   2021-01-15 [1] standard (@0.4.2)  
#>  fs             1.5.0   2020-07-31 [1] standard (@1.5.0)  
#>  generics       0.1.0   2020-10-31 [1] standard (@0.1.0)  
#>  glue           1.4.2   2020-08-27 [1] standard (@1.4.2)  
#>  highr          0.9     2021-04-16 [1] standard (@0.9)    
#>  htmltools      0.5.1.1 2021-01-22 [1] standard (@0.5.1.1)
#>  httr           1.4.2   2020-07-20 [1] standard (@1.4.2)  
#>  kableExtra     1.3.4   2021-02-20 [1] standard (@1.3.4)  
#>  knitr          1.33    2021-04-24 [1] standard (@1.33)   
#>  lifecycle      1.0.0   2021-02-15 [1] standard (@1.0.0)  
#>  magrittr       2.0.1   2020-11-17 [1] standard (@2.0.1)  
#>  modelsummary * 0.8.1   2021-06-17 [1] standard (@0.8.1)  
#>  munsell        0.5.0   2018-06-12 [1] standard (@0.5.0)  
#>  pillar         1.6.1   2021-05-16 [1] standard (@1.6.1)  
#>  pkgconfig      2.0.3   2019-09-22 [1] standard (@2.0.3)  
#>  purrr          0.3.4   2020-04-17 [1] standard (@0.3.4)  
#>  R.cache        0.14.0  2019-12-06 [1] standard (@0.14.0) 
#>  R.methodsS3    1.8.1   2020-08-26 [1] standard (@1.8.1)  
#>  R.oo           1.24.0  2020-08-26 [1] standard (@1.24.0) 
#>  R.utils        2.10.1  2020-08-26 [1] standard (@2.10.1) 
#>  R6             2.5.0   2020-10-28 [1] standard (@2.5.0)  
#>  reprex         2.0.0   2021-04-02 [1] standard (@2.0.0)  
#>  rlang          0.4.11  2021-04-30 [1] standard (@0.4.11) 
#>  rmarkdown      2.8     2021-05-07 [1] CRAN (R 4.1.0)     
#>  rstudioapi     0.13    2020-11-12 [1] standard (@0.13)   
#>  rvest          1.0.0   2021-03-09 [1] standard (@1.0.0)  
#>  scales         1.1.1   2020-05-11 [1] standard (@1.1.1)  
#>  sessioninfo    1.1.1   2018-11-05 [1] standard (@1.1.1)  
#>  stringi        1.6.2   2021-05-17 [1] CRAN (R 4.1.0)     
#>  stringr        1.4.0   2019-02-10 [1] standard (@1.4.0)  
#>  styler         1.3.2   2020-02-23 [1] standard (@1.3.2)  
#>  svglite        2.0.0   2021-02-20 [1] standard (@2.0.0)  
#>  systemfonts    1.0.2   2021-05-11 [1] standard (@1.0.2)  
#>  tables         0.9.6   2020-09-22 [1] standard (@0.9.6)  
#>  tibble         3.1.2   2021-05-16 [1] standard (@3.1.2)  
#>  tidyr          1.1.3   2021-03-03 [1] standard (@1.1.3)  
#>  tidyselect     1.1.1   2021-04-30 [1] standard (@1.1.1)  
#>  utf8           1.2.1   2021-03-12 [1] standard (@1.2.1)  
#>  vctrs          0.3.8   2021-04-29 [1] standard (@0.3.8)  
#>  viridisLite    0.4.0   2021-04-13 [1] standard (@0.4.0)  
#>  webshot        0.5.2   2019-11-22 [1] standard (@0.5.2)  
#>  withr          2.4.1   2021-01-26 [1] standard (@2.4.1)  
#>  xfun           0.23    2021-05-15 [1] standard (@0.23)   
#>  xml2           1.3.2   2020-04-23 [1] standard (@1.3.2)  
#>  yaml           2.2.1   2020-02-01 [1] standard (@2.2.1)  
#> 
#> [1] C:/Users/vince/R/win-library/4.1
#> [2] C:/Program Files/R/R-4.1.0/library
```

</details>
