### ISSUE TITLE
Float in Latex

### ISSUE THREAD

**Issue by mathijsdevaan** [vincentarelbundock/modelsummary#324]
Is it possible to turn off the float environment when saving a Latex table? So instead of being wrapped in \begin{table}, \end{table}, the output would start with \begin{tabular}. This feature would be similar to Stargazer's float argument. Thanks!

**Comment by vincentarelbundock** [comment]
Have you tried `output="latex_tabular"ˋ (in versions >0.8.0)?

**Comment by mathijsdevaan** [comment]
Fantastic. Thank you.
