### ISSUE TITLE
circular error message: loo is not supported if model has weights 

### ISSUE THREAD

**Issue by heffaywrit** [vincentarelbundock/modelsummary#325]
When I call modelsummary() on a stanreg object fitted with weights, I receive the loo error message that it's not supported. It recommends calling kfold() to refit the object without weights. When I follow that recommendation, I get a loo error message that it's not supported for models fit with weights. 

Can I toggle a setting so that it doesn't perform the check? 

class(mod)
[1] "stanreg" "glm"     "lm"      "lmerMod"

modelsummary(mod, statistic = "[{conf.low}, {conf.high}]")
'loo' is not supported if model has weights. If refitting the model 'nobs(x)' times is feasible, we recommend calling 'kfold' with K equal to the total number of observations in the data to perform exact LOO-CV.

kfold(mod, K = 18457)
Error in kfold.stanreg(mod, K = 18457) : 
  kfold is not currently available for models fit using weights.

**Comment by vincentarelbundock** [comment]
This is a problem with one of the upstream packages that are used to extract information from model objects, either `broom` or `parameters`. I have never worked with this kind of object personally, but I think `stanreg` models are handled by `parameters`. If that's the case, you can specify the goodness-of-fit statistics you want using a `metrics` argument. See here:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#why-is-modelsummary-so-slow-

Let me know if that helps.

**Comment by vincentarelbundock** [comment]
Since this seems to be an upstream issue, I think it should be reported to the `performance` package repository rather than here. In the meantime, you should be able to use the `metrics` argument to avoid the issue.

Feel free to re-open the issue or open a new one if you think my diagnostic is erroneous.

Thanks for the report!
