### ISSUE TITLE
Support new statistical models

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#329]
Feature request: Support new statistical models

`modelsummary` does not extract estimates or statistical results from model objects itself. Instead, it relies on [the `broom`](https://broom.tidymodels.org/) and the [`parameters`](https://github.com/easystats/parameters) packages to do this work.

The `broom` package uses two simple functions to extract model info: `tidy` and `glance`. In an ideal world, the package maintainers for individual statistical models would supply these functions for their models. Many maintainers are already doing this, as `tidy` and `glance` look like an emerging "standard" in the community.

If the package maintainer is unwilling or unable to implement these functions, the next best option is to file requests on the Github pages of the `broom` and/or `parameters` packages to request support for the model in question. Obviously, the maintainers of `broom` and `parameters` packages are doing this for free, and their time is limited, so it's always a great idea to supply code if possible.

Finally, if you just want `modelsummary` to work immediately with your (previously unsupported) model, it is *very* easy to define `tidy` and `glance` methods that will do the work for you. This section of the documentation gives the intuition and a couple very simple examples:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-models-part-i-

**Comment by Nelson-Gon** [comment]
Hi, thanks for the package. Commenting to vote for addition of `gam` class to `modelsummary`

**Comment by vincentarelbundock** [comment]
Hi @Nelson-Gon 

GAMs are already supported. Are you having problems with a specific model? Can you show me some replicable code and data?

This recent Twitter thread may be helpful:

https://twitter.com/vincentab/status/1519792906571292672?s=21&t=4ZF5juCeBWzSyGh-T5r1uw

**Comment by Nelson-Gon** [comment]
Thanks, I'll try again and if it fails provide a reprex.

**Comment by vincentarelbundock** [comment]
This is now requested much less often since we rely on `parameters` and `performance`. I will close this.
