### ISSUE TITLE
datasummary_crosstab minimalist

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#331]
How to use `statistic` to make it super minimalist?

**Comment by vincentarelbundock** [comment]
@elbersb , FYI I just pushed a commit to allow `statistic=NULL` for very simple crosstabs:

``` r
library(modelsummary)
datasummary_crosstab(gear * cyl ~ am, statistic = NULL, data = mtcars)
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
gear
</th>
<th style="text-align:left;">
cyl
</th>
<th style="text-align:right;">
0
</th>
<th style="text-align:right;">
1
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
1.0
</td>
<td style="text-align:right;">
0.0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
0.0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
8
</td>
<td style="text-align:right;">
12.0
</td>
<td style="text-align:right;">
0.0
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
6.0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
2.0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
8
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
0.0
</td>
</tr>
<tr>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2.0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
1.0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
8
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
2.0
</td>
</tr>
</tbody>
</table>

**Comment by elbersb** [comment]
nice!
