### ISSUE TITLE
gtsummary vs modelsummary?

### ISSUE THREAD

**Issue by seanhardison1** [vincentarelbundock/modelsummary#34]
I'm trying to run the code included in the `.README` file to install the package:

`remotes::install_github('vincentarelbundock/modelsummary')`

Shouldn't this instead be `remotes::install_github('vincentarelbundock/gtsummary')`?

**Comment by vincentarelbundock** [comment]
@seanhardison1 I'm finalizing the package name change motivated by the issues described here: https://github.com/DeclareDesign/estimatr/issues/287#issuecomment-493191842 

You caught me while it was only half done. I think things should work now, but please let me know if you encounter problems, as this is potentially a breaking change.

Thanks!

**Comment by vincentarelbundock** [comment]
more directly: I just changed the repo name on github, so update your URL!

**Comment by vincentarelbundock** [comment]
@seanhardison1 

FYI,

the package has now been released to cran as "modelsummary".

Thanks again for trying it out, and let me know if you have any issues or feature requests.

Best,

Vincent
