### ISSUE TITLE
modelsummary vs modelsummary_wide output for multinomial models

### ISSUE THREAD

**Issue by meflynn** [vincentarelbundock/modelsummary#343]
I'm working with multiple multinomial logit models in brms. I can get the desired output using modelsummary_wide using a tidy.custom function to parse the brms DV prefixes into y.level variables. I also leave the model variable blank in tidy.custom, and remove the DV prefixes from the term column. The desired output is below. The table is organized according to the three separate models (i.e. Troops, Government, and People), and each outcome/equation from the model is groups under the appropriate model (i.e. Positive, Negative, and Don't know).

![image](https://user-images.githubusercontent.com/38762394/128243213-81f6dc12-e8ff-4fe7-b23e-47338ca8d397.png)

Using modelsummary with formula term ~ model + y.level and/or term ~ y.level + model produces the following output. Here the models aren't grouped by the model but by the y.level variable. Using either arrangement of model + y.level just flips the ordering and doesn't ultimately group by model first.

![image](https://user-images.githubusercontent.com/38762394/128243412-647361b7-77fe-4f3a-85b1-f3ef9f689a50.png)

Thanks!

**Comment by vincentarelbundock** [comment]
See here for more use cases: 

https://twitter.com/maksympolyakov/status/1423035479583203328?s=21

**Comment by vincentarelbundock** [comment]
@meflynn would you mind trying the Github version? In principle, the order of terms in the `group` formula should now dictate the order of rows/columns of the table.

Warning: the next version of `modelsummary` (including current Github) will require `\usepackage{siunitx}` in the LaTeX preamble. This package is loaded automatically in Rmarkdown, but it needs to be added manually if you are working in raw LaTeX. (`siunitx` gives us super nice typesetting of numbers.)

Minimal examples:

``` r
library(modelsummary)
library(nnet)

dat_multinom <- mtcars
dat_multinom$cyl <- as.factor(dat_multinom$cyl)

mod <- list(
  multinom(cyl ~ mpg, data = dat_multinom, trace = FALSE),
  multinom(cyl ~ mpg + drat, data = dat_multinom, trace = FALSE)
)

modelsummary(mod, group = term ~ y.level + model)
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">

<thead>

<tr>

<th style="text-align:left;">

</th>

<th style="text-align:center;">

6 / Model 1

</th>

<th style="text-align:center;">

6 / Model 2

</th>

<th style="text-align:center;">

8 / Model 1

</th>

<th style="text-align:center;">

8 / Model 2

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:left;">

(Intercept)

</td>

<td style="text-align:center;">

47.252

</td>

<td style="text-align:center;">

89.573

</td>

<td style="text-align:center;">

72.440

</td>

<td style="text-align:center;">

117.971

</td>

</tr>

<tr>

<td style="text-align:left;">

</td>

<td style="text-align:center;">

(34.975)

</td>

<td style="text-align:center;">

(86.884)

</td>

<td style="text-align:center;">

(37.175)

</td>

<td style="text-align:center;">

(87.998)

</td>

</tr>

<tr>

<td style="text-align:left;">

mpg

</td>

<td style="text-align:center;">

−2.205

</td>

<td style="text-align:center;">

−3.627

</td>

<td style="text-align:center;">

−3.580

</td>

<td style="text-align:center;">

−4.838

</td>

</tr>

<tr>

<td style="text-align:left;">

</td>

<td style="text-align:center;">

(1.638)

</td>

<td style="text-align:center;">

(3.869)

</td>

<td style="text-align:center;">

(1.775)

</td>

<td style="text-align:center;">

(3.915)

</td>

</tr>

<tr>

<td style="text-align:left;">

drat

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

−3.210

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

−5.028

</td>

</tr>

<tr>

<td style="text-align:left;">

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

(3.810)

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

(4.199)

</td>

</tr>

</tbody>

</table>

``` r
modelsummary(mod, group = term ~ model + y.level)
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">

<thead>

<tr>

<th style="text-align:left;">

</th>

<th style="text-align:center;">

Model 1 / 6

</th>

<th style="text-align:center;">

Model 1 / 8

</th>

<th style="text-align:center;">

Model 2 / 6

</th>

<th style="text-align:center;">

Model 2 / 8

</th>

</tr>

</thead>

<tbody>

<tr>

<td style="text-align:left;">

(Intercept)

</td>

<td style="text-align:center;">

47.252

</td>

<td style="text-align:center;">

72.440

</td>

<td style="text-align:center;">

89.573

</td>

<td style="text-align:center;">

117.971

</td>

</tr>

<tr>

<td style="text-align:left;">

</td>

<td style="text-align:center;">

(34.975)

</td>

<td style="text-align:center;">

(37.175)

</td>

<td style="text-align:center;">

(86.884)

</td>

<td style="text-align:center;">

(87.998)

</td>

</tr>

<tr>

<td style="text-align:left;">

mpg

</td>

<td style="text-align:center;">

−2.205

</td>

<td style="text-align:center;">

−3.580

</td>

<td style="text-align:center;">

−3.627

</td>

<td style="text-align:center;">

−4.838

</td>

</tr>

<tr>

<td style="text-align:left;">

</td>

<td style="text-align:center;">

(1.638)

</td>

<td style="text-align:center;">

(1.775)

</td>

<td style="text-align:center;">

(3.869)

</td>

<td style="text-align:center;">

(3.915)

</td>

</tr>

<tr>

<td style="text-align:left;">

drat

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

−3.210

</td>

<td style="text-align:center;">

−5.028

</td>

</tr>

<tr>

<td style="text-align:left;">

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

</td>

<td style="text-align:center;">

(3.810)

</td>

<td style="text-align:center;">

(4.199)

</td>

</tr>

</tbody>

</table>

**Comment by meflynn** [comment]
I'll keep working on this to see if I can figure out where it's going wrong on my end, but I keep getting this error:

```{r}
Error in `[<-.data.frame`(`*tmp*`, , timevar, value = "Troops") : 
  replacement has 1 row, data has 0
```

I've tried a few things so far, but still get the error. Will keep trying, but I suspect this will mean more to you since you're more familiar with the internal workings of the function.

1. Models in model list are named and unnamed
2. Changing ordering of group formula
3. Removing add_rows
4. Running only on modelsummary and omitting kableExtra segments of code

**Comment by vincentarelbundock** [comment]
Are you renaming coefficients and groups? If so, could you try without that?

**Comment by meflynn** [comment]
Just to clarify, here's the code I'm working with. I have the tidy.custom segment to clean up the brms output, otherwise I don't get clear group IDs (unless that's changed in the update?). I still get the error even when I omit the new coefficient names. 

```{r}
m.c.t1 <- readRDS(here::here("Output/Chapter-Contact/m.c.t1.rds"))
m.c.p1 <- readRDS(here::here("Output/Chapter-Contact/m.c.p1.rds"))
m.c.g1 <- readRDS(here::here("Output/Chapter-Contact/m.c.g1.rds"))


mod.list <- list("Troops" = m.c.t1,
                 "People" = m.c.p1,
                 "Government" = m.c.g1)

class(mod.list[[1]]) = c("custom", class(mod.list[[1]]))
class(mod.list[[2]]) = c("custom", class(mod.list[[2]]))
class(mod.list[[3]]) = c("custom", class(mod.list[[3]]))


#### Troops Tables ####

# tidy method extracts level names into new column
tidy.custom <- function(x, conf.level=.95, ...) {
  out = parameters::parameters(x, ci=conf.level, verbose=FALSE) %>%
        parameters::standardize_names(style="broom") %>%
        mutate(y.level = case_when(grepl("mudk", term) ~ "Don't Know",
                                 grepl("muneg", term) ~ "Negative",
                                 grepl("mupos", term) ~ "Positive"),
               model = "",
               term = gsub("dk|neg|pos", "", term)) # remove outcome prefix brms attaches to variable names
  return(out)
}

glance.custom <- function(x, ...) {
  ret <- tibble::tibble(N = summary(x)$nobs)
  ret
}

rows <- tribble(~term, ~col1, ~col2, ~col3, ~col4, ~col5, ~col6, ~col7, ~col8, ~col9,
                "N", as.character(summary(mod.list[[1]])[[4]]), "", "", as.character(summary(mod.list[[2]])[[4]]), "", "", as.character(summary(mod.list[[3]])[[4]]), "", "",
                "Group", "Country", "", "", "Country", "", "", "Country", "", "",
                "# Groups", as.character(summary(mod.list[[1]])[[5]]), "", "", as.character(summary(mod.list[[2]])[[5]]), "", "", as.character(summary(mod.list[[3]])[[5]]), "", "",
                "sd(Intercept, Don't know)", as.character(round(summary(mod.list[[1]])[[17]][[1]][[1]], 3)), "", "", as.character(round(summary(mod.list[[2]])[[17]][[1]][[1]], 3)), "", "", as.character(round(summary(mod.list[[3]])[[17]][[1]][[1]], 3)), "", "",
                "sd(Intercept, Negative)", as.character(round(summary(mod.list[[1]])[[17]][[1]][[2]], 3)), "", "", as.character(round(summary(mod.list[[2]])[[17]][[1]][[2]], 3)), "", "", as.character(round(summary(mod.list[[3]])[[17]][[1]][[2]], 3)), "", "",
                "sd(Intercept, Positive)", as.character(round(summary(mod.list[[1]])[[17]][[1]][[3]], 3)), "", "", as.character(round(summary(mod.list[[2]])[[17]][[1]][[3]], 3)), "", "", as.character(round(summary(mod.list[[3]])[[17]][[1]][[3]], 3)), "", "",
                "cor(mudk_Intercept,muneg_Intercept)", as.character(round(summary(mod.list[[1]])[[17]][[1]][[4]], 3)), "", "", as.character(round(summary(mod.list[[2]])[[17]][[1]][[4]], 3)), "", "", as.character(round(summary(mod.list[[3]])[[17]][[1]][[4]], 3)), "", "",
                "cor(mudk_Intercept,mupos_Intercept)", as.character(round(summary(mod.list[[1]])[[17]][[1]][[5]], 3)), "", "", as.character(round(summary(mod.list[[2]])[[17]][[1]][[5]], 3)), "", "", as.character(round(summary(mod.list[[3]])[[17]][[1]][[5]], 3)), "", "",
                "cor(muneg_Intercept,mupos_Intercept)", as.character(round(summary(mod.list[[1]])[[17]][[1]][[6]], 3)), "", "", as.character(round(summary(mod.list[[2]])[[17]][[1]][[6]], 3)), "", "", as.character(round(summary(mod.list[[3]])[[17]][[1]][[6]], 3)), "", "")



gof.check <- modelsummary::gof_map
gof.check$omit <- TRUE

coef.list <- c("b_mu_contact_persYes" = "Personal Contact: Yes",
               "b_mu_contact_persDontknowDdeclinetoanswer" = "Personal Contact: DK/Decline",
               "b_mu_contact_nonpersYes" = "Network Contact: Yes",
               "b_mu_contact_nonpersDontknowDdeclinetoanswer" = "Network Contact: DK/Decline",
               "b_mu_benefit_persYes" = "Personal Benefit: Yes",
               "b_mu_benefit_persDontknowDdeclinetoanswer" = "Personal Benefit: DK/Decline",
               "b_mu_benefit_nonpersYes" = "Network Benefit: Yes",
               "b_mu_benefit_nonpersDontknowDdeclinetoanswer" = "Network Benefit: DK/Decline",
               "b_mu_age25to34years" = "25-34",
               "b_mu_age35to44years" = "35-44",
               "b_mu_age45to54years" = "45-54",
               "b_mu_age55to64years" = "55-65",
               "b_mu_ageAge65orolder" = ">65",
               "b_mu_income.5.cat21M40." = "21-40",
               "b_mu_income.5.cat41M60." = "41-60",
               "b_mu_income.5.cat61M80." = "61-80",
               "b_mu_income.5.cat81M100." = "81-100",
               "b_mu_genderFemale" = "Female",
               "b_mu_genderNonMbinary" = "Non-binary",
               "b_mu_genderNoneoftheabove" = "None of the above",
               "b_mu_minorityYes" = "Minority: Yes",
               "b_mu_minorityDeclinetoanswer" = "Minoriy: Decline to answer",
               "b_mu_religCatholicism" = "Catholic",
               "b_mu_religChristianityprotestant" = "Protestant",
               "b_mu_religBuddhism" = "Buddhism",
               "b_mu_religHinduism" = "Hindu",
               "b_mu_religIslam" = "Islam",
               "b_mu_religJudaism" = "Judaism",
               "b_mu_religShinto" = "Shinto",
               "b_mu_religMormonism" = "Mormonism",
               "b_mu_religLocal" = "Local Religion",
               "b_mu_religOther" = "Other",
               "b_mu_religDeclinetoanswer" = "Religion: Decline to answer",
               "b_mu_ed_z" = "Education",
               "b_mu_ideology_z" = "Ideology",
               "b_mu_troops_crime_persYes" = "Crime Experience: Yes",
               "b_mu_american_inf_1DontknowDdeclinetoanswer" = "Influence 1: DK/Decline",
               "b_mu_american_inf_1Alittle" = "Influence 1: A little",
               "b_mu_american_inf_1Some" = "Influence 1: Some",
               "b_mu_american_inf_1Alot" = "Influence 1: A lot",
               "b_mu_american_inf_2DontknowDdeclinetoanswer" = "Influence 2: DK/Decline",
               "b_mu_american_inf_2Veryative" = "Influence 2: Very negative",
               "b_mu_american_inf_2Negative" = "Influence 2: Negative",
               "b_mu_american_inf_2Positive" = "Influence 2: Positive",
               "b_mu_american_inf_2Veryitive" = "Influence 2: Very positive",
               "b_mu_basecount_z" = "Base count",
               "b_mu_gdp_z" = "GDP",
               "b_mu_pop_z" = "Population",
               "b_mu_troops_z" = "Troop deployment size",
               "b_mu_Intercept" = "Intercept")




panel.1 <- modelsummary::modelsummary(mod.list,
                  estimate = "{estimate}",
                  statistic = "conf.int",
                  fmt = 2,
                  group = term ~ y.level + model,
                  gof_map = gof.check,
                  coef_map = coef.list,
                  stars = FALSE,
                  add_rows = rows,
                  longtable = TRUE,
                  output = "latex",
                  caption = "Bayesian multilevel multinomial logistic regressions \\label{tab:contactfull}") %>% 
  kable_styling(latex_options = c("striped", "scale_down", "repeat_header"), protect_latex = TRUE, font_size = 7, position = "left",
                stripe_index = c(1:2, 5:6, 9:10, 13:14, 17:18, 21:22, 25:26, 29:30, 33:34, 37:38, 41:42, 45:46, 49:50, 53:54, 57:58, 61:62, 65:66, 69:70, 73:74, 77:78, 81:82, 85:86, 89:90, 93:94, 97:98)) %>%
  add_header_above(c(" ", "U.S. Troops" = 3, "U.S. People" = 3, "U.S. Government" = 3)) %>% 
  pack_rows("Contact Status", 1, 8, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Economic Benefits", 9, 16, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Age", 17, 26, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Income Quantile", 27, 34, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Gender Identification", 35, 40, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Minority Status", 41, 44, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Religious Identification", 45, 66, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Education", 67, 68, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Ideology", 69, 70, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Personal Experience with Crime", 71, 72, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Amount of U.S. Influence", 73, 80, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Quality of U.S. Influence", 81, 90, bold = TRUE, background = "gray", color = "white") %>% 
  pack_rows("Group-level Variables", 91, 98, bold = TRUE, background = "gray", color = "white") %>%
  row_spec(100, hline_after = TRUE) %>% 
  landscape() %>% 
  save_kable(here("Tables/Chapter-Contact/model-contact-full.tex"),
             keep_tex = TRUE)

```

**Comment by vincentarelbundock** [comment]
hmmm, sorry I don't immediately see the problem in your code. Would you be able to email me those `.rds` files? No worries if they're confidential, but they would probably help me diagnose.

**Comment by vincentarelbundock** [comment]
Looks like you need to remove this line from your definition of `tidy.custom`:

```r
               model = "",
```

On my computer at least, with the latest Github version, this simplified version of your code seems to work fine:

```r
library(modelsummary)
library(tidyverse)
library(brms)

models <- list(
    "Troops" = readRDS("m.c.t1.rds"),
    "People" = readRDS("m.c.p1.rds"),
    "Government" = readRDS("m.c.t1.rds"))

for (i in seq_along(models)) {
    class(models[[i]]) <- c("custom", class(models[[i]]))
}

tidy.custom <- function(x, conf.level=.95, ...) {
  out = parameters::parameters(x, ci=conf.level, verbose=FALSE) %>%
        parameters::standardize_names(style="broom") %>%
        mutate(y.level = case_when(grepl("mudk", term) ~ "Don't Know",
                                 grepl("muneg", term) ~ "Negative",
                                 grepl("mupos", term) ~ "Positive"),
               term = gsub("dk|neg|pos", "", term))
  return(out)
}



glance.custom <- function(x, ...) {
  ret <- data.frame(N = summary(x)$nobs)
  ret
}

coef.list <- c("b_mu_contact_persYes" = "Personal Contact: Yes",
               "b_mu_contact_persDontknowDdeclinetoanswer" = "Personal Contact: DK/Decline",
               "b_mu_contact_nonpersYes" = "Network Contact: Yes",
               "b_mu_contact_nonpersDontknowDdeclinetoanswer" = "Network Contact: DK/Decline",
               "b_mu_benefit_persYes" = "Personal Benefit: Yes",
               "b_mu_benefit_persDontknowDdeclinetoanswer" = "Personal Benefit: DK/Decline",
               "b_mu_benefit_nonpersYes" = "Network Benefit: Yes",
               "b_mu_benefit_nonpersDontknowDdeclinetoanswer" = "Network Benefit: DK/Decline",
               "b_mu_age25to34years" = "25-34",
               "b_mu_age35to44years" = "35-44",
               "b_mu_age45to54years" = "45-54",
               "b_mu_age55to64years" = "55-65",
               "b_mu_ageAge65orolder" = ">65",
               "b_mu_income.5.cat21M40." = "21-40",
               "b_mu_income.5.cat41M60." = "41-60",
               "b_mu_income.5.cat61M80." = "61-80",
               "b_mu_income.5.cat81M100." = "81-100",
               "b_mu_genderFemale" = "Female",
               "b_mu_genderNonMbinary" = "Non-binary",
               "b_mu_genderNoneoftheabove" = "None of the above",
               "b_mu_minorityYes" = "Minority: Yes",
               "b_mu_minorityDeclinetoanswer" = "Minoriy: Decline to answer",
               "b_mu_religCatholicism" = "Catholic",
               "b_mu_religChristianityprotestant" = "Protestant",
               "b_mu_religBuddhism" = "Buddhism",
               "b_mu_religHinduism" = "Hindu",
               "b_mu_religIslam" = "Islam",
               "b_mu_religJudaism" = "Judaism",
               "b_mu_religShinto" = "Shinto",
               "b_mu_religMormonism" = "Mormonism",
               "b_mu_religLocal" = "Local Religion",
               "b_mu_religOther" = "Other",
               "b_mu_religDeclinetoanswer" = "Religion: Decline to answer",
               "b_mu_ed_z" = "Education",
               "b_mu_ideology_z" = "Ideology",
               "b_mu_troops_crime_persYes" = "Crime Experience: Yes",
               "b_mu_american_inf_1DontknowDdeclinetoanswer" = "Influence 1: DK/Decline",
               "b_mu_american_inf_1Alittle" = "Influence 1: A little",
               "b_mu_american_inf_1Some" = "Influence 1: Some",
               "b_mu_american_inf_1Alot" = "Influence 1: A lot",
               "b_mu_american_inf_2DontknowDdeclinetoanswer" = "Influence 2: DK/Decline",
               "b_mu_american_inf_2Veryative" = "Influence 2: Very negative",
               "b_mu_american_inf_2Negative" = "Influence 2: Negative",
               "b_mu_american_inf_2Positive" = "Influence 2: Positive",
               "b_mu_american_inf_2Veryitive" = "Influence 2: Very positive",
               "b_mu_basecount_z" = "Base count",
               "b_mu_gdp_z" = "GDP",
               "b_mu_pop_z" = "Population",
               "b_mu_troops_z" = "Troop deployment size",
               "b_mu_Intercept" = "Intercept")


modelsummary(models,
             statistic = "conf.int",
             coef_map = coef.list,
             group = term ~ y.level + model)
```

**Comment by meflynn** [comment]
I still get the following error even after deleting the model line from the custom tidy function.

```{r}
Error in `[<-.data.frame`(`*tmp*`, , timevar, value = "Troops") : 
  replacement has 1 row, data has 0

```

**Comment by vincentarelbundock** [comment]
But can you run my minimal code above with the most recent GitHub? 

If so, we can narrow things down further from there…

**Comment by meflynn** [comment]
Gotcha! Yes, it works great. Flipping the right hand terms in the formula appears to produce the desired result, too.

**Comment by meflynn** [comment]
I'm working my way through the lines right now. so far everything up to and including my add_rows line works fine.

**Comment by meflynn** [comment]
Ok, it trips up as soon as I get to the output = "latex" line. That's what's tripping the error.

**Comment by vincentarelbundock** [comment]
Thanks for helping me track this down! Super useful. For the record, there seems to be a conflict between `output = "latex"` and `coef_map`. Here's a minimal example that I will include in the test suite when I find the true origin of the bug:

Works:

```r
library(nnet)
library(modelsummary)
dat_multinom <- mtcars
dat_multinom$cyl <- as.factor(dat_multinom$cyl)

mod <- list(
    "a" = nnet::multinom(cyl ~ mpg, data = dat_multinom, trace = FALSE),
    "b" = nnet::multinom(cyl ~ mpg + drat, data = dat_multinom, trace = FALSE))

coef_list = c("(Intercept" = "Constant", "Miles" = "mpg")

modelsummary(mod,
             output = "latex",
             group = term ~ model + y.level)
```

Does NOT work:

```r
modelsummary(mod,
             output = "latex",
             coef_map = coef_list,
             group = term ~ model + y.level)
```

I'm working on this now and expect to find a solution soon.

**Comment by vincentarelbundock** [comment]
Wow, this was tickyyyyy! The bug only appears when ALL FIVE of these conditions hold:

1. `group` is used
2. `coef_map` is used
3. All of the variables in `coef_map` include underscores
4. `escape=TRUE`
5. `output="latex"`

I believe that my new commit fixes the issue. Hopefully I didn't break anything else on my way there.

Thanks again for your persistence and help.

**Comment by meflynn** [comment]
That’s very specific! I *think* it’s working. I’m on my Mac right now and having trouble compiling the Latex document to check, but I’ll look in the morning when I’m back on my desktop. The code seems to be running fine, but I’ll let you know when I’ve had a chance to verify.

And thanks so much for all of your work on this, too! This package has been a lifesaver.

**Comment by vincentarelbundock** [comment]
Cool! Will close this. Feel free to open a new one if the problem persists or another one arises. This is all very helpful.
