### ISSUE TITLE
siunitx newcolumntype options

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#354]
Currently we use:

```latex
\newcolumntype{d}{S[
  input-symbols = ()
]}
```

Eventually, we probably want to move back to something like this, since it should work with a wider variety of symbols beyond parentheses (allows "glue" strings, confidence intervals, etc.):

```latex
\newcolumntype{d}{S[
  input-open-uncertainty=,
  input-close-uncertainty=,
  table-align-text-pre=false,
  table-align-text-post=false
]}
```

However, we can only move back when a substantial proportion of users can be expected to have the bugfix release of `siunitx` installed by default. Follow here for progress:

https://github.com/josephwright/siunitx/issues/526

**Comment by vincentarelbundock** [comment]
Another issue with the current options is that the `stars` argument does not work, because it doesn't exclude characters like `*` or `+` or the arbitrary characters that users might pass.

**Comment by vincentarelbundock** [comment]
Bug will be fixed in version 3.0.25 of `siunitx`

**Comment by ecrjak** [comment]
Hi there. Could I ask whether this has been actually resolved or, if not, when it will be? I use modelsummary version 1.0.2 in R and keep getting the this message when trying use stars in a d-column:

``Error in sanity_align(align, estimate = estimate, statistic = statistic, : The "d" character is only supported in the `align` argument for LaTeX/PDF tables produced by the `kableExtra` package. It is not supported when the `estimate` or `statistic` arguments include glue strings or confidence intervals. It is only supported when the `stars` argument is `FALSE`. These constraints should be relaxed in the near future. See here to follow progress: https://github.com/vincentarelbundock/modelsummary/issues/354``

**Comment by vincentarelbundock** [comment]
Right. The error message states that `d` columns are not supported with stars.

The issue is that this was an upstream bug in the `siunitx` TeX package. It is now fixed, but taking advantage of the fix would require me to change the preamble in a way that breaks LaTeX compilation for anyone not using a recent version of `siunitx`.

I'm not sure familiar with all the LaTeX package distributions platforms for Mac, Windows, and Linux. 

1. Is it reasonable to expect that everyone runs a version of `siunitx` (say ~8 months old)?
2. Is there a good cross-platform way for me to check what `siunitx` version is installed?
3. Is there an easy upgrade path on all platforms for those who need it? Can I document that?

Any tips on dealing with this would be appreciated.

**Comment by vincentarelbundock** [comment]
Note to self: This could be a good baseline in the preamble

```latex
\newcolumntype{d}{S[
    input-open-uncertainty=,
    input-close-uncertainty=,
    parse-numbers = false,
    table-align-text-pre=false,
    table-align-text-post=false
]}
```

One issue is that `parse-numbers=false` sets everything in math mode, so asterisks get weird spacing. We should wrap those in `\mbox{}` but what if there are some `d` columns and some `c` columns? `\mbox{}` cannot be used inside `\num{}`, and it cannot be used outside of `\num{}` either, because that is not math mode.

MWE:

```latex
\documentclass{article}
\RequirePackage{booktabs}
\RequirePackage{siunitx}
\newcolumntype{d}{S[
    input-open-uncertainty=,
    input-close-uncertainty=,
    parse-numbers = false,
    table-align-text-pre=false,
    table-align-text-post=false
]}

\begin{document}

\begin{table}
\centering
\begin{tabular}[t]{lc}
\toprule
  & {Model 1}\\
\midrule
    (Intercept) & 30.099\mbox{-}\\
    & (2.045)\\
hp & -0.068\mbox{**+.@}\\
    & (2.045)\\
\midrule
Num.Obs. & 32\\
R2 & 0.602\\
R2 Adj. & 0.589\\
AIC & 181.2\\
BIC & 185.6\\
Log.Lik. & -87.619\\
F & 45.460\\
RMSE & 3.74\\
\bottomrule
\end{tabular}
\end{table}

\end{document}
```

**Comment by ecrjak** [comment]
I should say that I'm really no expert on this matter, but adding a note to the documentation that version X of tex package Y is required, should already do the job.

One thing I wanted to add is that I'm not even using the `siunitx` package but the `dcolumn` package and it works well with the `modelsummary` output for me. Maybe switching recommended latex package could help solving the problem?

**Comment by ecrjak** [comment]
Just quickly checking if there any updates on this. Many thanks!

**Comment by vincentarelbundock** [comment]
Sorry this is taking a while. It's a more complicated issue than it seems at first (I can't just switch to `dcolumn`), and I am too busy with my day job to spend too much time on this right now. 

I expect this will be resolved in the next CRAN release of `modelsummary`, most likely in the next couple months.

**Comment by vincentarelbundock** [comment]
I think it has been long enough that the upstream fix should be available for most users, so I merged in a fix in the Github development version: 

```r
remotes::install_github("vincentarelbundock/modelsummary")
```

Restart R completely and try again.

Closing this issue now, but feel free to comment or open a new issue if things don't work as expected.

Thanks for your patience!

**Comment by leonardmichels** [comment]
Hi, I just installed the Github development version to use the `dcolumn` option and when running `datasummary`, I now get the following error:
```
Error in checkmate::assert_string(sep, n.chars = 1) : 
  unused argument (n.chars = 1)
```

Any help would be much appreciated, thanks!

**Comment by vincentarelbundock** [comment]
@leonardmichels please update thé `checkmate` package, restart R, and try again.
