### ISSUE TITLE
LAtex

### ISSUE THREAD

**Issue by emantzo** [vincentarelbundock/modelsummary#355]
Hi
I tried 
`datasummary_skim(mtcars,output = 'latex')`

in a Rnw file, compiled with knitr, but I got this error:

Running pdflatex.exe on ww.tex...failed

Error: ww.tex:152: LaTeX Error: Illegal character in array arg.
Error: ww.tex:152: LaTeX Error: Illegal character in array arg.
Error: ww.tex:153: Undefined control sequence.
Error: ww.tex:155: Undefined control sequence.
Error: ww.tex:167: Undefined control sequence.
Bad Box: ww.tex:152: Overfull \hbox (53.50429pt too wide) in paragraph at lines 152--169
Bad Box: ww.tex:175: Overfull \hbox (15.0pt too wide) in paragraph at lines 175--178

**Comment by vincentarelbundock** [comment]
Thanks for the report. But to have any chance of diagnosing the problem, I would need a lot more info. For example:

1. What version of modelsummary?
2. Does it work with xelatex?
3. Can you supply a super minimalist example of a .rnw file with a call of datasunmary_skim on a built in dataset line mtcars to illustrate the problem?

**Comment by emantzo** [comment]
Thank you for your qyick reply!
I am only now starting to use Latex (through Sweave in Rstudio)

The modelsummary version is 0.9.1
I did not add `siunitx`
I am using pdfLatex 


My code in the Rnw file is
```
% !Rnw weave = knitr



\documentclass{article}


\begin{document}


\Sexpr{opts_chunk$set(message=FALSE,warning=F)} 




<<>>=
library(tidyverse)

library(modelsummary)
@


<<>>=

 datasummary(All(mtcars) ~ Mean + SD ,output = 'latex',data=mtcars)
@

\end{document}

```

**Comment by vincentarelbundock** [comment]
Thanks for thé example!

Try adding `\usepackage{siunitx}` to your preamble and using xelatex instead of pdflatex. If that doesn't work, let me know and I will look into this when I come back from vacation and have computer access again.

**Comment by emantzo** [comment]
Thank you for your reply!

It seems I have problms with MikTex and I cannot install siunitx

Any other solutions you could think of?

Hoping this is a short answer.. otherwise don't bother and enjoy your 
vacations!


Στις 14/8/2021 6:56 μ.μ., ο/η Vincent Arel-Bundock έγραψε:

**Comment by vincentarelbundock** [comment]
Try ˋ options(modelsummary_format_numeric_latex = "plain")ˋ

**Comment by emantzo** [comment]
Thank you! It works ok now, after following all your advice.

I am now trying to prevent floating.

Have a good one!

Στις 15/8/2021 2:57 μ.μ., ο/η Vincent Arel-Bundock έγραψε:
