### ISSUE TITLE
LaTeX / PDF compilation

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#358]
Tips on compiling LaTeX tables:

1. Load the `booktabs` and `siunitx` packages in your LaTeX preamble.
2. To disable `siunitx` globally and prevent `modelsummary` from using the`\num{}` LaTeX function, call: `options(modelsummary_format_numeric_latex = "plain")`
3. Try compiling your document with `xelatex` instead of `pdflatex`

**Comment by qm2021-jfremere** [comment]
Hello, I am using an rticles template rticles::arxiv_article as it enables bookdown references of tables and figures. However, it seems to me that the options
 header-includes:
  - \usepackage{booktabs}
  - \usepackage{siunitx}

are not supported in the yaml. Could you provide a support how I could get around this issue? Not sure what you mean exactly with getting booktabs in Latex preamble (Hope the above is donig the trick).

Also, I am not sure which engine is used as default for the template and I am not certain how I can costumize these templates. I often run into problems, if I try to change something in the yaml-option.

**Comment by vincentarelbundock** [comment]
Hi,

It sounds like you are asking for help using the `rticles` package and *not* the `modelsummary` package. For PDF output in Rmarkdown document, the `modelsummary` requirement is stated clearly: You need to make sure that the `booktabs` and `siunitx` packages are loaded in the LaTeX preamble.

If you need to know how to achieve this using `header-includes` in `rticles` templates, you should consult that package's documentation. I am not the developer of `rticles`, and I can't offer support for other people's software.

Here are some examples of Rmarkdown; maybe they will be helpful: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#rmarkdown

**Comment by kjayhan** [comment]
Hi,

I saved three plm models, and trying to render them within my manuscript (pdf, and docx).

When I run modelsummary with these models, it produces the table without any problem.

But when I render it throws the folllowing error: 

> Error: `modelsummary could not extract the required information from a model of
>   class "plm". The package tried a sequence of 2 helper functions to
>   extract estimates:
>   
>   parameters::parameters(model)
>   broom::tidy(model)
>   
>   To draw a table, one of these commands must return a `data.frame` with a
>   column named "term". The `modelsummary` website explains how to
>   summarize unsupported models or add support for new models yourself:
>   https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html
>   
>   These errors messages were generated during extraction:
>   
>   `parameters::parameters(model)` did not return a valid data.frame.
> `broom::tidy(model)` did not return a valid data.frame.
> Execution halted

My code is as follows:


```
within_time_model_z <- readRDS(here("results/plm/main_0212_fixed.rds"))
random_time_model_z <- readRDS(here("results/plm/main_0212_random.rds"))
pooled_model_z <- readRDS(here("results/plm/main_0212_pooled.rds"))

plm <- list(
  "Random effects" = random_time_model_z, 
  "Fixed effects" = within_time_model_z, 
  "Pooled effects" = pooled_model_z
)

modelsummary::modelsummary(plm,
                           stars = TRUE,
                           output = "kableExtra")
```

**Comment by vincentarelbundock** [comment]
What happens when you execute the two commands that the error message lists on your models?

**Comment by kjayhan** [comment]
Thank you for quick response.

parameters::parameters(random_time_model_z)

> Error: Sorry, `model_parameters()` failed with the following error (possible class `plm` not supported):
> 
> $ operator is invalid for atomic vectors

broom::tidy(random_time_model_z)
> Show in New Window
> Error in s$coefficients : $ operator is invalid for atomic vectors

**Comment by vincentarelbundock** [comment]
Hmm, not sure. Those errors are not super informative. My guess is there's something weird going on with your model objects. Perhaps the save file is bad?

What happens if you try a super simple model like this?

```{r}
library(modelsummary)
library(plm)
data(Grunfeld)
p <- plm(inv ~ value + capital, data = Grunfeld, model = "pooling")
modelsummary(p)
```

Can you reproduce the error with a minimal example so we can isolate it?

**Comment by kjayhan** [comment]
Yes, this example worked. But again, when I run my code, modelsummary produces the table I want. The problem occurs only when I try to render the file (.qmd).

**Comment by vincentarelbundock** [comment]
Maybe try a different output format, like `output="latex"` if you're outputting to PDF.

But the bottom line is I am very unlikely to be able to solve this unless you can supply code that I can use to reproduce the exact error on my computer.

**Comment by kjayhan** [comment]
Changing to "latex" worked. Thank you. I tried this before, and it didn't work, but I guess something else was wrong then.

**Comment by vincentarelbundock** [comment]
Great news! I'll leave myself a note to look into this the next time I play with quarto and `modelsummary`
