### ISSUE TITLE
hardcoded subs in coef_rename

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#362]
@grantmcdermott

2 Questions:

  - Should the `coef_rename` argument of `modelsummary` default to a function like `modelsummary::coef_rename`?
  - Should the substituting `:` by `x` in interactions be done in this function?

Benefit: users could turn off all of this processing by setting `coef_rename=FALSE`.

Downside: overloading the `coef_rename` would make it complicated to substitute interaction signs when *also* renaming coefficients.

An alternative would be to have an additional argument or global option:

``` r
options(modelsummary_coef_clean = function(x) gsub(":", "x", x))
```

Benefit: unobtrusive

Downside: I'm starting to abuse global options

Note that we currently have an exported function called `coef_rename` which allows stuff like this:

``` r
library(palmerpenguins)
library(modelsummary)

mod <- lm(bill_length_mm ~ flipper_length_mm + factor(island), penguins)

modelsummary(mod, "markdown", coef_rename = coef_rename)
```

|                   |  Model 1  |
| :---------------- | :-------: |
| (Intercept)       | \-19.498  |
|                   |  (3.777)  |
| Flipper Length Mm |   0.309   |
|                   |  (0.018)  |
| Dream             |   4.047   |
|                   |  (0.529)  |
| Torgersen         |  \-0.591  |
|                   |  (0.677)  |
| Num.Obs.          |    342    |
| R2                |   0.549   |
| R2 Adj.           |   0.545   |
| AIC               |  1868.4   |
| BIC               |  1887.6   |
| Log.Lik.          | \-929.210 |
| F                 |  137.006  |

**Comment by grantmcdermott** [comment]
I think I like the function option better... so long as we can find an elegant way to handle the potential renaming + interaction symbol conflict.

The first option that comes to mind is simply adding an additional argument/dictionary to `coef_rename` that handles how this is done. Say we call this extra argument `symbol_dict` and it ensure that it is implemented last; so after any other user-defined changes. By default it would follow the existing rules that have been hardcoded. But users could swap in their own or turn it off completely by setting to NULL.

Something like this internally:

```r
symbol_dict = c("::" = " = ", ":" = " x ")

symbol_dict_func =
    function(x, sym_dict = symbol_dict) {
        is_null = is.null(sym_dict)
        if (is.null(sym_dict)) stop(return(x))
        ii = 0
        while (ii < length(sym_dict)) {
            ii = ii + 1
            x = gsub(names(sym_dict)[ii], sym_dict[ii], x)
        }
        return(x)
    }

x = 'Month::6:treated'

symbol_dict_func(x)
#> [1] "Month = 6 x treated"
symbol_dict_func(gsub('6','June',x))
#> [1] "Month = June x treated"
symbol_dict_func(gsub('6','June',x), sym_dict = c('::' = ' == ', ':' = ' * '))
#> [1] "Month == June * treated"
symbol_dict_func(gsub('6','June',x), sym_dict = NULL)
#> symbol_dict_func(gsub('6','June',x), sym_dict = NULL)
```

**Comment by vincentarelbundock** [comment]
Agreed. So what's the user-interface? Currently we have this:

```{r}
modelsummary(mod, coef_rename = c("blah_blah" = "Blah blah"))
```

It's quite important that this still works, I think.

So how do people disable stars-sub?

**Comment by grantmcdermott** [comment]
How do users invoke the other `coef_rename` args, like titling?

Stars are important enough that they should be handled as a separate argument, as currently happens (at least, as I think currently happens. I'm away from my computer now so can't check).

**Comment by vincentarelbundock** [comment]
Sorry, meant `:`-multiplication sub.

Right now, `coef_rename` accepts a named vector like shown above, or a function that accepts a character vector and returns a vector of the same name with "cleaned" values.

**Comment by grantmcdermott** [comment]
> Sorry, meant :-multiplication sub.

Hmmm, I'm confused. That's handled automatically, no? (Obvs we'd swap " x " for the actual unicode variant in the real code.)

I guess you could use one more `coef_rename_args` argument that accepts a list of the other possible arguments to be passed down.

**Comment by vincentarelbundock** [comment]
Sorry, that really wasn't clear. Currently the `coef_rename` argument accepts 2 inputs:

1. Named vector substitutes names as requested by user, but internally we also do some hard-coded subs for interaction signs. There is no way to disable or customize those internal subs.
2. Function takes in the raw term names and returns a character vector of the same length. 

The `modelsummary::coef_rename` is an exported FUNCTION that illustrates what kind of function users can feed to the `coef_rename` ARGUMENT of `modelsummary`.

My proposal was to (1) take out the hard-coded substitutions from `modelsummary`, (2) insert them in `coef_rename`, and (3) make the default value of the `coef_rename` argument a function whose own defaults are all `FALSE`, except for the `:`-to-`x` substitution.

That way, users could specify `coef_rename=NULL` and cancel those hard-coded subs.

When users input a named vector, that named vector could be fed as an argument to `modelsummary::coef_rename`.

In principle, that would work well, but my main worry is that it is kind of a complicated design.

**Comment by vincentarelbundock** [comment]
You know what, maybe this is getting too complicated for nothing. The hard-coded subs feel quite unobjectionable. Unless someone complains we can just leave things as-is.

**Comment by grantmcdermott** [comment]
Ah, gotcha. Sorry should also have waited until I was back at my computer to better understand the overloading part.

I like your proposal. So, you would probably just want to change the default `msummary(..., coef_rename = NULL)` argument to something like `msummary(..., coef_rename = 'auto')`, or `msummary(..., coef_rename = 'coef_rename()')` (see below). In other words, `coef_name = NULL` is now preserved for literally no changes, including interaction symbols.

I would probably make one other change: Set the defaults of the `coef_rename()` FUNCTION to `FALSE`, except for the new `symbol_dict` argument. That would allow for cleaning implementation and also provide a link to this function in the `msummary()` docs if users want to follow that bread trail.

**Comment by grantmcdermott** [comment]
Whoops. Didn't see your last reply before commenting again. I think either works, but happy to let you make the final call.
