### ISSUE TITLE
How to override existing tidy methods?

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#37]
I want to override `tidy.lm` to add new columns, thus allowing me to include new statistics.

For instance, I would like to do this:

```r
library(broom)
library(sandwich)

f <- function(x, ...) {
    out <- broom:::tidy.lm(x, ...)
    out$std.error.hc1 <- sqrt(diag(sandwich::vcovHC(x, type = 'HC1')))
    out$std.error.hc3 <- sqrt(diag(sandwich::vcovHC(x, type = 'HC3')))
    out$std.error.hac <- sqrt(diag(sandwich::vcovHAC(x)))
    return(out)
}
setMethod("tidy", "lm", f)

x <- rnorm(10)
y <- rnorm(10)
model <- lm(y ~ x)
tidy(model)
```

This works when I simply call `tidy(model)` from the interactive console, that is, the output has new columns for the other types of standard errors. 

Unfortunately, the functions in my package which use `@importFrom generics tidy` continue to return the output of `broom::tidy` internally, instead of using the newly defined method:

https://github.com/vincentarelbundock/modelsummary/blob/master/R/extract_estimates.R#L31

**Comment by vincentarelbundock** [comment]
Curious to know if @alexpghayes has insights into this issue. Obviously, this is not your problem at all, so please feel free to ignore.

**Comment by alexpghayes** [comment]
I would not overwrite tidy(). I would use an additional verb. For example,
use my_tidy() throughout the package and have my_tidy.default <- tidy and
overwrite individual methods as needed.

**Comment by vincentarelbundock** [comment]
Good suggestion. Thanks a lot for your time @alexpghayes !

**Comment by LukasWallrich** [comment]
Is there any way to implement this and let the user specify their own (my_)tidy methods? For example, I am trying to summarise polr models, for which broom's tidy.polr does not provide p-values (for good reasons, but I still need to show significance stars with a footnote explaining why they should not be fully relied upon). That would probably require a change in the my_tidy function to look for methods first in the global environment? If you deem this a sufficiently common use case, I'd be happy to try to implement it.

**Comment by vincentarelbundock** [comment]
Most straightforward is probably something like this:

```r
library(modelsummary)
glance.customclass <- function(x, ...) data.frame('Bad' = TRUE)
mod <- lm(hp ~ mpg, data = mtcars)
class(mod) <- c('customclass', class(mod))
msummary(mod)
```

**Comment by LukasWallrich** [comment]
So simple, thanks! For some reason, I just assumed that wouldn't work and didn't even try.

**Comment by alexpghayes** [comment]
For things like missing p-values, please just a make a PR to `broom` so everybody can benefit from your work! But otherwise the custom class trick is a good one.
