### ISSUE TITLE
Snapshot tests

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#373]
I just came across this and it sounds useful for modelsummary tests:
https://testthat.r-lib.org/articles/snapshotting.html

Haven't tried it yet, though! Just wanted to share in case you haven't seen this functionality before.

**Comment by vincentarelbundock** [comment]
Oh wow, I had missed this. Automatic file paths seems like a small thing, but it's actually a major win for this particular project. 

I only browsed quickly and I'm not sure what happens when there are multiple snapshot in a single test file. I'll try it eventually...

Thanks for the pointer!

**Comment by elbersb** [comment]
Yeah, apparently this was introduced in testthat 3.0.0, last October.  Seems like a straightforward way to cover more use cases and simplify the testing code.

**Comment by vincentarelbundock** [comment]
absolutely. It's probably not worth spending a ton of time on this now, but let's leave the issue open to make sure I remember this for the next time I have to write tests.
