### ISSUE TITLE
coef_map of variables with underscore when output is latex

### ISSUE THREAD

**Issue by kennchua** [vincentarelbundock/modelsummary#378]
Hello, 
Thank you for putting together this great package. 

I was recently trying to output some regression results to latex using modelsummary and found what may be a small bug in the coef_map argument.

I find that when one is trying to output a latex or latex_tabular using modelsummary, there are problems when specifying raw variable names that contain an underscore in the coef_map argument.

For example:

```r
library(modelsummary)
library(kableExtra)
sessionInfo()

mtcars2 <- mtcars
mtcars2$disp_x <- mtcars2$disp
mtcars2$wt_x <- mtcars2$wt


# Problem 1:  When there is a variable with underscore raw name not displayed in output; not in expected order 
reg_prob1 <- list()
reg_prob1[[1]] <- lm(data = mtcars2, mpg ~ disp_x)
reg_prob1[[2]] <- lm(data = mtcars2, mpg ~  disp_x + wt)
reg_prob1[[3]] <- lm(data = mtcars2, mpg ~  disp_x + wt + am)


msummary(reg_prob1, coef_map = c("disp_x", "wt"), output = "latex")


# Problem 2: When there are two or more variables with underscores rows for coefficients and std errors are not in the right place and names are not displayed
reg_prob2 <- list()
reg_prob2[[1]] <- lm(data = mtcars2, mpg ~ disp_x)
reg_prob2[[2]] <- lm(data = mtcars2, mpg ~  disp_x + wt_x)
reg_prob2[[3]] <- lm(data = mtcars2, mpg ~  disp_x + wt_x + am)

msummary(reg_prob2, coef_map = c("disp_x", "wt_x"), output = "latex")

```

I think this only happens specifically for latex output and when the raw name (or the name given to the variable) has an underscore. 

Thanks.

**Comment by vincentarelbundock** [comment]
Thanks for this exceptionally detailed and useful bug report, I really appreciate it!

I believe that the new commit 5b60204 fixes this issue.

I'm waiting on some contributions before releasing a new version, so it might take a little bit to get to CRAN, but you can use the Github version now.

Thanks again!

**Comment by kennchua** [comment]
Awesome! Thanks for the quick turnaround. I've downloaded the Github version. Thank you!
