### ISSUE TITLE
Set `use.fallback = TRUE` in `extract_gof` to get `nobs` for models w/o `nobs` method

### ISSUE THREAD

**Issue by ramorel** [vincentarelbundock/modelsummary#38]
First off, great package, really happy to be using it.

I ran into an issue trying to create a regression table for a series of fixed-effects models using the [lfe](https://github.com/sgaure/lfe) package. There is no `nobs` method for the models produced by this package, and so I can't get the number of observations in the table. 

This can be solved by adding the argument `use.fallback = TRUE` in the `nobs` function call in the `extract_gof` function.

For example:

``` r
library(lfe)
#> Loading required package: Matrix

## create covariates
x <- rnorm(1000)
x2 <- rnorm(length(x))

## individual and firm
id <- factor(sample(20,length(x),replace=TRUE))
firm <- factor(sample(13,length(x),replace=TRUE))

## effects for them
id.eff <- rnorm(nlevels(id))
firm.eff <- rnorm(nlevels(firm))

## left hand side
u <- rnorm(length(x))
y <- x + 0.5*x2 + id.eff[id] + firm.eff[firm] + u

## estimate and print result
est <- felm(y ~ x+x2| id + firm)

nobs(est)
#> Error in nobs.default(est): no 'nobs' method is available

nobs(est, use.fallback = TRUE)
#> [1] 1000
```

<sup>Created on 2019-07-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I will create a pull request modifying the `nobs` call. I don't think that adding the `use.fallback` argument will cause any unwanted behavior.

**Comment by ramorel** [comment]
I suppose until this is [fixed upstream in broom](https://github.com/vincentarelbundock/modelsummary/issues/16)?

**Comment by vincentarelbundock** [comment]
Right. Ideally, a new method in the `lfe` package would be ideal. A method in `broom` is second best, and `use.fallback` third best. But i’m On vacation with just an iPad, so i wont be submitting patches upstream in the next couple days. Either way, your pull is now merged, so that should improve things. 

Thanks again!
