### ISSUE TITLE
Weights not working in datasummary_balance

### ISSUE THREAD

**Issue by antrologos** [vincentarelbundock/modelsummary#383]
Model summary is really great. Thank you for making if publicly available!

However, I'm experiencing a possible bug: weights are not working with `datasummary_balance`. 

Consider this toy example:

```r
library(modelsummary)
library(dplyr)

dat <- iris

# Making up arbitrary weights
dat$weights <- exp(dat$Sepal.Length)

# datasummary_balance should automatically take weights into account (according to the help file)
datasummary_balance(~Species, data = dat)

# But the group means datasummary_balance  gives are exactly the same as these ones:
dat %>%
  group_by(Species) %>%
  summarise(Sepal.Length = mean(x = Sepal.Length),
            Sepal.Width  = mean(x = Sepal.Width),
            Petal.Length = mean(x = Petal.Length),
            Petal.Width  = mean(x = Petal.Width)) %>%
  t()

# These are what I was expecting... 
dat %>%
  group_by(Species) %>%
  summarise(Sepal.Length = weighted.mean(x = Sepal.Length, w = weights),
            Sepal.Width  = weighted.mean(x = Sepal.Width,  w = weights),
            Petal.Length = weighted.mean(x = Petal.Length, w = weights),
            Petal.Width  = weighted.mean(x = Petal.Width,  w = weights)) %>%
  t()


# Weights only work if there is only two groups... 
datasummary_balance(~Species, data = dat %>% filter(Species != "setosa"))

```

I understand the two-group case is the standard for the group-comparison/mean-difference to be calculated. And it probably has to do with how the underlying package, `estimatr` works. But once `datasummary_balance` allows for multi-group descriptives, I suppose weights should be allowed in those cases as well

**Comment by vincentarelbundock** [comment]
Thanks for the report. I need to think about the best strategy, but I agree that this is a problem that needs solving.

What would you have expected in the `N` and `Pct` columns when there are categorical variables?

**Comment by antrologos** [comment]
In the case of categorical variables I think it would be nice to have the weighted count and percentages. 

I know, survey/sampling weights usually come from a complex sample design... which also alters how sampling distributions/variance of estimators are obtained. 

But most of the times we are interested in point estimates. So, weighted means, sums, sds/variances and proportions would be really really great
