### ISSUE TITLE
Equivalence of `output = 'data.frame'`

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#393]
I would prefer using my own kable function, however, the 'dataframe' output is quite different (extra columns etc) than the 'kableExtra' output. Is it possible to get them to work in the same way? 

```
library(modelsummary)

lm(dist ~ speed, cars) |>
  modelsummary(output = 'kableExtra')

lm(dist ~ speed, cars) |>
  modelsummary(output = 'data.frame') |>
  kableExtra::kbl()
```

**Comment by vincentarelbundock** [comment]
What could be cool is if we could supply a function to the `output` argument. The function would then be fed all the `output="data.frame"` content, as well as all the other arguments. This would allow users to create customized output formats.

**Comment by vincentarelbundock** [comment]
Cool cool. Now that I think about it, I'm going to use the theming infrastructure to do this. In the Github version, you can now define a custom theming function and set the `"modelsummary_theme_dataframe"` global option. This will post-process your table automatically whenever `output="dataframe"` automatically. Here's an example:

https://vincentarelbundock.github.io/modelsummary/articles/appearance.html#themes-data-frame-1

**Comment by statzhero** [comment]
Just to say that the “theme” option works well. (Although I’m sometimes stumped because the modelsummary theme also applies to the `datasummary` function.)

**Comment by vincentarelbundock** [comment]
Ah, thanks for checking in!

Yeah, I can see how this could get tricky. I guess that in some situations, writing our own custom post-processing functions might be better...

(Trying to be aggressive about closing issues to avoid them getting out of control ;) )

**Comment by statzhero** [comment]
Right - and for anyone reading: I reset the theme option at a strategic point.
