### ISSUE TITLE
Stack Summary Statistics from Multiple Data Frames

### ISSUE THREAD

**Issue by AndreWal** [vincentarelbundock/modelsummary#408]
Hi, 

I haven't found a solution so I wanted to ask if it is possible to use datasummary to stack the summary statistics from different data frames on top of each other? 

Best,
André

**Comment by vincentarelbundock** [comment]
To my knowledge, the the `kableExtra`, `gt`, `flextable`, and `huxtable` do *not* offer an easy way to `rbind` two different tables. So there is no "automatic" way to achieve what you want.

One option is to output one table as a `data.frame` and to insert it in the other table using the `add_rows` argument, as shown in my answer to this StackOverflow question:

https://stackoverflow.com/questions/69872439/error-with-function-to-include-in-datasummary/69872702#69872702

Another strategy would be to output both tables as data frames, combine them, and then convert them to a nice table with the `datasummary_df` function.

**Comment by AndreWal** [comment]
datasummary_df as a workaround is sufficient.

Thanks!
