### ISSUE TITLE
`gof_map`: `data.frame` or `tibble` with functions

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#409]
See example below. I hope it is clear.

```r
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url) 
dat <- purrr::map_dfr(seq_len(20), ~ dat)
# So we can see big.mark

models <- list(
  "OLS 1"     = lm(Donations ~ Literacy + Clergy, data = dat),
  "Poisson 1" = glm(Donations ~ Literacy + Commerce, family = poisson, data = dat),
  "OLS 2"     = lm(Crime_pers ~ Literacy + Clergy, data = dat),
  "Poisson 2" = glm(Crime_pers ~ Literacy + Commerce, family = poisson, data = dat),
  "OLS 3"     = lm(Crime_prop ~ Literacy + Clergy, data = dat)
)

f <- function(x) format(round(x, 3), big.mark=",")

gm <- tibble::tribble(
  ~raw,        ~clean,          ~fmt,
  "nobs",      "N",             f)

modelsummary(models, gof_map = gm)
# FAILS: 1720 

gm <- list(
  list("raw" = "nobs", "clean" = "N", "fmt" = f)
  )

modelsummary(models, gof_map = gm)
# WORKS: 1,720
```

**Comment by vincentarelbundock** [comment]
Thanks!

The problem is almost certainly this line:

https://github.com/vincentarelbundock/modelsummary/blob/main/R/sanitize_gof_map.R#L32

The trick would be to find an alternative line of code that yields the equivalent list structure to the "clean" one you show when there is a function, but behaves as before for any other type.

I'm kind of overloaded at work these days, so not sure when I'll have time to look at this. If you have an idea, let me know.

**Comment by kennchua** [comment]
Yes, these are definitely similar concerns. 
I am going with a list of lists instead of a tibble for the future. 

Thank you!

**Comment by vincentarelbundock** [comment]
Sorry it took so long, but this now works in the development version of `modelsummary`:

``` r
library(tibble)
library(modelsummary)

mod <- lm(mpg ~ hp, mtcars)

gm <- tribble(
  ~raw,        ~clean,      ~fmt,
  "r.squared", "R-Squared", function(x) sprintf("%.7f", x))

modelsummary(mod, gof_map = gm)
```

|             |  Model 1  |
| :---------- | :-------: |
| (Intercept) |  30.099   |
|             |  (1.634)  |
| hp          |  \-0.068  |
|             |  (0.010)  |
| R-Squared   | 0.6024373 |
