### ISSUE TITLE
SEs to the side

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/modelsummary#41]
Hey Vincent,

Apologies if I missed it, but is there a way to put the SEs (or whatever statistic you prefer) to the side of the coefficient values, rather than underneath?

Thanks!

**Comment by vincentarelbundock** [comment]
No, you didn't miss it. But it's an excellent idea!

I pushed a commit which should allow you to do this using the `statistic_vertical = FALSE` argument. Let me know if it works for you, or if you think the argument should be named differently (it's consistent with the `statistic_` scheme, but I'm very open for alternatives). 

On my computer, this code produces the table pasted below:


```r
library(MASS)
library(modelsummary)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url) 
dat$Clergy <- ifelse(dat$Clergy > 40, 1, 0) # binary variable for logit model

models <- list()
models[['OLS 1']] <- lm(Literacy ~ Crime_prop + Infants, dat)
models[['NBin 1']] <- glm.nb(Literacy ~ Crime_prop + Donations, dat)
models[['OLS 2']] <- lm(Desertion ~ Crime_prop + Infants, dat)
models[['NBin 2']] <- glm.nb(Desertion ~ Crime_prop + Donations, dat)
models[['Logit 1']] <- glm(Clergy ~ Crime_prop + Infants, dat, family = binomial())
msummary(models, statistic_vertical = FALSE, statistic = 'conf.int') 
```

![horizontal uncertainty example](https://user-images.githubusercontent.com/987057/71588264-d4dc1e80-2aee-11ea-9610-deef05d7ca8a.png)

**Comment by grantmcdermott** [comment]
Worked a charm. Thanks mate!
