### ISSUE TITLE
`modelsummary()` does not automatically detect `github_document` output format

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#411]
The `modelsummary()` function does not seem to recognize that `github_document` is a markdown output format so the code below will produce the error that an HTML-producing function was detected inside the markdown document (no matter if `results='asis'` is enabled or not). Adding `output = "markdown"` does the trick but it would of course be phenomenal if `modelsummary()` could handle this case as smoothly as it does with PDF and HTML output formats.

``````
---
title: "Test"
output: github_document
---

```{r, results='asis'}
mod <- lm(mpg ~ disp, data = mtcars)
modelsummary::modelsummary(mod)
```
``````

**Comment by turbanisch** [comment]
This is another issue imported from `kableExtra` it seems.

**Comment by vincentarelbundock** [comment]
No, this one is on us. I pushed a change here: https://github.com/vincentarelbundock/modelsummary/commit/8d9c4c8d0c90535b5687da717c39a56dcdeafe1e

Would you mind installing from Github and trying again?

**Comment by turbanisch** [comment]
Works like a charm, thanks for making the effort!

**Comment by vincentarelbundock** [comment]
It was a great suggestion. I'll use this a ton myself :)
