### ISSUE TITLE
`modelsummary()` adds "^^" before stars note in markdown

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#412]
Another minor thing: If markdown is chosen as the output format, `^^` will be inserted in between "Notes" and the lenged for the stars. I'm not sure if this is actually meant to be markdown syntax (reminds me of the footnote notation) but anyways it doesn't get rendered on GitHub if I export as `github_document`:

```````
---
title: "Test"
output: github_document
---

```{r, results='asis'}
mod <- lm(mpg ~ disp, data = mtcars)
modelsummary::modelsummary(mod,
                           output = "markdown",
                           stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01))
```
```````

**Comment by vincentarelbundock** [comment]
Thanks for the report. This is the default footnote format from the `kableExtra` package. I don't personally have a strong view about whether this is appropriate (it might not be!), but it's not something that we control at `modelsummary`. If you think there's a more "standard" way of printing those in markdown tables, you might consider opening an issue at the `kableExtra` repo. 

(I'm not sure if `knitr::kable` supports footnotes.)

**Comment by turbanisch** [comment]
Thank you so much! I managed to localize where the bug came from and filed an issue at kableExtra: https://github.com/haozhu233/kableExtra/issues/672
