### ISSUE TITLE
Add example for coef_rename with function

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#413]
Another mini-comment: I was wondering if an example on how to use the `coef_rename` argument in `modelsummary` with a function would be useful, either in the help text or on the [modelsummary page](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#coef_rename). 

For example, I noticed that only matches of the whole word are replaced when `coef_rename` is given a named vector; passing a function allows more liberal matching that could also capture interaction terms etc. (see example below). 

I see that it makes sense to make the default version with a named vector reasonably conservative and non-greedy, but a hint might be appreciated by the reader. (In fact the example given in the help file for `coef_rename` uses `coef_map` instead: 
`# coef_rename modelsummary(models, coef_map = c('Volume' = 'Large', 'Height' = 'Tall')` )

``` r
library(modelsummary)

# works (example from https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#coef_rename)
x <- list(lm(hp ~ drat, mtcars),
          lm(hp ~ vs, mtcars))

modelsummary(x,
             output = "markdown",
             coef_rename = c("drat" = "Explanator",
                             "vs" = "Explanator"))
```

|             | Model 1  | Model 2  |
|:------------|:--------:|:--------:|
| (Intercept) | 353.653  | 189.722  |
|             | (76.049) | (11.347) |
| Explanator  | -57.545  | -98.365  |
|             | (20.922) | (17.155) |
| Num.Obs.    |    32    |    32    |
| R2          |  0.201   |  0.523   |
| R2 Adj.     |  0.175   |  0.507   |
| AIC         |  359.2   |  342.7   |
| BIC         |  363.6   |  347.1   |
| Log.Lik.    | -176.588 | -168.347 |
| F           |  7.565   |  32.876  |

``` r
# interaction terms are not replaced (match only at word boundary?)
y <- list(lm(hp ~ drat:mpg, mtcars),
          lm(hp ~ vs:mpg, mtcars))

modelsummary(y,
             output = "markdown",
             coef_rename = c("drat" = "Explanator",
                             "vs" = "Explanator"))
```

|             | Model 1  | Model 2  |
|:------------|:--------:|:--------:|
| (Intercept) | 264.305  | 189.134  |
|             | (22.186) | (10.854) |
| drat:mpg    |  -1.581  |          |
|             | (0.275)  |          |
| vs:mpg      |          |  -3.951  |
|             |          | (0.654)  |
| Num.Obs.    |    32    |    32    |
| R2          |  0.523   |  0.549   |
| R2 Adj.     |  0.508   |  0.534   |
| AIC         |  342.7   |  340.9   |
| BIC         |  347.1   |  345.3   |
| Log.Lik.    | -168.328 | -167.447 |
| F           |  32.948  |  36.514  |

``` r
# define rename function
rename_explanator <- function(varnames) {
  
  # add word boundaries to variable names
  pattern <- stringr::str_c("\\b", c("drat", "vs"), "\\b", collapse = "|")  
  
  old_names <- varnames
  new_names <-  stringr::str_replace_all(old_names, pattern, "Explanator")
  
  setNames(new_names, old_names)
}

# using a function to rename works
modelsummary(y,
             output = "markdown",
             coef_rename = rename_explanator)
```

|                | Model 1  | Model 2  |
|:---------------|:--------:|:--------:|
| (Intercept)    | 264.305  | 189.134  |
|                | (22.186) | (10.854) |
| Explanator:mpg |  -1.581  |  -3.951  |
|                | (0.275)  | (0.654)  |
| Num.Obs.       |    32    |    32    |
| R2             |  0.523   |  0.549   |
| R2 Adj.        |  0.508   |  0.534   |
| AIC            |  342.7   |  340.9   |
| BIC            |  347.1   |  345.3   |
| Log.Lik.       | -168.328 | -167.447 |
| F              |  32.948  |  36.514  |

<sup>Created on 2021-11-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
For sure. I would definitely accept a PR with a change to the docs and/or vignette.

**Comment by turbanisch** [comment]
Perfect, I'll try to come up with something by the weekend!
