### ISSUE TITLE
Add "No" if there is no fixed effects

### ISSUE THREAD

**Issue by AntoineCastet** [vincentarelbundock/modelsummary#417]
Hello Mr. Arel-Bundock,

Thank you for the "modelsummary" package, it is incredibly helpful and a huge time saver.

I am trying to create a table presenting two models side-by-side, one with fixed effects and one without.

I prefer to display "Yes"/"No" instead of "X"/" ".

In order to display the "Yes" instead of "X", I wrote:
glance_custom.fixest <- function(x) {
  #Fixed effect  
  out<- tibble(.rows = 1)
  for (n in x$fixef_vars) {
    out[[paste('Fixed effect:', n)]] <- 'Yes'}
  return(out)
}

However, I do not find how to replace the " "with "No".

Do you know if there is a way to manage that? 

Thank you in advance for your help

**Comment by vincentarelbundock** [comment]
Your `glance_custom` method could include a list of potential fixed effects names, check if they are included in the model, and include a new column with "No" as needed.

For any single model, there is an infinite set of potential fixed effects names; `modelsummary` does not know all the possibilities.
