### ISSUE TITLE
Hability to choose both standard error and p-value in argument dinm_statistic

### ISSUE THREAD

**Issue by pgesteirads** [vincentarelbundock/modelsummary#418]
Hello,

I've tried to use datasummary_balance to produce a table containing both of these statistics, but couldn't make the function understand that i want both of them. So i figured it must be a feature that the function don't have yet.

If not, i'm deeply sorry for wasting your time. It's my first contact with R language, and there's a lot of things i don't know yet.

Anyway, thanks for your package, modelsummary helped me a lot in my previous assignment. Thank you!

**Comment by vincentarelbundock** [comment]
Thanks for the report!

Unfortunately, this is not currently possible. The good news is that it should quite easy to implement this. I will ping you when I get a chance to do it.

**Comment by vincentarelbundock** [comment]
Sorry, but this turns out to be hard to implement after all. I wish I could do it, but I don't think I'll have the time get to it. Sorry again.

**Comment by pgesteirads** [comment]
> Sorry, but this turns out to be hard to implement after all. I wish I could do it, but I don't think I'll have the time get to it. Sorry again.

Thanks for trying Vincent!
