### ISSUE TITLE
Inconsistent output with `output = "modelsummary_list"`

### ISSUE THREAD

**Issue by jolyphil** [vincentarelbundock/modelsummary#420]
Thank you very much for this fantastic package!

I have been playing with the argument output = "modelsummary_list" in the function modelsummary() and noticed that the structure of the output varies depending on the number of models passed to the function. 

If you provide a single model, the output has the following structure: 2 data frames nested in a list. 
If you provide more than one model, the output has the following structure: 2 data frames nested in lists nested a list.

```
library(modelsummary)

m1 <- lm(mpg ~ hp, data = mtcars)
m2 <- lm(mpg ~ hp + wt, data = mtcars)
output1 <- modelsummary(list(m1), output = "modelsummary_list")
output2 <- modelsummary(list(m1, m2), output = "modelsummary_list")
str(output1)
str(output2)

```

For programming purposes, I was wondering if it would not be better to keep a consistent output. 

Thanks for your feedback!

**Comment by vincentarelbundock** [comment]
Ah, yes, this is an excellent point! I'm inclined to agree with you. But just play devil's advocate, here are three arguments against changing the current behavior:

1. Backward compatibility, or "Vincent committed the original sin and we are stuck."
2. This is very convenient: `modelsummary(mod)$glance`
3. One way to think about this feels consistent: Input 1 object output 1 object. Input a list of objects, output a list of objects.

To be clear, I don't mean to say that these arguments mean we shouldn't change things. I'm just trying to figure out the strongest arguments on either side before we make a decision.

**Comment by jolyphil** [comment]
These are definitely good arguments to keep the current output. 

The problem I had was that I was trying to create a wrapper around `modelsummary() ` to print the results of ordinal logistic regressions with stars representing p values. The wrapper will be integrated in a package to reproduce the results of a paper. Sometimes I want to provide one model, sometimes more than one to the function. 

Since the wrapper will be integrated in a package I preferred not using the solution you documented with `tidy_custom()`.

The solution I finally came with was to treat each element of a list of models separately in a `lapply()` function. This way `modelsummary()` always returns a consistent output. 

```
olr_tbl <- function(models_list, title = NA) {
  # Assumes the user provides models in a list
  modelsummary_list <- lapply(models_list, add_p_values)
  names(modelsummary_list) <- names(models_list)
  modelsummary::modelsummary(modelsummary_list, stars = TRUE)
}

add_p_values <- function(one_model) {
  one_modelsummary_list <- modelsummary::modelsummary(one_model,
                                                      output = "modelsummary_list")
  
  tidy_df <- one_modelsummary_list$tidy
  coeftest_out <- lmtest::coeftest(one_model)
  p <- coeftest_out[, "Pr(>|t|)"]
  varnames <- rownames(coeftest_out)
  tidy_df$p.value <- NA_real_
  for (i in seq_along(p)){
    term <- varnames[i]
    tidy_df[tidy_df$term == term, "p.value"] <- p[i]
  }
  one_modelsummary_list$tidy <- tidy_df
  one_modelsummary_list
}

m1 <- MASS::polr(ordered(gear) ~ mpg, data = mtcars)
m2 <- MASS::polr(ordered(gear) ~ mpg + hp, data = mtcars)

olr_tbl(list("Model A" = m1))
olr_tbl(list("Model A" = m1, "Model B" = m2))

```
It's a little bit more work.

**Comment by vincentarelbundock** [comment]
Right. I'll leave this thread open and think about it some more.


In the meantime, another option might be to write a hack-y wrapper like this:

``` r
library(modelsummary)

get_modelsummary_list <- function(x, ...) {
    out <- modelsummary(x, output = "modelsummary_list", ...)
    if (is.list(out) && names(out)[1] == "tidy") {
        out <- list(out)
    }
    return(out)
}

mod <- list(
    lm(mpg ~ hp, mtcars),
    lm(mpg ~ hp + vs, mtcars))

get_modelsummary_list(mod[[1]])
```

    ## [[1]]
    ## $tidy
    ## # A tibble: 2 × 5
    ##   term        estimate std.error statistic  p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
    ## 1 (Intercept)  30.1       1.63       18.4  6.64e-18
    ## 2 hp           -0.0682    0.0101     -6.74 1.79e- 7
    ## 
    ## $glance
    ## # A tibble: 1 × 13
    ##   r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC
    ##       <dbl>         <dbl> <dbl>     <dbl>       <dbl> <dbl>  <dbl> <dbl> <dbl>
    ## 1     0.602         0.589  3.86      45.5 0.000000179     1  -87.6  181.  186.
    ## # … with 4 more variables: deviance <dbl>, df.residual <int>, nobs <int>,
    ## #   F <dbl>
    ## 
    ## attr(,"class")
    ## [1] "modelsummary_list"

``` r
get_modelsummary_list(mod)
```

    ## $`Model 1`
    ## $tidy
    ## # A tibble: 2 × 5
    ##   term        estimate std.error statistic  p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
    ## 1 (Intercept)  30.1       1.63       18.4  6.64e-18
    ## 2 hp           -0.0682    0.0101     -6.74 1.79e- 7
    ## 
    ## $glance
    ## # A tibble: 1 × 13
    ##   r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC
    ##       <dbl>         <dbl> <dbl>     <dbl>       <dbl> <dbl>  <dbl> <dbl> <dbl>
    ## 1     0.602         0.589  3.86      45.5 0.000000179     1  -87.6  181.  186.
    ## # … with 4 more variables: deviance <dbl>, df.residual <int>, nobs <int>,
    ## #   F <dbl>
    ## 
    ## attr(,"class")
    ## [1] "modelsummary_list"
    ## 
    ## $`Model 2`
    ## $tidy
    ## # A tibble: 3 × 5
    ##   term        estimate std.error statistic  p.value
    ##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
    ## 1 (Intercept)  27.0       2.89        9.33 3.13e-10
    ## 2 hp           -0.0545    0.0145     -3.77 7.52e- 4
    ## 3 vs            2.58      1.97        1.31 2.01e- 1
    ## 
    ## $glance
    ## # A tibble: 1 × 13
    ##   r.squared adj.r.squared sigma statistic     p.value    df logLik   AIC   BIC
    ##       <dbl>         <dbl> <dbl>     <dbl>       <dbl> <dbl>  <dbl> <dbl> <dbl>
    ## 1     0.625         0.599  3.82      24.1 0.000000677     2  -86.7  181.  187.
    ## # … with 4 more variables: deviance <dbl>, df.residual <int>, nobs <int>,
    ## #   F <dbl>
    ## 
    ## attr(,"class")
    ## [1] "modelsummary_list"
