### ISSUE TITLE
Lowercase vcov strings (vcov = "hc1" etc.)

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/modelsummary#423]
Hey Vincent,

Just a quick one: 

How about enabling lowercase shorthand `vcov` strings? E.g. `msummary(mod, vcov="hc1")` equivalent to `msummary(mod, vcov="HC1")`. 

Apart from enabling slightly fewer keystrokes, one reason for supporting this would be wider consistency. Not only does `iid` work internally (as does `IID`), but the lowercase "hc1" works for `fixest::etable`. So my students would thank you for it!

**Comment by vincentarelbundock** [comment]
Yes that makes sense.

I'll try to take a look at some point. 

For reference, this should be very easy to accomplish by modifying the `sanitize_vcov` function here:

https://github.com/vincentarelbundock/modelsummary/blob/main/R/sanitize_vcov.R

The range strings we accept is quite limited, so perhaps we can just change everything to lower case with `tolower` and then have a "dictionary" that translates it back to what `sandwich` expects.

Just need to be careful to make sure that our change does not affect other types of `vcov` inputs (functions, matrices, vectors of strings, etc.).

**Comment by vincentarelbundock** [comment]
In principle, this should work in commit https://github.com/vincentarelbundock/modelsummary/commit/4b4c2de390ccd8f785ea5883b835a5a317ff82a7:

``` r
library(modelsummary)
mod <- lm(mpg ~ hp + drat, mtcars)
modelsummary(mod, vcov = c("RObust", "hC1", "hc2"))
```

|             | Model 1  | Model 2  | Model 3  |
| :---------- | :------: | :------: | :------: |
| (Intercept) |  10.790  |  10.790  |  10.790  |
|             | (4.587)  | (3.626)  | (3.958)  |
| hp          | \-0.052  | \-0.052  | \-0.052  |
|             | (0.013)  | (0.010)  | (0.011)  |
| drat        |  4.698   |  4.698   |  4.698   |
|             | (0.991)  | (0.850)  | (0.891)  |
| Num.Obs.    |    32    |    32    |    32    |
| R2          |  0.741   |  0.741   |  0.741   |
| R2 Adj.     |  0.723   |  0.723   |  0.723   |
| AIC         |  169.5   |  169.5   |  169.5   |
| BIC         |  175.4   |  175.4   |  175.4   |
| Log.Lik.    | \-80.752 | \-80.752 | \-80.752 |
| F           |  36.884  |  41.153  |  40.916  |
| Std.Errors  |  Robust  |   HC1    |   HC2    |

**Comment by grantmcdermott** [comment]
Perfect! Thanks mate. I was going to carve out time to put in a PR today, but glad you beat me to it.
