### ISSUE TITLE
modelsummary polr example not working for me

### ISSUE THREAD

**Issue by spobox** [vincentarelbundock/modelsummary#424]
I'm trying the below part of the modelsummary documentation.
library(MASS)
library(AER)
library(modelsummary)

tidy_custom.polr <- function(x, ...) {
  s <- lmtest::coeftest(x)
  out <- data.frame(
    term = row.names(s),
    p.value = s[, "Pr(>|t|)"])
  out
}

mod_ordinal <- polr(as.ordered(gear) ~ mpg + drat, data = mtcars)

modelsummary(mod_ordinal, stars = TRUE)

After the last line, it throw me: "Error in s[, "Pr(>|t|)"] : subscript out of bounds"

This is my first time to post to a buq to a github page. Apologies if there is etiquette I'm missing. (R version is 4.1.2)

I'm also very new to rstats and I apologize if I've done something obviously wrong. I spent a good bit of spent time trying to figure this out on my own to no avail.

**Comment by vincentarelbundock** [comment]
Try calling: `lmtest::coeftest(mod_ordinal)`. You'll see that the column is named with a `Pr(>|z|)` instead of a `Pr(>|t|)`. This is a typo in the documentation.

Thanks for the note!

**Comment by spobox** [comment]
I'd been staring at it like forever and didn't notice the z vs t. Thanks, it works great now!
