### ISSUE TITLE
Allow markdown styling in variable names

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#425]
Is it possible to add formatting to variable names in regression output? I would love if something like this would result in "log" being italicized: 

```r
library(modelsummary)
mod <- lm(disp ~ drat + log(mpg), data = mtcars)
varnames_markdown <- c("log(mpg)" = "*log* mpg")
modelsummary(mod, coef_rename = varnames_markdown)
```

The only way I managed to add styling to variable names was to prevent escaping in LaTeX output (which probably isn't ideal either) and italicize via `\emph{}`: 

```r
varnames_latex <- c("log(mpg)" = "\\emph{log} mpg")
modelsummary(mod,
             coef_rename = varnames_latex,
             output = "latex",
             escape = FALSE)
```
I think it would be great if Markdown styling (being the lingua franca) would be supported, perhaps with an option to turn it on deliberately? Apparently `fixest` just recently added this feature... and I even managed to add styling to variable names in ggplot, using `ggtext::element_markdown()` which I thought would be the much bigger issue ;)

**Comment by vincentarelbundock** [comment]
Please remember that `modelsummary` does not actually draw the table
itself, but instead relies on external packages to do that. As far as I
can tell, the default table packing package – `kableExtra` – does not
support markdown rendering out of the box. However, the `gt` package
*does* support it, and other packages like `flextable` and `huxtable`
may support it as well (I’m not sure).

For example:

``` r
library(gt)
library(modelsummary)

mod = lm(hp ~ log(mpg), mtcars)

cr = c("log(mpg)" = "*log*(mpg)")
modelsummary(mod, output = "gt", coef_rename = cr) |>
  fmt_markdown(columns = everything()) |>
  as_latex() |>
  cat()
```

    ## \captionsetup[table]{labelformat=empty,skip=1pt}
    ## \begin{longtable}{lc}
    ## \toprule
    ##   & Model 1 \\ 
    ## \midrule
    ## (Intercept) & 684.297 \\ 
    ##  & (76.685) \\ 
    ## \emph{log}(mpg) & -181.778 \\ 
    ##  & (25.802) \\ 
    ## Num.Obs. & 32 \\ 
    ## R2 & 0.623 \\ 
    ## R2 Adj. & 0.611 \\ 
    ## AIC & 335.1 \\ 
    ## BIC & 339.5 \\ 
    ## Log.Lik. & -164.567 \\ 
    ## F & 49.632 \\ 
    ##  \bottomrule
    ## \end{longtable}

**Comment by turbanisch** [comment]
Thanks again for your super fast reply! I honestly thought this might be something that `modelsummary` could take care of before piping the output to the packages used for rendering but I do see now that this might cause problems further down the line - who knows what mechanisms they use to escape characters. 

Also thanks for pointing me to the markdown-LaTeX conversion function in `gt`! I wish `gt`'s LaTeX capabilities were a bit more advanced and customizable already though... Perhaps I can steal the `fmt_markdown` idea and hope it gets incorporated into `kableExtra` (unfortunately Hao Zhu doesn't seem to be quite as responsive as you are). 

Have a great Christmas break!
