### ISSUE TITLE
lmer output hang with large number of random effects (varying intercepts); stargazer ok though

### ISSUE THREAD

**Issue by bshor** [vincentarelbundock/modelsummary#426]
I'm trying to generate a modelsummary output within a markdown file. Unfortunately, modelsummary hangs when trying to display lme4::lmer models with a lot of random effects, while stargazer has no problem. Here's the call:

```r
mlm.roll <-list()
mlm.roll[["D Majority"]] <- lmer(majparty.roll ~ (1 | st) + (1 | bill_id) + sponsor.maj.dist + sponsor.party.majmin + gparty + bowen1, data = subset(rollcalls.m,majparty=="D"),control=lmerControl(optimizer = "nloptwrap"))
mlm.roll[["R Majority"]] <- lmer(majparty.roll ~ (1 | st) + (1 | bill_id) + sponsor.maj.dist + sponsor.party.majmin + gparty + bowen1, data = subset(rollcalls.m,majparty=="R"),control=lmerControl(optimizer = "nloptwrap"))

```

The data set is very large, with hundreds of thousands of observations per model, 50 states (denoted as "st"), and tens/hundreds of thousands of bills (denoted as "bill_id"). If I remove the varying intercept for bill, I get modelsummary with no issue. But when I include it, R is frozen for a long time until I kill Rstudio. Again, stargazer shows instant output. But I prefer to use modelsummary.

```r
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Garuda Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.10.0
LAPACK: /usr/lib/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] kableExtra_1.3.4   lme4_1.1-27.1      Matrix_1.4-0       knitr_1.36         pryr_0.1.5         tictoc_1.0.1      
 [7] modelsummary_0.9.4 stargazer_5.2.2    janitor_2.1.0      ggrepel_0.9.1      ggplot2_3.3.5      dplyr_1.0.7       
[13] stringr_1.4.0      fst_0.9.4         

loaded via a namespace (and not attached):
 [1] httr_1.4.2        tidyr_1.1.4       viridisLite_0.4.0 splines_4.1.2     carData_3.0-4     gtools_3.9.2      assertthat_0.2.1 
 [8] stats4_4.1.2      tables_0.9.6      yaml_2.2.1        pillar_1.6.4      backports_1.4.0   lattice_0.20-45   glue_1.5.1       
[15] visdat_0.5.3      digest_0.6.29     rvest_1.0.2       snakecase_0.11.0  minqa_1.2.4       colorspace_2.0-2  MuMIn_1.43.17    
[22] htmltools_0.5.2   plyr_1.8.6        pkgconfig_2.0.3   qdapRegex_0.7.2   broom_0.7.10      purrr_0.3.4       webshot_0.5.2    
[29] scales_1.1.1      lobstr_1.1.1      svglite_2.0.0     naniar_0.6.1      gdata_2.18.0      tibble_3.1.6      mgcv_1.8-38      
[36] farver_2.1.0      generics_0.1.1    car_3.0-12        ellipsis_0.3.2    withr_2.4.3       cli_3.1.0         magrittr_2.0.1   
[43] crayon_1.4.2      evaluate_0.14     fansi_0.5.0       nlme_3.1-153      MASS_7.3-54       xml2_1.3.3        tidyfast_0.2.1   
[50] tools_4.1.2       data.table_1.14.2 lifecycle_1.0.1   munsell_0.5.0     compiler_4.1.2    systemfonts_1.0.3 rlang_0.4.12     
[57] nloptr_1.2.2.3    grid_4.1.2        rstudioapi_0.13   labeling_0.4.2    rmarkdown_2.11    boot_1.3-28       gtable_0.3.0     
[64] codetools_0.2-18  abind_1.4-5       DBI_1.1.1         R6_2.5.1          zoo_1.8-9         lubridate_1.8.0   textclean_0.9.3  
[71] fastmap_1.1.0     utf8_1.2.2        stringi_1.7.6     parallel_4.1.2    Rcpp_1.0.7        vctrs_0.3.8       tidyselect_1.1.1 
[78] xfun_0.28        
```

**Comment by vincentarelbundock** [comment]
Thanks for the report. I tracked this down to an issue with the upstream package `parameters`: https://github.com/easystats/parameters/issues/644

In the meantime, you can load this library before calling `modelsummary` and things should get back to being essentially instantaneous:

```r
library(broom.mixed)
```

In the long run, it would be much better for `parameters` package to become faster, and then I would recommend stopping the use of `broom.mixed`.

**Comment by bshor** [comment]
Awesome! Thank you so much!

But ... I don't get stars anymore, as modelsummary complains that there is no "p.value" column. When I try broom.mixed::tidy, I see indeed there is no p.value column. Interestingly, broom::tidy.mlm does this, but for some reason it's not being called by broom.mixed.

```
Error in format_estimates(est = msl[[i]]$tidy, fmt = fmt, estimate = estimate[[i]],  : 
  To use the `stars` argument, the `tidy` function must produce a column called "p.value"
```

**Comment by strengejacke** [comment]
I found the bottle neck (see discussion here: https://github.com/easystats/parameters/issues/644), which should in theory make _modelsummary_ way faster now. _parameters_ will be updated the next days, and so will _modelsummary_, so probably (hopefully) you'll be able to produce "quick" tables even for models with very large samples in a few days again...

**Comment by bshor** [comment]
Amazing that you followed up this way! This is really above and beyond. Can't wait.

**Comment by vincentarelbundock** [comment]
In addition, a recent update to the `insight` package also makes things a fair bit faster. You can install the devel version here:

```{r}
remotes::install_github("easystats/insight")
```

Will all of these changes, we should be in business pretty soon :)

**Comment by bshor** [comment]
Any quick fix for stars with broom.mixed? If not, it's ok.

**Comment by vincentarelbundock** [comment]
> Any quick fix for stars with broom.mixed? If not, it's ok.

No, unfortunately. You could create the stars yourself with a `tidy_custom` method (see website docs), but that's quite involved.

Frankly, I think you're better off installing the `insight` and `parameters` packages from Github and avoid loading `broom.mixed`. @strengejacke will merge the fix in `parameters` soon, so in the next couple days you could do this:

```{r}
library(remotes)
install_github("easystats/insight")
install_github("easystats/parameters")
```

Then restart `R`, and try again. My guess is this will take <10s even with lots of units.

**Comment by bshor** [comment]
Ok, I'll install the development version and give it a shot.

**Comment by bshor** [comment]
Unfortunately, I still get a hang (or at least I gave up after several minutes).

I have the 0.15.0.1 versions of both insight and parameters (I tried both install_github and install_packages with the development repo set).

I restarted R as per your suggestion.

> > Any quick fix for stars with broom.mixed? If not, it's ok.
> 
> No, unfortunately. You could create the stars yourself with a `tidy_custom` method (see website docs), but that's quite involved.
> 
> Frankly, I think you're better off installing the `insight` and `parameters` packages from Github and avoid loading `broom.mixed`. @strengejacke will merge the fix in `parameters` soon, so in the next couple days you could do this:
> 
> ```
> library(remotes)
> install_github("easystats/insight")
> install_github("easystats/parameters")
> ```
> 
> Then restart `R`, and try again. My guess is this will take <10s even with lots of units.

**Comment by bshor** [comment]
Oh I didn't see the part where you said it'd take a few days. Got it!

**Comment by strengejacke** [comment]
>  and so will modelsummary

Sorry, I confused modelsummary with marginaleffects - the latter was just updated, modelsummary is not planned to be updated the next days.

> Unfortunately, I still get a hang (or at least I gave up after several minutes).

I was working on a different branch, but now it is merged. Please try again 

```
library(remotes)
install_github("easystats/insight")
install_github("easystats/parameters")
```

and make sure **both packages are of version 0.15.0.2** - then it would (hopefully) become much faster.

**Comment by bshor** [comment]
I successfully installed 0.15.0.2 of both packages but I am still waiting after several minutes :( Sorry for the trouble.

**Comment by vincentarelbundock** [comment]
@bshor ,

Did you restart R after installing? Can you tell us more about your model? Do you get the same result when you type these commands?

``` r
packageVersion("insight")
    ## [1] '0.15.0.2'
packageVersion("parameters")
    ## [1] '0.15.0.2'
```

Here’s an example with two levels and 1000 units, and it only takes 3 seconds on my machine: 

``` r
library(lme4)
library(tictoc)
library(modelsummary)

N <- 1e6
dat <- data.frame(
  x = rnorm(N),
  y = rnorm(N),
  k = factor(sample(1:50, N, replace = TRUE)),
  m = factor(sample(1:1000, N, replace = TRUE)))

mod <- lmer(y ~ x + (1 | k) + (1 | m), data = dat)

tic()
tab <- modelsummary(mod)
toc()
```

    ## 3.591 sec elapsed

You can also play with the `metrics` argument, which limits the range of
goodness of fit statistics which are computed (type:
`?performance::model_performance.merMod`)

``` r
modelsummary(mod, metrics = "RMSE")
```

**Comment by bshor** [comment]
Yep, I restarted R. And here's the versions:

```
> packageVersion("insight")
[1] ‘0.15.0.2’
> packageVersion("parameters")
[1] ‘0.15.0.2’
```

Here's the model call:

```
   mlm.roll.com <-list()
    mlm.roll.com[["D Majority"]] <- lmer(majparty.roll ~ (1 | st) + (1 | bill_id) + sponsor.maj.dist + sponsor.party.majmin + prop.maj + gparty + bowen1, data = subset(rollcalls.m,!floor & majparty=="D" & !gparty=="X"),control=lmerControl(optimizer = "nloptwrap"))
    mlm.roll.com[["R Majority"]] <- lmer(majparty.roll ~ (1 | st) + (1 | bill_id) + sponsor.maj.dist + sponsor.party.majmin + prop.maj + gparty + bowen1, data = subset(rollcalls.m,!floor & majparty=="R" & !gparty=="X"),control=lmerControl(optimizer = "nloptwrap"))

```

In model "D Majority" I have about 160k observations, 65k bills (bill_id), 13 states (st). In model "R Majority" I have about 160k observations, 89k bills and 25 states.

**Comment by vincentarelbundock** [comment]
¯\_(ツ)_/¯

If this is something you can share, you could save it like this:

```{r}
saveRDS(mlm.roll.com, file = "model.rds")
```

and send it to me by email or Dropbox. I'd take a look and do some profiling.

**Comment by bshor** [comment]
Happy to do so, but setting metrics=RMSE gives me instant results!!

**Comment by vincentarelbundock** [comment]
Wonderful! I'll look into the metrics issue eventually, but I think we're good for now.

**Comment by strengejacke** [comment]
Does metrics include R2 by default?

**Comment by bshor** [comment]
No, just RMSE in this example.

**Comment by vincentarelbundock** [comment]
@strengejacke yes, by default. I thought it was part of the "common" set. Do you recommend a different default?

**Comment by strengejacke** [comment]
Not particular in your example, but I'm general, if you don't explicitly set the metrics argument.

**Comment by strengejacke** [comment]
> @strengejacke yes, by default. I thought it was part of the "common" set. Do you recommend a different default?

No, not necessarily, but that might explain the longer computation time.

**Comment by bshor** [comment]
I sent both of you the offending model fit :)

Right, if I don't set metrics="RMSE", I do get R2 estimates (but those take several minutes).

**Comment by strengejacke** [comment]
```r
performance::r2(mlm.roll.com[[1]]) # 65 sec.
```

takes approx. 65 seconds to compute R2. I profiled the function, and literally almost the full 65 seconds were due to `ranef()` - I think this is something that can't be improved (regarding speed) from our side.

**Comment by bshor** [comment]
Thanks, Daniel. Now I'll hold off computing the R2 until I really need it. I appreciate your help very much.

**Comment by vincentarelbundock** [comment]
FYI, the next version of `modelsummary` (coming out in a few days) will no longer compute `R2` by default, and will generate a once-per-session warning to inform users of the `metrics` argument.
