### ISSUE TITLE
confidence interval as +- value

### ISSUE THREAD

**Issue by jamarav** [vincentarelbundock/modelsummary#437]
Hi everybody, First of all, congratulations for this amazing package. I'm writing my phd thesis with R and knitr+Latex and this is one of the extension packages that allows me to elegantly report the results of my models. 

I'm traying to obtain a simple model table including the estimate +- the confidence interval.  I checked the documentation but this is not an output value included in `get_estimates()`. I tryed some options with the estimate parameter and glue but without succes.

This is a simple example:

```
#Model
STR <- c(15, 17, 19, 20, 22, 23.5, 25)
TestScore <- c(680, 640, 670, 660, 630, 660, 635) 

linear_model<-lm(TestScore ~ STR)
 
#Confidence interval 95% automatically
confint(linear_model)

             2.5 % 97.5 %
(Intercept) 610.08 817.05
STR          -8.02   2.08

#Taking as example the STR coefficient
lm_summ <- summary(linear_model)

#Confidence interval 95% manually
c("lower" = lm_summ$coef[2,1] - qt(0.975, df = lm_summ$df[2]) * lm_summ$coef[2, 2],"upper" = lm_summ$coef[2,1] + qt(0.975, df = lm_summ$df[2]) * lm_summ$coef[2, 2])

lower upper 
-8.02  2.08 

#Desired format
paste0(round(lm_summ$coef[2,1], 3), " ± ", round(qt(0.975, df = lm_summ$df[2]) * lm_summ$coef[2, 2], 2) 

[1] "-2.968 ± 5.05"

#Test in modelsummary without succes
modelsummary(linear_model, fmt = "%.4e", estimate = "{estimate} {get_estimates(linear_model)[,2] - get_estimates(linear_model)[,6]}")
``` 
Addiionally, I'm not able to provide different round between the estimate values and the confidence interval. The page area is limited and I would like to decrease the significant digits only in the confidence value. I checked the `fmt` parameter but it changes globally the significant digits for all the data included in the summary table.

Any suggestion will be welcome.

Thanks in advance

**Comment by jamarav** [comment]
Amazing!!! I didin't know these extension functions. Thanks you very much @vincentarelbundock. Following your suggestion this `tidy_custom.lm` funtion solves my problem:

```
tidy_custom.lm <- function(x, conf_level = 0.95, ...) {
  s <- summary(x)$coefficients
  
  alpha<-1-conf_level
  
  new_col<-qt(1-alpha/2, df = df.residual(x)) * s[, 'Std. Error'] #Manual calculation confidence interval
  #new_col<-summary(x)$coefficients[, 1] - confint(x, level  = conf_level)[,1] #Confidence interval extracted from confint() function
  
  out <- data.frame(
    term = row.names(s),
    `conf.int.custom` = new_col)
  
  return(out)
}


#Example table + glue
modelsummary(mod, estimate = '{estimate} ± {conf.int.custom}')
```
The solution is easy to implement. However, I would like to suggest to implemment this `conf.int.custom` in a future release. It allow us to compact the information if we have enough horizontal space.

Regarding to the significant digits, Is it possible to specify different  significant digits in the estimate value and the confidence interval?

Thanks in advance

**Comment by vincentarelbundock** [comment]
You can round the digits directly in the `tidy_custom.lm` function instead of relying on the `fmt` argument.

Just call `round` or `sprintf` or `format` or whatever formating function you need to pic the digits of each term.

**Comment by jamarav** [comment]
All right now. I updated the `tidy_custom.lm` function:

```
tidy_custom.lm <- function(x, conf_level = 0.95, ...) {
  s <- summary(x)$coefficients
  
  alpha<-1-conf_level
  
  new_col<-qt(1-alpha/2, df = df.residual(x)) * s[, 'Std. Error'] #Manual calculation confidence interval
  #new_col<-summary(x)$coefficients[, 1] - confint(x, level  = conf_level)[,1] #Confidence interval extracted from confint() function
  
  out <- data.frame(
    term = row.names(s),
    `conf.int.custom` = formatC(new_col, format = "e", digits = 1) )
  
  return(out)}
```

Thank you very much @vincentarelbundock!!!
