### ISSUE TITLE
Exponentiated and Non-Exponentiated Models Together

### ISSUE THREAD

**Issue by ftraylor** [vincentarelbundock/modelsummary#458]
I would appreciate being able to include exponentiated models (`exponentiate = TRUE`) and non-exponentiated models in the same `modelsummary()` table.  As I understand it, all models in a table are exponentiated if set to TRUE.  Occasionally, I will need to present logit and OLS models together, or present the exponentiated and non-exponentiated results for the same model together. Maybe it takes the form of an estimate output, like how we can alter the estimate outputs for each model in a table:  `estimate  = ("estimate",
 "{estimate} ({std.error})")`

**Comment by vincentarelbundock** [comment]
Thanks for this excellent suggestion. I pushed a change to the development version on Github to allow this. You can install it now or wait until the next CRAN release to do this:

``` r
library(modelsummary)
mod <- list(
    glm(am ~ mpg, data = mtcars, family = binomial),
    glm(am ~ mpg + drat, data = mtcars, family = binomial))

modelsummary(mod, output = "markdown")
```

|             | Model 1  | Model 2  |
| :---------- | :------: | :------: |
| (Intercept) | \-6.604  | \-20.504 |
|             | (2.351)  | (7.931)  |
| mpg         |  0.307   |  0.128   |
|             | (0.115)  | (0.131)  |
| drat        |          |  4.729   |
|             |          | (2.159)  |
| Num.Obs.    |    32    |    32    |
| AIC         |   33.7   |   26.6   |
| BIC         |   36.6   |   31.0   |
| Log.Lik.    | \-14.838 | \-10.289 |
| F           |  7.148   |  3.715   |
| RMSE        |   0.99   |   0.84   |


First model stays the same, but the second is exponentiated:

``` r
modelsummary(mod, exponentiate = c(FALSE, TRUE), output = "markdown")
```

|             | Model 1  |  Model 2  |
| :---------- | :------: | :-------: |
| (Intercept) | \-6.604  |   0.000   |
|             | (2.351)  |  (0.000)  |
| mpg         |  0.307   |   1.136   |
|             | (0.115)  |  (0.149)  |
| drat        |          |  113.156  |
|             |          | (244.358) |
| Num.Obs.    |    32    |    32     |
| AIC         |   33.7   |   26.6    |
| BIC         |   36.6   |   31.0    |
| Log.Lik.    | \-14.838 | \-10.289  |
| F           |  7.148   |   3.715   |
| RMSE        |   0.99   |   0.84    |

**Comment by ftraylor** [comment]
Amazing - thanks so much!

**Comment by kaseyzapatka** [comment]
Hi @vincentarelbundock, 

I'm stuck using Rstudio in a data enclave and they have an old version of modelsummary (version9.6) that I can't update to use this feature. Is there a way to include exponentiated exponents manually? What did users do before you added this feature? 

Thanks!

**Comment by ftraylor** [comment]
My previous solution was to simply create two separate tables, one exponentiated and the other not. 

```
m1 <-  glm(am ~ mpg, data = mtcars, family = binomial)

library(modelsummary)
modelsummary(m1, title = "Log Odds")
modelsummary(m1, title = "Odds Ratios", exponentiate = T)
```

Another possible solution could be to build the model objects yourself, as described in "[Adding New Models (Part I)](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-models-part-i)." 

```
m1.glance <- glance(m1)
m1.tidy.noexp <- tidy(m1)
m1.tidy.exp <- tidy(m1, exponentiate = T)

m1.nonexp <- list(tidy = m1.tidy.noexp, glance = m1.glance)
m1.expon <- list(tidy = m1.tidy.exp, glance = m1.glance)

class(m1.nonexp) <- "modelsummary_list"
class(m1.expon) <- "modelsummary_list"

mods <- list("Log Odds" = m1.nonexp, "Odds Ratios" = m1.expon)
modelsummary(mods)
```

**Comment by vincentarelbundock** [comment]
Thanks for your comments @ftraylor! That's a good approach.

2 things I'll note. First, the `exponentiate` argument should work in prior versions, it will just be applied to all models in the table. This Issue was about allowing it to apply to different models.

Second, if `exponentiate` doesn't do anything, you may want to switch the parameter extracting backend from the `broom` package to the `parameters` package: `options(modelsummary_get = "parameters")`

I think some `tidy` methods don't have an `exponentiate` argument, so they will just silently ignore it, and `parameters` is more complete in that regard.

In the next version of `modelsummary` (on its way to CRAN), we handle `exponentiate` in-house, so it should work everywhere.

**Comment by kaseyzapatka** [comment]
thanks, @vincentarelbundock! really appreciate your thoughts here and love modelsummary package.
