### ISSUE TITLE
Journal themes

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#463]

**Comment by strengejacke** [comment]
I _think_ this is what I just wanted to suggest in a new issue...

**Comment by vincentarelbundock** [comment]
Right, this would be a very cool feature. There is already a theme mechanism that we could leverage for some of: https://vincentarelbundock.github.io/modelsummary/articles/appearance.html#themes

**Comment by vincentarelbundock** [comment]
I thought about this and I don't think that *I* (me personally) will be implementing this. First, I am almost certainly never going to us this myself, as I like to control the tables I publish. Second, I looked at alternative package (which shall not be named) and I was less than impressed by the theming functionality.

As I pointed out above, there is already theming functionality built in, and I'll be more than happy to review PRs if someone feels the urge to do it. However, realistically, I'm never going to get around to doing this, so I'll close for now.
