### ISSUE TITLE
Changes in the internal structure of `fixest_multi` objects

### ISSUE THREAD

**Issue by lrberge** [vincentarelbundock/modelsummary#469]
Hi Vincent,

I have overhauled the internal structure of the `fixest_multi` objects, now they're much easier to handle. In particular, to avoid to deal with the internal quirks, I created the `models` function which provides the "model" information for each estimation. 

Yet, internally, the previous elements that you used, e.g. the attribute `meta`, don't exist any more, leading to a problem here:
https://github.com/vincentarelbundock/modelsummary/blob/c63c9b2b79f124a2f19252cecce7e2093711a265/R/sanitize_models.R#L8

I'm sorry for the change, which would require a condition on the package version. But the code for the new version would be more direct:
```R
tree = models(x)
if ("lhs" %in% names(tree)) {
  out <- paste0(out, tree$lhs, " ")
}
if ("sample" %in% names(att$tree)) {
  out <- paste0(out, tree$sample)
}
```

It concerns the development version of `fixest` which won't be out before a good three weeks. I'm deeply sorry for the bother!

**Comment by vincentarelbundock** [comment]
No worries at all, Laurent.

I think I've got it working now; was very easy with your suggested code as a starting point.

From now on, I think I'll just support one version at a time. When I am made aware of breaking changes from `fixest`, I'll make the update and issue a prompt for users to update. Should be easier than holding a ton of if-elses.

**Comment by lrberge** [comment]
I'm with you, it makes a lot of sense to sustain only one version.
But I'll try really hard not to break things again!
