### ISSUE TITLE
RMSE v Residual standard error in OLS

### ISSUE THREAD

**Issue by scipima** [vincentarelbundock/modelsummary#473]
hi, this is my first-ever issue to an R package, so bear with me.

i just noticed the following and could not find an explanation in the package documentation (apologies in advance if i missed it!). 
there seems to be a misalignment between what the 'modelsummary' labels as RMSE and what the summary function labels as residuals standard error for an OLS model. 
code below hopefully illustrates. 

`library(tidyverse); library(janitor); stackloss <- stackloss |> janitor::clean_names()`

The summary of the linear model has Residual standard error: 3.243 on 17 degrees of freedom
`stack_loss_lm <- lm(stack_loss ~ ., data = stackloss)
summary(stack_loss_lm)`

The formula for Residual standard error is
`sqrt(sum(stack_loss_lm$residuals^2) / (nrow(stackloss) - length(stack_loss_lm$coefficients))) `

However, the output of modelsummary has an RMSE which is equal to Residual standard error
`modelsummary::modelsummary(list(OLS=stack_loss_lm), output = "huxtable")`

But the formula for RMSE does indeed give us a different value
`sqrt(mean(stack_loss_lm$residuals^2)) # formula for RMSE gives different value`

Thanks in advance for a great package!!

**Comment by vincentarelbundock** [comment]
@scipima, thanks so much for this report, I really appreciate it\!

You’re 100% right. The fix will be part of the next release on CRAN, which should be in about 2 weeks. In the meantime, I pushed a fix to Github, which you can install with:

``` r
library(remotes)
install_github("vincentarelbundock/modelsummary")
```

Restart `R` completely, then:

``` r
library(modelsummary)
mod <- lm(mpg ~ hp + factor(cyl), data = mtcars)
modelsummary(mod, "markdown")
```

|              | Model 1  |
| :----------- | :------: |
| (Intercept)  |  28.650  |
|              | (1.588)  |
| hp           | \-0.024  |
|              | (0.015)  |
| factor(cyl)6 | \-5.968  |
|              | (1.639)  |
| factor(cyl)8 | \-8.521  |
|              | (2.326)  |
| Num.Obs.     |    32    |
| R2           |  0.754   |
| R2 Adj.      |  0.727   |
| AIC          |  169.9   |
| BIC          |  177.2   |
| Log.Lik.     | \-79.948 |
| F            |  28.585  |
| RMSE         |   2.94   |

``` r

sqrt(mean(residuals(mod)^2))
#> [1] 2.943041
```

Feel free to open a new issue if the fix does not work for you or if you spot other problems.

Thanks again\!

**Comment by scipima** [comment]
great! happy to have helped.
take care, marco
