### ISSUE TITLE
Follow-up of issues #442 and #473: including sigma parameter by default

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#482]
Include residual standard error (cf. issue #473 ): I've seen it included in the output of `model_performance` at least for `lm` objects.

Also the corresponding `df` (`insight::get_df`-alike).

And F-statistic together with the p-value (returned by `broom::glance`).

Thanks!

**Comment by iago-pssjd** [comment]
And also the corresponding `df` (`insight::get_df`-alike)

**Comment by vincentarelbundock** [comment]
Thanks for the suggestions.

* Sigma is already available, but omitted by default by `gof_map`. You can modify the default `gof_map` data frame to avoid the omission.
* By default, `modelsummary` now uses the output of `performance::performance` to collect goodness of fit statistics. Degrees of freedom are not reported by default. You can open a feature request on the `performance` repo and see what they think.
* You can always change the extractor function back to `broom` using: `options(modelsummary_get="broom")`. I think this will give you the statistics you want, including the `p.value`.

**Comment by iago-pssjd** [comment]
Oh! sorry. I've seen just now your example
```r
gm <- modelsummary::gof_map
gm$omit <- FALSE
modelsummary(models, gof_map = gm)
```
and saw that all the parameters I asked for are reported.

Thanks!

**Comment by vincentarelbundock** [comment]
Great! Although fair warning: they may no longer be there in the next version that will no longer rely on broom

**Comment by iago-pssjd** [comment]
Thanks @vincentarelbundock ! I will ask for them to `performance`.

Beyond that,  it seems that there is a documentation bug in
https://github.com/vincentarelbundock/modelsummary/blob/1f3f3e5a6cf0929974ae8437d6a1bb3e20fc52b6/man-roxygen/modelsummary_examples.R#L105-L109
where it should be `gm` instead of `gof_custom`.

**Comment by vincentarelbundock** [comment]
Thanks! I updated the docs.

**Comment by iago-pssjd** [comment]
Thanks to you for the great package and the quick updates!
Just note that there is yet a `gof_custom` in
https://github.com/vincentarelbundock/modelsummary/blob/d41f3be7c116e2a38cd5fceacb63a2ffaf3d3faf/man-roxygen/modelsummary_examples.R#L107

**Comment by vincentarelbundock** [comment]
good catch!
