### ISSUE TITLE
Error with webshot webshot.js returned failure value (png-output creation)

### ISSUE THREAD

**Issue by qm2021-jfremere** [vincentarelbundock/modelsummary#484]
I try to creeate a png-output with the datasummary package. Sadly, I have problems with the interactive webshot package despite I installed phantomjs.
I uploaded a zip-file of our current code. Basically, it is in line 1000-1020 and further I try to use the datasummary package and it works wonderful with the interactive shiny-version. However, saving the output as for example tex- png- or any other type of document does not work doe to the error: could not load:..... .html : Error in websho::webshot(file_temp_html, file, ...): webshot.js returned failure value: 1.

Sadly, the webshot package was not very helpful to get a workaround - I tried to some input which I took from the webshot- R help website. Code is in line 1012 ff. Sadly, it did not work.

f <- All(ESS_funds_regions_sumfull_num) ~  Mean + SD + Min + Median + Max + Histogram 

datasummary(f, ESS_funds_regions_sumfull_num, 
            title = caption_sumfull_num,
            notes = reference_sumfull,
            output="kableExtra") #this does work!

datasummary(f, ESS_funds_regions_sumfull_num, 
            title = caption_sumfull_num,
            notes = reference_sumfull,
            output="summay_table_all.png") #this does not work!
[Euroscepticism-arXiv-template2.zip](https://github.com/vincentarelbundock/modelsummary/files/8812919/Euroscepticism-arXiv-template2.zip)

**Comment by vincentarelbundock** [comment]
This sounds like a `webshot` problem, and not a `modelsummary` problem. You probably want to make sure your `webshot` installation is working by trying one of the minimal examples in that package's vignette:

https://cran.r-project.org/web/packages/webshot/readme/README.html

If this is indeed a `webshot` problem and not a bug in `modelsummary`, you should consult that package's documentation or report the bug on their development website. But before you do so, I *strongly* recommend you learn how to compose *Minimal Working Examples*. Very few developers will want to (a) open potentially dangerous Zip files submitted by anonymous people on the interenet, and (b) sift through 1000+ lines of code to figure out the problem. Here are two links to help you learn how to ask good questions about software problems:

https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610

https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html
