### ISSUE TITLE
Documentation bug according to new `modelsummary` "path"

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#486]
According to the new way of extracting estimates and goodness-of-fit statistics using `easystats` instead of `broom`, the following two messages may should be updated:
https://github.com/vincentarelbundock/modelsummary/blob/d41f3be7c116e2a38cd5fceacb63a2ffaf3d3faf/R/get_estimates.R#L49-L66
https://github.com/vincentarelbundock/modelsummary/blob/d41f3be7c116e2a38cd5fceacb63a2ffaf3d3faf/R/get_gof.R#L87-L98

Thanks!

**Comment by vincentarelbundock** [comment]
thanks 230a46afc0a8578baed0f556
