### ISSUE TITLE
Add a vignette on the best way using `output = "modelsummary_list"`

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#487]
I think it would be very useful to have more examples on how to use this output, expanding mainly https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#customizing-existing-models-part-iii

For me it is very useful this 2-steps customization process. Let's see your example
```r
library("lme4")
mod <- lmer(mpg ~ drat + (1 | am), data = mtcars)
mod_list <- modelsummary(mod, output = "modelsummary_list", effects = "fixed")
mod_list_kenward <- as.list(mod_list)
mod_list_kenward$tidy$p.value <- parameters::p_value_kenward(mod)$p

modelsummary(list("Wald" = mod_list, "Kenward" = mod_list_kenward), 
            statistic = "{std.error} ({p.value}) {stars}")
```
In the first step you use the option `effects = "fixed"`, while in the second step you use the option `statistic = "{std.error} ({p.value}) {stars}"`. What do I mean by this? If I'm not wrong, `modelsummary` options  like  `notes`, `title` or `stars` only have their effect on the second step, while `effects`  have it on the first step, and `output` is needed on the two steps; also the `estimate` or `statistic` options are needed on the 2 steps when they include `conf.int`. A table describing in which of the steps these options are needed would be very useful.

Thanks!

**Comment by vincentarelbundock** [comment]
It sounds like a good idea to add a longer section on that in the `modelsummary` vignette.
I'd be happy to merge a Pull Request if you want to submit improvements to the documentation.

**Comment by vincentarelbundock** [comment]
Closing this to clean up the issues, but feel free to open a PR with improvements to the existing vignettes if you have time/want. FWIW, I would prefer adding to existing vignettes rather than creating a whole new one.
