### ISSUE TITLE
Improve documentation on extracting additional fixest statistics

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#488]
Since I mentioned my struggles to get IV-specific statistics into `modelsummary()` in another thread, I thought I might as well expand a bit on that here. The first comment is a suggestion to alter the example in the [vignette](https://github.com/vincentarelbundock/modelsummary/blob/230a46afc0a8578baed0f556be0ef05207d56e0f/vignettes/modelsummary.Rmd#L1071-L1100) very slightly; the second comment is basically a question on how to improve the workflow with the `glance_custom()` method.

The example from the vignette defines a method to look up the `"ivwald"` statistic from `fixest` models. Somewhat arbitrarily, we end up extracting the first-stage Wald statistic only for the first endogenous regressor, not for the second one (nor for the second stage that is being shown here):

``` r
library(fixest)
library(tidyverse)
library(modelsummary)

# create a toy dataset
set.seed(1)
base <- iris
names(base) <- c("y", "x1", "x_endo_1", "x_inst_1", "fe")
base$x_inst_2 <- 0.2 * base$y + 0.2 * base$x_endo_1 + rnorm(150, sd = 0.5)
base$x_endo_2 <- 0.2 * base$y - 0.2 * base$x_inst_1 + rnorm(150, sd = 0.5)

# estimate an instrumental variable model
mod <- feols(y ~ x1 | fe | x_endo_1 + x_endo_2 ~ x_inst_1 + x_inst_2, base)

# custom extractor function returns a one-row data.frame (or tibble)
glance_custom.fixest <- function(x) {
  tibble("IV Wald" = fitstat(x, "ivwald")[[1]]$stat)
}

# draw table
modelsummary(mod, output = "markdown")
#> Registered S3 methods overwritten by 'effectsize':
#>   method              from      
#>   standardize.Surv    datawizard
#>   standardize.bcplm   datawizard
#>   standardize.clm2    datawizard
#>   standardize.default datawizard
#>   standardize.mediate datawizard
#>   standardize.wbgee   datawizard
#>   standardize.wbm     datawizard
```

|                | Model 1  |
|:---------------|:--------:|
| fit_x\_endo_1  |  0.379   |
|                | (0.235)  |
| fit_x\_endo_2  |  5.185   |
|                | (14.608) |
| x1             |  -0.594  |
|                | (3.293)  |
| Num.Obs.       |   150    |
| R2             |  -9.097  |
| R2 Adj.        |  -9.448  |
| R2 Within      | -25.481  |
| R2 Within Adj. | -26.032  |
| RMSE           |   2.62   |
| Std.Errors     |   IID    |
| FE: fe         |    X     |
| IV Wald        |  28.632  |

``` r
# value above refers to the first-stage Wald statistic only for the first endogenous regressor
etable(mod, fitstat = "ivwald")
#>                                        mod
#> Dependent Var.:                          y
#>                                           
#> x_endo_1                   0.3790 (0.2348)
#> x_endo_2                     5.185 (14.61)
#> x1                         -0.5938 (3.293)
#> Fixed-Effects:             ---------------
#> fe                                     Yes
#> __________________________ _______________
#> S.E.: Clustered                     by: fe
#> Wald (1st stage), x_endo_1          28.632
#> Wald (1st stage), x_endo_2         0.29314
#> ---
#> Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

I get that you expect some background in both econometrics and R programming in your examples and that you intend to keep them as short as possible. In this case, however, I suggest either pointing out which Wald statistic is being shown or add the one for the other endogenous regressor/second stage (similar to the output from `etable()` above). Apparently, the corresponding statistic for the other endogenous regressor can be extracted with `fitstat(mod, "ivwald")[[2]]$stat` and the one for the second stage as `fitstat(mod, "ivwald2")[[1]]$stat`. Another idea would be to use `"ivwaldall"` which picks the corresponding Wald stat for each estimation when the first stage is shown:

``` r
etable(mod, stage = 1:2, fitstat = "ivwaldall")
#>                           mod.1           mod.2           mod.3
#> IV stages                 First           First          Second
#> Dependent Var.:        x_endo_1        x_endo_2               y
#>                                                                
#> x_inst_1        0.8151 (0.4561) 0.0092 (0.0262)                
#> x_inst_2        0.2907 (0.1166) 0.0433 (0.1278)                
#> x1              0.1885 (0.1759) 0.2231 (0.1040) -0.5938 (3.293)
#> x_endo_1                                        0.3790 (0.2348)
#> x_endo_2                                          5.185 (14.61)
#> Fixed-Effects:  --------------- --------------- ---------------
#> fe                          Yes             Yes             Yes
#> _______________ _______________ _______________ _______________
#> S.E.: Clustered          by: fe          by: fe          by: fe
#> Wald (IV only)           28.632         0.29314          14.359
#> ---
#> Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```

The second comment relates to my workflow with the `glance_custom()` method. Having it set up as above, it will fail for any non-IV estimation with `feols()`:

``` r
mod2 <- feols(y ~ x1 | fe, data = base)
modelsummary(mod2, output = "markdown")
#> Error in fitstat(x, "ivwald")[[1]]$stat: $ operator is invalid for atomic vectors
```

Because it is set globally, I would either have to remove it from the environment and redefine it each time or make it more flexible with several case differentiations, right? These checks could include finding out whether the model object is an IV estimation and, if so, how many endogenous regressors it contains. I would like to be able to specify the additional statistics in each call to `modelsummary()` but I see that this would be hard to implement without loss of generality. My first attempt looks like this then:

``` r
glance_custom.fixest <- function(x) {
  if (length(fitstat(x, "ivwaldall")[[1]]) != 1L) {
    tibble("IV Wald" = fitstat(x, "ivwaldall")[[1]]$stat)
  }
}

# show all stages
summary(mod, stage = 1:2) %>% 
  modelsummary(output = "markdown")
```

|                | iv: First stage: x_endo_1 | iv: First stage: x_endo_2 | iv: Second stage |
|:---------------|:-------------------------:|:-------------------------:|:----------------:|
| x_inst_1       |           0.815           |           0.009           |                  |
|                |          (0.456)          |          (0.026)          |                  |
| x_inst_2       |           0.291           |           0.043           |                  |
|                |          (0.117)          |          (0.128)          |                  |
| x1             |           0.189           |           0.223           |      -0.594      |
|                |          (0.176)          |          (0.104)          |     (3.293)      |
| fit_x\_endo_1  |                           |                           |      0.379       |
|                |                           |                           |     (0.235)      |
| fit_x\_endo_2  |                           |                           |      5.185       |
|                |                           |                           |     (14.608)     |
| Num.Obs.       |            150            |            150            |       150        |
| R2             |           0.963           |           0.029           |      -9.097      |
| R2 Adj.        |           0.962           |          -0.005           |      -9.448      |
| R2 Within      |           0.373           |           0.024           |     -25.481      |
| R2 Within Adj. |           0.360           |           0.004           |     -26.032      |
| RMSE           |           0.34            |           0.52            |       2.62       |
| Std.Errors     |          by: fe           |          by: fe           |      by: fe      |
| FE: fe         |             X             |             X             |        X         |
| IV Wald        |          28.632           |           0.293           |      14.359      |

``` r
# only second stage
summary(mod) %>% 
  modelsummary(output = "markdown")
```

|                | Model 1  |
|:---------------|:--------:|
| fit_x\_endo_1  |  0.379   |
|                | (0.235)  |
| fit_x\_endo_2  |  5.185   |
|                | (14.608) |
| x1             |  -0.594  |
|                | (3.293)  |
| Num.Obs.       |   150    |
| R2             |  -9.097  |
| R2 Adj.        |  -9.448  |
| R2 Within      | -25.481  |
| R2 Within Adj. | -26.032  |
| RMSE           |   2.62   |
| Std.Errors     |  by: fe  |
| FE: fe         |    X     |
| IV Wald        |  14.359  |

``` r
# non-IV estimation
summary(mod2) %>% 
  modelsummary(output = "markdown")
```

|                | Model 1 |
|:---------------|:-------:|
| x1             |  0.804  |
|                | (0.071) |
| Num.Obs.       |   150   |
| R2             |  0.726  |
| R2 Adj.        |  0.720  |
| R2 Within      |  0.281  |
| R2 Within Adj. |  0.276  |
| RMSE           |  0.43   |
| Std.Errors     | by: fe  |
| FE: fe         |    X    |

<sup>Created on 2022-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       macOS Monterey 12.3.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Berlin
#>  date     2022-06-03
#>  pandoc   2.17.1.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version     date (UTC) lib source
#>  assertthat     0.2.1       2019-03-21 [1] CRAN (R 4.1.0)
#>  backports      1.4.1       2021-12-13 [1] CRAN (R 4.1.1)
#>  bayestestR     0.12.1      2022-05-02 [1] CRAN (R 4.1.1)
#>  broom          0.8.0       2022-04-13 [1] CRAN (R 4.1.1)
#>  cellranger     1.1.0       2016-07-27 [1] CRAN (R 4.1.0)
#>  checkmate      2.1.0       2022-04-21 [1] CRAN (R 4.1.1)
#>  cli            3.3.0       2022-04-25 [1] CRAN (R 4.1.1)
#>  codetools      0.2-18      2020-11-04 [1] CRAN (R 4.1.2)
#>  colorspace     2.0-3       2022-02-21 [1] CRAN (R 4.1.1)
#>  crayon         1.5.1       2022-03-26 [1] CRAN (R 4.1.1)
#>  datawizard     0.4.1.1     2022-05-21 [1] Github (easystats/datawizard@c9aad90)
#>  DBI            1.1.2       2021-12-20 [1] CRAN (R 4.1.1)
#>  dbplyr         2.1.1       2021-04-06 [1] CRAN (R 4.1.0)
#>  digest         0.6.29      2021-12-01 [1] CRAN (R 4.1.1)
#>  dplyr        * 1.0.9       2022-04-28 [1] CRAN (R 4.1.1)
#>  dreamerr       1.2.3       2020-12-05 [1] CRAN (R 4.1.0)
#>  effectsize     0.6.0.1     2022-01-26 [1] CRAN (R 4.1.1)
#>  ellipsis       0.3.2       2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate       0.15        2022-02-18 [1] CRAN (R 4.1.1)
#>  fansi          1.0.3       2022-03-24 [1] CRAN (R 4.1.1)
#>  fastmap        1.1.0       2021-01-25 [1] CRAN (R 4.1.0)
#>  fixest       * 0.10.5      2022-05-25 [1] https://fastverse.r-universe.dev (R 4.1.2)
#>  forcats      * 0.5.1       2021-01-27 [1] CRAN (R 4.1.0)
#>  Formula        1.2-4       2020-10-16 [1] CRAN (R 4.1.0)
#>  fs             1.5.2       2021-12-08 [1] CRAN (R 4.1.1)
#>  future         1.25.0      2022-04-24 [1] CRAN (R 4.1.1)
#>  future.apply   1.9.0       2022-04-25 [1] CRAN (R 4.1.1)
#>  generics       0.1.2       2022-01-31 [1] CRAN (R 4.1.1)
#>  ggplot2      * 3.3.6       2022-05-03 [1] CRAN (R 4.1.1)
#>  globals        0.15.0      2022-05-09 [1] CRAN (R 4.1.1)
#>  glue           1.6.2       2022-02-24 [1] CRAN (R 4.1.1)
#>  gtable         0.3.0       2019-03-25 [1] CRAN (R 4.1.0)
#>  haven          2.5.0       2022-04-15 [1] CRAN (R 4.1.1)
#>  highr          0.9         2021-04-16 [1] CRAN (R 4.1.0)
#>  hms            1.1.1       2021-09-26 [1] CRAN (R 4.1.1)
#>  htmltools      0.5.2       2021-08-25 [1] CRAN (R 4.1.1)
#>  httr           1.4.3       2022-05-04 [1] CRAN (R 4.1.1)
#>  insight        0.17.1      2022-05-13 [1] CRAN (R 4.1.1)
#>  jsonlite       1.8.0       2022-02-22 [1] CRAN (R 4.1.1)
#>  kableExtra     1.3.4       2021-02-20 [1] CRAN (R 4.1.0)
#>  knitr          1.39        2022-04-26 [1] CRAN (R 4.1.1)
#>  lattice        0.20-45     2021-09-22 [1] CRAN (R 4.1.2)
#>  lifecycle      1.0.1       2021-09-24 [1] CRAN (R 4.1.1)
#>  listenv        0.8.0       2019-12-05 [1] CRAN (R 4.1.0)
#>  lubridate      1.8.0       2021-10-07 [1] CRAN (R 4.1.1)
#>  magrittr       2.0.3       2022-03-30 [1] CRAN (R 4.1.1)
#>  modelr         0.1.8       2020-05-19 [1] CRAN (R 4.1.0)
#>  modelsummary * 0.10.0.9000 2022-05-25 [1] Github (vincentarelbundock/modelsummary@1a2f257)
#>  munsell        0.5.0       2018-06-12 [1] CRAN (R 4.1.0)
#>  nlme           3.1-157     2022-03-25 [1] CRAN (R 4.1.1)
#>  numDeriv       2016.8-1.1  2019-06-06 [1] CRAN (R 4.1.0)
#>  parallelly     1.31.1      2022-04-22 [1] CRAN (R 4.1.1)
#>  parameters     0.18.0      2022-05-24 [1] CRAN (R 4.1.1)
#>  performance    0.9.0.6     2022-05-25 [1] https://easystats.r-universe.dev (R 4.1.3)
#>  pillar         1.7.0       2022-02-01 [1] CRAN (R 4.1.1)
#>  pkgconfig      2.0.3       2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr        * 0.3.4       2020-04-17 [1] CRAN (R 4.1.0)
#>  R.cache        0.15.0      2021-04-30 [1] CRAN (R 4.1.0)
#>  R.methodsS3    1.8.1       2020-08-26 [1] CRAN (R 4.1.0)
#>  R.oo           1.24.0      2020-08-26 [1] CRAN (R 4.1.0)
#>  R.utils        2.11.0      2021-09-26 [1] CRAN (R 4.1.1)
#>  R6             2.5.1       2021-08-19 [1] CRAN (R 4.1.1)
#>  Rcpp           1.0.8.3     2022-03-17 [1] CRAN (R 4.1.1)
#>  readr        * 2.1.2       2022-01-30 [1] CRAN (R 4.1.1)
#>  readxl         1.4.0       2022-03-28 [1] CRAN (R 4.1.1)
#>  reprex         2.0.1       2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang          1.0.2       2022-03-04 [1] CRAN (R 4.1.1)
#>  rmarkdown      2.14        2022-04-25 [1] CRAN (R 4.1.1)
#>  rstudioapi     0.13        2020-11-12 [1] CRAN (R 4.1.0)
#>  rvest          1.0.2       2021-10-16 [1] CRAN (R 4.1.1)
#>  sandwich       3.0-1       2021-05-18 [1] CRAN (R 4.1.0)
#>  scales         1.2.0       2022-04-13 [1] CRAN (R 4.1.1)
#>  sessioninfo    1.2.2       2021-12-06 [1] CRAN (R 4.1.1)
#>  stringi        1.7.6       2021-11-29 [1] CRAN (R 4.1.1)
#>  stringr      * 1.4.0       2019-02-10 [1] CRAN (R 4.1.0)
#>  styler         1.7.0       2022-03-13 [1] CRAN (R 4.1.1)
#>  svglite        2.1.0       2022-02-03 [1] CRAN (R 4.1.1)
#>  systemfonts    1.0.4       2022-02-11 [1] CRAN (R 4.1.1)
#>  tables         0.9.6       2020-09-22 [1] CRAN (R 4.1.0)
#>  tibble       * 3.1.7       2022-05-03 [1] CRAN (R 4.1.1)
#>  tidyr        * 1.2.0       2022-02-01 [1] CRAN (R 4.1.1)
#>  tidyselect     1.1.2       2022-02-21 [1] CRAN (R 4.1.1)
#>  tidyverse    * 1.3.1       2021-04-15 [1] CRAN (R 4.1.0)
#>  tzdb           0.3.0       2022-03-28 [1] CRAN (R 4.1.1)
#>  utf8           1.2.2       2021-07-24 [1] CRAN (R 4.1.0)
#>  vctrs          0.4.1       2022-04-13 [1] CRAN (R 4.1.1)
#>  viridisLite    0.4.0       2021-04-13 [1] CRAN (R 4.1.0)
#>  webshot        0.5.3       2022-04-14 [1] CRAN (R 4.1.1)
#>  withr          2.5.0       2022-03-03 [1] CRAN (R 4.1.1)
#>  xfun           0.31        2022-05-10 [1] CRAN (R 4.1.1)
#>  xml2           1.3.3       2021-11-30 [1] CRAN (R 4.1.1)
#>  yaml           2.3.5       2022-02-21 [1] CRAN (R 4.1.1)
#>  zoo            1.8-10      2022-04-15 [1] CRAN (R 4.1.1)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by vincentarelbundock** [comment]
that sounds reasonable. Feel free to open a Pull Request.
