### ISSUE TITLE
Support bookdown-style table referencing for model summary tables

### ISSUE THREAD

**Issue by ashirwad** [vincentarelbundock/modelsummary#49]
Hello,  

It would be a nice addition to your package if you can support bookdown-style table referencing for model summary tables.  Bookdown version of the output formats (e.g., `pdf_document2()`, `word_document2()`, etc.) are now becoming the standard and are being preferred over their rmarkdown counterparts.  Please check out the last paragraph of this chapter: https://bookdown.org/yihui/bookdown/tables.html for a potential idea.

Thanks!

**Comment by vincentarelbundock** [comment]
Thanks.

This is really an issue that should be addressed upstream in the `gt` package. At this point, referencing is not supported at all by `gt`, but this feature is often requested and I expect it will be implemented eventually. See:

https://github.com/rstudio/gt/issues/115

Currently, `modelsummary` offers a temporary hack that works for PDF output via the `clean_latex` or `knit_latex` functions. When a more general system is included upstream, these functions will be deprecated.

In the meantime, I'll note that the bookdown referencing model uses the same LaTeX mechanics as the `clean_latex` funcation that I wrote. For example, if you have something like:

```r
msummary(models, title = 'Model summary') %>% 
    knit_latex(label = 'tab:example')
```

Some variation of this should work:

```md
In Table \@ref(tab:example).
```

(or remove the "tab:" or some variation.)

**Comment by ashirwad** [comment]
@vincentarelbundock, thanks for your response & apologies for my late response!

**Comment by vincentarelbundock** [comment]
This is now officially supported using the `kableExtra` package. This Rmarkdown document will produce PDF or HTML documents with proper table numbering and references:

````
---
header-includes: \usepackage{booktabs}
output: 
  bookdown::pdf_document2: default
  bookdown::html_document2: default
---

And see Table \@ref(tab:test)

```{r test, echo=FALSE}
options(modelsummary_html = 'kableExtra')
library(modelsummary)
library(kableExtra)
mod <- lm(hp ~ mpg, mtcars)
msummary(mod, title = 'This title describes the content of this table.') %>%
    kable_styling()
```
````

**Comment by paulcbauer** [comment]
@vincentarelbundock Is it possible that this does not work yet with datasummary_skim()?

**Comment by vincentarelbundock** [comment]
@paulcbauer In principle it should work. With version 0.8.1 this works for me:

````
---
output: 
  bookdown::pdf_document2: default
  bookdown::html_document2: default
---

And see Table \@ref(tab:test).


```{r test, echo=FALSE}
library(modelsummary)
datasummary_skim(mtcars, title = "blah blah")
```
````

**Comment by paulcbauer** [comment]
@vincentarelbundock Awesome we just created a new Pagedown working paper template where we use them now: https://osf.io/k8jhx Thank you for all the work!

**Comment by vincentarelbundock** [comment]
very cool!
