### ISSUE TITLE
Separate fixed from random effects in mixed models?

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#493]
When creating a mixed models table, random effects are currently directly following the fixed effects, w/o any "visual" separation, see following code:

```r
model <- lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
modelsummary::modelsummary(model, estimate  = "{estimate} [{conf.low}, {conf.high}]", statistic = NULL, fmt = 2)
parameters::model_parameters(model) |> print(select = "minimal")
```

Current HTML output:
![image](https://user-images.githubusercontent.com/26301769/172483429-6785f3cf-c566-4e0f-86fc-812cb2dcd42b.png)

Desired (roughly, not in text output, of course):

``` r
#> # Fixed Effects
#> 
#> Parameter    | Coefficient |       95% CI |      p
#> --------------------------------------------------
#> (Intercept)  |        2.00 | [0.89, 3.11] | < .001
#> Petal Length |        0.28 | [0.16, 0.40] | < .001
#> 
#> # Random Effects
#> 
#> Parameter               | Coefficient |       95% CI
#> ----------------------------------------------------
#> SD (Intercept: Species) |        0.89 | [0.33, 2.43]
#> SD (Residual)           |        0.32 | [0.28, 0.35]
```

**Comment by vincentarelbundock** [comment]
Would using the `kableExtra::group_rows()` function be good enough?

``` r
library(lme4)
library(modelsummary)
library(kableExtra)

model <- lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)

modelsummary(
    model,
    estimate  = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    fmt = 2) |>
    group_rows(indent = FALSE,
               index = c("Fixed Effects" = 2, "Random Effects" = 2, "Fit" = 2))
```

<img src="https://user-images.githubusercontent.com/987057/172513704-184a927d-cbec-4dd6-9c1c-a903b46ca4e7.png" width="300">



So far, my philosophy has been to return a “raw” table, and to leave most of the visual customization to users, who can use `kableExtra` and `gt` functions to their hearts’ content.

For example, I’m not sure I would personally use these groupings in my own publications, and it is much easier to add a `group_rows` call than to *remove* stuff from a table programmatically.

I’d be happy to consider counter-arguments, but here are a few implementation challenges I’m noting down here for future Vincent:

1.  Multiple models may have different numbers of fixed effects, so we need to count the model with the largest number. Also count estimate + statistic, considering the fact that there could be multiple statistics.
2.  Users may change the order of coefficients, including mixing fixed and random effects with the `coef_map` argument.
3.  Take into account coef omission with `coef_omit` and `coef_map`.
4.  `group_rows` works in `kableExtra` HTML and LaTeX, but not markdown
5.  Find equivalent code for `gt`, `flextable`, `huxtable`.

**Comment by strengejacke** [comment]
Ok, I think your philosophy makes sense - from a basic user perspective, it would be nice to have some "templates". I'm teaching R to novice / less experienced R users, and these people will definitely struggle with customizing the table, so a short one-liner is always helpful ;-) but - I think this issue can be regarded as resolved.

Regarding your 5 points, multiple models is a mess (see https://strengejacke.github.io/sjPlot/articles/tab_mixed.html#more-complex-models or https://strengejacke.github.io/sjPlot/articles/tab_bayes.html#mixing-multivariate-and-univariate-response-models for some complex use cases, but _sjPlot_ is less flexible, so I'm going to switch to _modelsummary_).

At least for fixed effects only, you may benefit from  [`compare_parameters()`](https://github.com/easystats/parameters/blob/main/R/compare_parameters.R). It's important to (temporarily) modify parameters names for different model components (count vs. zi, e.g.), so merging works.

The machinery to group table parts for multiple models (see https://easystats.github.io/parameters/articles/model_parameters_print.html#group-parameters-of-multiple-model-tables) is mostly done while printing in `insight::export_table()`, I think, but this is a mess as well...

**Comment by vincentarelbundock** [comment]
> I'm teaching R to novice / less experienced R users, and these people will definitely struggle with customizing the table, so a short one-liner is always helpful ;-)

Oh yeah, absolutely, this is tricky.

What do you mean by a "one-liner"? Should I add something to the "Appearance" vignette?

**Comment by vincentarelbundock** [comment]
> Regarding your 5 points, multiple models is a mess (see https://strengejacke.github.io/sjPlot/articles/tab_mixed.html#more-complex-models or https://strengejacke.github.io/sjPlot/articles/tab_bayes.html#mixing-multivariate-and-univariate-response-models for some complex use cases, but _sjPlot_ is less flexible, so I'm going to switch to _modelsummary_).

Looks cool, I'll read more carefully later.

I think I "fixed" the group merge order with a commit in the other Issue. Crossing fingers it works.
