### ISSUE TITLE
including p-values in customized output omits random effects from mixed models

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#494]
```r
model <- lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
modelsummary::modelsummary(model, estimate  = "{estimate} [{conf.low}, {conf.high}] {p.value}", statistic = NULL, fmt = 2)
```

Current output:
![image](https://user-images.githubusercontent.com/26301769/172483665-4586d17f-926b-4fdb-b17f-5b4bc95c807c.png)

It would be great to keep the random effects, and just set blank fields for p-values in the random effects rows.

**Comment by vincentarelbundock** [comment]
Thanks for reporting\! I don’t use mixed-effects models often, so these are very useful test cases.

Should be fixed in 0959b0296f5142b7b740b23253fc06c8f7c40fa1

Note that user-input in glue strings is totally arbitrary, so my current checks won’t catch every possibility, but it should be a considerable improvement.

``` r
library(lme4)
library(modelsummary)
model <- lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
modelsummary(model,
    "markdown",
    estimate  = "{estimate} [{conf.low}, {conf.high}] {p.value}",
    statistic = NULL)
```

|                        |           Model 1            |
| :--------------------- | :--------------------------: |
| (Intercept)            | 1.998 \[0.888, 3.109\] 0.001 |
| Petal.Length           | 0.282 \[0.165, 0.399\] 0.000 |
| SD (Intercept Species) |            0.892             |
| SD (Observations)      |            0.316             |
| Num.Obs.               |             150              |
| RMSE                   |             0.31             |

**Comment by strengejacke** [comment]
Nice, thanks!

**Comment by strengejacke** [comment]
I'm re-opening it, because it doesn't fully work when CIs are only partially available, see:

``` r
m1 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
m2 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1 + Petal.Length |Species), data = iris)
m3 <- lme4::lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 + Petal.Length |Species), data = iris)
#> boundary (singular) fit: see help('isSingular')
parameters::compare_models(m1, m2, m3, effects = "all")
#> Your model may suffer from singularity (see '?lme4::isSingular' and
#>   '?performance::check_singularity').
#>   Some of the standard errors and confidence intervals of the random
#>   effects parameters are probably not meaningful!
#> Parameter                    |                m1 |                     m2 |                    m3
#> -------------------------------------------------------------------------------------------------
#> (Intercept)                  | 2.00 (0.89, 3.11) | 1.99 ( 0.89,     3.10) | 1.76 (0.44,     3.08)
#> Petal Length                 | 0.28 (0.16, 0.40) | 0.29 ( 0.16,     0.41) | 0.16 (0.03,     0.29)
#> SD (Intercept)               | 0.89 (0.33, 2.43) | 0.88 ( 0.27,     2.87) | 1.10 (0.36,     3.30)
#> SD (Observations)            | 0.32 (0.28, 0.35) | 0.32 ( 0.28,     0.35) | 0.30 (0.26,     0.33)
#> SD (Petal.Length)            |                   | 0.02 ( 0.00, 1.76e+07) | 0.03 (0.00, 2.33e+05)
#> Cor (Intercept~Petal.Length) |                   | 0.19 (-1.00,     1.00) | 1.00 (    ,     1.00)
#> Petal Width                  |                   |                        | 0.61 (0.34,     0.88)
#> -------------------------------------------------------------------------------------------------
#> Observations                 |               150 |                    150 |                   150
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


In this case, the following code produces following table:

```r
modelsummary::modelsummary(model, estimate  = "{estimate} [{conf.low}, {conf.high}]", 
                           shape = group + term + statistic ~ model,
                           statistic = NULL, fmt = 2)
```

![image](https://user-images.githubusercontent.com/26301769/172547166-0c7d4a4e-0442-490f-a296-a859576f5c70.png)

Note the message from `compare_parameters()` (requires [this PR](https://github.com/easystats/parameters/pull/720) to work, I think).

**Comment by vincentarelbundock** [comment]
Is this working as you expected with the latest commits?

``` r
library(modelsummary)
models <- list(
    lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris),
    lme4::lmer(Sepal.Width ~ Petal.Length + (1 + Petal.Length |Species), data = iris),
    lme4::lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 + Petal.Length |Species), data = iris))
modelsummary(
    models,
    estimate = "{estimate} [{conf.low}, {conf.high}]",
    statistic = NULL,
    gof_map = NA,
    output = "markdown")
```

|                                       |        Model 1         |            Model 2            |           Model 3           |
| :------------------------------------ | :--------------------: | :---------------------------: | :-------------------------: |
| (Intercept)                           | 1.998 \[0.888, 3.109\] |    1.993 \[0.890, 3.096\]     |   1.762 \[0.439, 3.084\]    |
| Petal.Length                          | 0.282 \[0.165, 0.399\] |    0.286 \[0.164, 0.408\]     |   0.160 \[0.027, 0.292\]    |
| Petal.Width                           |                        |                               |   0.610 \[0.341, 0.878\]    |
| SD (Intercept Species)                | 0.892 \[0.328, 2.430\] |    0.885 \[0.273, 2.866\]     |   1.096 \[0.364, 3.300\]    |
| SD (Petal.Length Species)             |                        | 0.024 \[0.000, 17569330.944\] | 0.026 \[0.000, 232874.419\] |
| Cor (Intercept\~Petal.Length Species) |                        |    0.189 \[-1.000, 1.000\]    |      1.000 \[, 1.000\]      |
| SD (Observations)                     | 0.316 \[0.281, 0.354\] |    0.315 \[0.281, 0.354\]     |   0.296 \[0.264, 0.332\]    |

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Preparing a Ripley-induced emergency release, so closing all the issues which seem (to me) complete. Feel free to re-open or keep the discussion going if you see a need.
