### ISSUE TITLE
Improve print for mixed models with multiple grouping variables

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#495]
Currently, for mixes models with multiple grouping factors, `modelsummary()` yields a warning, and the printed HTML table could be improved:

> Warning message:
There are duplicate term names in the table. The `shape` argument of the `modelsummary` function can be used to print related terms together, and to label them appropriately. You can find the group identifier to use in the `shape` argument by calling `get_estimates()` on one of your models. Candidate group identifiers include: effect, group. See `?modelsummary` for details. 

```r
modelsummary(model, statistic = NULL)
```

![image](https://user-images.githubusercontent.com/26301769/172484559-2dc73821-5264-4b7d-8c2e-9ba645831b3d.png)

Using `shape`, as mentioned in the warning, doesn't improve much, because the group is shown, but one parameter name is missing:

```r
modelsummary(model, statistic = NULL, shape = group + term + statistic ~ model)
```

![image](https://user-images.githubusercontent.com/26301769/172484785-51cdc61e-5298-4b68-9d60-a99e2d795af4.png)

Would be nice to include the name of the grouping factor somewhere in the random effects, all necessary information is available:

``` r
library(lme4)
#> Loading required package: Matrix
data(sleepstudy)
set.seed(12345)
sleepstudy$grp <- sample(1:5, size = 180, replace = TRUE)
model <- lmer(
  Reaction ~ Days + (1 | grp ) + (1 | Subject),
  data = sleepstudy
)

parameters::model_parameters(model)
#> # Fixed Effects
#> 
#> Parameter   | Coefficient |   SE |           95% CI | t(175) |      p
#> ---------------------------------------------------------------------
#> (Intercept) |      251.52 | 9.80 | [232.19, 270.86] |  25.67 | < .001
#> Days        |       10.45 | 0.80 | [  8.86,  12.04] |  12.99 | < .001
#> 
#> # Random Effects
#> 
#> Parameter               | Coefficient |   SE |          95% CI
#> --------------------------------------------------------------
#> SD (Intercept: Subject) |       37.16 | 6.82 | [25.94,  53.24]
#> SD (Intercept: grp)     |        1.97 | 6.03 | [ 0.00, 795.84]
#> SD (Residual)           |       30.94 | 1.75 | [27.70,  34.56]
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

parameters::model_parameters(model) |> as.data.frame()
#>           Parameter Coefficient        SE   CI       CI_low   CI_high        t
#> 1       (Intercept)  251.524054 9.7967118 0.95 2.321891e+02 270.85897 25.67433
#> 2              Days   10.451388 0.8043805 0.95 8.863853e+00  12.03892 12.99309
#> 3    SD (Intercept)   37.162562 6.8178100 0.95 2.593851e+01  53.24347       NA
#> 4    SD (Intercept)    1.968885 6.0292451 0.95 4.870984e-03 795.83672       NA
#> 5 SD (Observations)   30.938572 1.7454922 0.95 2.769984e+01  34.55599       NA
#>   df_error            p Effects    Group
#> 1      175 3.063860e-61   fixed         
#> 2      175 1.855914e-27   fixed         
#> 3       NA           NA  random  Subject
#> 4       NA           NA  random      grp
#> 5       NA           NA  random Residual
```

<sup>Created on 2022-06-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by strengejacke** [comment]
Just saw, it "works" for this example:

```r
library(lme4)
data(sleepstudy)
set.seed(12345)
sleepstudy$grp <- sample(1:5, size = 180, replace = TRUE)
model <- lmer(
  Reaction ~ Days + (1 | grp ) + (1 + Days | Subject),
  data = sleepstudy
)
modelsummary(model, statistic = NULL, shape = group + term + statistic ~ model)
```

![image](https://user-images.githubusercontent.com/26301769/172485385-6c2f7493-ea04-4a42-ba5c-9d2e718d66f4.png)


So I'm not sure, the blank field for parameter names of "grp" in the previous example is just due to omit repeated parameter names?

**Comment by vincentarelbundock** [comment]
Good suggestion. Does 966c2e36f30e149b116f911e94a36924c0dbb28b close this issue? Perhaps there may be weird models this won’t handle?

``` r
library(lme4)
library(modelsummary)
data(sleepstudy)
set.seed(12345)
sleepstudy$grp <- sample(1:5, size = 180, replace = TRUE)

model <- lmer(
  Reaction ~ Days + (1 + Days | Subject),
  data = sleepstudy)
modelsummary(model, "markdown")
```

|                               | Model 1 |
| :---------------------------- | :-----: |
| (Intercept)                   | 251.405 |
|                               | (6.825) |
| Days                          | 10.467  |
|                               | (1.546) |
| SD (Intercept Subject)        | 24.741  |
| SD (Days Subject)             |  5.922  |
| Cor (Intercept\~Days Subject) |  0.066  |
| SD (Observations)             | 25.592  |
| Num.Obs.                      |   180   |
| RMSE                          |  23.44  |

``` r

model <- lmer(
  Reaction ~ Days + (1 | grp ) + (1 + Days | Subject),
  data = sleepstudy)
modelsummary(model, "markdown")
```

|                               | Model 1 |
| :---------------------------- | :-----: |
| (Intercept)                   | 251.405 |
|                               | (6.825) |
| Days                          | 10.467  |
|                               | (1.546) |
| SD (Intercept Subject)        | 24.741  |
| SD (Intercept grp)            |  0.000  |
| SD (Days Subject)             |  5.922  |
| Cor (Intercept\~Days Subject) |  0.066  |
| SD (Observations)             | 25.592  |
| Num.Obs.                      |   180   |
| RMSE                          |  23.44  |

**Comment by strengejacke** [comment]
Yes, looks good!

You _may_ think about removing the redundant group label when using `shape`:

```r
modelsummary(model, statistic = NULL, shape = group + term + statistic ~ model)
```

![image](https://user-images.githubusercontent.com/26301769/172546190-2705ac43-035b-4875-80fa-1600a98e8a78.png)

**Comment by vincentarelbundock** [comment]
With your two excellent issues, we now have auto-labeling and correct groupings of terms, so my guess is that very few users will actually have to use the `shape` argument for simple mixed models anymore. So duplicate labels will only be an issue for 0.0001% of users.

The code to remove duplicates in such a corner case would be pretty convoluted, so maybe we just let them rename coefficients as they want with `coef_rename` when they want total control.

**Comment by vincentarelbundock** [comment]
Preparing a Ripley-induced emergency release, so closing all the issues which seem (to me) complete. Feel free to re-open or keep the discussion going if you see a need.
