### ISSUE TITLE
How to separate fixed from random for multiple mixed models

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#496]
Related to #493 

Using following code, the order of fixed and random effects is messed up:

```r
m1 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
m2 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1 + Petal.Length |Species), data = iris)
m3 <- lme4::lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 + Petal.Length |Species), data = iris)
modelsummary::modelsummary(list(m1, m2, m3), estimate  = "{estimate} [{conf.low}, {conf.high}]", statistic = NULL, fmt = 2)
```

![image](https://user-images.githubusercontent.com/26301769/172545334-8658fa3c-b8f5-4ecb-8e43-dadc0a9378e8.png)

I know this is not trivial (and that's the reason why it doesn't work properly for `parameters::compare_models()` yet):

``` r
m1 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris)
m2 <- lme4::lmer(Sepal.Width ~ Petal.Length + (1 + Petal.Length |Species), data = iris)
m3 <- lme4::lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 + Petal.Length |Species), data = iris)
#> boundary (singular) fit: see help('isSingular')
parameters::compare_models(m1, m2, m3, effects = "all")
#> Your model may suffer from singularity (see '?lme4::isSingular' and
#>   '?performance::check_singularity').
#>   Some of the standard errors and confidence intervals of the random
#>   effects parameters are probably not meaningful!
#> Parameter                    |                m1 |                     m2 |                    m3
#> -------------------------------------------------------------------------------------------------
#> (Intercept)                  | 2.00 (0.89, 3.11) | 1.99 ( 0.89,     3.10) | 1.76 (0.44,     3.08)
#> Petal Length                 | 0.28 (0.16, 0.40) | 0.29 ( 0.16,     0.41) | 0.16 (0.03,     0.29)
#> SD (Intercept)               | 0.89 (0.33, 2.43) | 0.88 ( 0.27,     2.87) | 1.10 (0.36,     3.30)
#> SD (Observations)            | 0.32 (0.28, 0.35) | 0.32 ( 0.28,     0.35) | 0.30 (0.26,     0.33)
#> SD (Petal.Length)            |                   | 0.02 ( 0.00, 1.76e+07) | 0.03 (0.00, 2.33e+05)
#> Cor (Intercept~Petal.Length) |                   | 0.19 (-1.00,     1.00) | 1.00 (    ,     1.00)
#> Petal Width                  |                   |                        | 0.61 (0.34,     0.88)
#> -------------------------------------------------------------------------------------------------
#> Observations                 |               150 |                    150 |                   150
```

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But I think the "correct" order is required when you want to insert header rows to separate fixed from random effects, or is there a way to reorder rows?

**Comment by vincentarelbundock** [comment]
Here’s a slightly more difficult case with a `lm()` model in addition, using the commit I just pushed:

``` r
library(lme4)
library(modelsummary)
models <- list(
    lm(Sepal.Width ~ Petal.Length, data = iris),
    lmer(Sepal.Width ~ Petal.Length + (1|Species), data = iris),
    lmer(Sepal.Width ~ Petal.Length + (1 + Petal.Length |Species), data = iris),
    lmer(Sepal.Width ~ Petal.Length + Petal.Width + (1 + Petal.Length |Species), data = iris))

modelsummary(
    models,
    output = "markdown",
    statistic = NULL)
```

|                                       | Model 1 | Model 2 | Model 3 | Model 4 |
| :------------------------------------ | :-----: | :-----: | :-----: | :-----: |
| (Intercept)                           |  3.455  |  1.998  |  1.993  |  1.762  |
| Petal.Length                          | \-0.106 |  0.282  |  0.286  |  0.160  |
| Petal.Width                           |         |         |         |  0.610  |
| SD (Intercept Species)                |         |  0.892  |  0.885  |  1.096  |
| SD (Petal.Length Species)             |         |         |  0.024  |  0.026  |
| Cor (Intercept\~Petal.Length Species) |         |         |  0.189  |  1.000  |
| SD (Observations)                     |         |  0.316  |  0.315  |  0.296  |
| Num.Obs.                              |   150   |   150   |   150   |   150   |
| R2                                    |  0.184  |         |         |         |
| R2 Adj.                               |  0.178  |         |         |         |
| AIC                                   |  151.1  |         |         |         |
| BIC                                   |  160.2  |         |         |         |
| F                                     | 33.275  |         |         |         |
| RMSE                                  |  0.39   |  0.31   |  0.31   |  0.29   |

**Comment by vincentarelbundock** [comment]
Preparing a Ripley-induced emergency release, so closing all the issues which seem (to me) complete. Feel free to re-open or keep the discussion going if you see a need.
