### ISSUE TITLE
Separate columns for estimate, SE, CI, p...

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/modelsummary#498]
Not a bug, and maybe I have missed something, but is it possible to have estimates, SE, CI etc. in separate columns? This is often useful when copying the table to Word or similar writing tools, because often journals want a table formatted is that way.

Something like

``` r
library(parameters)
model <- lm(mpg ~ wt + cyl, data = mtcars)
model_parameters(model) |> print_md()
```

| Parameter   | Coefficient |  SE  |     95% CI     | t(29) |    p    |
|:------------|:-----------:|:----:|:--------------:|:-----:|:-------:|
| (Intercept) |    39.69    | 1.71 | (36.18, 43.19) | 23.14 | \< .001 |
| wt          |    -3.19    | 0.76 | (-4.74, -1.64) | -4.22 | \< .001 |
| cyl         |    -1.51    | 0.41 | (-2.36, -0.66) | -3.64 |  0.001  |

<sup>Created on 2022-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment]
Yes! I must say that I am quite proud of the new `shape` argument: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#shape

There is almost certainly going to be some problems with labeling with glue strings, but the basic infrastructure is there and should be very easy to improve over time.
