### ISSUE TITLE
tidy.MIresult function

### ISSUE THREAD

**Issue by lamhine** [vincentarelbundock/modelsummary#499]
Hello - I am doing design-based analyses of data that I have imputed using the `mi`, `mitools`, and `survey` packages. In struggling to extract elements from `MIresult` objects, I came across [this tantalizing documentation](https://www.rdocumentation.org/packages/modelsummary/versions/0.3.0/topics/tidy.MIresult) of a function called `tidy.MIresult` from the `modelsummary` package. However, upon installing the package (v. 0.11.1) it seems as if this function does not exist. I noticed on the rdocumentation page it says v. 0.3.0 - is `tidy.MIresult` planned for inclusion in a forthcoming release? Thanks!

**Comment by vincentarelbundock** [comment]
Thanks for using the package.

This function was removed a long time ago, after I made contributions to the `mice` package to include a `tidy.mipo` method there. FWIW, the original function was extremely simple, and it would be trivial for you to write. As soon as you load it in your environment, `modelsummary` should work. This is was we had originally:

```r
library(dplyr)
tidy.MIresult <- function(x, ...) {
    nil <- utils::capture.output(out <- summary(x, ...))
    out <- out %>% 
           tibble::rownames_to_column('term') %>%
           stats::setNames(c('term', 'estimate', 'std.error', 'conf.low', 'conf.high', 'missing.pct'))
    out
}
```

**Comment by lamhine** [comment]
Thank you!! This is so helpful. The `mice` package seems much more intuitive language-wise as I prefer `dplyr` syntax, but unfortunately it seems to not play super nicely with design effects - or that interaction seems not well documented.
