### ISSUE TITLE
How to put a comma (or a space) as a thousand separator? 

### ISSUE THREAD

**Issue by dragonattheend** [vincentarelbundock/modelsummary#503]
![image](https://user-images.githubusercontent.com/83570780/175108304-7cef16bc-fc10-4205-9eaa-51c30fed8d3f.png)

Is there an option that I'm missing?

**Comment by vincentarelbundock** [comment]
I updated the package vignette with this example. Feel free to re-open the issue or keep commenting if this does not meet your needs.

``` r
library(modelsummary)

mod <- lm(I(mpg * 100) ~ hp, mtcars)
f <- function(x) formatC(x, digits = 2, big.mark = ",", format = "f")
modelsummary(mod, "markdown", fmt = f)
```

|             | Model 1  |
| :---------- | :------: |
| (Intercept) | 3,009.89 |
|             | (163.39) |
| hp          |  \-6.82  |
|             |  (1.01)  |
| Num.Obs.    |    32    |
| R2          |  0.602   |
| R2 Adj.     |  0.589   |
| AIC         |  476.0   |
| BIC         |  480.4   |
| F           |  45.460  |
| RMSE        |  374.03  |
