### ISSUE TITLE
Parameters performance predicts wald vs profile ci_methods

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#515]
`parameters:::.ci_generic` uses `wald` as default

`parameters::ci.glm` uses `profile` as default

Varies from method to method for other models, with `NULL` as default.

**Comment by strengejacke** [comment]
It does so to mimic the default behaviour of R, so users won't get unexpected results. I think that all `ci()` methods should mimic the default `confint()` behaviour (if there's such a method).

**Comment by vincentarelbundock** [comment]
Thanks that's very useful. Will stick with defaults then
