### ISSUE TITLE
Use inherits() and never class() %in% ... + more

### ISSUE THREAD

**Issue by HenrikBengtsson** [vincentarelbundock/modelsummary#516]
I spotted:

https://github.com/vincentarelbundock/modelsummary/blob/23b905699a15ce4e33d3d384c4c34f98ea4326d7/R/modelsummary.R#L562

Following best practices in R, you always want to use `inherits()` when testing for classes, i.e.

```r
parallel_flag <- !inherits(future::plan(), "sequential") && number_of_models > 1 
```

Now, there might be-other future strategies/plans than 'sequential' that use a single worker.  Because of this, you don't want to use `plan()` to infer the number of workers.  It's better to use:

```r
parallel_flag <- future::nbrOfWorkers() > 1 && number_of_models > 1 
```

**Comment by vincentarelbundock** [comment]
Thanks a lot! I'm new to future and didn't know the `nbOfWorkers` function, so this is extremely helpful. Will make the change as soon as possible.

Thanks for taking the time.

**Comment by vincentarelbundock** [comment]
091d7c1 thanks again!
