### ISSUE TITLE
converting tibble to data.frame produces staggered histogram

### ISSUE THREAD

**Issue by aja2182** [vincentarelbundock/modelsummary#526]
Hi there, 

I'm really sorry if this was answered elsewhere, I couldn't find the discussion. I was wondering if anyone ran into trouble after turning a tibble into a data.frame and then running datasummary(). My histograms are coming out staggered.  I can attach an image. I tried to reproduce this with cars dataset and I couldn't which leads me to believe there's probably an issue on my end? 

The reason I am using datasummary this is because I would like to modify my table to exclude unique numbers and missing percentage, which is default when using datasummary_skim(). 

My nonreproducible code: 
```
test_df <- data.frame(test)
datasummary(All(test_df) ~ Mean + SD + Min + Max + Histogram,
            data = test_df,
            output = "default")

```
<img width="166" alt="Screen Shot 2022-07-25 at 4 13 35 PM" src="https://user-images.githubusercontent.com/70495748/180866314-43d5f2cc-d7e7-415c-8f92-4353d08ad737.png">

**Comment by vincentarelbundock** [comment]
Yes, see here: https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#histograms

**Comment by aja2182** [comment]
Amazing thank you - it worked!
