### ISSUE TITLE
Weights in datasummary

### ISSUE THREAD

**Issue by stuartjames1990** [vincentarelbundock/modelsummary#527]
Is it possible to include survey weights when creating the datasummary tables?

**Comment by vincentarelbundock** [comment]
Have you read the documentation? For example:

https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#arguments-weighted-mean
https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#weighted-percentages
https://vincentarelbundock.github.io/modelsummary/articles/datasummary.html#datasummary_balance

**Comment by vincentarelbundock** [comment]
If your question is not covered there, please let me know exactly what you need and what you tried.

**Comment by vincentarelbundock** [comment]
Closing now because no response. But feel free to keep the conversation going if my answer above is insufficient
