### ISSUE TITLE
R^2 value does not match lm_robust when weights are included

### ISSUE THREAD

**Issue by MichaelKistner** [vincentarelbundock/modelsummary#530]
Hi. I'm using modelsummary to create regression tables for an analysis, and ran into a bug. When reporting the R squared value for a model estimated using the lm_robust() command from the estimatr package, modelsummary returned a negative value. The issue appears to be caused by weights. When weights are included, the reported R squared differs. Here's some code for a MWE:

```
library(modelsummary)
library(estimatr)

toy_df <- data.frame(y = c(1, 2, 3),
                     x = c(1, 2, 4),
                     weights = c(0.2, 0.2, 0.6))
```

If we estimate a linear regression with weights specified, the R2 differs for the two:

```
model_weights <- lm_robust(x ~ y,
                           weights = weights,
                           data = toy_df)

summary(model_weights)

modelsummary(model_weights)
```

Whereas if the regression is estimated without weights, the R2 is the same:

```
model_noweights <- lm_robust(x ~ y,
                             data = toy_df)
 
summary(model_noweights)

modelsummary(model_noweights)
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report and MWE! I think this is now fixed in the upstream package `performance`. Could you try installing the dev version, **restarting R completely**, and trying again?

```r
library(remotes)
install_github("easystats/performance")
```

**Comment by MichaelKistner** [comment]
That fixed the issue! Thanks for the quick response.
