### ISSUE TITLE
Better number formatting to avoid `0.000***`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#544]
Better rounding:

> Hi. In my anecdotal experience if a coefficient is -0.00007*** but my default settings are to display out to three digits, stargazer will know to make an exception for the -0.00007*** but modelsummary will actually display 0.000*** (including dropping the negative sign).

Source: https://twitter.com/jacobgellman/status/1561065469250920448

**Comment by jacobgellman** [comment]
Thank you for your responsiveness Vincent!

**Comment by vincentarelbundock** [comment]
"Responsiveness" should only be judged *after* the feature is implemented ;-)

Will let you know when I have a chance to look at this.

**Comment by vincentarelbundock** [comment]
Using the very latest version of `modelsummary` from Github, you can pass any arbitrary function to the `fmt` argument to round in exactly the way you want. For example, to keep 3 digits, including at least two after the decimal:

``` r
library(modelsummary)
mod <- lm(mpg ~ I(hp * 1000) + drat, data = mtcars)

f <- function(x) format(x, digits = 3, nsmall = 2, scientific = FALSE)
modelsummary(mod, fmt = f, output = "markdown", gof_map = NA)
```

|               |   Model 1    |
| :------------ | :----------: |
| (Intercept)   |    10.79     |
|               |    (5.08)    |
| I(hp \* 1000) | \-0.0000518  |
|               | (0.00000929) |
| drat          |     4.70     |
|               |    (1.19)    |

Same thing, but with scientific notation:

``` r
f <- function(x) format(x, digits = 3, nsmall = 2)
modelsummary(mod, fmt = f, output = "markdown", gof_map = NA)
```

|               |  Model 1   |
| :------------ | :--------: |
| (Intercept)   |   10.79    |
|               |   (5.08)   |
| I(hp \* 1000) | \-5.18e-05 |
|               | (9.29e-06) |
| drat          |    4.70    |
|               |   (1.19)   |

For reference, the default formatter is this:

``` r
f <- function(x) format(round(x, 3), nsmall = 3)
modelsummary(mod, fmt = f, output = "markdown", gof_map = NA)
```

|               | Model 1 |
| :------------ | :-----: |
| (Intercept)   | 10.790  |
|               | (5.078) |
| I(hp \* 1000) |  0.000  |
|               | (0.000) |
| drat          |  4.698  |
|               | (1.192) |

Questions for @jacobgellman : Is there a good argument for changing the default formatter? What is the best alternative?

**Comment by jacobgellman** [comment]
Hi @vincentarelbundock. I see from your example that there is more optionality already available in the current version. I had not thought to experiment with that, though. I see in the latest version of the package manual (14 July 2022) that there is not an example of that, though. What if you added an example of those lines of code in the manual, perhaps on (current) page 47 below the gof_map examples? Thanks once again for your response.

**Comment by vincentarelbundock** [comment]
I added information and examples to the documentation and vignette.

I have also merged a commit that should improve default formatting of numbers, displaying at least one significant digit, use scientific notation to avoid super long numbers, and also convert p values to <0.001 when necessary.

Of course, the `fmt` functions still work as shown above.

Thanks for the nudge, and let me know if you run into issues with the new version.

**Comment by pyacobellis** [comment]
Hi Vincent, love this package, thank you.   Is it possible to have similar functionality for modelplot?  For very small decimal values, points on coefficient plots are fixed at zero, with no confident interval.  Would be great if we could have the actual value with confidence bands. Thanks.

**Comment by vincentarelbundock** [comment]
What do you mean, exactly by "similar functionality"? What does the plot you want look like, specifically?

**Comment by pyacobellis** [comment]
![image](https://user-images.githubusercontent.com/58760482/222600856-54a4d2e3-f77a-456a-8f82-b4ad63bacad0.png)

Basically these values are fixed at zero with no confidence band.  Would be good to have an option/parameter to include confidence bands, regardless of value size.

**Comment by vincentarelbundock** [comment]
These confidence bands are *not* actually fixed at zero. They are just tiny and are almost entirely hidden by the dots. If you save a very hi resolution picture and you zoom in very close, you'll see small bars.

One option for you would be to reduce the size of the dots (see the vignette on plot customization.). But I can't increase the size of the bands, because that would be inaccurate.

**Comment by pyacobellis** [comment]
Aahh, makes complete sense.  Thank you for clarifying, and again, thank you for this awesome package.  Love it!

**Comment by vincentarelbundock** [comment]
great!
