### ISSUE TITLE
Incorrect p-values for coxph models

### ISSUE THREAD

**Issue by simontrlifaj** [vincentarelbundock/modelsummary#547]
Hi, thanks a lot for this superb package! I ran into the following issue: a summary of the Cox Proportional-Hazards Model (from the survival package) produces incorrect  p-values and stars.

Here is a reproducible example:
```
library(modelsummary)
library(survival)

# Sample data
test2 <- list(start=c(1, 2, 5, 2, 1, 7, 3, 4, 8, 8),
              stop =c(2, 3, 6, 7, 8, 9, 9, 9,14,17),
              event=c(1, 1, 1, 1, 1, 1, 1, 0, 0, 0),
              x    =c(1, 0, 0, 1, 0, 1, 1, 1, 0, 0) )

# Model
bladder1 <- bladder[bladder$enum < 5, ] 
survival3 = coxph(Surv(stop, event) ~ (rx + size + number) * strata(enum),
      cluster = id, bladder1, robust = TRUE)

# This shows correct p-values
summary(survival3)

# This shows incorrect p-values
modelsummary(survival3, estimate = "{estimate} ({p.value}) {stars}")
```

For example, the p-value for `number` should be 0.00141 (two stars), but modelsummary shows 0.941 (insignificant). The `get_estimates` function, too, returns the same incorrect p-values. The standard errors seem to be correct.

Is there anything I am doing incorrectly here, or is there a workaround?

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report @simontrlifaj . This seems to be an upstream problem in the `insight` package. Would you mind installing the development version of that package and trying again?

```{r}
library(remotes)
install_github("easystats/insight")
```

Restart R completely.

Try again.

**Comment by simontrlifaj** [comment]
Perfect, now it's resolved (together with some missing goodness-of-fit statistics). Thanks for the prompt reply!

**Comment by vincentarelbundock** [comment]
Great news!
