### ISSUE TITLE
About labelled variables

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/modelsummary#549]
Hello Vincent, I just saw all the PRs you have made to use variable labels automatically, thanks for this feature!

Just a few comments so far:

1. I think there should be a message/warning when 2 variables from 2 different datasets share the same label, like below. I don't have a real-life example for this but I think informing the user about this would be useful (without stopping the code since having the same label could be intentional):
``` r
 library(modelsummary)
 
 dat1 <- mtcars
 dat1$mpg <- haven::labelled(dat1$mpg, label = "Miles per gallon")
 
 dat2 <- mtcars
 dat2$mpg2 <- haven::labelled(dat2$mpg, label = "Miles per gallon")

 # mpg and mpg2 have the same label
 should_warn_across <- list(
   lm(hp ~ mpg + drat, dat = dat1),
   lm(hp ~ mpg2 + wt, dat = dat2)
 )

 modelsummary(should_warn_across, output = "markdown")
```

|                  | Model 1  |  Model 2  |
|:-----------------|:--------:|:---------:|
| (Intercept)      | 278.515  |  349.287  |
|                  | (55.415) | (103.509) |
| Miles per gallon |  -9.985  |  -9.417   |
|                  | (1.792)  |  (2.676)  |
| drat             |  19.126  |           |
|                  | (20.198) |           |
| wt               |          |  -4.168   |
|                  |          | (16.485)  |
| Num.Obs.         |    32    |    32     |
| R2               |  0.614   |   0.603   |
| R2 Adj.          |  0.588   |   0.576   |
| AIC              |  337.9   |   338.8   |
| BIC              |  343.7   |   344.6   |
| Log.Lik.         | -164.940 | -165.392  |
| F                |  23.100  |  22.053   |
| RMSE             |  41.91   |   42.50   |

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2. `modelsummary()` doesn't use labels for factors:
``` r
library(modelsummary)

mtcars$cyl <- haven::labelled(mtcars$cyl, label = "Number of cylinders")
mtcars$hp <- haven::labelled(mtcars$hp, label = "Horsepower")

mod <- lm(mpg ~ hp + factor(cyl), data = mtcars)

modelsummary(
  mod,
  output = "markdown"
)
```

|              | Model 1 |
|:-------------|:-------:|
| (Intercept)  | 28.650  |
|              | (1.588) |
| Horsepower   | -0.024  |
|              | (0.015) |
| factor(cyl)6 | -5.968  |
|              | (1.639) |
| factor(cyl)8 | -8.521  |
|              | (2.326) |
| Num.Obs.     |   32    |
| R2           |  0.754  |
| R2 Adj.      |  0.727  |
| AIC          |  169.9  |
| BIC          |  177.2  |
| Log.Lik.     | -79.948 |
| F            | 28.585  |
| RMSE         |  2.94   |

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

3. The `if` condition here does the same thing as the line above:
https://github.com/vincentarelbundock/modelsummary/blob/50a747b3f3309de17da5ad3cbeb47a1ac8941ea4/R/utils_labels.R#L21-L27

4. This feature should be explained somewhere in the docs

**Comment by vincentarelbundock** [comment]
Thanks a lot!

I removed the duplicate code and added something to the appearance vignette, which will be updated the next time I build the website.

Frankly, I'm not convinced that there needs to be a warning there. If the same label is assigned, it seems safe to assume that users want to merge the rows, and the behavior should be pretty easy to spot and understand in cases where this is not desired. (It's quite self-explanatory.) And in general we probably want to minimize warnings.

The factor issue is a bit more challenging as there may be some upstream changes needed in `insight`, which seems to discard factor labels for some reason. I'll be trying to write a replicable example to file an issue on that package's repo.

**Comment by vincentarelbundock** [comment]
I believe that calling `factor()` in a model formula strips the variable of its attributes and that, as a result, the data stored in the model object no longer includes the required information to print the label.

I added new code to display character variables properly, so I would recommend converting your variable to character before fitting the model.

I also opened an issue here: https://github.com/easystats/insight/issues/620

**Comment by etiennebacher** [comment]
Here's a (not very clean) way to extract the label from the factor variables:
``` r
library(modelsummary)

mtcars$cyl <- haven::labelled(mtcars$cyl, label = "Number of cylinders")
mtcars$hp <- haven::labelled(mtcars$hp, label = "Horsepower")
mtcars$am <- haven::labelled(mtcars$am, label = "Transmission")

mod <- lm(mpg ~ hp + factor(cyl) + factor(am), data = mtcars)

fac <- insight::find_terms(mod)$conditional
fac <- fac[startsWith(fac, "factor(")]
fac <- gsub("^factor\\(", "", fac)
fac <- gsub("\\)$", "", fac)

x <- expand.model.frame(mod, fac)[, fac]

modelsummary:::get_variable_labels_data(x)
#>                   cyl                    am 
#> "Number of cylinders"        "Transmission"
```
<sup>Created on 2022-08-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


`expand.model.frame()` probably doesn't work on all models but better than nothing

**Comment by strengejacke** [comment]
I added a function, which - based on the `pretty_names` argument from `model_parameters()` - tries to extract labels, if there are any:

https://github.com/easystats/parameters/blob/1de1a2575dce124a826f711f66e850649aa250e2/R/format_parameters.R#L338

``` r
library(parameters)
data(efc, package = "datawizard")

# simple model
m <- lm(neg_c_7 ~ e42dep + c172code, data = efc)
mp <- model_parameters(m)

print(mp)
#> Parameter   | Coefficient |   SE |         95% CI | t(80) |     p
#> -----------------------------------------------------------------
#> (Intercept) |        8.72 | 3.56 | [ 1.63, 15.80] |  2.45 | 0.017
#> e42dep [2]  |       -1.00 | 3.72 | [-8.41,  6.41] | -0.27 | 0.789
#> e42dep [3]  |        2.68 | 3.16 | [-3.60,  8.96] |  0.85 | 0.398
#> e42dep [4]  |        3.88 | 3.10 | [-2.29, 10.04] |  1.25 | 0.214
#> c172code    |        1.14 | 0.93 | [-0.70,  2.99] |  1.23 | 0.221
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

print(mp, pretty_names = "labels")
#> Parameter                                 | Coefficient |   SE |         95% CI | t(80) |     p
#> -----------------------------------------------------------------------------------------------
#> (Intercept)                               |        8.72 | 3.56 | [ 1.63, 15.80] |  2.45 | 0.017
#> elder's dependency [slightly dependent]   |       -1.00 | 3.72 | [-8.41,  6.41] | -0.27 | 0.789
#> elder's dependency [moderately dependent] |        2.68 | 3.16 | [-3.60,  8.96] |  0.85 | 0.398
#> elder's dependency [severely dependent]   |        3.88 | 3.10 | [-2.29, 10.04] |  1.25 | 0.214
#> carer's level of education                |        1.14 | 0.93 | [-0.70,  2.99] |  1.23 | 0.221
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

# with interactions
m <- lm(neg_c_7 ~ e42dep * c12hour, data = efc)
mp <- model_parameters(m)

print(mp)
#> Parameter            | Coefficient |   SE |          95% CI |    t(86) |      p
#> -------------------------------------------------------------------------------
#> (Intercept)          |       11.00 | 7.09 | [ -3.09, 25.09] |     1.55 | 0.124 
#> e42dep [2]           |        1.29 | 7.92 | [-14.45, 17.03] |     0.16 | 0.871 
#> e42dep [3]           |        2.12 | 7.18 | [-12.16, 16.39] |     0.29 | 0.769 
#> e42dep [4]           |        2.06 | 7.17 | [-12.18, 16.31] |     0.29 | 0.774 
#> c12hour              |    3.49e-14 | 0.38 | [ -0.75,  0.75] | 9.25e-14 | > .999
#> e42dep [2] * c12hour |       -0.07 | 0.39 | [ -0.83,  0.70] |    -0.17 | 0.863 
#> e42dep [3] * c12hour |        0.01 | 0.38 | [ -0.74,  0.76] |     0.03 | 0.976 
#> e42dep [4] * c12hour |        0.01 | 0.38 | [ -0.74,  0.76] |     0.04 | 0.969
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.

print(mp, pretty_names = "labels")
#> Parameter                                                                            | Coefficient |   SE |          95% CI |    t(86) |      p
#> -----------------------------------------------------------------------------------------------------------------------------------------------
#> (Intercept)                                                                          |       11.00 | 7.09 | [ -3.09, 25.09] |     1.55 | 0.124 
#> elder's dependency [slightly dependent]                                              |        1.29 | 7.92 | [-14.45, 17.03] |     0.16 | 0.871 
#> elder's dependency [moderately dependent]                                            |        2.12 | 7.18 | [-12.16, 16.39] |     0.29 | 0.769 
#> elder's dependency [severely dependent]                                              |        2.06 | 7.17 | [-12.18, 16.31] |     0.29 | 0.774 
#> average number of hours of care per week                                             |    3.49e-14 | 0.38 | [ -0.75,  0.75] | 9.25e-14 | > .999
#> elder's dependency [slightly dependent] * average number of hours of care per week   |       -0.07 | 0.39 | [ -0.83,  0.70] |    -0.17 | 0.863 
#> elder's dependency [moderately dependent] * average number of hours of care per week |        0.01 | 0.38 | [ -0.74,  0.76] |     0.03 | 0.976 
#> elder's dependency [severely dependent] * average number of hours of care per week   |        0.01 | 0.38 | [ -0.74,  0.76] |     0.04 | 0.969
#> 
#> Uncertainty intervals (equal-tailed) and p-values (two-tailed) computed
#>   using a Wald t-distribution approximation.
```

<sup>Created on 2022-09-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
@strengejacke this is super cool! Will it be part of the next `parameters` release? (soon I imagine?)

**Comment by strengejacke** [comment]
Yes, will be part of the next release. We've run revdep checks, and providing the opportunity for other package maintainers to deal with breaking changes in _parameters_, we expect the update to be submitted around 7-10th October (see https://github.com/easystats/parameters/pull/777).

**Comment by vincentarelbundock** [comment]
Great! Just to be sure I understand: there will always be two attributes `pretty_names` and `pretty_labels`, they will always be of the same length as the number of rows in the output, and they will be identical if there are no labels.

So basically, I can just use `attr(x, "pretty_labels")` and be "safe". Correct?

**Comment by strengejacke** [comment]
Yes, `"pretty_labels"` is, first, a copy of `"pretty_names"`, and then, if there are value labels, names are overwritten by labels. If no labels, `"pretty_names"` and `"pretty_labels"` are identical. I decided to go for two attributes for now, since this feature is still somewhat experimental and may not work as expected for `as.factor(x)` or `poly(x)`.

The relevant code is here:

https://github.com/easystats/parameters/blob/18be51a69b9fafca035659755e8e0d382d4e2291/R/format_parameters.R#L350-L415

**Comment by vincentarelbundock** [comment]
Note to self: we can complete the transition to `parameters` support for labels when this issue is fixed: https://github.com/easystats/parameters/issues/785

**Comment by vincentarelbundock** [comment]
I opened a PR, so things should naturally fix themselves.

**Comment by vincentarelbundock** [comment]
To get auto labels, we need this argument in `modelsummary(mod, coef_rename = TRUE)`

**Comment by vincentarelbundock** [comment]
@etiennebacher,

We now have support for this thanks to upstream changes in `parameters`. The `factor()` issue remains, but it is quite easy to work around. Note that you need to set `coef_rename=TRUE` and that you need the dev versions of `modelsummary` and Pull Request 785 of  `parameters`.

I included this code in the “Examples” section of the documentation:

``` r
library(modelsummary)
datlab <- mtcars
datlab$cyl <- factor(datlab$cyl)
attr(datlab$hp, "label") <- "Horsepower"
attr(datlab$cyl, "label") <- "Cylinders"
modlab <- lm(mpg ~ hp * drat + cyl, data = datlab)
modelsummary(modlab, output = "markdown", coef_rename = TRUE)
```

|                   | Model 1  |
| :---------------- | :------: |
| (Intercept)       |  14.850  |
|                   | (11.923) |
| Horsepower        | \-0.011  |
|                   | (0.082)  |
| drat              |  3.612   |
|                   | (3.019)  |
| Cylinders \[6\]   | \-4.091  |
|                   | (1.881)  |
| Cylinders \[8\]   | \-5.019  |
|                   | (3.056)  |
| Horsepower × drat | \-0.006  |
|                   | (0.021)  |
| Num.Obs.          |    32    |
| R2                |  0.784   |
| R2 Adj.           |  0.742   |
| AIC               |  169.7   |
| BIC               |  180.0   |
| Log.Lik.          | \-77.860 |
| F                 |  18.871  |
| RMSE              |   2.76   |

**Comment by etiennebacher** [comment]
That's great, @vincentarelbundock! Thanks a lot
