### ISSUE TITLE
Standard errors for stanreg objects

### ISSUE THREAD

**Issue by RohanAlexander** [vincentarelbundock/modelsummary#555]
Hi Vincent,

I can follow your (incredible) instructions [here](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#adding-new-information-to-existing-models) to add standard errors to `stanreg` objects with:

`tidy_custom.stanreg <- function(x, ...) {
  out <- data.frame(
    term = tidy(x)$term,
    std.error = tidy(x)$std.error
    )
  out
}`

This works, but I was wondering if you would consider a pull request that added this by default?

Rohan

**Comment by vincentarelbundock** [comment]
Thanks for the issue\!

A couple notes:

1.  RStudio has announced that the `broom` package would no longer be developed (only maintained), so I have switched to `parameters` as the default package to extract info from model objects.
2.  `modelsummary` can pass a bunch of extra arguments to `parameters` to get extra info. See here: <https://easystats.github.io/parameters/reference/model_parameters.stanreg.html>
    - `dispersion = TRUE`
    - `centrality = "mean"`

Perhaps we should set `dispersion = TRUE` by default so it is more easily accessible…

For instance, you can extract an estimate of dispersion by setting `dispersion=TRUE`. Then, the `centrality` argument can be used to determine if we get Mean+SD or Median+MAD:

``` r
library(rstanarm)
library(modelsummary)

mod <- stan_glm(am ~ mpg + drat, data = mtcars, family = binomial)

get_estimates(mod, dispersion = TRUE)
#>          term    estimate       mad conf.level     conf.low   conf.high
#> 1 (Intercept) -20.2887522 6.6715055       0.95 -37.72546249 -10.0070923
#> 2         mpg   0.1583419 0.1315808       0.95  -0.06423978   0.4500406
#> 3        drat   4.5244335 1.7947657       0.95   1.59050410   8.8902913
#>   prior.distribution prior.location prior.scale group
#> 1             normal              0   2.5000000      
#> 2             normal              0   0.4148036      
#> 3             normal              0   4.6757049

get_estimates(mod, centrality = "mean", dispersion = TRUE)
#>          term    estimate   std.dev conf.level     conf.low   conf.high
#> 1 (Intercept) -21.2443586 7.1096095       0.95 -37.72546249 -10.0070923
#> 2         mpg   0.1665776 0.1310319       0.95  -0.06423978   0.4500406
#> 3        drat   4.7263150 1.8755161       0.95   1.59050410   8.8902913
#>   prior.distribution prior.location prior.scale group
#> 1             normal              0   2.5000000      
#> 2             normal              0   0.4148036      
#> 3             normal              0   4.6757049

modelsummary(
    mod,
    statistic = "std.dev",
    centrality = "mean",
    dispersion = TRUE)
```

|             | Model 1  |
| :---------- | :------: |
| (Intercept) | \-21.244 |
|             | (7.110)  |
| mpg         |  0.167   |
|             | (0.131)  |
| drat        |  4.726   |
|             | (1.876)  |
| Num.Obs.    |    32    |
| R2          |  0.590   |
| Log.Lik.    | \-10.358 |
| ELPD        |  \-13.0  |
| ELPD s.e.   |   3.4    |
| LOOIC       |   26.0   |
| LOOIC s.e.  |   6.7    |
| WAIC        |   25.9   |
| RMSE        |   0.33   |

**Comment by RohanAlexander** [comment]
Dear Vincent,

Firstly, thank you very much for such a thorough response quickly.

I didn't know that about `broom`, but it's very useful to know and I appreciate you letting me know. 

I also didn't know about the `centrality` and `dispersion` options - these are exactly what I was looking for.

Thank you again for this.

Rohan
