### ISSUE TITLE
Separate panels

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#557]
How to replicate something like this (Moscona & Seck)?

![complex](https://user-images.githubusercontent.com/987057/192305108-d0e32feb-a05b-4e68-b91b-35d3d0e75aec.jpg)

**Comment by adrianadermon** [comment]
Did you figure this out? I'm looking for a solution to the same problem.

**Comment by vincentarelbundock** [comment]
Yes, it is pretty easy to achieve a similar effect:

1. Create a first table with the `output="data frame"`
2. Create a second table with the output format you want, and use the `add_rows` argument to append the first table.
3. Use functions from thé `kableExtra` package to add identifiers for groups of rows. See the documentation of that package for functions like `pack_rows`.

If you get a good result, feel free to report back with an example using the `mtcars` dataset. I'd love to add this kind of example to the vignette.

Good luck!
