### ISSUE TITLE
Many bugs in `coef_omit` with `shape`

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#558]
https://stackoverflow.com/questions/73873402/reporting-mgcvgam-summary-with-modelsummary

Bugs:

* `coef_omit` does not work with `shape`
* p values are not displayed properly in HTML with `shape`. This is probably because `<` should be escaped or it gets interpreted as the start of an HTML tag. I already have a fix for this, but it is in the "label" branch and should be merged soon.

Relevant code:

```r
library(mgcv)
library(modelsummary)

dat <- gamSim(1, n = 4000, dist = "normal", scale = 2)
mod <- gam(y ~ s(x0) + s(x1) + s(x2), data = dat)

get_estimates(mod)

tidy_custom.gam <- function(x, ...) {
    out <- parameters::parameters(x)
    out <- parameters::standardize_names(out, style = "broom")
    out$combined <- ifelse(is.na(out$estimate), out$df, out$estimate)
    out$p <- format.pval(out$p.value)
    return(out)
}

modelsummary(
    mod,
    estimate = "combined",
    coef_omit = "^s\\(",
    statistic = c(
        "std.error",
        "statistic",
        "p.value"),
    shape = term ~ model + statistic,
    gof_map = NA)
```

**Comment by mps9506** [comment]
Thanks for opening an issue on this. After the SO post, I noticed that removing the `gof_map=NA` argument avoids the error. That doesn't directly help get to the solution (where I don't need/want the gof metrics on this table), but it seems to be interacting with `coef_omit` and `shape` in some way. I'm pretty ignorant on the inner workings of the package though.

**Comment by vincentarelbundock** [comment]
Thanks again for the report @mps9506 I believe this should be fixed in the Github development version. Let me know if you try it and it doesn't work as expected. (make sure you restart R after `remotes::install_github("vincentarelbundock/modelsummary")`

**Comment by vincentarelbundock** [comment]
Will close now, but feel free to keep commenting or to reopen an issue of the problem persists with the dev version.
