### ISSUE TITLE
Error when gof_matrix has no omit = FALSE

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#56]
modelsummary:::extract_gof throws a very unclear error when all gof are set to be ommitted. A clear error message might be better, or ideally, it should just return the summary without gof information?

**Comment by LukasWallrich** [comment]
Your current version depends on dplyr v. >1, which is higher than the current GitHub version - so I am not sure how to install it? Or is there a dplyr version more recent than the "tidyverse/dplyr" one?

**Comment by vincentarelbundock** [comment]
ooops, sorry! I adjusted the dplyr version.

**Comment by LukasWallrich** [comment]
Thanks. I now get a different error.
```
fit1 <- lm(cyl~am, mtcars)
gof_map <- modelsummary::gof_map
gof_map$omit <- TRUE
msummary(fit1, gof_map = gof_map)
```
Gives: `Error in .::dplyr : unused argument (drop_na)` Not sure if that is now a dplyr version issue.

One other thing: at the top of extract_statistic_override.R, you have the line 
`#' importFrom broom tidy` I guess there should be an @?

**Comment by vincentarelbundock** [comment]
huuuuh, `drop_na` is part of `tidyr`, not `dplyr`. I pushed a fix. Thanks for testing!

**Comment by LukasWallrich** [comment]
Now I get `Error in tibble(term = NA, value = NA) : could not find function "tibble"`

**Comment by vincentarelbundock** [comment]
yep, i failed to import tibble from tibble.

Sorry I'm doing such a crappy job coding. I only get half days of work since the kids have been out of school, and work hasn't let up. So my mental bandwidth is pretty exhausted.

**Comment by vincentarelbundock** [comment]
I pushed a commit with the correc timport

**Comment by LukasWallrich** [comment]
Now dplyr is back:         
`out <- tibble::tibble(term = NA, value = NA) %>% dplyr::drop_na`

But no worries and no rush at all - these are crazy days indeed.

**Comment by vincentarelbundock** [comment]
fuuuu*&! 

ea1ed3d

**Comment by LukasWallrich** [comment]
Nearly there - I think brackets are missing at the end of the line? At least I get
`Error in .::tidyr : unused argument (drop_na)`

**Comment by vincentarelbundock** [comment]
obviously ;)

After a good night of sleep, with my head clear, I finally did the sensible thing and wrote a test based on your code. The test clears on my machine, so hopefully it works now. 

Thanks again for your help and attention to detail!

**Comment by vincentarelbundock** [comment]
https://github.com/vincentarelbundock/modelsummary/blob/master/tests/testthat/test-gof_map.R

**Comment by LukasWallrich** [comment]
Works now - thanks!
