### ISSUE TITLE
bug in latex version of modelsummary of Fixest models with an interaction of fixed effects

### ISSUE THREAD

**Issue by Laurent-Smeets-GSS-Account** [vincentarelbundock/modelsummary#560]
When using the modelsummary command to make a latex table in a Markdown document, the modelsummary does not properly escape the "^" in the name of fixed effects in a `fixest` model if I use an interaction of fixed effects. 

For example this Markdown file 
\---
title: "Untitled"
header-includes:
   \usepackage{booktabs}
   \usepackage{siunitx}
   \newcolumntype{d}{S[input-symbols = ()]}
output: pdf_document
\---

```{r}
library(fixest)
library(modelsummary)

base = iris
names(base) = c("y", paste0("x", 1:3), "fe1")

base$fe2 = rep(letters[1:5], 30)
base$fe3 = rep(letters[1:5], 30)

est_comb = feols(y ~ x1 | fe1 +fe2 +fe3, data = base, cluster= "fe1^fe2")
modelsummary::modelsummary(est_comb)
```

gives this error message

```
! Undefined control sequence.
l.171 Std.Errors & by: fe1\textasciicircumfe
                                            2\\ 
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. I believe this is fixed by the commit linked above. You can install from Github, RESTART R COMPLETELY, and try again:

```{r}
remotes::install_github("vincentarelbundock/modelsummary")
```

Will close now to keep the repo clean, but feel free to reopen or comment again if the fix does not work for you.
