### ISSUE TITLE
Model R-squared changes strangely with using 'standardize' argument and removing the intercept

### ISSUE THREAD

**Issue by tzoltak** [vincentarelbundock/modelsummary#565]
I observed a strange change in the model R-squared reported by `modelsummary()` while calling for standardised coefficients using the `standardize` argument and removing model intercept, comparing to the analogous model with the intercept. Moreover, model statistics in this first case are different comparing to the situation in which I perform data standarisation and refitting *by hand*. I would expect R-squared to be the same in these cases, but I get:

```r
library(modelsummary)
# baseline model - with intercept
m1a <- lm(mpg ~ cyl, data = mtcars)
# model excluding the intercept
m1b <- lm(mpg ~ cyl - 1, data = mtcars)
# model without intercept, estimated on the data that is standardised "by hand"
m1c <- lm(mpg ~ cyl - 1, data = transform(mtcars,
                                          mpg = scale(mpg)[, 1],
                                          cyl = scale(cyl)[, 1]))
cbind(modelsummary(list("Unstandardised" = m1a,
                        "Standardised by hand, no intercept" = m1c),
                   output = "huxtable"),
      modelsummary(list("Standardised with 'refit', intercept included" = m1a,
                        "Standardised with 'refit', no intercept" = m1b),
                   standardize = "refit", output = "huxtable"))
```

sessionInfo():
```
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.utf8  LC_CTYPE=Polish_Poland.utf8    LC_MONETARY=Polish_Poland.utf8
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] modelsummary_1.1.0

loaded via a namespace (and not attached):
 [1] compiler_4.2.1       pillar_1.8.1         parameters_0.19.0.10 tools_4.2.1          digest_0.6.30       
 [6] huxtable_5.5.0       evaluate_0.17        lifecycle_1.0.3      tibble_3.1.8         checkmate_2.1.0     
[11] lattice_0.20-45      pkgconfig_2.0.3      rlang_1.0.6          DBI_1.1.3            cli_3.4.1           
[16] rstudioapi_0.14      xfun_0.34            fastmap_1.1.0        stringr_1.4.1        withr_2.5.0         
[21] bayestestR_0.13.0    dplyr_1.0.10         knitr_1.40           generics_0.1.3       vctrs_0.4.2         
[26] tidyselect_1.2.0     lmtest_0.9-40        grid_4.2.1           glue_1.6.2           performance_0.10.0  
[31] R6_2.5.1             fansi_1.0.3          rmarkdown_2.17       magrittr_2.0.3       tables_0.9.10       
[36] backports_1.4.1      htmltools_0.5.3      assertthat_0.2.1     datawizard_0.6.3     insight_0.18.6      
[41] effectsize_0.8.1     utf8_1.2.2           stringi_1.7.8        crayon_1.5.2         zoo_1.8-11 
```

**Comment by vincentarelbundock** [comment]
`modelsummary` does not standardize coefficients or compute R2 itself. Instead, it calls `parameters::parameters` to extract and standardize coefficients, and `performance::r2` to compute R2.

`standardize="refit"` only affects the extracted coefficients in the top of the table. Since it is not s supported argument by the `performance` package, it does *nothing* to any of the goodness-of-fit statistics at the bottom of the table. In other words, R2 is only applied to a standardized model if it was standardized *beforehand*, it does not take into account the `standardize` argument transformation, which only applies to the coefficients.

In the first three models, we obtain the same R2, because they are all exactly equivalent.

In the fourth model, we obtain a different R2 because when we call `performance::r2` we apply it to an *unstandardized* model without an intercept, which is obviously a different model.

**Comment by tzoltak** [comment]
OK, technically that's reasonable and, now it's clear to me that internally the whole thing goes back to the problem that `summary.lm()` behaves differently while computing R-squared for models without an intercept.

Nevertheless, still I see this as a problem, because I want to use `modelsummary()` feautures as a shorthand to getting something that is a little specific, but perfectly reasonable in a rather popular use case (lm with all predictors being continuous) and get results that are badly wrong.

Probably there is no way to fix this other than hard-coding some nasty workaround, and it doesn't seem appealing at all, I must say. But what would you think about throwing a warning while detecting that one is calling `modelsummary()` with a lm object that involves no intercept term and uses `standardize` argument at the same time?

**Comment by vincentarelbundock** [comment]
Yes, that makes sense. The latest development version from Github should issue a warning for linear models with the `standardize="refit"` argument and no intercept.

Make sure you restart R after installing from Github and before trying.

**Comment by vincentarelbundock** [comment]
closing now to clean the repo, but feel free to comment again if this doens't work for you or if you have other feature requests.
