### ISSUE TITLE
Consistency in labelling interactions in `modelsummary`

### ISSUE THREAD

**Issue by marklhc** [vincentarelbundock/modelsummary#566]
I notice that currently for mixed effect models (e.g., `lme4`, `glmmTMB`), interaction terms are shown by simply chaining the two variables together without the multiplication sign, whereas I remember there was a multiplication sign in earlier versions. Is this a bug or the intended behavior? Below is an example where the same interaction is labelled differently in `lm` and in `lme4`. Thanks a lot!

``` r
library(lme4)
#> Loading required package: Matrix
library(modelsummary)
data(Orthodont,package="nlme")
Orthodont$nsex <- as.numeric(Orthodont$Sex=="Male")
m1 <- lm(distance ~ age * nsex, data=Orthodont)
m2 <- lmer(distance ~ age * nsex + (1|Subject), data=Orthodont)
modelsummary(list(m1, m2), output = "markdown")
```

|                        | Model 1  | Model 2 |
|:-----------------------|:--------:|:-------:|
| (Intercept)            |  17.373  | 17.373  |
|                        | (1.708)  | (1.184) |
| age                    |  0.480   |  0.480  |
|                        | (0.152)  | (0.093) |
| nsex                   |  -1.032  | -1.032  |
|                        | (2.219)  | (1.537) |
| age × nsex             |  0.305   |         |
|                        | (0.198)  |         |
| agensex                |          |  0.305  |
|                        |          | (0.121) |
| SD (Intercept Subject) |          |  1.816  |
| SD (Observations)      |          |  1.386  |
| Num.Obs.               |   108    |   108   |
| R2                     |  0.423   |         |
| R2 Adj.                |  0.406   |         |
| R2 Marg.               |          |  0.410  |
| R2 Cond.               |          |  0.783  |
| AIC                    |  488.2   |  445.8  |
| BIC                    |  501.7   |  461.9  |
| ICC                    |          |   0.6   |
| Log.Lik.               | -239.121 |         |
| F                      |  25.386  |         |
| RMSE                   |   2.21   |  1.21   |

<sup>Created on 2022-10-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04.1 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] modelsummary_1.1.0 lme4_1.1-30        Matrix_1.5-1      
#> 
#> loaded via a namespace (and not attached):
#>  [1] httr_1.4.4         viridisLite_0.4.1  splines_4.2.1      R.utils_2.12.0    
#>  [5] datawizard_0.6.3   highr_0.9          tables_0.9.10      yaml_2.3.6        
#>  [9] bayestestR_0.13.0  globals_0.16.1     pillar_1.8.1       backports_1.4.1   
#> [13] lattice_0.20-45    glue_1.6.2         digest_0.6.30      checkmate_2.1.0   
#> [17] rvest_1.0.3        minqa_1.2.4        colorspace_2.0-3   sandwich_3.0-2    
#> [21] htmltools_0.5.3    R.oo_1.25.0        pkgconfig_2.0.3    listenv_0.8.0     
#> [25] purrr_0.3.5        xtable_1.8-4       mvtnorm_1.1-3      webshot_0.5.4     
#> [29] scales_1.2.1       svglite_2.1.0      emmeans_1.8.1-1    tibble_3.1.8      
#> [33] styler_1.7.0       generics_0.1.3     TH.data_1.1-1      withr_2.5.0       
#> [37] cli_3.4.1          survival_3.4-0     magrittr_2.0.3     effectsize_0.7.0.5
#> [41] estimability_1.4.1 evaluate_0.17      R.methodsS3_1.8.2  fs_1.5.2          
#> [45] future_1.28.0      fansi_1.0.3        parallelly_1.32.1  R.cache_0.16.0    
#> [49] nlme_3.1-159       MASS_7.3-58.1      xml2_1.3.3         tools_4.2.1       
#> [53] lifecycle_1.0.3    multcomp_1.4-20    stringr_1.4.1      munsell_0.5.0     
#> [57] reprex_2.0.2       kableExtra_1.3.4   compiler_4.2.1     systemfonts_1.0.4 
#> [61] rlang_1.0.6        grid_4.2.1         nloptr_2.0.3       parameters_0.19.0 
#> [65] rstudioapi_0.14    rmarkdown_2.17     boot_1.3-28        codetools_0.2-18  
#> [69] R6_2.5.1           zoo_1.8-11         knitr_1.40         performance_0.10.0
#> [73] fastmap_1.1.0      future.apply_1.9.1 utf8_1.2.2         insight_0.18.6    
#> [77] stringi_1.7.8      parallel_4.2.1     Rcpp_1.0.9         vctrs_0.5.0       
#> [81] xfun_0.34          coda_0.19-4        lmtest_0.9-40
```

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. I believe this is now fixed in the development version of the package on Github. Make sure you restart R after install when you try it.

**Comment by marklhc** [comment]
Thanks for the quick fix! It looks good on my side with the latest version.
