### ISSUE TITLE
tidy.mira no longer called automatically

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#57]
When running the README example for mice-models, the correct tidy function no longer gets called, resulting in an error.

```
library(mice)
# Create a new dataset with missing values
url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
tmp <- read.csv(url)[, c('Clergy', 'Donations', 'Literacy')]
tmp$Clergy[sample(1:nrow(tmp), 3)] <- NA
tmp$Donations[sample(1:nrow(tmp), 3)] <- NA
tmp$Literacy[sample(1:nrow(tmp), 3)] <- NA
# Impute dataset 5 times
tmp <- mice(tmp, m = 5, printFlag = FALSE, seed = 1024)
# Estimate models
mod <- list()
mod[[1]] <- with(tmp, lm(Clergy ~ Donations))
mod[[2]] <- with(tmp, lm(Clergy ~ Donations + Literacy))
generics::tidy(mod[[1]])
```

Error in seq_len(nrow(x)) : 
  argument must be coercible to non-negative integer

With the current modelsummary, modelsummary::tidy() does not work either. However, if I install an old version ("1824f065ac037438e0a019d3968ec2f4acf6ff99"), right after you committed my changes to tidy.mira, modelsummary::tidy() works. Any idea what happened there?

**Comment by LukasWallrich** [comment]
Actually, this is a bit more complicated - modelsummary::tidy() does not work for mira objects unless modelsummary is loaded - but after library(modelsummary) all works as expected. 

So this won't be an issue for most users. It is a bit annoying for me as I am working on a wrapper function for a rather specific use case, but I can work around it, and it should be resolved if and when the tidiers move to broom.

**Comment by vincentarelbundock** [comment]
well yeah. `tidy.mira` is a function of this package. It can't be in the namespace unless the package is loaded. Otherwise every single function and method from every package you have installed would always be there.

Also, `modelsummary::tidy` does not exist. We are not reimplementing a whole new `tidy` function. All we do is supply a new method for it.

**Comment by LukasWallrich** [comment]
I would have expected UseMethod (in the modelsummary::tidy function reexported from generics) to look for methods in the modelsummary namespace as well - like this, I am not entirely sure what the point of re-exporting it is, but I am still getting to grips with the generics package :)

**Comment by vincentarelbundock** [comment]
Honestly, I'm not sure how to deal with generics either. Let me know if you find a better way.
