### ISSUE TITLE
Cannot extract a table following predictions()

### ISSUE THREAD

**Issue by alonadoli** [vincentarelbundock/modelsummary#571]
I am trying to extract a table (e.g., .html) for the results of predictions() (after running a glm() regression model) but am getting an error.

The following is the code I am using:

library(modelsummary)
library(marginaleffects)

sessionInfo()

mod <- glm(
  am ~ cyl + hp + wt, 
  data = mtcars, 
  family = binomial)

p <- predictions(
  mod, 
  variables = list(hp = 55:60), 
  by = "hp")

class(p) <- c("custom", class(p))

tidy.costum <- function(x, ...) {
  colnames(x)[colnames(x) == "predicted"] <- "estimate"
  x$term <- paste("HP =", x$hp)
  return(x)
}

modelsummary(p)

the output including sessionInfo() and the error I'm getting is in the attached file:

<img width="1385" alt="Screenshot 2022-11-10 at 17 19 48" src="https://user-images.githubusercontent.com/99336720/201164013-e4996b20-15bc-484f-89bb-c4d1daa6946f.png">

thank you for the help.

**Comment by vincentarelbundock** [comment]
Looks like a typo: "tidy.costum" vs. "tidy.custom"
