### ISSUE TITLE
Testing of the shape = 'rbind'

### ISSUE THREAD

**Issue by michaeltopper1** [vincentarelbundock/modelsummary#593]
Hey @vincentarelbundock ,

I tested the new argument and I think, overall, it's a nice addition. However, I came across something that I think would be hard to capture within the `modelsummary::modelsummary` function without putting in addtional arguments. The biggest issue I see is with the following code:

```
library(fixest)
library(tidyverse)
library(modelsummary)

## estimating two models for mpg
mpg_1 <- mtcars |>
  feols(mpg ~  cyl | gear + carb + am, cluster = ~hp)

mpg_2 <- mtcars |>
  filter(mpg >20) |>
  feols(mpg ~  cyl | gear + carb + am, cluster = ~hp)


## estimating the same two models for disp
disp_1 <- mtcars |> 
  feols(disp ~ cyl | gear + carb, cluster = ~hp)

disp_2 <- mtcars |> 
  feols(disp ~ cyl | gear + carb + am, cluster = ~hp)

panels <- list("Panel A: MPG" = list(mpg_1, mpg_2), "Panel B: Disp" = list(disp_1, disp_2))

modelsummary(
  panels, 
  shape = "rbind",
  gof_omit = "IC|R2")

```

Notice the output here has some fixed effects in Panel A (the ones that are distinct to this panel) and some that are in Panel B. In this case, I think the table would be more clear if the gof statistics were not all "collapsed" to a final panel—I think having the information in both Panels would be best. 

It would be excellent if modelsummary could internally check whether the gof statistics that the user wants are the same within all of the model and can "collapse" them to final model only if they are the same. Morevover, it could also be a great feature for the user to choose whether they want to "collapse" these at all. Of course, this would involve another argument, or alternatively (to avoid yet another argument), making a new function within `modelsummary` that is specifically for designing tables with panels.  I have a preference for the latter only because I feel like the shape = "rbind" argument is an important feature that many users want but may struggle to find it. 

Would love to hear your thoughts on this!

**Comment by vincentarelbundock** [comment]
Thanks for the feedback, I really appreciate it. I also agree that the current collapsing of the FEs could be confusing, so I added a new option:

```r
modelsummary(panels, shape = "rcollapse")
modelsummary(panels, shape = "rbind")
```

There is also special treatment for FE rows, where we only collapse them if the rows are exactly identical in both panels.

Discoverability is a real problem with a package like this, which has a lot of functionality. There are lots of other features that would "deserve" more exposure. For example, my guess is that summarizing multinomial models in "wide" format is a very popular feature outside economics (probably *more* popular overall than panel-summaries). Do I need a new function for that as well? Where does this stop?

For now, I've just decided to:

1. Add a visual example of panel summaries to the mozaik at the top of the website
2. Improve the docs of the `shape` argument
3. Add a section called "shape: pivot, groups, panels, and stacks" to the `modelsummary` vignette

I hope that's enough for people to find this cool option.

The nice thing is that we now have access to those panels with *all* the other features of the package, including all the table-making backends, all arguments, and all supported models (100+). So this is pretty cool, I think.

Thanks for the inspiration!

**Comment by michaeltopper1** [comment]
This is definitely awesome and far more refined than my puny function. I'll continue testing this in the following days and let you know if I see anything else, but thanks for implementing this great feature so quickly! I'll be sure to pass this knowledge around in my department and advocate to add it to our data wrangling classes.

**Comment by vincentarelbundock** [comment]
Yeah, I'm super happy about this. Thanks for the inspiration and for pushing me a bit on the rough corners!
