### ISSUE TITLE
gof issues continued - error when only some models have gof statistics

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#60]
I just ran into a situation where I only had gof statistics for 2 out of 4 models I wanted to summarise (for the other two, all were omitted). That does not work due to a step in modelsummary::extract - here broken down into separate commands to show where the error occurs:

![image](https://user-images.githubusercontent.com/60155545/79485952-e863b480-800d-11ea-9b24-c22bb1fbea6f.png)

**Comment by vincentarelbundock** [comment]
This is hard to diagnose with just a screenshot. Could you supply a minimal reproducible example? Ideally using the `reprex` package/command: https://github.com/tidyverse/reprex

I would be able to reproduce locally, and then just copy the code in a new test file to ensure this bug never shows up again.

**Comment by vincentarelbundock** [comment]
Ideally using a built-in small dataset like `mtcars`

**Comment by LukasWallrich** [comment]
Here you go:

``` r
library(modelsummary)
mod1 <- glm(vs ~ mpg, data = mtcars, family = "binomial")
mod2 <- lm(vs ~ mpg, data = mtcars)
gof_map <- modelsummary::gof_map
gof_map$omit <- TRUE
gof_map$omit[gof_map$raw == "r.squared"] <- FALSE
msummary(list(mod1, mod2), gof_map = gof_map)
#> Error: Can't join on 'term' x 'term' because of incompatible types (character / logical)
```

<sup>Created on 2020-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by LukasWallrich** [comment]
Yes, that seems to work - also works with my original models. Thanks.
