### ISSUE TITLE
`fixest` `vcov` seems broken again

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#600]
what changed again?

```{r}
library(fixest)
library(modelsummary)

m1 <- feols(mpg ~ hp | gear + am, mtcars)

m2 <- lm(mpg ~ demean(hp, list(gear, am)), mtcars)

modelsummary(list(m1, m2), fmt = 6, vcov = ~gear + am)

demean(mtcars$mpg, mtcars$gear) |> str()

dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/plm/Grunfeld.csv")

models <- list(
    feols(inv ~ value + capital | firm, data = Grunfeld),
    lm(inv ~ demean(value, firm) + demean(capital, firm), data = Grunfeld)
)
modelsummary(models, fmt = 5, vcov = "HC1")


models <- list(
    feols(inv ~ value + capital | firm + year, data = Grunfeld),
    lm(inv ~ demean(value, list(firm, year)) + demean(capital, list(firm, year)), data = Grunfeld)
)
modelsummary(models, fmt = 5, vcov = "HC3")
```

**Comment by etiennebacher** [comment]
Error here: 
https://github.com/vincentarelbundock/modelsummary/blob/9a14dd1ccac373239e31d42ba7bbb2336cf9dcd8/R/sanitize_vcov.R#L112-L114

Need a function in the error case of `tryCatch()`:
```r
vcov[[i]] <- tryCatch(
  sandwich::vcovHC(models[[j]]),
  error = function(e) "HC1"
)
```

**Comment by vincentarelbundock** [comment]
Merci @etiennebacher !

@Nadjim10 Aurais-tu tu temps pour regarder ça en détail? J'ai fait la modification proposée par Étienne, mais j'aimerais que tu crées beaucoup de tests pour cette situation.

The issue is that:

1. `fixest` sometimes (but not always) estimates robust standard errors at FIT TIME.
2. `modelsummary` sometimes wants to override the `fixest` standard errors with its own estimates at TABLE TIME.
3. When nothing is specified in `vcov` argument of `modelsummary` (or if `vcov = list(NULL, NULL)`), then we want the original `fixest` SEs.

What we need now is a bunch of different combinations of fit/time table/time settings, to make sure that the label which appears in the final table matches the standard errors.

There are already some tests at the link below, but we could write a couple dozen more to make sure that most of the cases are covered:

https://github.com/vincentarelbundock/modelsummary/blob/main/inst/tinytest/test-pkg-fixest.R#L47

**Comment by Nadjim10** [comment]
Oui bien sûr @vincentarelbundock !

**Comment by vincentarelbundock** [comment]
I fixed the `tryCatch` issue, and now think that I was seeing mismatches because I did not input the correct `fixest` arguments. Closing for now. Happy to work on this if someone can show a clear example of mismatch.
