### ISSUE TITLE
get_estimates doesn't seem to know aliases in vcov argument

### ISSUE THREAD

**Issue by ethans-carl** [vincentarelbundock/modelsummary#605]
When using get_estimates(model, vcov = "stata"), there is a blank error returned.  However, get_estimates(model, vcov = "HC1") returns the expected output. The same is true for "robust" as an alias for "HC3."

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. This should be fixed in the development version on Github. Make sure you restart R after installing for the change to take effect.
