### ISSUE TITLE
`modelsummary()` doesn't use labels

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/modelsummary#606]
`datasummary_skim()` works fine with labels but `modelsummary()` doesn't.

Example from [this vignette](https://vincentarelbundock.github.io/modelsummary/articles/appearance.html#variable-labels):

``` r
library(haven)
library(modelsummary)

dat <- mtcars
dat$am <- haven::labelled(dat$am, label = "Transmission")
dat$mpg <- haven::labelled(dat$mpg, label = "Miles per Gallon")
mod <- lm(hp ~ mpg + am, dat = dat)

datasummary_skim(dat[, c("am", "mpg")], output = "markdown", histogram = FALSE)
```

|                  | Unique (#) | Missing (%) | Mean |  SD |  Min | Median |  Max |
|:-----------------|-----------:|------------:|-----:|----:|-----:|-------:|-----:|
| Transmission     |          2 |           0 |  0.4 | 0.5 |  0.0 |    0.0 |  1.0 |
| Miles per Gallon |         25 |           0 | 20.1 | 6.0 | 10.4 |   19.2 | 33.9 |

``` r

modelsummary(mod, output = "markdown")
```

|             |  \(1\)   |
|:------------|:--------:|
| (Intercept) | 352.312  |
|             | (27.226) |
| mpg         | -11.200  |
|             | (1.494)  |
| am          |  47.725  |
|             | (18.048) |
| Num.Obs.    |    32    |
| R2          |  0.680   |
| R2 Adj.     |  0.658   |
| AIC         |  331.9   |
| BIC         |  337.8   |
| Log.Lik.    | -161.971 |
| F           |  30.766  |
| RMSE        |  38.19   |

<sup>Created on 2023-03-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Thanks. In `modelsummary`, we need to add the `coef_rename=TRUE` argument. This is a bit inconsistent, but I kind of like that `modelsummary` is a bit “vanilla”. I fixed the vignette.

``` r
library(haven)
library(modelsummary)

dat <- mtcars
dat$am <- haven::labelled(dat$am, label = "Transmission")
dat$mpg <- haven::labelled(dat$mpg, label = "Miles per Gallon")
mod <- lm(hp ~ mpg + am, dat = dat)

modelsummary(mod, coef_rename = TRUE)
```

|                  |    (1)    |
| :--------------- | :-------: |
| (Intercept)      |  352.312  |
|                  | (27.226)  |
| Miles per Gallon | \-11.200  |
|                  |  (1.494)  |
| Transmission     |  47.725   |
|                  | (18.048)  |
| Num.Obs.         |    32     |
| R2               |   0.680   |
| R2 Adj.          |   0.658   |
| AIC              |   331.9   |
| BIC              |   337.8   |
| Log.Lik.         | \-161.971 |
| F                |  30.766   |
| RMSE             |   38.19

**Comment by etiennebacher** [comment]
Great, thank you!

**Comment by etiennebacher** [comment]
Actually, the vignette wasn't updated. I don't know if you just forgot to push a commit or wanted to do it later but I reopen this so that it's not forgotten.

**Comment by vincentarelbundock** [comment]
Thanks. It is now updated on the dev website. The main website will be updated at the next release to CRAN: https://vincentarelbundock.github.io/modelsummary/dev/articles/appearance.html#variable-labels
