### ISSUE TITLE
`modelsummary()` fails with a list of `fixest_multi`

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/modelsummary#608]
Two things in the example below:

1. `modelsummary()` works with `est1` but not with `modelsummary(list(est1, est2))` whereas `est1` and `est2` are the same model. Is it expected that a list of `fixest_multi` fails?
2. if failure is expected, there are both a warning and an error with almost the same message. I guess it should be one of the two?

``` r
library(fixest)
library(modelsummary)

packageVersion("modelsummary")
#> [1] '1.3.0.9009'

base <- iris
names(base) <- c("y1", "y2", "y3", "x1", "species")

est1 <- feols(c(y1,y2) ~ x1, base)
est2 <- feols(c(y1,y2) ~ x1, base)

modelsummary(est1, gof_map = c("r.squared", "nobs"))
```

|             | lhs: y1 | lhs: y2 |
|:------------|:-------:|:-------:|
| (Intercept) |  4.778  |  3.308  |
|             | (0.073) | (0.062) |
| x1          |  0.889  | -0.209  |
|             | (0.051) | (0.044) |
| R2          |  0.669  |  0.134  |
| Num.Obs.    |   150   |   150   |

``` r

modelsummary(list(est1, est2), gof_map = c("r.squared", "nobs"))
#> Warning: `modelsummary could not extract goodness-of-fit statistics from a model
#> of class "fixest_multi". The package tried a sequence of 2 helper functions:
#> 
#> performance::model_performance(model)
#> broom::glance(model)
#> 
#> One of these functions must return a one-row `data.frame`. The `modelsummary` website explains how to summarize unsupported models or add support for new models yourself:
#> 
#> https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html
#> Error: `modelsummary could not extract the required information from a model of
#>   class "fixest_multi". The package tried a sequence of 2 helper functions
#>   to extract estimates:
#>   
#>   parameters::parameters(model)
#>   broom::tidy(model)
#>   
#>   To draw a table, one of these commands must return a `data.frame` with a
#>   column named "term". The `modelsummary` website explains how to
#>   summarize unsupported models or add support for new models yourself:
#>   https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html
#>   
#>   These errors messages were generated during extraction:
#>   
#>   `parameters::parameters(model)` did not return a valid data.frame.
#> `broom::tidy(model)` did not return a valid data.frame.
```

<sup>Created on 2023-03-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
No, I just didn't expect this use-case. Can we just combine two `fixest_multi` objects?

Current handling is here: https://github.com/vincentarelbundock/modelsummary/blob/main/R/sanitize_models.R

**Comment by etiennebacher** [comment]
Actually yes we can combine them with `c()`:
``` r
library(fixest)
library(modelsummary)

base <- iris
names(base) <- c("y1", "y2", "y3", "x1", "species")

est1 <- feols(c(y1,y2) ~ x1, base)
est2 <- feols(c(y1,y2) ~ x1, base)

modelsummary(c(est1, est2), gof_map = c("r.squared", "nobs"))
```

|             | lhs: y1 | lhs: y2 | lhs: y1 | lhs: y2 |
|:------------|:-------:|:-------:|:-------:|:-------:|
| (Intercept) |  4.778  |  3.308  |  4.778  |  3.308  |
|             | (0.073) | (0.062) | (0.073) | (0.062) |
| x1          |  0.889  | -0.209  |  0.889  | -0.209  |
|             | (0.051) | (0.044) | (0.051) | (0.044) |
| R2          |  0.669  |  0.134  |  0.669  |  0.134  |
| Num.Obs.    |   150   |   150   |   150   |   150   |

I don't have time for a PR now

**Comment by vincentarelbundock** [comment]
Should work now.

``` r
packageVersion("modelsummary")
# [1] '1.3.0.9010'

library(fixest)
library(modelsummary)

base <- iris
names(base) <- c("y1", "y2", "y3", "x1", "species")
mod <- list(
  "A" = feols(c(y1,y2) ~ x1, base),
  "B" = feols(c(y1,y2) ~ x1, base))
modelsummary(mod, gof_map = c("r.squared", "nobs"))
```

|             | A lhs: y1 | A lhs: y2 | B lhs: y1 | B lhs: y2 |
| :---------- | :-------: | :-------: | :-------: | :-------: |
| (Intercept) |   4.778   |   3.308   |   4.778   |   3.308   |
|             |  (0.073)  |  (0.062)  |  (0.073)  |  (0.062)  |
| x1          |   0.889   |  \-0.209  |   0.889   |  \-0.209  |
|             |  (0.051)  |  (0.044)  |  (0.051)  |  (0.044)  |
| R2          |   0.669   |   0.134   |   0.669   |   0.134   |
| Num.Obs.    |    150    |    150    |    150    |    150    |

**Comment by etiennebacher** [comment]
Looks great, thanks!
