### ISSUE TITLE
Add gof_omit = "all" option

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#61]
For me, it would be very helpful to have a simple way to exclude gof in the msummary call. Would you be open to considering a PR that implements gof_omit = "all"? It would add half a line to the msummary documentation, though :)

(Background to my gof struggles): I am often showing the same model with differently scaled coefficients, and don't want to show gof twice, as in the below)

![Example](https://user-images.githubusercontent.com/60155545/79487332-03cfbf00-8010-11ea-8881-4babf5eef19d.JPG)

**Comment by LukasWallrich** [comment]
Sorry, not my brightest day today - given that this uses regex, I can of course easily achieve what I need :/

**Comment by vincentarelbundock** [comment]
Haha! I was already thinking through various solutions. But you're right that a simple `.*` should work.

**Comment by LukasWallrich** [comment]
Hi - it's been a while and I am still appreciating your package a lot. 

However, this old question has become an issue again - `gof_omit = ".*"` no longer works but results in an error. Any chance to get that back? (The actual error appears to be thrown by gt, I'll try to investigate a bit further.)

``` r
mod <- lm(mpg~wt, mtcars)
modelsummary::msummary(mod, gof_omit = ".*")
#> Error: All column or row indices given must be present in `data_tbl`.
```

<sup>Created on 2020-08-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by LukasWallrich** [comment]
As I read the code, the error occurs because hline is passed as NA to factory(), but then later checked with is.null() - since NA is not NULL, gt then tries to draw the horizontal line. I will fork and send a PR that sets that NA to NULL in msummary() so that I can install from there and get my script to work again - however, you might want to fix it deeper down in the stack if that works better with your logic of NULLs and NAs.
