### ISSUE TITLE
`modelplot(exponentiate = TRUE)` should use a log scale

### ISSUE THREAD

**Issue by larmarange** [vincentarelbundock/modelsummary#614]
When `modelplot()` is called with `exponentiate = TRUE`, coefficients are currently plotted with a linear scale.

A good practice is to plot such exponentiated coefficients according to a log scale. cf. for example https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5805472/ or https://www.jahonline.org/article/S1054-139X(17)30424-X/fulltext

It could be relevant to update `modelplot()` for changing the X scale to log-scale when `exponentiate = TRUE`.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. The beauty of `modelplot()` is that it generates a standard `ggplot2` object. This means that it is trivial for users to change the scale to log with a single line of code if they want to.

In general, I agree with your view that logs tend to be preferable in that context, but I try not to implement features that can be achieved super easily with a single line of `ggplot2`.

**Comment by vincentarelbundock** [comment]
Yeah that's a great idea. I'm swamped at work right now, but will try to come round to it eventually. (Or very happy to merge a PR!)

**Comment by larmarange** [comment]
I have drafted a quick example. See #615
