### ISSUE TITLE
Website: some values are not entirely shown in the table

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/modelsummary#618]
Just a minor thing: on the website, when you show how to use [glue strings](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#statistic-se-t-p-ci-etc-) to display several stats, there's a problem with the width:

![image](https://user-images.githubusercontent.com/52219252/229789795-820accdf-f65d-464c-8422-328061a1ed59.png)

The display is completely fine locally so I'm not sure there's something you can do, but it seems like a bug because the table below correctly breaks line for the confidence interval:

![image](https://user-images.githubusercontent.com/52219252/229789847-d4ed4070-9e42-49a0-b80f-ec992aab367e.png)

**Comment by vincentarelbundock** [comment]
Thanks, I had not noticed. I switched the dev version of the website to `gt` output by default, which should fix things: https://vincentarelbundock.github.io/modelsummary/dev/articles/modelsummary.html

**Comment by etiennebacher** [comment]
Indeed, thank you!
