### ISSUE TITLE
Group column (e.g., from multinomial models) disappears after pooling

### ISSUE THREAD

**Issue by yjin-chae** [vincentarelbundock/modelsummary#621]
Hi! Thank you for the great package. This has made my life so much easier.

When using multinom and mice packages together, modelsummary does not properly pull the group variable from the pooled model. So I cannot use 'shape=' or 'group=' argument to structure the output by response group.

Below is a toy example:

library(mice)
library(nnet)
library(modelsummary)

data = ampute(mtcars) ## Ampute mtcars and impute two data sets
imp = mice(data$amp, m=2)
imp.l = complete(imp, action="long") 

model = list() ## Fit and pool models
for(i in 1:2) model[[i]] = multinom(carb ~ disp + hp, data = imp.l, subset = .imp == i)
pooled = pool(model)

modelsummary(pooled, shape = term + statistic ~ model + y.level) ## None of these code work
modelsummary(pooled, shape = term + statistic ~ model + response)
modelsummary(pooled, shape = term + statistic ~ model + group)

get_estimates(pooled, conf_level = NULL) ## get_estimates does not return proper group column.

term     estimate std.error statistic p.value group ## this group column is empty.
1  (Intercept)  -2.38     2.069    -1.154    0.27      
2         disp      -0.00     0.013    -0.009    0.99      
3           hp        0.02     0.036     0.777    0.45      
4  (Intercept)  -15.54     2.069    -1.154    0.27      
5         disp       -0.05     0.013    -0.009    0.99      
6           hp         0.20     0.036     0.777    0.45      
7  (Intercept)  -14.28     2.069    -1.154    0.27      
8         disp      -0.05     0.013    -0.009    0.99      
9           hp        0.20     0.036     0.777    0.45      
10 (Intercept) -20.18     2.069    -1.154    0.27      
11        disp       -1.64     0.013    -0.009    0.99      
12          hp       1.63     0.036     0.777    0.45      
13 (Intercept)  -29.14     2.069    -1.154    0.27      
14        disp     -0.24     0.013    -0.009    0.99      
15          hp      0.45     0.036     0.777    0.45      

I'm sorry the output is not well aligned. broom::tidy did not have any issue with pulling group column, which is y.level. Is this a bug of modelsummary, or is there any other way to properly use the shape argument? Thanks!

**Comment by vincentarelbundock** [comment]
The amazing @strengejacke fixed this upstream. If you install two packages from Github and restart `R` completely, things should work as expected:

```r
remotes::install_github("easystats/parameters")
remotes::install_github("easystats/insight")
```

**Comment by yjin-chae** [comment]
That’s awesome. Thanks!
