### ISSUE TITLE
Feature request: Panels in data summary tables

### ISSUE THREAD

**Issue by simonheb** [vincentarelbundock/modelsummary#624]
Hi, I'm summarizing two datasets and would like to show summary stats in one table in two panels. Like so:

```
        |     N    |  mean |    sd
--------+----------+-------+-------
Panel 1: Some data
var1    |    100   | 0.3   | 0.2
var2    |    100   | 0.2   | 0.2
Panel 2: Other data
var1    |   1000   | 0.33  | 0.21
var2    |   1000   | 0.22  | 0.23
```

I saw that `modelsummary` allows this via lists and `shape`: https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html?q=panel#shape-pivot-groups-panels-and-stacks

Is this entirely impossible with `datasummary'?

**Comment by vincentarelbundock** [comment]
Unfortunately not possible out of the box (and hard to implement).

I think that the easiest way to hack your way there would to by selecting output="dataframe" for one table, rbind-ing a row of headers, and then feeding that in add_rows argument to the second table.

**Comment by simonheb** [comment]
Thanks for the quick reply. Would it be possible to add in-between headers into formulas like so:

`datasummary(x + y + Heading("Now come other variables") + z + a ~ Mean + SD, data=dta)`?

**Comment by vincentarelbundock** [comment]
Not 100% sure.

Check out the website section where the show how to add inline histograms manually. In that example I insert and empty column. Maybe you can do the same with an empty row.

**Comment by simonheb** [comment]
Ok thanks (also for this great piece of software)

**Comment by vincentarelbundock** [comment]
Yet another option might be to rbind your two datasets, even if they don't have any columns on common.

I'm on my phone now and kind of overwhelmed with "real" work, but try things out and if you get stuck, show me where you ended up. I can then take a look, but probably not before the end of next week.
