### ISSUE TITLE
Gof values of probit model

### ISSUE THREAD

**Issue by nithinmkp** [vincentarelbundock/modelsummary#633]
Although summary(model) of a probit model returns log likelihood, get_gof from modelsummary does not include this. is there a workaround to inlcude gof statistics that we need to add ?

**Comment by vincentarelbundock** [comment]
Can you make sure you are running the latest version and supply a reproducible example? I can’t reproduce this problem:

``` r
packageVersion("modelsummary")
# [1] '1.4.0'

library(modelsummary)
mod = glm(am ~ mpg, mtcars, family = binomial("probit"))
get_gof(mod)
#        aic      bic r2.nagelkerke      rmse nobs       F    logLik
# 1 33.55942 36.49089     0.4691834 0.3919157   32 8.88849 -14.77971
```

**Comment by nithinmkp** [comment]
Hello Vincent,
Thanks for getting back. I am sorry for not providing complete details of
the issue.
I am actually using package "pglm" for panel probit estimation. The get_gof
function does not return log likelihood which is an important measure of
such class of models. However, I was quick to file an issue too. Reading
thoroughly through the documentation, I could figure out a way to add it by
using the glance function from the broom package and the add_rows function
in modelsummary. basically, my issue is solved for now.

Thanks and regards,
Nithin



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/12/23,
07:18:31 PM
