### ISSUE TITLE
modelsummary::datasummary() return "could not find function "labelSubset"" when the library is not imported.

### ISSUE THREAD

**Issue by toshifumikuroda** [vincentarelbundock/modelsummary#634]
I find a minor bug in the modelsummary::datasummary().
When I try to summarize data by following code, it returns the error.

```
rm(list = ls())

library(magrittr)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv'
penguins <- read.csv(url)

penguins %>%
  modelsummary::datasummary(
  bill_length_mm + bill_depth_mm + flipper_length_mm ~ mean * sex,
  data = .
)
```
Error
```
Error in modelsummary::datasummary(bill_length_mm + bill_depth_mm + flipper_length_mm ~  : 
  could not find function "labelSubset"
```
However, after I import the library once, the code above worked well.
`
library(modelsummary)
penguins %>%
  modelsummary::datasummary(
    bill_length_mm + bill_depth_mm + flipper_length_mm ~ mean * sex,
    data = .
  )
`
I think some dependencies are missing in modelsummary::datasummary().

Thank you,
Toshi

**Comment by vincentarelbundock** [comment]
Thanks for the report.

`labelSubset` is a function from a dependency: the `tables` package. It needs to be re-exported from `modelsummary`. Unfortunately, this is done when `library(modelsummary)` is called, and I don't know how to achieve the same thing when the package is not loaded and people use `::`.

Unless someone can help me find a solution, I'm afraid you will have to load the library before using this function.
