### ISSUE TITLE
`pkgdown` examples

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#639]
+ [ ] `datasummary_skim` does not show histograms
+ [ ] `coef_omit` does not work

**Comment by vincentarelbundock** [comment]
Did you change the default output to `DT`? Inline histograms are not supported with that table format, which is what the error message says.

**Comment by sfd99** [comment]
Hi Vincent - 
wow! that was quick...

how to change the default output to "DT" ?
in 
datasummary_skim(penguins) ?.

(sorry if it's a silly Q)

**Comment by vincentarelbundock** [comment]
What happens if you try a different output format like `output="kableExtra"?

**Comment by sfd99** [comment]
This:

datasummary_skim("penguins",output = "kableExtra")
Error in datasummary_skim_numeric(data, output = output, fmt = fmt, histogram = histogram,  : 
  data contains no numeric variable.

**Comment by vincentarelbundock** [comment]
Penguins shouldn't be in quotes

**Comment by sfd99** [comment]
oops, sorry!.
So:
  datasummary_skim( penguins ,output = "kableExtra")
works perfectly!
and:
datasummary_skim( penguins) # works great, too!.

btw: 
datasummary_skim( penguins, output = "DT") # does not work, DT is "loaded" 
====
