### ISSUE TITLE
`dvnames()`: preserve transformations of DV

### ISSUE THREAD

**Issue by seawavevan** [vincentarelbundock/modelsummary#641]
Sometimes it's useful to output regression results with dependent variables listed in the head of the table. But I noticed that if the dv has been log transformed, using `dvnames` would generate the original dv in the table instead of the transformed one. 

```
m1 <- lm(mpg ~ cyl + hp, data = mtcars)
m2 <- lm(log(mpg+1) ~ cyl + hp, data = mtcars)
msummary(dvnames(list(m1, m2)))
```

|             |   mpg   |   mpg   | 
|:------------|--------:|--------:|
| (Intercept) |  36.908 |  3.795  | 
|             | (2.191) | (0.100) | 
| cyl         |  -2.265 |  -0.102 | 
|             | (0.576) | (0.026) | 
| hp          |  -0.019 |  -0.001 | 
|             | (0.015) | (0.001) | 
| Num.Obs.    |    32   |    32   | 
| R2          |  0.741  |  0.752  | 
| R2 Adj.     |  0.723  |  0.735  | 
| AIC         |  169.6  |  133.9  | 
| BIC         |  175.4  |  139.7  | 
| Log.Lik.    | -80.781 |  17.869 | 
| F           |  41.422 |  44.013 | 
| RMSE        |   3.02  |   0.14  | 

In the above regressions, the output table would both use `mpg` as dv name which can cause confusion.

**Comment by vincentarelbundock** [comment]
Thanks for the feature request.

Ideally, I think we would add a new argument to the `dvnames` function to determine if transformations should be stripped or printed. I'm not sure what the name of this argument should be.

Unfortunately, I don't have the time to implement this right now. However, the `dvnames()` is extremely simple, so it would be very easy to do this: https://github.com/vincentarelbundock/modelsummary/blob/main/R/dvnames.R

I marked the issue with the "help wanted" and "good first issue" labels. Hopefully someone will come along and submit a Pull Request with code contribution.

**Comment by vincentarelbundock** [comment]
Thanks for this. For the record, I would like the eventual solution we adopt to rely on Base R functions to avoid on-boarding a new dependency.

**Comment by vincentarelbundock** [comment]
thanks again for the suggestions. The latest dev version on Github has a `strip` argument which defaults to `FALSE`
