### ISSUE TITLE
How do you achieve the first example (side-by-side panel)? 

### ISSUE THREAD

**Issue by alanzchen** [vincentarelbundock/modelsummary#643]
How do one achieve this?

![](https://user-images.githubusercontent.com/987057/82855711-0a3c3b00-9eda-11ea-8a81-1eebfbb7cb73.png)

I can use nested list and `shape` to achieve this in a top-and-bottom fashion, but couldn't figure out how to do it side-by-side as the example shows.

Thanks!

**Comment by vincentarelbundock** [comment]
It’s not panels. It’s just a muticolumn header with the kableExtra.  I think it’s add_row_header, but this should be easy to confirm in the vignettes of both packages

**Comment by alanzchen** [comment]
Thanks! Is there a way to achieve this with panels? The convention in my field is to display panels side-by-side. It would be nice to use the nested list to specify different panels.

**Comment by vincentarelbundock** [comment]
How is the visual output different from the table above? If the example you showed above is not actually what you want, can you show an example?

**Comment by alanzchen** [comment]
What I got is something like this:

![](https://user-images.githubusercontent.com/987057/210188882-8f2c83d6-18d3-46c6-b640-a446f0474b8a.png)

It would like the "Outcome" header to be displayed like the first example in the first row, and model names in the second row, so such the two panels are displayed side-by-side but not top-and-bottom.

**Comment by vincentarelbundock** [comment]
It's still not clear to me why you can't just use the `kableExtra::add_row_header()` syntax I recommended above. Just don't use a nested list. If there's currently a very easy way to achieve the first table you posted, I'm not convinced it is worth implementing a second equivalent syntax...
