### ISSUE TITLE
Order of glance_custom.ivreg() elements changes when also including lm model

### ISSUE THREAD

**Issue by ChrNikEsc** [vincentarelbundock/modelsummary#648]
Hi,

when adding additional statistics using (in my case for ivreg) glance_custom.ivreg(), the order of those changes when I add a lm model next to it. See MWE below, just running modelsummary(IV) returns the intended order as provided by glance_custom.ivreg(). When passing both OLS and IV to modelsummary(), the order is changed. Multiple ivreg models do _not_ cause the issue.
By the way, in the project where I came across this, the order changed differently (here in MWE it is Sargan - Weak Instr. - WuHausman, in my other project it changed to WuHausman - Sargan - Weak Instr).
The issue does _not_ occur when using panels and shape = "rbind". However, I want to have the models side by side.

Huge thanks for your thoughts on this!

```
library(tidyverse)
library(ivreg)
library(modelsummary)

glance_custom.ivreg <- function(x, digits = 1, ...) {
  summary.x <- summary(x)
  
  summary.x$diagnostics %>%
    as_tibble(rownames = NA) %>%
    rownames_to_column(var = "term") %>%
    mutate(term = str_replace_all(term, "-", "–")) %>% 
    mutate(out = paste0(
      round(statistic, digits),
      case_when(
        `p-value` < 0.001 ~ "***",
        `p-value` < 0.01 ~ "**",
        `p-value` < 0.05 ~ "*",
        `p-value` < 0.1 ~ "+",
        TRUE ~ ""
      )
    )) %>% 
    mutate(out = ifelse(str_detect(out, "NA"), "", out)) %>%
    select(term, out) %>%
    pivot_wider(names_from = "term", values_from = "out")
}

OLS <- lm(mpg ~ hp + disp, data = mtcars)
IV <- ivreg::ivreg(mpg ~ hp + disp | cyl + disp, data = mtcars)

glance_custom.ivreg(IV)

models <- list("OLS" = OLS, "IV" = IV)

modelsummary(IV) # when just having ivreg models, the order of diagnostics is as returned by glance_custoum.ivreg()

modelsummary(models) # when adding a lm model, the order changes

```

sessionInfo():

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] modelsummary_1.4.1.9006 ivreg_0.6-2             lubridate_1.9.2         forcats_1.0.0           stringr_1.5.0           dplyr_1.1.2            
 [7] purrr_1.0.1             readr_2.1.4             tidyr_1.3.0             tibble_3.2.1            ggplot2_3.4.2           tidyverse_2.0.0

**Comment by vincentarelbundock** [comment]
Have you tried using the `gof_map` argument to control the order?

**Comment by ChrNikEsc** [comment]
I now figured out this solution to keep the order, leaving it here in case anyone else faces a similar problem. Maybe something like this could be implemented as the default behavior if the gof_map argument is not provided.
```
gm <- function(models) {
  map(models, ~names(get_gof(.x))) %>% # get all gof measures of the models
  unlist() %>% # collapse list of vectors to one vector
  unique() %>% # remove duplicates
  data.frame(raw = ., clean = ., fmt = 0, omit = FALSE) %>% # create new df to be appended to modelsummary::gof_map
  bind_rows(modelsummary::gof_map, .) %>% # append to original modelsummary::gof_map
  distinct(raw, .keep_all = TRUE) # makes sure that gof measures already present in modelsummary::gof_map are not overwritten
}

modelsummary(
  models,
  gof_map = gm(models)
)
```

**Comment by vincentarelbundock** [comment]
Great!
