### ISSUE TITLE
`Percentage` should be `Percent` in example

### ISSUE THREAD

**Issue by barryrowlingson** [vincentarelbundock/modelsummary#650]
Typo in examples here:

https://github.com/vincentarelbundock/modelsummary/blob/43bfea5d9bb86dea5663ede54dfc64036f7bd25f/R/datasummary_crosstab.R#L52C59-L52C59

Fails:

```
> datasummary_crosstab(am ~ gear, statistic = ~ Percentage("col"), data = mtcars)
Error in datasummary_crosstab(am ~ gear, statistic = ~Percentage("col"),  : 
  The right-hand side of `statistic` may only contain 1, N, Percent(), Percent('row'), or Percent('col').To produce more complex tables, consider using the datasummary() function.
> 
```

Works:

`> datasummary_crosstab(am ~ gear, statistic = ~ Percent("col"), data = mtcars)`

**Comment by vincentarelbundock** [comment]
Thanks a lot, I appreciate it.

a661ce99
