### ISSUE TITLE
Using `options(modelsummary_get = "all")` causes `coef_rename = TRUE` having no effect

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#654]
1. Using `options(modelsummary_get = "all")` causes `coef_rename = TRUE` having no effect

2.
```r
datlab <- mtcars
datlab$cyl <- factor(datlab$cyl)
attr(datlab$cyl, "label") <- "Cylinders"
attr(datlab$am, "label") <- "Transmission"
modlab <- lm(mpg ~ cyl + am, data = datlab)
modelsummary(modlab, coef_rename = TRUE)
# fine; however
options(modelsummary_get = "all")
modelsummary(modlab, coef_rename = TRUE)
```

|             |   (1)   | 
|:------------|--------:|
| (Intercept) |  24.802 | 
|             | (1.323) | 
| cyl6        |  -6.156 | 
|             | (1.536) | 
| cyl8        | -10.068 | 
|             | (1.452) | 
| am          |  2.560  | 
|             | (1.298) | 
|:------------|--------:|
| Num.Obs.    |    32   | 
| R2          |  0.765  | 
| R2 Adj.     |  0.740  | 
| AIC         |  168.4  | 
| BIC         |  175.7  | 
| Log.Lik.    | -79.199 | 
| F           |  30.402 | 
| RMSE        |   2.87  | 

3. `sessionInfo()` output
```r
sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3 
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3;  LAPACK version 3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
 [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

time zone: UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] modelsummary_1.4.1

loaded via a namespace (and not attached):
 [1] digest_0.6.32      tables_0.9.17      backports_1.4.1    tidyr_1.3.0        utf8_1.2.3         R6_2.5.1          
 [7] fastmap_1.1.1      tidyselect_1.2.0   xfun_0.39          magrittr_2.0.3     glue_1.6.2         tibble_3.2.1      
[13] knitr_1.43         pkgconfig_2.0.3    htmltools_0.5.5    dplyr_1.1.2        generics_0.1.3     lifecycle_1.0.3   
[19] cli_3.6.1          fansi_1.0.4        performance_0.10.4 vctrs_0.6.3        compiler_4.3.1     purrr_1.0.1       
[25] tools_4.3.1        broom_1.0.5        checkmate_2.2.0    pillar_1.9.0       rlang_1.1.1        insight_0.19.3   
```

**Comment by iago-pssjd** [comment]
I've just seen that this option rests on the `pretty_labels` attribute and the `parameters` function/library, so I acknowledge it has no easy solution.

However, FWIW, I use `options(modelsummary_get = "all")` just for gof indices, since `broom::glance` gives me the ones I want, instead of `performance`. Ideally, we could separate estimate and gof options having
```r
`options(modelsummary_get_estimates = "easystats")
`options(modelsummary_get_gof = "all")
```

Thanks!

**Comment by iago-pssjd** [comment]
Otherwise, I could try combining a modelsummary with only estimates (by means of `gof_omit = ".*"`) with a modelsummary with only gof indices. Is this last output available (let's say, something like `estimates_omit = TRUE`)?

**Comment by vincentarelbundock** [comment]
Sorry for the delay. Work has been crazy, and then vacation, etc.

Yes, you're right that this option requires `parameters` and doesn't work with `broom`.

The `broom` package is not actively developed anymore, so I want to *strongly* discourage everyone to use it, and I don't want to implement new features to facilitate its use. My recommended workflow is to *not* use the `modelsummary_get` global option, and to instead customize GOF labels and content using the `gof_map` and `glance_custom()` mechanisms.

**Comment by iago-pssjd** [comment]
@vincentarelbundock Thanks! I was looking for some example illustrating how to use `glance_custom`, but I couldn't find. The 1 row data.frame output, what is supposed to be (column names)? And where and how should it be used?

**Comment by vincentarelbundock** [comment]
See https://modelsummary.com/articles/modelsummary.html#new-models-and-custom-statistics
