### ISSUE TITLE
datasummary N function

### ISSUE THREAD

**Issue by eweisbrod** [vincentarelbundock/modelsummary#656]
Can you please allow a "fmt" argument in the N function in datasummary?  I would like to be able to comma format the sample size. 

Something like this I think? 

```
#N function to handle format for N 
NN <- function(x, fmt = NULL, na.rm = TRUE, ...) {
  out <-  if (is.logical(x) && all(is.na(x))) {
    length(x)
    # number of non-missing observations
  } else {
    sum(!is.na(x))
  }
  out <- sanitize_fmt(fmt)(out, ...)
  return(out)
}

```
but for now I had to just do the below because my custom function couldn't access the internal formatting functions.
```
NN <- function(x) {
  out <-  if (is.logical(x) && all(is.na(x))) {
    length(x)
    # number of non-missing observations
  } else {
    sum(!is.na(x))
  }
  out <- formattable::comma(out, digits=0)
  return(out)
}

```
Hope it makes sense.

Thanks for all your work on the package!

**Comment by vincentarelbundock** [comment]
the `N()` function is supplied by the upstream `tables` package, and does not have a `fmt` argument. Fortunately, it is easy to override the built-in function to use custom formatting:


```{r}
tmp <- data.frame(X = sample(letters[1:3], 1e6, replace = TRUE))
N <- \(x) format(length(x), big.mark = ",")
datasummary(X ~ N, data = tmp)
```

**Comment by eweisbrod** [comment]
Thanks!!
