### ISSUE TITLE
Markdown exported with U+2007 Figure Space

### ISSUE THREAD

**Issue by leehach** [vincentarelbundock/modelsummary#657]
I'm using `modelsummary` to output a markdown table. When I use decimal alignment, the columns are all padded with Unicode character 2007 "figure space".

This creates problems if I then try to convert to PDF (via LaTeX) using pandoc. I get the following error.

```
! LaTeX Error: Unicode character   (U+2007)
               not set up for use with LaTeX.
```

I wouldn't call this a bug, as I assume it is the intended behavior, but is there any option that would allow me to change this behavior?

FWIW, I'm not sure that I see the benefit of using U+2007. Does this help with output to other formats like HTML?

**Comment by vincentarelbundock** [comment]
Thanks for the report. I just pushed a new commit. Can you try the latest version from GitHub?

**Comment by leehach** [comment]
This appears to work. All spaces in exported markdown file are now "regular" spaces, not U+2007 figure spaces.
