### ISSUE TITLE
Removing fixed effects using FEOLS

### ISSUE THREAD

**Issue by JakartaLaw** [vincentarelbundock/modelsummary#659]
If I want to remove a fixed effect (FE: year) it seems i cannot use coef_omit? What's the reason? how do i tackle the problem?

**Comment by vincentarelbundock** [comment]
`gof_omit` with the string in `get_gof()`

**Comment by vincentarelbundock** [comment]
For future reference:

``` r
library(fixest)
library(modelsummary)

mod <- feols(mpg ~ cyl + disp | carb, mtcars)

modelsummary(mod, "markdown", gof_omit = "FE")
```

|                |      (1) |
| :------------- | -------: |
| cyl            |  \-0.643 |
|                |  (0.408) |
| disp           |  \-0.027 |
|                |  (0.009) |
| Num.Obs.       |       32 |
| R2             |    0.799 |
| R2 Adj.        |    0.741 |
| R2 Within      |    0.639 |
| R2 Within Adj. |    0.608 |
| AIC            |    169.4 |
| BIC            |    181.1 |
| RMSE           |     2.66 |
| Std.Errors     | by: carb |
