### ISSUE TITLE
How to run Clustered standard error after running multinom() in R. I have pooled cross-section data from 2005 to 2021. Outcome variable has 5 classifications and independent variables are continuous and binary.

### ISSUE THREAD

**Issue by nikkiuuu** [vincentarelbundock/modelsummary#660]
Bug reports must include:

1. *Concise* description of the bug
2. *Minimal* reproducible example using publicly available data and the bare minimum code and libraries needed to reproduce the bug.
    - Consider using the `mtcars` dataset which is distributed by default with `R`, or one of the [CSV files from the RDatasets archive.](https://vincentarelbundock.github.io/Rdatasets/articles/data.html)
3. `sessionInfo()` output

Make sure you are running the *latest development version* of `modelsummary` and its dependencies: https://vincentarelbundock.github.io/modelsummary/#installation

**Comment by vincentarelbundock** [comment]
Is this model supported by the sandwich package? If not, must find a way to compute the variance covariance matrix yourself and pass that to the vcov argument.

**Comment by nikkiuuu** [comment]
The sanwich package does not work with the multinom. Do you know how to compute the variance-covariance matrix?

**Comment by vincentarelbundock** [comment]
I do not.
