### ISSUE TITLE
standard cluster error multinom() in r

### ISSUE THREAD

**Issue by nikkiuuu** [vincentarelbundock/modelsummary#661]
I am attempting to identify the appropriate code for calculating clustered standard errors following the execution of a regression using the multinom() function in r.

I attempted the following code but consistently encountered an error:

Calculate the cluster-robust variance-covariance matrix
vcov_clustered <- vcovCL(reg1, cluster = mtcars$cyl) Error in UseMethod("estfun") : no applicable method for 'estfun' applied to an object of class "c('multinom', 'nnet')"

**Comment by vincentarelbundock** [comment]
What is the difference between this issue and that one: https://github.com/vincentarelbundock/modelsummary/issues/660

I don't think clustered standard errors are available for this kind of model, either for the `sandwich` package of the `clubSandwich`. As is documented, `modelsummary` does not actually compute standard errors itself. It just displays them. Unless you can supply your own cluster-robust variance-covariance matrix, there is nothing I can do on the `modelsummary` side.
