### ISSUE TITLE
How to explain the regression results after using lrm() in r

### ISSUE THREAD

**Issue by nikkiuuu** [vincentarelbundock/modelsummary#662]
Hello, 

I am looking to explain the following regression results: 

lrm(formula = region_5 ~ relative_pt + relative_yt + 
    relative_ur + relative_cp data = df, x = T, y = T)

Frequencies of Responses

      1       2       3       4       5 
1403840    4428   15399    8098    4703 

                           Model Likelihood         Discrimination    Rank Discrim.    
                                 Ratio Test                Indexes          Indexes    
Obs         1436468    LR chi2    229115.98         R2       0.616    C       0.970    
max |deriv|   2e-09    d.f.              31    R2(31,1436468)0.147    Dxy     0.941    
                       Pr(> chi2)   <0.0001    R2(31,95675.4)0.909    gamma   0.942    
                                                    Brier    0.006    tau-a   0.042    

                            Coef     S.E.   Wald Z  Pr(>|Z|)
y>=2                        -20.5013 0.2182  -93.95 <0.0001 
y>=3                        -21.0916 0.2220  -95.00 <0.0001 
y>=4                        -23.4748 0.2368  -99.14 <0.0001 
y>=5                        -25.3832 0.2449 -103.63 <0.0001 
relative_pt                    1.9706 0.0251   78.41 <0.0001 
relative_yt                      0.4227 0.0089   47.54 <0.0001 
relative_ur                      1.3315 0.0778   17.12 <0.0001 
relative_cp                    0.1378 0.0031   44.74 <0.0001

**Comment by vincentarelbundock** [comment]
Is this a bug in modelsummary? This is the development website to report bugs and make feature requests. It is not a general statistics assistance website.
