### ISSUE TITLE
Warning about `All()` with labelled data should become irrelevant in the future

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/modelsummary#667]
Hi Vincent, just a small info that there was a bug fix in `tables` to allow labelled variables in `tabular` (related issue: https://github.com/dmurdoch/tables/issues/17). It is still only in the devel version for now, but I suppose that when the CRAN version is updated then this warning will become irrelevant:

https://github.com/vincentarelbundock/modelsummary/blob/64f1bc01ea5bc94277b542654e2ba23dfede3d55/R/sanity_checks.R#L277-L284

Of course, you can't do much about it for now. Example with devel version of `tables`:
``` r
library(modelsummary)

mtcars$mpg <- haven::labelled(mtcars$mpg, label = "miles per gallon")
f <- All(mtcars) ~ Mean + SD + Min + Median + Max
datasummary(f, mtcars)
#> Warning: 
#> It is not safe to use labelled data with the `All()` command in a datasummary()` formula.
#>  This warning appears once per session.
```

|                  |   Mean |     SD |   Min | Median |    Max |
|:-----------------|-------:|-------:|------:|-------:|-------:|
| miles per gallon |  20.09 |   6.03 | 10.40 |  19.20 |  33.90 |
| cyl              |   6.19 |   1.79 |  4.00 |   6.00 |   8.00 |
| disp             | 230.72 | 123.94 | 71.10 | 196.30 | 472.00 |
| hp               | 146.69 |  68.56 | 52.00 | 123.00 | 335.00 |
| drat             |   3.60 |   0.53 |  2.76 |   3.70 |   4.93 |
| wt               |   3.22 |   0.98 |  1.51 |   3.33 |   5.42 |
| qsec             |  17.85 |   1.79 | 14.50 |  17.71 |  22.90 |
| vs               |   0.44 |   0.50 |  0.00 |   0.00 |   1.00 |
| am               |   0.41 |   0.50 |  0.00 |   0.00 |   1.00 |
| gear             |   3.69 |   0.74 |  3.00 |   4.00 |   5.00 |
| carb             |   2.81 |   1.62 |  1.00 |   2.00 |   8.00 |

**Comment by vincentarelbundock** [comment]
Thanks for the note! 

The `tables` release schedule is pretty slow, so I'll leave this open until I see an update.

**Comment by vincentarelbundock** [comment]
Made the change already because this will soon becom obsolete, the warning was never critical, and I have time to do this now but may not in the future: 

2499b5567628a055c292bbc580576aca8a313199
