### ISSUE TITLE
datasummary: merging columns? 

### ISSUE THREAD

**Issue by akarlinsky** [vincentarelbundock/modelsummary#673]
Not sure if this is feature request or help request: I'd like to merge columns in datasumary.

For example, I have a descriptive stats table with Mean and SD, and instead of having one column for each, I'd like the Mean column to be Mean/(SD) i.e. Mean in first row and then a second row with SD in parentheses. Similar to how in modelsummary we have the coefficent and then in the same cell next row the SE in parentheses.

This is what it looks like now:

```
datasummary(mpg + cyl ~ N + Mean + SD, data = mtcars, output = "markdown")


|     |  N |  Mean |  SD  | 
|:----|---:|------:|-----:|
| mpg | 32 | 20.09 | 6.03 | 
| cyl | 32 |  6.19 | 1.79 | 
```

I'd like it to be:
![image](https://github.com/vincentarelbundock/modelsummary/assets/48435065/c031780f-e7fe-491b-bb87-d8186054d5ca)

**Comment by vincentarelbundock** [comment]
There may be a clever way to use formulas to achieve this, but I can't think of it now. You could always use `add_rows`; or output as data frame, reshape the data manually, and feed it to `datasummary_skim()`
