### ISSUE TITLE
MODEL SUMMARY FOR OOHBCHOICE

### ISSUE THREAD

**Issue by donaldkip77** [vincentarelbundock/modelsummary#674]
oohb1 <- oohbchoice(R1 + R2 ~ 1 | log(BL) + log(BH), data = oohbsyn)
oohb2 <- oohbchoice(R1 + R2 ~ age + gender | log(BL) + log(BH), data = oohbsyn)
modelsummary(oohb2)
I tried to extract model summary for this oohbchoice model. Could you please help
Error: `modelsummary could not extract the required information from a model of class   "oohbchoice". The package tried a sequence of 2 helper functions to extract estimates:      parameters::parameters(model)   broom::tidy(model)                                  
 
To draw a table, one of these commands must return a `data.frame` with a column named   "term". The `modelsummary` website explains how to summarize unsupported models or add   support for new models yourself:   https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html      These errors messages were generated during extraction:      `parameters::parameters(model)` did not return a valid data.frame. `broom::tidy(model)` did not return a valid data.frame. In addition: Warning message: `modelsummary could not extract goodness-of-fit statistics from a model of class "oohbchoice". The package tried a sequence of 2 helper functions:  performance::model performance(model) broom::glance(model)  One of these functions must return a one-row `data.frame`. 
As much as the `modelsummary` website explains how to summarize unsupported models or add support for new models yourself i am finding this difficult to create a command for this model could you please help.
 
  |

**Comment by vincentarelbundock** [comment]
As the error message says, this package is not supported by the upstream packages that `modelsummary` uses to extract information from models. For `modelsummary` to support these models, the `parameters` and `performance` packages would need to add support. You can open issues on the respective repositories of these packages. Please make sure that your example is minimal and reproducible: it should include all lines of code, including the initial `library()` call.

https://github.com/easystats/parameters

https://github.com/easystats/performance

**Comment by donaldkip77** [comment]
I have initiated the pull requests in the respective repositories of the above packages
https://github.com/easystats/performance/issues/637#issuecomment-1750301894
https://github.com/easystats/parameters/pull/908

**Comment by vincentarelbundock** [comment]
Thanks! I appreciate you took the time.

**Comment by strengejacke** [comment]
This works now, after updating the latest _insight_ and _performance_ (will be soon on CRAN, too).

```r
library(DCchoice)
data(oohbsyn)
m <- oohbchoice(R1 + R2 ~ age + gender | log(BL) + log(BH), data = oohbsyn)
modelsummary::modelsummary(m)
```

**Comment by vincentarelbundock** [comment]
awesome!
