### ISSUE TITLE
`ci_method` warnings in `modelplot`

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#682]
Hi!

I try including `ci_method = "wald"` argument in `modelplot`, as it is possible to do it in `modelsummary` and it is documented it is possible in the help of `modelplot`. However, I always get the warning
```r
Warning message:
In ggplot2::geom_pointrange(ggplot2::aes(y = term, x = estimate,  :
  Ignoring unknown parameters: `ci_method`
```

Thanks!

**Comment by iago-pssjd** [comment]
Ok! Thanks for the answer!

**Comment by vincentarelbundock** [comment]
@florence-laflamme,

Can you try to convert all calls to `...` in `R/modelplot.R` to `do.call()` with a filtered list of arguments.

You can read the discussion above, and then the discussion below I had with Chat-GPT. The suggested solution makes sense, I think.

[Note: This may (or may not) be a challenge. Let me know if you hit a wall and we can talk through the problem together.]


### My question to Chat-GPT

In R, one of my functions generates this warning:

Warning message:
In ggplot2::geom_pointrange(ggplot2::aes(y = term, x = estimate,  :
  Ignoring unknown parameters: `ci_method`

This is the code that generates this warning:

ggplot2::geom_pointrange(ggplot2::aes(y = model, x = estimate, xmin = conf.low, xmax = conf.high), ...)

How can I filter out arguments that I know are not valid by name, and then pass execute the function again without them to avoid raising the warning. Use do.call() and list().


### Chat-GPT's answer

To filter out invalid arguments by name before executing a function in R and thus avoid warnings like the one you're encountering, you can use a combination of `do.call()`, which allows you to call a function with a list of arguments, and some logic to filter the arguments based on their names. Here's a general approach:

1. Define your arguments in a list.
2. Remove the unwanted or unknown arguments from the list based on their names.
3. Use `do.call()` to call the function with the filtered list of arguments.

Here's how you can apply this approach to your specific case with `ggplot2::geom_pointrange()`:

```r
# Your original arguments including the invalid one 'ci_method'
args_list <- list(
  mapping = ggplot2::aes(y = model, x = estimate, xmin = conf.low, xmax = conf.high)
)
args_list <- c(args_list, list(...))

# Function to remove invalid arguments
remove_invalid_args <- function(args, valid_args) {
  # Filter out invalid arguments based on their names
  args[names(args) %in% valid_args]
}

# Define the valid argument names for geom_pointrange
# You can find these by looking at the documentation of the function
valid_args_geom_pointrange <- c("mapping", "data", "stat", "position", "na.rm", "show.legend", "inherit.aes", "xmin", "xmax", "y", "x", "color", "size", "linetype", "alpha", "shape", "fill", "width")

# Filter out invalid arguments from your list
filtered_args <- remove_invalid_args(args_list, valid_args_geom_pointrange)

# Use do.call to execute geom_pointrange with the filtered arguments
# Assuming 'ggplot_obj' is your ggplot object you want to add the geom to
ggplot_obj <- ggplot_obj + do.call(ggplot2::geom_pointrange, filtered_args)

# Plot
print(ggplot_obj)
```

In this example, `remove_invalid_args()` is a custom function that filters out arguments not present in the `valid_args_geom_pointrange` vector. You should replace `"some_value"` with whatever you were actually passing to `ci_method`, and `ggplot_obj` should be your ggplot object onto which you're trying to add the `geom_pointrange`.

Remember, this approach requires that you know beforehand which arguments are valid for the function you're calling. For `ggplot2::geom_pointrange()`, you can find the list of valid arguments in the function's documentation.

**Comment by vincentarelbundock** [comment]
@florence-laflamme, here's the Chat-GPT tutorial on ellipsis to pass arguments:

### GPT tutorial

Certainly! The ellipsis (`...`) in R is a powerful feature that allows you to pass arbitrary arguments from one function to another. This can be particularly useful when you're writing wrapper functions or when you need to pass along additional parameters to a function without explicitly naming all of them. Here's a simple tutorial with an example to demonstrate how to use ellipsis to pass unknown arbitrary arguments by name from one function to another.

### Objective

We'll create a wrapper function for the `plot()` function that allows us to pass arbitrary plotting parameters. Our wrapper function will be called `custom_plot()`, and it will add some custom behavior before calling the base `plot()` function with any additional arguments the user provides.

### Step 1: Define the Wrapper Function with Ellipsis

The `custom_plot()` function will take a fixed argument (`x`) and then use `...` to capture any number of additional arguments.

```r
custom_plot <- function(x, ...) {
  # Custom behavior (e.g., print a message)
  cat("Creating a custom plot...\n")
  
  # Call the base plot function, passing along any additional arguments
  plot(x, ...)
}
```

### Step 2: Using the Wrapper Function

Now, let's use our `custom_plot()` function to create a simple plot. We'll pass `x` as our data and use the ellipsis (`...`) to pass additional plotting parameters such as `type`, `col`, and `main` (for the plot type, color, and title, respectively).

```r
# Sample data
x <- 1:10
y <- x^2

# Create a plot using the custom wrapper function
custom_plot(x, y, type = "b", col = "red", main = "Custom Plot Example")
```

### How It Works

- **`custom_plot()` Functionality:** When `custom_plot()` is called, it first executes any custom behavior defined within it. In this example, it prints a message. Then, it calls the `plot()` function, passing along the `x` argument and any additional arguments it received via `...`.
  
- **Passing Additional Arguments:** The `...` in the `plot(x, ...)` call inside `custom_plot()` ensures that any extra arguments (e.g., `type = "b"`, `col = "red"`, `main = "Custom Plot Example"`) are passed directly to the `plot()` function. This means `custom_plot()` can flexibly support the same parameters as `plot()` without needing to explicitly define them all.

This example demonstrates the elegance and power of using `...` to write flexible functions in R. By leveraging ellipsis, you can create functions that are adaptable to a wide range of use cases without cluttering your code with numerous parameter definitions.

**Comment by vincentarelbundock** [comment]
Fixed in the dev version on github. Thanks again for the report!
