### ISSUE TITLE
New statistic request for `gof_map`: RSE or SER (Residual Standard Error or Standard Error of the Regression)

### ISSUE THREAD

**Issue by zekiakyol** [vincentarelbundock/modelsummary#690]
### Background

Firstly, thank you for this great package!

Today, I asked a question on stackoverflow <https://stackoverflow.com/questions/77652459/adding-residual-standard-errorstandard-error-of-the-regression-to-regression-o> to report Residual Standard Error in the regression table and I adapted the answer to the `performance` package.

I wonder whether we can add `rse` statistic to the `gof_map` so that we do not have to create `glance_custom.lm` in the following way:

```
glance_custom.lm <- function(x, ...) {
  rse <- performance::performance_rse(x)
  data.frame(RSE = format(rse, digits = 3))
}
```

--- 

### Expected Result without Creating `glance_custom.lm`

``` r
library(modelsummary)

reg1 <- lm(mpg ~ disp, data = mtcars)
summary(reg1)
#> 
#> Call:
#> lm(formula = mpg ~ disp, data = mtcars)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -4.8922 -2.2022 -0.9631  1.6272  7.2305 
#> 
#> Coefficients:
#>              Estimate Std. Error t value Pr(>|t|)    
#> (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
#> disp        -0.041215   0.004712  -8.747 9.38e-10 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 3.251 on 30 degrees of freedom
#> Multiple R-squared:  0.7183, Adjusted R-squared:  0.709 
#> F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10


modelsummary(reg1, output = "markdown")
```

|             |   \(1\) |
|:------------|--------:|
| (Intercept) |  29.600 |
|             | (1.230) |
| disp        |  -0.041 |
|             | (0.005) |
| Num.Obs.    |      32 |
| R2          |   0.718 |
| R2 Adj.     |   0.709 |
| AIC         |   170.2 |
| BIC         |   174.6 |
| Log.Lik.    | -82.105 |
| F           |  76.513 |
| RMSE        |    3.15 |
| RSE         |   3.25  |

**Comment by vincentarelbundock** [comment]
Thanks for the question. `modelsummary` returns all the metrics returned by `performance::model_performance()`, so including this statistic in the default output is something that should be requested upstream in that package: https://github.com/easystats/performance/
