### ISSUE TITLE
LaTeX Output Distorted when Setting "shape" Option with "align"

### ISSUE THREAD

**Issue by tedihsin** [vincentarelbundock/modelsummary#702]
Latex code is not generated correctly when the shape and alitgn options are set as follows:

R
```{r}
library(tidyverse)

res <- lm(displ ~ cty + hwy, mpg)

modelsummary::modelsummary(
  res,
  output = "kableExtra",
  shape = term ~ model + statistic,
  align = "ldd",
)
```

Latex code from above
> \begin{table}
> \centering
> \begin{tabular}[t]{ldd}
> \toprule
> \multicolumn{1}{c}{ } & \multicolumn{2}{c}{\{(1)} \\
> \cmidrule(l{3pt}r{3pt}){2-3}
>   & Est.} & S.E.}\\
> \midrule
> (Intercept) & 7.565 & 0.211\\
> cty & -0.233 & 0.041\\
> hwy & -0.007 & 0.029\\
> \midrule\\
> Num.Obs. & 234 & {}\\
> R2 & 0.638 & {}\\
> R2 Adj. & 0.635 & {}\\
> AIC & 553.4 & {}\\
> BIC & 567.2 & {}\\
> Log.Lik. & -272.676 & {}\\
> F & 203.319 & {}\\
> RMSE & 0.78 & {}\\
> \bottomrule
> \end{tabular}
> \end{table}

Error message of LaTex

> ! Extra }, or forgotten $.
> l.178   & Est.}
>                 & S.E.}\\ 

On a separate note, is it possible to change labels such as "Est." or "S.E." for this format?

**Comment by vincentarelbundock** [comment]
Sorry for the delay, I dropped the ball on this one.

This is fixed on Github, but note that the next version will use `tinytable` as a default table-drawing backend, rather than `kableExtra`.

I also opened a separate issue for customization of statistics when in wide format. I'm not exactly sure what a good user interface would be here, but I'll think about it.

Thanks!

https://github.com/vincentarelbundock/modelsummary/issues/717

**Comment by vincentarelbundock** [comment]
@tedihsin

**Comment by vincentarelbundock** [comment]
@tedihsin Renaming columns is now possible in the dev version from Github. Thanks for raising the issue. Example:

https://modelsummary.com/vignettes/modelsummary.html#renaming-estimates-and-statistics

**Comment by vincentarelbundock** [comment]
@tedihsin Renaming columns is now possible in the dev version from Github. Thanks for raising the issue. Example:

https://modelsummary.com/vignettes/modelsummary.html#renaming-estimates-and-statistics
