### ISSUE TITLE
Separation between coefficients and model statistics when using add_rows

### ISSUE THREAD

**Issue by toshifumikuroda** [vincentarelbundock/modelsummary#712]
Hi, I am thinking about how to add the Randomization inference p-values in the table of modelsummary.

Because add_rows do not care about the additional coefficient stats, adding rows in the table lets the added statistic below the delimiter line for the model statistic.

The sample code is the following. (Of course, each RI(p) is calculated by other packages like RI2 or ritest per coefficients)
```
models <- list()
models[['OLS']] <- lm(mpg ~ factor(cyl), mtcars)
models[['Logit']] <- glm(am ~ factor(cyl), mtcars, family = binomial)
rows <- tribble(~term,          ~OLS,  ~Logit,
                'RI(p)', '{pval}',   '{pval}',
                'RI(p)', '{pval}',   '{pval}'
)
attr(rows, 'position') <- c(3, 6)

modelsummary(
  models, 
  coef_map = c(
    "factor(cyl)6" = "cyl 6",
    "factor(cyl)8" = "cyl 8"
  ),
  add_rows = rows
  )
```

My one bad practice is keeping some other row in the bottom of coefficient.
The sample code is the following. 
```
attr(rows, 'position') <- c(3, 6, 10)

modelsummary(
  models, 
  coef_map = c(
    "factor(cyl)6" = "cyl 6",
    "factor(cyl)8" = "cyl 8",
    '(Intercept)' = 'Constant'
  ),
  add_rows = rows
)
```
However, I want to show only the coefficients which have RI(p). Is there any other way to add the coefficient stat in the table?
Thank you,
Toshifumi

**Comment by vincentarelbundock** [comment]
Use tidy_custom(). I wrote a whole tutorial about this here: https://modelsummary.com/vignettes/modelsummary_extension.html
