### ISSUE TITLE
tidy_custom and glance_custom not working as expected?

### ISSUE THREAD

**Issue by acoppock** [vincentarelbundock/modelsummary#714]
I'm trying to use modelsummary with output from the `robu` package, but I can't seem to get the custom tidier and glance functions to work with modelsummary just right. Any help much appreciated!

```
library(robumeta)
library(modelsummary)
library(tidyverse)

# make fake data
dat <- 
  tibble(
    studynum = rep(LETTERS[1:5], each = 10),
    estimate = runif(50, min = 0, max = 1),
    var.eff.size = runif(50, min = 0.5, max = 1)
  ) |> 
  as.data.frame()


# estimate model
fit <- robu(estimate ~ 1, studynum = studynum,
            var.eff.size = var.eff.size, modelweights = "HIER", data = dat)

# define custom tidy and glance functions
tidy_custom.robu <- function(x, ...) {
  x$reg_table |>
    as_tibble() |>
    rename(
      term = labels,
      estimate = b.r,
      std.error = SE,
      statistic = t,
      df = dfs,
      p.value = prob,
      conf.low = CI.L,
      conf.high = CI.U
    ) |>
    select(-sig) |> 
    as.data.frame()
}

glance_custom.robu <- function(x, ...) {
  out <- data.frame("DV" = "TEST")
  return(out)
}

# works
tidy_custom(fit_1)
# works
glance_custom(fit_1)
# Doesn't work!
modelsummary(fit_1)
```

**Comment by vincentarelbundock** [comment]
Looks like `robumeta` is not supported at all by `broom` or `parameters`, the two packages that `modelsummary` can use to extract information from a model object. `tidy_custom()` is used when there already exists an extractor for the particularly model, to *customize* the results. In this case, you don't want to customize, you want to create the extractor from scratch.

Good news: You can just rename your two functions `glance.robu` and `tidy.robu`. On my computer, this seems to work.

**Comment by acoppock** [comment]
wow mine too! (though i'd tried that combination, but thanks for the quick response!)
