### ISSUE TITLE
`shape`: Customize labels for statistics (ex: Est. Std.Error, etc.)

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#717]
Proposed syntax:

```r
library(tidyverse)

res <- lm(displ ~ cty + hwy, mpg)

modelsummary::modelsummary(
  res,
  statistic = c("SE" = "std.error", "p value" = "p.value", "Custom stat" = "{std.error}({p.value})"),
  shape = term ~ model + statistic,
  align = "ldd",
)
```

Maybe we can then pass the `statistic` named vector to `shape_estimate`, check if the vector is named, rename the columns if appropriate, and get this feature with little effort.

**Comment by vincentarelbundock** [comment]
Renaming columns is now possible in the dev version from Github. Thanks for raising the issue. Example:

https://modelsummary.com/vignettes/modelsummary.html#renaming-estimates-and-statistics

**Comment by tedihsin** [comment]
@vincentarelbundock 

Thank you for implementing Custom labels. It's great.
I found one issue and would like to report it.

It seems that when glue format is set to estimate, Custom labels are not reflected. This becomes a problem when we want to set stars parameters to change the format or threshold of stars, but we also want to display stars in statistic.

When setting "estimate" to the estimate option, Custom labelsl is set.

``` r
m1 <- lm(Sepal.Length ~ Sepal.Width + Petal.Length + Petal.Width, data = iris)

modelsummary::modelsummary(
  m1,
  estimate = c("EST_Custom" = "estimate"),
  statistic = c("STAT_Custom" = "({std.error}){stars}"),
  stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
  shape = term ~ model + statistic
)
```

<table style="width:58%;">
<colgroup>
<col style="width: 20%" />
<col style="width: 18%" />
<col style="width: 19%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th colspan="2"><ol type="1">
<li></li>
</ol></th>
</tr>
<tr class="odd">
<th></th>
<th>EST_Custom</th>
<th>STAT_Custom</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>1.856***</td>
<td>(0.251)***</td>
</tr>
<tr class="even">
<td>Sepal.Width</td>
<td>0.651***</td>
<td>(0.067)***</td>
</tr>
<tr class="odd">
<td>Petal.Length</td>
<td>0.709***</td>
<td>(0.057)***</td>
</tr>
<tr class="even">
<td>Petal.Width</td>
<td>-0.556***</td>
<td>(0.128)***</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td>150</td>
<td></td>
</tr>
<tr class="even">
<td>R2</td>
<td>0.859</td>
<td></td>
</tr>
<tr class="odd">
<td>R2 Adj.</td>
<td>0.856</td>
<td></td>
</tr>
<tr class="even">
<td>AIC</td>
<td>84.6</td>
<td></td>
</tr>
<tr class="odd">
<td>BIC</td>
<td>99.7</td>
<td></td>
</tr>
<tr class="even">
<td>Log.Lik.</td>
<td>-37.321</td>
<td></td>
</tr>
<tr class="odd">
<td>F</td>
<td>295.539</td>
<td></td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>0.31</td>
<td></td>
</tr>
</tbody>
</table>


When setting "{estimate}" that is glue format to the estimate option, Custom labelsl is not set. Label is the default "Est.".

``` r

modelsummary::modelsummary(
  m1,
  estimate = c("EST_Custom" = "{estimate}"),
  statistic = c("STAT_Custom" = "({std.error}){stars}"),
  stars = c("*" = 0.1, "**" = 0.05, "***" = 0.01),
  shape = term ~ model + statistic
)
```

<table style="width:54%;">
<colgroup>
<col style="width: 20%" />
<col style="width: 13%" />
<col style="width: 19%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th colspan="2"><ol type="1">
<li></li>
</ol></th>
</tr>
<tr class="odd">
<th></th>
<th>Est.</th>
<th>STAT_Custom</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>1.856</td>
<td>(0.251)***</td>
</tr>
<tr class="even">
<td>Sepal.Width</td>
<td>0.651</td>
<td>(0.067)***</td>
</tr>
<tr class="odd">
<td>Petal.Length</td>
<td>0.709</td>
<td>(0.057)***</td>
</tr>
<tr class="even">
<td>Petal.Width</td>
<td>-0.556</td>
<td>(0.128)***</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td>150</td>
<td></td>
</tr>
<tr class="even">
<td>R2</td>
<td>0.859</td>
<td></td>
</tr>
<tr class="odd">
<td>R2 Adj.</td>
<td>0.856</td>
<td></td>
</tr>
<tr class="even">
<td>AIC</td>
<td>84.6</td>
<td></td>
</tr>
<tr class="odd">
<td>BIC</td>
<td>99.7</td>
<td></td>
</tr>
<tr class="even">
<td>Log.Lik.</td>
<td>-37.321</td>
<td></td>
</tr>
<tr class="odd">
<td>F</td>
<td>295.539</td>
<td></td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>0.31</td>
<td></td>
</tr>
</tbody>
</table>

<sup>Created on 2024-04-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
