### ISSUE TITLE
Format detection in Quarto document wrongly choose word

### ISSUE THREAD

**Issue by cderv** [vincentarelbundock/modelsummary#721]
This was reported first in 
* https://github.com/quarto-dev/quarto-cli/issues/9040

This specific issue above won't probably happen again as it seems you are now always using **tinytable** as a default when guessing format, but I do think this will only hide the problem. 

I am opening this issue to raise concerns about how formats are detected 
https://github.com/vincentarelbundock/modelsummary/blob/98778c909b58d36a4c807833fba8767dc883e028/R/sanitize_output.R#L146-L149

`knitr::pandoc_to()` should be the only thing needed to check the format output in R Markdown or Quarto rendering. If there is a case where value is not correct, then this is an issue on R Markdown, Quarto, or **knitr**.  Looking at the metadata field written in the header document is not considered safe. 

I am talking about this part 
https://github.com/vincentarelbundock/modelsummary/blob/98778c909b58d36a4c807833fba8767dc883e028/R/sanitize_output.R#L145-L171

when `docx` is present in `format`, `word` will always be chosen as the output format no matter the real output format (which is set in `knitr::pandoc_to()`)

To provide you with an example of what I think it caused by this behavior, I found while debugging, here is a qmd document. 

* Setting **flextable** as a default
* But getting **tinytable** because `word` is found as `output_format`, 
	* `output_factory <- factory_dict[[output_format]]` will result to `tinytable` (`word = get_factory_name("word", default = "tinytable")`) 
	*  which will trigger a new call to `knitr::pandoc_to()` fixing the output_format to Latex
	* https://github.com/vincentarelbundock/modelsummary/blob/98778c909b58d36a4c807833fba8767dc883e028/R/sanitize_output.R#L193-L199

````markdown
---
format:
  docx: default
  pdf: default
keep-md: true
---

```{r}
#| include: false
library(modelsummary)
```


```{r}
modelsummary::config_modelsummary("flextable")
modelsummary:::sanitize_output("default")
modelsummary:::settings_get("output_factory")
modelsummary:::settings_get("output_format")
modelsummary:::settings_get("output_file")
```
````

* Rendering with Quarto to pdf will result in

![image](https://github.com/vincentarelbundock/modelsummary/assets/6791940/2c61a94f-657c-4340-a7b0-febb66062cf5)

which shows incorrect behavior, I believe. 

This will be the same if trying to set `config_modelsummary(factory_default = 'kableExtra')` but `docx` is present in `format`. `word` will be identified as `output_format` and so `tinytable` will be used 

another example rendering to `docx` now with the above doc just setting to `kableExtra` as default 
![image](https://github.com/vincentarelbundock/modelsummary/assets/6791940/6e76b898-cbb2-4ad1-8477-992e9d37538b)

Hope this helps improve.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the detailed report and investigation. I appreciate it.

I will switch to your recommended solution in the next release.

And sorry my bad code gave you work!

**Comment by cderv** [comment]
Sure no problem - Happy I can help ! 

If you have any question about Quarto and its Table support - please to not hesitate to ping me. 

For the context, a major difference with R Markdown is that Quarto can parse HTML tables (https://quarto.org/docs/authoring/tables.html#html-tables) and has improved rendering for mardown tables, in multiple formats. 

R has a lot of packages that will handle writing to output in raw code, so it can sometimes create conflicts. R packages needs to be aware of quarto context sometimes to do the right thing.

**Comment by vincentarelbundock** [comment]
Yep yep, thanks. In `tinytable` I use this when I need to apply custom styles to an HTML table: `<table data-quarto-disable-processing="true">`

**Comment by vincentarelbundock** [comment]
I believe this is now fixed on Github. I took advantage of the opportunity to refactor `sanitize_output()`, which was a horrrrrible mess.

Thanks again.
