### ISSUE TITLE
datasummary() way to handle/ ignore missing values for factor levels when calculating percentages?

### ISSUE THREAD

**Issue by ylvaandersson** [vincentarelbundock/modelsummary#724]
Hello, first of all, thanks for a fantastic package! 

I have one issue that I've tried my best to find a way around without much success: I would like to make a summary table of counts/ percentages of each level for a factor variable. My issue is that some of my variables have missing values which I want to ignore when calculating percentages for that variable. The datasummary Percent() default calculation appears to always include the total number of observations in the denominator for calculating percentages. There does not seem to be a way to manually handle missing factor levels. It would be great if there was an option to (i) calculate the percentage as a fraction of the total and (ii) as a fraction of the number of valid responses. A workaround I've been doing now is to omit NA observations for each variable before calculating the percentage, and then merge back together, but it becomes tedious with a lot of variables.

Code below illustrates difference in how datasummary and e.g., tbl_summary handles missing values for factor levels when calculating percentages

```r
library(modelsummary)

dat <- data.frame(z = c(0,0,1,0,NA,0,1))

prop.table(table(dat))
# z
#         0         1 
# 0.6666667 0.3333333

datasummary(Factor(z) ~ N + Percent(), data = dat)
```

| z   | N   | Percent |
|-----|-----|---------|
| 0   | 4   | 57.14   |
| 1   | 2   | 28.57   |

Edit by VAB with a simpler example.

**Comment by vincentarelbundock** [comment]
Here's a potential workaround:

```{r}
library(modelsummary)

x <- data.frame(y = factor(c(0,0,1,0,NA,0,1), exclude = NULL))

datasummary(Factor(y) ~ N + Percent("col") * Heading("Pct") * complete.cases(x), data = x)
```

**Comment by vincentarelbundock** [comment]
sorry, i thought I had a solution but didn't. will try some things.

**Comment by vincentarelbundock** [comment]
OK, here’s a working trick. Supply a boolean index to the `Percent` function:

``` r
library(modelsummary)

dat <- data.frame(z = c(0,0,1,0,NA,0,1))

datasummary(Factor(z) ~ N + Percent(), data = dat)
```

| z   | N   | Percent |
|-----|-----|---------|
| 0   | 4   | 57.14   |
| 1   | 2   | 28.57   |

``` r

datasummary(Factor(z) ~ N + Percent(!is.na(dat$z)), data = dat)
```

| z   | N   | Percent |
|-----|-----|---------|
| 0   | 4   | 66.67   |
| 1   | 2   | 33.33   |

**Comment by ylvaandersson** [comment]
Thanks a mill for looking into this! And apologies, I should have made my example match my actual data a bit better. I suppose the issue with this solution is that it requires having to specify on a variable by variable basis which values to use for the denominator. I hope below illustrates a bit better: 

```
library(modelsummary)

dat <- data.frame(x = c(0,0,1,0,NA,0,1),
y = c(0,0,NA,0,NA,0,1),
z = c(NA,0,NA,0,1,0,1)
)
```

```
prop.table(table(dat$x))
#
#         0         1 
# 0.6666667 0.3333333

prop.table(table(dat$y))
#
#         0         1 
#0.8 0.2 

prop.table(table(dat$z))
#
#         0         1 
#0.6 0.4 
```

`datasummary(Factor(x) +Factor(y)+Factor(z) ~ N + Percent(), data = dat)`


  |   | N | Percent
-- | -- | -- | --
x | 0 | 4 | 57.14
  | 1 | 2 | 28.57
y | 0 | 4 | 57.14
  | 1 | 1 | 14.29
z | 0 | 3 | 42.86
  | 1 | 2 | 28.57

**Comment by vincentarelbundock** [comment]
Yes, I know it's not convenient, but I can't think of an alternative right now. As is documented, the formula interface is actually supplied by the `tables` package. `datasummary()` is just a convenience wrapper around it. You may want to look at their documentation:

https://cran.r-project.org/web/packages/tables/vignettes/tables.pdf

**Comment by ylvaandersson** [comment]
Ah, I see, thanks anyway! Will look into this and see if I can find some solution

**Comment by vincentarelbundock** [comment]
Let me know if you do. I'm very curious!

**Comment by ylvaandersson** [comment]
OK!! not the cleanest solution but found a workaround by multiplying each term with na.omit()
```
library(modelsummary)

dat <- data.frame(x = c(0,0,1,0,NA,0,1),
y = c(0,0,NA,0,NA,0,1),
z = c(NA,0,NA,0,1,0,1)
)

prop.table(table(dat$x))
#
#       0         1 
# 0.6666667 0.3333333 

prop.table(table(dat$y))
#
#       0         1 
# 0.8 0.2

prop.table(table(dat$z))
#
#       0         1 
# 0.6 0.4 
```
`datasummary(na.omit(dat$x)*(Factor(x)) + na.omit(dat$y)*(Factor(y)) + na.omit(dat$z)*(Factor(z)) ~ N + Percent(), data = dat)`

  |   |   | N | Percent
-- | -- | -- | -- | --
  | x | 0 | 4 | 66.67
  |   | 1 | 1 | 33.33
  | y | 0 | 3 | 80.00
  |   | 1 | 0 | 20.00
  | z | 0 | 2 | 60.00
  |   | 1 | 1 | 40.00
