### ISSUE TITLE
Headers are not printed if shape = "rbind" is used

### ISSUE THREAD

**Issue by MarcoPortmann** [vincentarelbundock/modelsummary#725]
It seems that panel headers are not printed using the latest developer version of modelsummary.

The following code results in the table attached below:
```r
gm <- c("r.squared", "nobs", "rmse")

panels <- list(
  list(
    lm(mpg ~ 1, data = mtcars),
    lm(mpg ~ qsec, data = mtcars)
  ),
  list(
    lm(hp ~ 1, data = mtcars),
    lm(hp ~ qsec, data = mtcars)
  )
)

modelsummary(
  panels,
  shape = "rbind",
  gof_map = gm)
```
![image](https://github.com/vincentarelbundock/modelsummary/assets/7468121/29496079-aa76-4c8e-8ce3-7d2d35252108)

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report! I think this should now be fixed in the development version on Github.
