### ISSUE TITLE
escape=FALSE ignored for output="latex_tabular/latex"

### ISSUE THREAD

**Issue by adamaltmejd** [vincentarelbundock/modelsummary#740]
Hey! Thanks for a great package! Although I'm loving tinytable, for my old code I'm now trying fix all the stuff that 2.0 broke for me :). I'm using latex_tabular with siunitx (first row is \begin{tabular}[S[table-format=....] so had to use lots of regex to change it back), but I think I also found a bug with escape=FALSE still escaping backslashes and curly braces. Using latest Github version of modelsummary.

```
library(modelsummary)
library(data.table)
tbl <- data.table("a"=c(1,2,3), "{}" = c(4,"\\times 5",6))
```

```
> datasummary_df(tbl, output = "latex_tabular", escape = TRUE)
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=l,},
}                     %% tabularray inner close
\toprule
a & \{\} \\ \midrule %% TinyTableHeader
\num{1.00} & 4                        \\
\num{2.00} & \textbackslash{}times 5 \\
\num{3.00} & 6                        \\
\bottomrule
\end{tblr} 
```

```
> datasummary_df(tbl, output = "latex_tabular", escape = FALSE)
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=l,},
}                     %% tabularray inner close
\toprule
a & \{\} \\ \midrule %% TinyTableHeader
\num{1.00} & 4                        \\
\num{2.00} & \textbackslash{}times 5 \\
\num{3.00} & 6                        \\
\bottomrule
\end{tblr} 
```

**Comment by adamaltmejd** [comment]
And a quick follow-up; how do I ensure output is using kableExtra when output="latex_tabular". Setting `options("modelsummary_factory_default" = "kableExtra")` does not matter.

**Comment by vincentarelbundock** [comment]
Aww, sorry to hear that! I was really hoping that `options()` and `config_modelsummary()` would be sufficient for most people.

Yep, you found a bug in `datasummary_df()`. Should be fixed on Github now. 

For that, I would do:

```{r}
library(modelsummary)
library(data.table)
tbl <- data.table("a"=c(1,2,3), "{}" = c(4,"\\times 5",6))

options(modelsummary_factory_default = "latex_tabular")
options(modelsummary_factory_latex_tabular = "kableExtra")

datasummary_df(tbl)
```

**Comment by adamaltmejd** [comment]
Hehe completely got myself to blame for doing too much messy customization :). Nothing a bit of regexp can't solve though :).

Thanks! Had missed "modelsummary_factory_latex_tabular".
