### ISSUE TITLE
Large tinytables

### ISSUE THREAD

**Issue by MarcoPortmann** [vincentarelbundock/modelsummary#742]
I have model summaries with 15 models with 2 coefficients each and 3 GOFs (5 models next to each other and 3 panels) that are around 400 MB in size. With summaries of quantreg::rq regressions, I have even obtained tables that are several GB in size. I couldn't quite work out where this came from. My first guess was that the models' data is saved as an attribute of the modelsummary-ouptut. I was able to reduce the `object.size` by deleting `lazy_style`. 

I'm also not quite sure how to provide a good, reproducible example. The `lm` and `rq` I ran are based on a large dataset that I can't provide.

**Comment by vincentarelbundock** [comment]
hard to diagnose without an example. What happens if you try with the version in this PR?

https://github.com/vincentarelbundock/modelsummary/pull/743

**Comment by MarcoPortmann** [comment]
> hard to diagnose without an example. What happens if you try with the version in this PR?
> 
> #743

This doesn't have an effect on the size of the table. However, If I run this code after `modelsummary`

```r

attr(out_table, "lazy_style") <- list()
```

it reduces the size.

**Comment by vincentarelbundock** [comment]
Weird. I'm stumped. Don't know.

Could you send me the big models by email?

**Comment by MarcoPortmann** [comment]
I cannot send the original data due to data protection reasons. But I think, I have some test code, that could help:

```r
library(tidyverse)
library(modelsummary)
library(tinytable)

utils::data(trees)
# dataset size doesn't have an effect on the modelsummary size
trees2 <- do.call(rbind, replicate(10, trees, simplify = FALSE))


models <- list()
models[['Bivariate']] <- lm(Girth ~ Height, data = trees2)
models[['Multivariate']] <- lm(Girth ~ Height + Volume, data = trees2)


# simple table

test <- modelsummary(models)

models2 <- list(a = models,
                b = models)

test2 <- modelsummary(models2, shape = "rbind")
test3 <- modelsummary(models2, shape = "cbind")



other_vars <- data.frame("text", t(rep("$\\checkmark$", times = 2)))
other_vars <- rbind(other_vars, other_vars)
attr(other_vars, "position") <- c(3 * 2 + 1, 3 * 2 + 16)

test4 <- modelsummary(models2, shape = "rbind", add_rows = other_vars)




other_vars <- data.frame("text", t(rep("$\\checkmark$", times = 4)))
attr(other_vars, "position") <- c(3 * 2 + 1)

test5 <- modelsummary(models2, shape = "cbind", add_rows = other_vars) 

test6 <- test5 %>% 
  theme_tt("resize", direction = "down")


test7 <- modelsummary(models2, shape = "cbind",
                      title = "Title",
                      stars = TRUE,
                      add_rows = other_vars) %>% 
  theme_tt("resize", direction = "down")




library(quantreg)
modelsrq <- list()
modelsrq[['Bivariate']] <- rq(Girth ~ Height, data = trees2, tau = 0.5)
modelsrq[['Multivariate']] <- rq(Girth ~ Height + Volume, data = trees2, tau = 0.5)


modelsrq2 <- list(a = modelsrq,
                  b = modelsrq)

test8 <- modelsummary(modelsrq2, shape = "cbind",
                      title = "Title",
                      stars = TRUE,
                      add_rows = other_vars) %>% 
  theme_tt("resize", direction = "down")



modelsrq3 <- modelsrq
modelsrq3[['Bivariate2']] <- rq(Girth ~ Height, data = trees2, tau = 0.5)
modelsrq3[['Multivariate2']] <- rq(Girth ~ Height + Volume, data = trees2, tau = 0.5)

modelsrq4 <- list(a = modelsrq3,
                  b = modelsrq3)

test9 <- modelsummary(modelsrq4, shape = "cbind"
                      ) %>% 
  theme_tt("resize", direction = "down")
```

The number of columns and `theme_tt` seem to be the drivers. `test9` is 778 MB heavy.

**Comment by vincentarelbundock** [comment]
Thanks, that's very helpful.

Could you install `tinytable` 0.2.1.5 from Github, restart `R`, completely, and try again?

**Comment by MarcoPortmann** [comment]
I tried `tinytable` 0.2.1.5 and everything is fine. Thank you for fixing this bug!
