### ISSUE TITLE
Splitting term category into term and term-value?

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#746]
I have just discovered in https://modelsummary.com/vignettes/modelsummary.html#formula the feature
> We can combine the `term` and group identifier columns by inserting an interaction colon `:` instead of the `+` in the formula:

Would it be possible the opposite feature, so for example for 
```r
datlab <- mtcars
datlab$cyl <- factor(datlab$cyl)
attr(datlab$cyl, "label") <- "Cylinders"
attr(datlab$am, "label") <- "Transmission"
modlab <- lm(mpg ~ cyl + am, data = datlab)
modelsummary(modlab, coef_rename = TRUE)
```
`Cylinders` and the other terms would appear in a column, but the factor values `[6]` and `[8]` would appear in another column?

**Comment by vincentarelbundock** [comment]
No, sorry, I won't implement this.

I would consider a code contribution, but if someone wants to contribute this, they should open an issue and discuss in very specific terms how they plan to implement this, because I'm not convinced this will be easy or generate a good user interface.
