### ISSUE TITLE
FR: allow `coef_rename` and `coef_map` simultaneous use when `coef_rename = TRUE`

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#747]
If `coef_rename = TRUE`, I am asking just for using label attribute of the corresponding variables, then `coef_map` should be allowed to reorder the variables.

Thanks!

**Comment by iago-pssjd** [comment]
I do, but I get
```r
Error in sanity_coef(coef_map, coef_rename, coef_omit) : 
  coef_map and coef_rename cannot be used together.
```

**Comment by vincentarelbundock** [comment]
Thanks for the report. Should be fixed now on Github.

**Comment by iago-pssjd** [comment]
Dear @vincentarelbundock,

I also tested this just now. I see it works, however, when the variables are factors, in `coef_map` one has to specify each value of the factor.  See again this example screenshot

![image](https://github.com/vincentarelbundock/modelsummary/assets/40892925/08bdee33-b795-41e9-b7f2-cd6dea0ae843)

One must specify in `coef_map`, `"Age [from31to40]"` and all others  `ageL` categories. 

It would be better if one could specify just the variable label (e.g. `Age`) or even better the variable name (`ageL`). Would some of these options be possible?

Thanks a lot!

**Comment by vincentarelbundock** [comment]
I can't think of an easy way to implement this right now, unfortuantely.
