### ISSUE TITLE
Default Table Making Package

### ISSUE THREAD

**Issue by cmschiller** [vincentarelbundock/modelsummary#756]
Hi Vincent,
it took me a long time to figure out that the default table-making package for 'latex' and 'latex_tabular' output apparently changed to something that's not compatible with kableExtra (broke my existing code). It would be nice to remark that somewhere on the package website under the "output" section where it currently says "kableExtra: set output to your destination format (e.g., “latex”, “html”, “markdown”), post-process your table, and use kableExtra::save_kable() function." 

Thank you!
Christoph

**Comment by vincentarelbundock** [comment]
Every time a user loads the package this message is printed:

```r
> library(modelsummary)

`modelsummary` 2.0.0 now uses `tinytable` as its default table-drawing backend.
  Learn more at: https://vincentarelbundock.github.io/tinytable/

Revert to `kableExtra` for one session:

  options(modelsummary_factory_default = 'kableExtra')

Change the default backend persistently:

  config_modelsummary(factory_default = 'gt')

Silence this message forever:

  config_modelsummary(startup_message = FALSE)
```

The breaking change was also noted prominently in `NEWS.md`

https://modelsummary.com/NEWS.html#section
