### ISSUE TITLE
stars for did package MP objects

### ISSUE THREAD

**Issue by baarthur** [vincentarelbundock/modelsummary#758]
Hi Vincent,

I would like to know if it is possible to include significance stars for MP objects generated by the `did` package.

The main challenge is that they do not supply p-values; however, `att_gt()` and `aggte()`both print stars based on the confidence interval (which depends on `alp`, the significance parameter, which defaults to 5%).

Maybe this could be done by adding notes in the `(i,j)` pairs, I wouldn't know how to do this, that's the only option I've thought of:

```
tab <- aggregate(mpg ~ cyl + am, FUN = mean, data = mtcars)
tab <- tab[order(tab$cyl, tab$am),]

tt(
  tab, digits = 2,
  notes = list(a = list(i = 1, j = 2, text = "Significant at 5%"), 
               b = list(i = c(3,5), j = 3, text = "Significant at 5%"))
) %>% 
style_tt(i = c(1, 3, 5), j = 1, rowspan = 2, alignv = "t")
```

**Comment by vincentarelbundock** [comment]
this would need to be supported in the upstream `parameters` package: https://github.com/easystats/parameters
