### ISSUE TITLE
Missing example for `gof_map` list of lists method in `modelsummary()` documentation

### ISSUE THREAD

**Issue by mccarthy-m-g** [vincentarelbundock/modelsummary#767]
The documentation for the `gof_map` argument of `modelsummary()` states that there should be an example for the "list of lists" value method, but there is no example for this in the examples section.

>gof_map: rename, reorder, and omit goodness-of-fit statistics and other model information. This argument accepts 4 types of values:
>- NULL (default): the modelsummary::gof_map dictionary is used for formatting, and all unknown statistic are included.
>- character vector: "all", "none", or a vector of statistics such as c("rmse", "nobs", "r.squared"). Elements correspond to colnames in the data.frame produced by get_gof(model). The modelsummary::gof_map default dictionary is used to format and rename statistics.
>- NA: excludes all statistics from the bottom part of the table.
>- data.frame with 3 columns named "raw", "clean", "fmt". Unknown statistics are omitted. See the 'Examples' section below. The fmt column in this data frame only accepts integers. For more flexibility, use a list of lists, as described in the next bullet.
>- **list of lists, each of which includes 3 elements named "raw", "clean", "fmt". Unknown statistics are omitted. See the 'Examples section below'.**

**Comment by vincentarelbundock** [comment]
You're right, there should probably be an example. FYI, there's an example in the gof_map section of this page: https://modelsummary.com/vignettes/modelsummary.html

**Comment by vincentarelbundock** [comment]
i added an example
