### ISSUE TITLE
[Feature request] Add ability to show the label of a factor variable on a seperate row and also show the base level of factors.

### ISSUE THREAD

**Issue by ami-null** [vincentarelbundock/modelsummary#770]
Is it possible to show the variable name of factor variables on a separate row and also show the base level of factor variables (output from `{gtsummary}` added for reference)?

``` r
mtcars$gear <- factor(mtcars$gear)

attributes(mtcars$mpg)$label <- "Miles per gallon"
attributes(mtcars$hp)$label <- "Horsepower"
attributes(mtcars$wt)$label <- "Weight"
attributes(mtcars$gear)$label <- "Gears"

mod1 <- lm(mpg ~ hp + wt + gear, data = mtcars)
```

``` r
modelsummary::modelsummary(
    mod1,
    statistic = c("95% CI" = "({conf.low}, {conf.high})", "p-value" = "{p.value}"),
    shape = term ~ - model + statistic,
    gof_map = NA,
    coef_rename = T
)
```

|             | Est.   | 95% CI           | p-value |
|-------------|--------|------------------|---------|
| (Intercept) | 34.872 | (29.578, 40.166) | \<0.001 |
| Horsepower  | -0.035 | (-0.061, -0.009) | 0.010   |
| Weight      | -3.239 | (-5.040, -1.437) | 0.001   |
| Gears \[4\] | 1.265  | (-1.486, 4.016)  | 0.354   |
| Gears \[5\] | 1.874  | (-1.956, 5.704)  | 0.324   |

``` r
gtsummary::tbl_regression(mod1)
```

<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Beta&lt;/strong&gt;"><strong>Beta</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;"><strong>95% CI</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;p-value&lt;/strong&gt;"><strong>p-value</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">Horsepower</td>
<td headers="estimate" class="gt_row gt_center">-0.03</td>
<td headers="ci" class="gt_row gt_center">-0.06, -0.01</td>
<td headers="p.value" class="gt_row gt_center">0.010</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Weight</td>
<td headers="estimate" class="gt_row gt_center">-3.2</td>
<td headers="ci" class="gt_row gt_center">-5.0, -1.4</td>
<td headers="p.value" class="gt_row gt_center">0.001</td></tr>
    <tr><td headers="label" class="gt_row gt_left">Gears</td>
<td headers="estimate" class="gt_row gt_center"><br /></td>
<td headers="ci" class="gt_row gt_center"><br /></td>
<td headers="p.value" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    3</td>
<td headers="estimate" class="gt_row gt_center">—</td>
<td headers="ci" class="gt_row gt_center">—</td>
<td headers="p.value" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    4</td>
<td headers="estimate" class="gt_row gt_center">1.3</td>
<td headers="ci" class="gt_row gt_center">-1.5, 4.0</td>
<td headers="p.value" class="gt_row gt_center">0.4</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    5</td>
<td headers="estimate" class="gt_row gt_center">1.9</td>
<td headers="ci" class="gt_row gt_center">-2.0, 5.7</td>
<td headers="p.value" class="gt_row gt_center">0.3</td></tr>
  </tbody>
  &#10;  <tfoot class="gt_footnotes">
    <tr>
      <td class="gt_footnote" colspan="4"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;"><sup>1</sup></span> CI = Confidence Interval</td>
    </tr>
  </tfoot>
</table>
</div>

<sup>Created on 2024-05-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment]
Maybe something like this:

```r
library(modelsummary)
mtcars$gear <- factor(mtcars$gear)
mod1 <- lm(mpg ~ hp + wt + gear, data = mtcars)

cr <- c(
    "mpg" = "Miles per gallon",
    "hp" = "Horsepower",
    "wt" = "Weight",
    "gear3" = "3",
    "gear4" = "4",
    "gear5" = "5"
)
ar <- data.frame("Gears", "", "")
attr(ar, "position") <- 4 


modelsummary(mod1, 
    coef_rename = cr, 
    include_reference = TRUE,
    add_rows = ar,
    gof_map = NA,
    shape = term ~ statistic)
```

<table style="width:43%;">
<colgroup>
<col style="width: 19%" />
<col style="width: 12%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th colspan="2"><ol type="1">
<li></li>
</ol></th>
</tr>
<tr class="odd">
<th></th>
<th>Est.</th>
<th>S.E.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>34.872</td>
<td>2.580</td>
</tr>
<tr class="even">
<td>Horsepower</td>
<td>-0.035</td>
<td>0.013</td>
</tr>
<tr class="odd">
<td>Weight</td>
<td>-3.239</td>
<td>0.878</td>
</tr>
<tr class="even">
<td>Gears</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>3</td>
<td><ul>
<li></li>
</ul></td>
<td></td>
</tr>
<tr class="even">
<td>4</td>
<td>1.265</td>
<td>1.341</td>
</tr>
<tr class="odd">
<td>5</td>
<td>1.874</td>
<td>1.867</td>
</tr>
</tbody>
</table>

**Comment by vincentarelbundock** [comment]
Alternatively, you can use the `group_tt()` argument from the `tinytable` package:

```{r}
library(modelsummary)
library(tinytable)
mtcars$gear <- factor(mtcars$gear)
mod1 <- lm(mpg ~ hp + wt + gear, data = mtcars)

cr <- c(
    "mpg" = "Miles per gallon",
    "hp" = "Horsepower",
    "wt" = "Weight",
    "gear4" = "4",
    "gear5" = "5"
)

modelsummary(mod1, 
    coef_rename = cr, 
    gof_map = NA,
    shape = term ~ statistic) |> 
    group_tt(i = list("Gears" = 4)) |>
    group_tt(i = list("3" = 5))
```

**Comment by ami-null** [comment]
> Maybe something like this:
> 
> ```r
> library(modelsummary)
> mtcars$gear <- factor(mtcars$gear)
> 
> cr <- c(
>     "mpg" = "Miles per gallon",
>     "hp" = "Horsepower",
>     "wt" = "Weight",
>     "gear3" = "3",
>     "gear4" = "4",
>     "gear5" = "5"
> )
> ar <- data.frame(c("Gears", "3"), c("", "-"), c("", "-"))
> attr(ar, "position") <- 4:5 
> 
> mod1 <- lm(mpg ~ hp + wt + gear, data = mtcars)
> 
> modelsummary(mod1, 
>     coef_rename = cr, 
>     add_rows = ar,
>     gof_map = NA,
>     shape = term ~ statistic)
> 
> 
> +-------------+--------+-------+
> |             | Est.   | S.E.  |
> +=============+========+=======+
> | (Intercept) | 34.872 | 2.580 |
> +-------------+--------+-------+
> | Horsepower  | -0.035 | 0.013 |
> +-------------+--------+-------+
> | Weight      | -3.239 | 0.878 |
> +-------------+--------+-------+
> | Gears       |        |       |
> +-------------+--------+-------+
> | 3           | -      | -     |
> +-------------+--------+-------+
> | 4           | 1.265  | 1.341 |
> +-------------+--------+-------+
> | 5           | 1.874  | 1.867 |
> +-------------+--------+-------+ 
> ```

Thank you for the reply. This seems to be what I was looking for. Is it possible to add this functionality into the package itself? I would send a PR if I could, but unfortunately I am not familiar enough with the codebase

**Comment by vincentarelbundock** [comment]
In a sense, this functionality is already "in the package itself", as `tinytable` is a hard dependency. I think this is really trivial to achieve, so I don't think it's worth adding a new argument for this.

But I do agree that it should be better documented. I added an even simpler solution to the website. You can see it here:

https://modelsummary.com/vignettes/modelsummary.html#factor-labels

This is what I recommend.

**Comment by ami-null** [comment]
Thank you, the example in the provided in the works well. 

However, when `indent` is non-zero in `tinytable::group_tt()`, the other variables (which are not under the group) are indented too which looks quite odd in a model summary table. I understand that this is the expected behavior and the functionality is provided by the `{tinytable}` package, however, I feel like it needed to be mentioned.

For example the below code:

```
library(modelsummary)
library(tinytable)

mod <- lm(mpg ~ hp + factor(gear) + factor(am), mtcars)

cr <- c(
    "hp" = "Horsepower",
    "factor(gear)3" = "3",
    "factor(gear)4" = "4",
    "factor(gear)5" = "5",
    "factor(am)0" = "Automatic",
    "factor(am)1" = "Manual"
)

modelsummary(mod,
             include_reference = TRUE,
             shape = term ~ statistic - model,
             coef_rename = cr,
             gof_map = NA) |>
    format_tt(replace = list("-" = "")) |>
    group_tt(i = list("Gears" = 3, "Transmission" = 6), indent = 2)
```

outputs this:
![Rplot](https://github.com/vincentarelbundock/modelsummary/assets/70378126/df7fd6e5-2ebc-4c65-a4bf-0d6b470cedaf)

Ideally, the red marked rows should not be indented.

**Comment by vincentarelbundock** [comment]
You can set indent to 0 and the manually indent the rows you like with style_tt()

**Comment by ami-null** [comment]
Thank you, that works perfectly for HTML documents!

But, there still seem to be some issue for LaTeX output. For example, the code below:

```
library(modelsummary)
library(tinytable)

mod <- lm(mpg ~ hp + factor(gear) + factor(am), mtcars)

cr <- c(
    "hp" = "Horsepower",
    "factor(gear)3" = "3",
    "factor(gear)4" = "4",
    "factor(gear)5" = "5",
    "factor(am)0" = "Automatic",
    "factor(am)1" = "Manual"
)

modelsummary(
    mod,
    include_reference = TRUE,
    shape = term ~ statistic - model,
    coef_rename = cr,
    gof_map = NA
) |>
    format_tt(replace = list("-" = "")) |>
    group_tt(i = list("Gears" = 3, "Transmission" = 6), indent = 0) |> 
    style_tt(i = c(1:3, 7), j = 1, bold = T) |> 
    style_tt(i = c(4:6, 8:9), indent = 2)
```

produces this output in the case **HTML** output in an rmd document:
![image](https://github.com/vincentarelbundock/modelsummary/assets/70378126/c0d36307-bb71-424b-8278-08c7fe683d7f)

However, the `indent` argument of `style_tt()` seems to be ignored in the case of **LaTeX** output. It produces:
![image](https://github.com/vincentarelbundock/modelsummary/assets/70378126/16864ffa-96a9-499a-a667-18806aa27aad)
and the generated LaTeX code for the table is:
```
\begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]Q[]},
cell{4}{1}={c=3}{},cell{8}{1}={c=3}{},
cell{2}{1}={preto={\hspace{0em}}},
cell{3}{1}={preto={\hspace{0em}}},
cell{5}{1}={preto={\hspace{0em}}},
cell{6}{1}={preto={\hspace{0em}}},
cell{7}{1}={preto={\hspace{0em}}},
cell{9}{1}={preto={\hspace{0em}}},
cell{10}{1}={preto={\hspace{0em}}},
cell{11}{1}={preto={\hspace{0em}}},
column{1}={halign=l,},
column{2}={halign=c,},
column{3}={halign=c,},
cell{2}{1}={}{,cmd=\bfseries,},
cell{3}{1}={}{,cmd=\bfseries,},
cell{4}{1}={}{,cmd=\bfseries,},
cell{8}{1}={}{,cmd=\bfseries,},
}                     %% tabularray inner close
\toprule
& Est. & S.E. \\ \midrule %% TinyTableHeader
(Intercept) & \num{27.480} & \num{1.974} \\
Horsepower & \num{-0.065} & \num{0.010} \\
Gears && \\
3 & - & - \\
4 & \num{0.076} & \num{1.829} \\
5 & \num{2.395} & \num{2.384} \\
Transmission && \\
Automatic & - & - \\
Manual & \num{4.135} & \num{1.809} \\
\bottomrule
\end{tblr}
\end{table}
```

Is this an issue with `{tinytable}`? Or, am I missing something and this is the expected behavior?

**Comment by vincentarelbundock** [comment]
Thanks for the report. Yes, this was a minor bug (typo) in `tinytable`. If you install that package from Github, then restart R completely, it should work.
