### ISSUE TITLE
Display reference category of factor variable as empty (or em dash) row

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/modelsummary#78]
Feature request by email:

> Second, I had a quick question for you: Is there a built in way to specify the reference category for categorical variables and have them displayed in the output table with an em dash or some other symbol? I work with a lot of experiments and when presenting results in regression table format, I like to specify the baseline condition if it wasn’t a pure control condition. I assume I could do this by passing the output to kable and modifying manually, but curious if there is a built in way to do this.

**Comment by vincentarelbundock** [comment]
example in Stata:

http://repec.org/bocode/e/estout/advanced.html#advanced007

**Comment by iago-pssjd** [comment]
Hi!
Is this feature added to `modelsummary`?
Thanks in advance!

**Comment by vincentarelbundock** [comment]
Yep, this is very easy to do using the `add_rows` argument. The website has an example of this specific use case:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#add_rows

**Comment by iago-pssjd** [comment]
Thanks!
