### ISSUE TITLE
Question: How tu update column's width in Rmarkdown

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#790]
I have a `modelsummary` in an Rmarkdown. Using `output = "kableExtra"` I would use `column_spec(, widths = ...)` to update column's width. I see that there is the `tt(width = ...)` function in the tinytable package, but I can't apply it to a modelsummary object. However, it seems  `style_tt` does not include `width` argument.

**Comment by vincentarelbundock** [comment]
As documented in `modelsummary`, you can pass additional arguments directly to `modelsummary()` --- including `width` --- and those will be passed automatically to the table-drawing functions like `tinytable::tt()`

**Comment by iago-pssjd** [comment]
Thank you!!!
