### ISSUE TITLE
Modelsummary of very large models are cut by Rmarkdown for PDF outputs

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#791]
I have an Rmarkdown document to build a `pdf_document`, including a modelsummary of a model with many variables. Both with `kableExtra` or `tinytable`, I can see just one part of the table, instead of being split through multiple pages.

**Comment by vincentarelbundock** [comment]
Please read the documentation for `tinytable`. In particular, if you look at the PDF version, search for "multipage"
