### ISSUE TITLE
Accept glue() output in notes

### ISSUE THREAD

**Issue by LukasWallrich** [vincentarelbundock/modelsummary#792]
Often it can be helpful to create notes with `glue()` - yet if you pass that directly, it fails with a very obscure error message (in a clean console, not in reprex - maybe because that defaults to a different table engine?) Maybe you can check if notes are string-like and then convert them before passing them on?

![image](https://github.com/vincentarelbundock/modelsummary/assets/60155545/4a19c7d2-1dd6-4014-b8d4-b96062033543)

**Comment by vincentarelbundock** [comment]
Thanks for the report. This can be fixed by installing version 0.3.0.32 of `tinytable` (not `modelsummary`!)

Background: The problem was that the `glue` output was not detected as an atomic vector by `check_atomic_vector()`
