### ISSUE TITLE
Footnote not escaped when it should be

### ISSUE THREAD

**Issue by dmurdoch** [vincentarelbundock/modelsummary#793]
This issue https://github.com/haozhu233/kableExtra/issues/855 is caused because the table ends up with a footnote `"+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001"' in an HTML kableExtra table, but sets `escape = FALSE`.

To duplicate:

```
library(modelsummary)
model <- lm(mpg ~ wt + hp, data = mtcars)
modelsummary(model, output = "kableExtra", stars = TRUE, escape = TRUE)
```

The table drops most of the footnote.  Setting the value of `escape` to `TRUE` here:   https://github.com/vincentarelbundock/modelsummary/blob/3c60e219b4a6eb741568354dc97944585c6e1ad6/R/factory_kableExtra.R#L155  fixes this example, but the code handles a lot of cases, and perhaps `FALSE` is needed for some of them.

**Comment by vincentarelbundock** [comment]
@dmurdoch thank you for the clear report and the investigation.

@michaelherndon97 I believe that if you install `modelsummary` from Github and restart your R session, your example should then work as expected. Let me know if it doesn't. Thanks for reporting the original issue.
