### ISSUE TITLE
More escaping issues in quarto with markdown output

### ISSUE THREAD

**Issue by nicolaiberk** [vincentarelbundock/modelsummary#805]
- [x]  Before reporting a bug, please update to the latest development version of `modelsummary` and make sure the bug has not been fixed yet.

Bug reports must include:

1. *Concise* description of the bug

**Underscore in variable name not escaped in quarto with `output = 'markdown'`.**

Not sure if entirely relevant, as avoiding underscores should be common knowledge at this point, but others with similar problem might find this issue helpful.

2. *Minimal* reproducible example using publicly available data and the bare minimum code and libraries needed to reproduce the bug.

**example.qmd**:
```
---
title: "Reproducible Example"
format: pdf
---


```{r}
library(dplyr)

m1 <- lm(mpg ~ wt * a_m, 
                    data = 
                      mtcars %>% 
                      mutate(
                        a_m = am
                      )
                    )

modelsummary::modelsummary(
        list("Model I" = m1), 
        output = "markdown",
        stars = T)
```

3. **`sessionInfo()` output**

> R version 4.4.1 (2024-06-14)
> Platform: x86_64-apple-darwin20
> Running under: macOS Sonoma 14.5
> 
> Matrix products: default
> BLAS:   /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRblas.0.dylib 
> LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> time zone: Europe/Vienna
> tzcode source: internal
> 
> attached base packages:
> [1] stats     graphics  grDevices datasets  utils     methods   base     
> 
> loaded via a namespace (and not attached):
>  [1] digest_0.6.37     later_1.3.2       fastmap_1.2.0     xfun_0.47        
>  [5] knitr_1.48        htmltools_0.5.8.1 rmarkdown_2.28    ps_1.7.7         
>  [9] cli_3.6.3         processx_3.8.4    renv_1.0.7        compiler_4.4.1   
> [13] rstudioapi_0.16.0 tools_4.4.1       quarto_1.4.4      evaluate_0.24.0  
> [17] yaml_2.3.10       Rcpp_1.0.13       rlang_1.1.4       jsonlite_1.8.8

**Comment by vincentarelbundock** [comment]
Thanks, but the problem is that you should not be using `output="markdown"` in a Quarto document. `modelsummary` should automatically detect the output format and create an appropriate table. Your example works if you remove that line.
