### ISSUE TITLE
`modelplot` Issue: How to change marker types?

### ISSUE THREAD

**Issue by ocolluphid** [vincentarelbundock/modelsummary#808]
Hi,
I'm trying to run the following but it has no impact on my marker shape types:
```
modelplot(models_subset, background = background_opts,
          coef_map = coef_map_sorted) + 
  theme_classic() +
  theme(legend.position="bottom") +
  xlab("Coefficient Estimates and 95% CIs") +
  scale_color_hue(labels=c("model_noCtrls" = "No Controls",
                           "model_w_Ctrls" = "With Controls")) +
  scale_shape_manual(values = c(16, 17))
```
I'm not seeing any documentation within modelplot for changing shapes, am I missing something?

**Comment by vincentarelbundock** [comment]
I don't think there's an easy to achieve this currently. 

Frankly, I don't recommend you use `modelplot` like this to draw super customized plots. It is usually much easier to call:

```r
modelplot(modlist, draw = FALSE)
```

And then call `ggplot2` directly.

The other options are all hacks.

**Comment by ocolluphid** [comment]
I see, thanks for the tip!
