### ISSUE TITLE
Option to select method for confidence intervals

### ISSUE THREAD

**Issue by dariorrr** [vincentarelbundock/modelsummary#810]
Hello,

For some anaylsis, I have run both `modelsummary()` and `broom.mixed::tidy()` to examine the output of a few [g]lmer models.

With broom.mixed::tidy(), I have specified the method for extracting the confidence intervals as follows: `conf.method = "profile"`. I would like to apply the same to modelsummary() but I cannot find the option to set the confint method to "profile". Now it looks like modelsummary is using the "Wald" method by default.

Thank you in advance for your reply.

Dario

**Comment by vincentarelbundock** [comment]
As document, all additional arguments that are not explicitly documented in `modelsummary` will be passed via `...` to `parameters::model_parameters()`.

See docs here for different options: https://easystats.github.io/parameters/reference/model_parameters.merMod.html
