### ISSUE TITLE
Variable labels

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#811]
Probably straightforward: what is the recommended way to do variable labels outside of `haven`? 

I was expecting `datasummary_balance()` etc. to have a `coef_map` argument as well, for example. 

Thank you!

**Comment by statzhero** [comment]
Perfect. Do you mind adjusting the example so that it takes a named list as per `coef_map`?

**Comment by vincentarelbundock** [comment]
I'd be happy to merge a pull request.

**Comment by statzhero** [comment]
I meant in the comment example because I can only come up with this hack: 

```r
dict <- c("am" = "Transmission")
mtcars %>% dplyr::rename_with(\(x) dict[x], .cols = intersect(names(dict), colnames(.)))
```
