### ISSUE TITLE
Modelsummary stopped being able to output to .tex files through kableExtra functions

### ISSUE THREAD

**Issue by sometimesabird** [vincentarelbundock/modelsummary#812]
### Description
Before the 2.0 version it was possible to pipe modelsummary() output into kableExtra styling functions and then use save_kable() to export it to latex. This doesn't seem to work now. Reverting factory options resolves the issue. The issue may stem from modelsummary not converting the core of the table to Latex and keeping it in HTML.

### Reproduction

```
# load libraries
library(modelsummary)
library(tibble)
library(kableExtra)

# a simple regression
model <- lm(sample(c(1, 2, 3), 10, replace = TRUE) ~ sample(c(1, 2, 4), 10, replace = TRUE))
```

Now, I want to export it to kableExtra, but when I do I get that the internal structure of the table is in HTML (?):
```
output <- modelsummary(model, output = 'kableExtra')
kbl(output, format = "latex")
```

This is the output:
```
\begin{tabular}[t]{l}
\hline
x\\
\hline
<table class="table" style="color: black; width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> \&amp;nbsp;(1) </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> (Intercept) </td>
   <td style="text-align:center;"> 0.750 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:center;"> (0.893) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> sample(c(1, 2, 4), 10, replace = TRUE) </td>
   <td style="text-align:center;"> 0.438 </td>
  </tr>
  <tr>
   <td style="text-align:left;box-shadow: 0px 1.5px">  </td>
   <td style="text-align:center;box-shadow: 0px 1.5px"> (0.353) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Num.Obs. </td>
   <td style="text-align:center;"> 10 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 </td>
   <td style="text-align:center;"> 0.161 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> R2 Adj. </td>
   <td style="text-align:center;"> 0.056 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> AIC </td>
   <td style="text-align:center;"> 29.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BIC </td>
   <td style="text-align:center;"> 30.8 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Log.Lik. </td>
   <td style="text-align:center;"> −11.938 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> RMSE </td>
   <td style="text-align:center;"> 0.80 </td>
  </tr>
</tbody>
</table>\\
\hline
\end{tabular}
```

When you save_kable that object, it's uncompilable in Latex. This is what it's _supposed_ to look like:

```
modelsummary(model, output = 'latex')

\begin{table}
\centering
\begin{tabular}[t]{lc}
\toprule
  & (1)\\
\midrule
(Intercept) & \num{0.750}\\
 & (\num{0.893})\\
sample(c(1, 2, 4), 10, replace = TRUE) & \num{0.438}\\
 & (\num{0.353})\\
\midrule
Num.Obs. & \num{10}\\
R2 & \num{0.161}\\
R2 Adj. & \num{0.056}\\
AIC & \num{29.9}\\
BIC & \num{30.8}\\
Log.Lik. & \num{-11.938}\\
RMSE & \num{0.80}\\
\bottomrule
\end{tabular}
\end{table}

```

Similarly, if instead of kbl() you pass output to add_header_above() and then save_kable() as a .tex file you get an empty file.

### Suspicions

Here are more investigations. 
`class(output)` gives a reasonable response: 
> [1] "kableExtra"  "knitr_kable"

However, its _structure_ seems weird:

> str(output)
'kableExtra' chr "<table class=\"table\" style=\"color: black; width: auto !important; margin-left: auto; margin-right: auto;\">\"| __truncated__
>  attr(*, "format")= chr "html"

I don't think that's supposed to happen. It seems to be an html table wrapped inside a latex container, and then kable doesn't know what to do with HTML, because it is told that the object is kable.

### Other Attempts

Let's try `output <- modelsummary(model, output = 'latex')`. That object is a nice piece of latex:

> \begin{table}
\centering
\begin{tblr}[         %% tabularray outer open
]                     %% tabularray outer close
{                     %% tabularray inner open
colspec={Q[]Q[]},
column{1}={halign=l,},
column{2}={halign=c,},
hline{6}={1,2}{solid, 0.05em, black},
}                     %% tabularray inner close
\toprule
& (1) \\ \midrule %% TinyTableHeader
(Intercept)                            & \num{2.300}   \\
& (\num{0.471}) \\
sample(c(1, 2, 4), 10, replace = TRUE) & \num{0.000}   \\
& (\num{0.207}) \\
Num.Obs.                               & \num{10}      \\
R2                                     & \num{0.000}   \\
R2 Adj.                                & \num{-0.125}  \\
AIC                                    & \num{25.5}    \\
BIC                                    & \num{26.4}    \\
Log.Lik.                               & \num{-9.731}  \\
RMSE                                   & \num{0.64}    \\
\bottomrule
\end{tblr}
\end{table} 

But its class is _tinytable_, which can't go into kable functions.

### Temporary Solution

So then what helps is reverting factory settings:

```
options(modelsummary_factory_default = 'kableExtra')
options(modelsummary_factory_latex = 'kableExtra')
options(modelsummary_factory_html = 'kableExtra')
output <- modelsummary(model, output = 'latex')
```

And that works as desired (and as it worked before):

`class(output)`:
> [1] "modelsummary_string" "knitr_kable"  

`kbl(output, format = "latex")`
> \begin{tabular}[t]{l}
\hline
x\\
\hline
\textbackslash{}begin\{table\}
\textbackslash{}centering
\textbackslash{}begin\{tabular\}[t]\{lc\}
\textbackslash{}toprule
  \& (1)\textbackslash{}\textbackslash{}
\textbackslash{}midrule
(Intercept) \& \textbackslash{}num\{2.300\}\textbackslash{}\textbackslash{}
 \& (\textbackslash{}num\{0.471\})\textbackslash{}\textbackslash{}
sample(c(1, 2, 4), 10, replace = TRUE) \& \textbackslash{}num\{0.000\}\textbackslash{}\textbackslash{}
 \& (\textbackslash{}num\{0.207\})\textbackslash{}\textbackslash{}
\textbackslash{}midrule
Num.Obs. \& \textbackslash{}num\{10\}\textbackslash{}\textbackslash{}
R2 \& \textbackslash{}num\{0.000\}\textbackslash{}\textbackslash{}
R2 Adj. \& \textbackslash{}num\{-0.125\}\textbackslash{}\textbackslash{}
AIC \& \textbackslash{}num\{25.5\}\textbackslash{}\textbackslash{}
BIC \& \textbackslash{}num\{26.4\}\textbackslash{}\textbackslash{}
Log.Lik. \& \textbackslash{}num\{-9.731\}\textbackslash{}\textbackslash{}
RMSE \& \textbackslash{}num\{0.64\}\textbackslash{}\textbackslash{}
\textbackslash{}bottomrule
\textbackslash{}end\{tabular\}
\textbackslash{}end\{table\}\\
\hline
\end{tabular}

### Session Info

```
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Garuda Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.12.0 
LAPACK: /usr/lib/liblapack.so.3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/New_York
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] kableExtra_1.4.0   tibble_3.2.1       modelsummary_2.2.0

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.8       highr_0.11           compiler_4.4.1       tinytable_0.4.0.1    xml2_1.3.6          
 [6] stringr_1.5.1        jquerylib_0.1.4      systemfonts_1.1.0    scales_1.3.0         yaml_2.3.10         
[11] fastmap_1.2.0        lattice_0.22-6       R6_2.5.1             tables_0.9.28        generics_0.1.3      
[16] knitr_1.48           backports_1.5.0      checkmate_2.3.2      insight_0.20.4.3     munsell_0.5.1       
[21] svglite_2.1.3        bslib_0.8.0          pillar_1.9.0         rlang_1.1.4          utf8_1.2.4          
[26] cachem_1.1.0         performance_0.12.3.2 stringi_1.8.4        xfun_0.46            sass_0.4.9          
[31] parameters_0.22.2.7  datawizard_0.12.2    estimability_1.5.1   viridisLite_0.4.2    cli_3.6.3           
[36] magrittr_2.0.3       emmeans_1.10.4       digest_0.6.36        grid_4.4.1           mvtnorm_1.3-1       
[41] rstudioapi_0.13      lifecycle_1.0.4      vctrs_0.6.5          evaluate_0.24.0      glue_1.7.0          
[46] data.table_1.15.4    zoo_1.8-12           fansi_1.0.6          colorspace_2.1-1     bayestestR_0.14.0   
[51] rmarkdown_2.27       purrr_1.0.2          tools_4.4.1          pkgconfig_2.0.3      htmltools_0.5.8.1   
```

**Comment by sometimesabird** [comment]
The issue might not be a problem for writing in Rmarkdown, but I think it's an important use case for writing academic articles, where you write the paper in Latex on Overleaf and import tables produced in R

**Comment by vincentarelbundock** [comment]
Set the factory option and the use `output="latex"`

**Comment by sverrirarnors** [comment]
I think the documentation has to be updated to reflect this. This still an example on [this website](https://modelsummary.com/articles/appearance.html#warning-saving-to-file), but piping the modelsummary with output set to 'latex' doesn't work.

    library(kableExtra)

    tab <- modelsummary(models, output = 'latex') %>%
      add_header_above(c(" " = 1, "Donations" = 2, "Crimes (person)" = 2, "Crimes (property)" = 1))

    kableExtra::save_kable(tab, file = "table.tex")

**Comment by vincentarelbundock** [comment]
Thanks @sverrirarnors the website should be updated now.

https://modelsummary.com/vignettes/appearance.html#warning-saving-to-file
