### ISSUE TITLE
Model naming while using shape = term~model+ statistic

### ISSUE THREAD

**Issue by daSilva5** [vincentarelbundock/modelsummary#816]
Hi,
I am having problems with one of my summaries related to the name of the model, and only happens when I include shape = term~model+ statistic in the code. When I leave only what is in brackets it works fine. But the models need to have the correct name. It seems to interact with the first model's name. If what is in brackets is identical in the first model it works.... Can you help?

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list(
    "Talk P %"     = lm(Donations ~ Literacy + Clergy, data = dat),
    "Talk P (kkkk)" = glm(Donations ~ Literacy + Commerce, family = poisson, data = dat)
    )

modelsummary(models,
             shape = term~model+ statistic)

![image](https://github.com/user-attachments/assets/1d510380-40b7-414d-953c-83cdca68eca8)
![image](https://github.com/user-attachments/assets/980c49b5-6a7b-464f-aa00-015690e3835f)
![image](https://github.com/user-attachments/assets/ec465731-4e5c-4fde-becb-97aa385e7015)
![image](https://github.com/user-attachments/assets/cc7242d0-c0d2-4053-b3f7-255f1131f39b)

Thanks

**Comment by vincentarelbundock** [comment]
Thanks a lot for the detailed report, I really appreciate it.

This should be fixed in the development version on Github. I plan to submit a new version to CRAN in the coming weeks.
