### ISSUE TITLE
`datasummary_skim_categorical` ignores the `fun_numeric` argument

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#822]
Probably intentional but somewhat unexpected, in my view. I was trying to use a custom "valid N" function instead of the default. 

```r
valid_N <- function(x) na.omit(x) |> length() 

mtcars |>
  dplyr::mutate(cyl = factor(ifelse(cyl == 4, NA, cyl))) |>
  datasummary_skim(type = "categorical",  fun_numeric = list(Unique = NUnique, `Valid N` = valid_N))
```

**Comment by vincentarelbundock** [comment]
Thanks for the report. I clarified the documentation. 

For custom summaries of categorical variables, I'd recommend the `datasummary()` function.
