### ISSUE TITLE
Standardize argument order

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#823]
A short one: I'm sad that it's `datasummary <- function(formula, data, etc ...) `  and not `datasummary <- function(data, formula, etc ...) ` it would be more consistent with the [tidy design principles](https://design.tidyverse.org/important-args-first.html). 

I appreciate that you may have other reasons, of course. And that it probably would break a lot.

**Comment by vincentarelbundock** [comment]
Yes, I appreciate this point. However, changing this now would break a lot of people's code, and I think it's best not to change this.
