### ISSUE TITLE
Dot aligned numbers in GoFs

### ISSUE THREAD

**Issue by svraka** [vincentarelbundock/modelsummary#827]
Consider this table:

```r
m <- lm(mpg ~ wt + factor(vs), data = mtcars)
modelsummary(m, stars = TRUE, align = "ld")
```

This is the rendered output:

![Annotation 2024-10-21 165846](https://github.com/user-attachments/assets/51c66aaf-424b-4224-90e6-f610ca04fb97)

Should all rows be dot aligned? Dot alignment is most useful for coefficients, especially if you have significance stars. We want to quickly compare coefficients, and the differing number of symbols for significance would prevent that in a center, or right aligned column, while in a left aligned column the negative sign would be an issue. 

Meanwhile GoFs are quite heterogenous, and in most cases we do not want to compare them either to the coefficients, or to other GoFs. Additionally, some GoFs can be much larger than any other number in the table. Imagine, if the model had millions of observations: the model's column would be very wide, even though in terms of number of characters, that number wouldn't be wider than a coefficient with many stars.

I it would be a good default to align only the coefficients part, and keep the GoF part center aligned, which is what modelsummary does if `align` is `NULL`.

**Comment by vincentarelbundock** [comment]
Thanks for raising this question.

I'm not sure. On the one hand, your arguments kind of make sense to me. On the other hand, I think this largely comes down to aesthetic considerations.

At the moment, I'm open, but not yet convinced that we should build in more code complexity for something that is a matter of preferences, and also trivial to do manually.

In any case, this nice solution should be documented:

````
---
title: Fixed dot aligned tables
format: pdf
---

```{r}
library(fixest)
library(modelsummary)
library(tinytable)

m <- feols(mpg ~ wt + factor(cyl) | carb, data = mtcars)

modelsummary(m, align = "ld") |>
  style_tt(tabularray_inner = "row{8-20}={guard,halign=c}")
```
````

**Comment by svraka** [comment]
> At the moment, I'm open, but not yet convinced that we should build in more code complexity for something that is a matter of preferences, and also trivial to do manually.

Trivial but slightly inconvenient, you'd have to manually set row numbers.

> In any case, this nice solution should be documented:

I agree.

**Comment by vincentarelbundock** [comment]
Implementation ideas:

Call `style_tt()` with the `tabularray` `{guard}` about here: https://github.com/vincentarelbundock/modelsummary/blob/main/R/factory_tinytable.R#L59

We probably need information about the number of GOF to know exactly where to insert the guard. This could be a new argument to the `factory_tinytable()` function. 

Similar counting code is here: https://github.com/vincentarelbundock/modelsummary/blob/main/R/modelsummary.R#L735

And we call `factory_tinytable()` here: https://github.com/vincentarelbundock/modelsummary/blob/main/R/modelsummary.R#L826

I'm totally swamped at work right now, so probably no time to fix this and write appropriate tests in the short run, but at least we have some ideas.

**Comment by vincentarelbundock** [comment]
I'm very sorry for the delay! The fall has been brutal at work.

I just implemented some safety measures for this. When there's a dot-aligned column, we now center the GOF cells for that column. 

Thanks for reporting this @svraka , and let me know if you try and run into issues.

Note that this requires the development versions of both `tinytable` and the PR version of `modelsummary`. I plan to release both packages to CRAN in early January.

Then, try to compile this Quarto document:

````
---
format: pdf
---

```{r}
remotes::install_github("vincentarelbundock/tinytable")
remotes::install_github("vincentarelbundock/modelsummary@issue826")
library(fixest)
library(modelsummary)
m <- feols(mpg ~ wt + factor(cyl) | carb, data = mtcars)
modelsummary(m, align = "ld")
```
````


On my computer, the result looks like this:

<img width="348" alt="Screenshot 2024-12-26 at 10 16 56 PM" src="https://github.com/user-attachments/assets/f85e88d2-19bd-4421-bce1-da6c90d98ddf" />

**Comment by vincentarelbundock** [comment]
merged to `main`

**Comment by vincentarelbundock** [comment]
Unfortunately, I have to reverse this change because it created lots of problems with inconsistent display/style of numbers.

I documented the workaround on the website.
