### ISSUE TITLE
modelsummary() reports wrong SE for feols() with sunab(, att = TRUE)

### ISSUE THREAD

**Issue by Passtar** [vincentarelbundock/modelsummary#829]
I noticed that `modelsummary()` reports wrong standard errors for the ATT estimated by `feols()` in combination with the Sun & Abraham extension `sunab(, att = TRUE)`. The Sun & Abraham TWFE estimator estimates adoption cohort-year specific ATTs that can be aggregated to obtain the "overall" ATT. It appears that `modelsummary()` reports the standard error of the first adoption cohort-year specific estimate instead of the aggregate standard error as for example `summary()` does.

```r
library(did)
library(tidyverse)
library(modelsummary)
library(fixest)

data(mpdta) # data from did package
head(mpdta)

model_att <-
  mpdta %>% 
  feols(lemp ~ sunab(first.treat, year, ref.p = -1:-4, att = TRUE) |
          countyreal + year,
        cluster = ~countyreal)


summary(model_att) # see SE from summary()
modelsummary(model_att, fmt = function(x) round(x, 5)) # see SE from modelsummary()
model_att$se # see SE of adoption-cohort specific estimates
```

The issue does not prevail when the adoption cohort-year specific estimates are aggregated to event study estimates on the year level.

```r
model_es <-
  mpdta %>% 
  feols(lemp ~ sunab(first.treat, year, ref.p = -1:-4) |
          countyreal + year,
        cluster = ~countyreal)

model_es
modelsummary(model_es, fmt = function(x) round(x, 5))
```

Session info: R version 4.4.1; fixest_0.12.1; modelsummary_2.1.1

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. I think this needs to be fixed upstream in the `parameters` package. I opened an issue on their Github repo: https://github.com/easystats/parameters/issues/1039
