### ISSUE TITLE
LLM Context Summary Function

### ISSUE THREAD

**Issue by cturnerbridger** [vincentarelbundock/modelsummary#830]
Feature Request

Hey thanks for your great work. It would be amazingly useful to have a specialised function that will output a dataset summary designed specifically to paste or attach into your LLM prompt. This would help the LLM write code for you. Ideally this would be in md output or perhaps txt with xml tags. 

Thanks again

**Comment by vincentarelbundock** [comment]
modelsummary already supports export in markdown and HTML. LLMs understand both of these formats very well.

**Comment by vincentarelbundock** [comment]
datasummary_skim(MTCARS, "markdown")
