### ISSUE TITLE
Fixed effect style for `fixest` object

### ISSUE THREAD

**Issue by statzhero** [vincentarelbundock/modelsummary#839]
My aim is to restyle the "X" for the fixed effects in the model object, similar to issue https://github.com/vincentarelbundock/modelsummary/issues/417 . Is the solution there still the recommended solution? 

I know this is a super subjective point but to me "Y" would make more sense than "X" as default. 

Or perhaps it is possible to port the `style.df(yesNo = c("Yes", "No"))` argument from the `fixest` package.

**Comment by vincentarelbundock** [comment]
Yes, this can easily be achieved with `glance_custom`
