### ISSUE TITLE
Suggestion: add more default options

### ISSUE THREAD

**Issue by DiogoFerrari** [vincentarelbundock/modelsummary#842]
Vincent, great package! It would be useful to add these options, one of which should be pretty straightforward. You may just need to relax the `sanity_factory` check

```
options("modelsummary_factory_default" = "modelsummary_list")
options("modelsummary_statistics" = '({conf.low}, {conf.high})')
options("modelsummary_stars" = TRUE)
```

**Comment by vincentarelbundock** [comment]
@DiogoFerrari 

This is a good suggestion. I've merged a commit to Github to allow this. The option names are slightly different than what you propose, but it's also more flexible because almost all function arguments can not be set using global options.

```r
options(modelsummary_output = "modelsummary_list")
options(modelsummary_statistic = '({conf.low}, {conf.high})')
options(modelsummary_stars = TRUE)
```
