### ISSUE TITLE
msummary shows incorrect number of stars in some circumstances

### ISSUE THREAD

**Issue by torfason** [vincentarelbundock/modelsummary#93]
The following example demonstrates that in some cases, `msummary()` shows an incorrect number of stars. This seems to depend on the value passed into the `statistic`parameter. The first version below shows (correctly, I believe) two stars for the `(Intercept)` estimate, but the second version shows three stars. 

```
> library(modelsummary)
> m <- lm(dist~speed, data=cars)
> msummary(m, "markdown", stars=TRUE, )

|            |Model 1   |
|:-----------|:---------|
|(Intercept) |-17.579** |
|            |(6.758)   |
|speed       |3.932***  |
|            |(0.416)   |
|Num.Obs.    |50        |
|R2          |0.651     |
|R2 Adj.     |0.644     |
|AIC         |419.2     |
|BIC         |424.9     |
|Log.Lik.    |-206.578  |

__Note:__
^^ * p < 0.1, ** p < 0.05, *** p < 0.01

> msummary(m, "markdown", stars=TRUE, statistic="p.value")

|            |Model 1    |
|:-----------|:----------|
|(Intercept) |-17.579*** |
|            |(0.012)    |
|speed       |3.932***   |
|            |(0.000)    |
|Num.Obs.    |50         |
|R2          |0.651      |
|R2 Adj.     |0.644      |
|AIC         |419.2      |
|BIC         |424.9      |
|Log.Lik.    |-206.578   |

__Note:__
^^ * p < 0.1, ** p < 0.05, *** p < 0.01
```

The example should be reproducible, I would have used an actual reprex, but `reprex()` insists on rendering the markdown as HTML, which seemed more trouble than it was worth.

**Comment by vincentarelbundock** [comment]
@torfason thanks a bunch for the report and for the clear example. This made it very easy to diagnose to add a test to the testtthat suite. 

I pushed a commit to github, and I believe that it should fix the issue. You can try it by installing the development version:

```r
library(remotes)
install_github('vincentarelbundock/modelsummary')

library(modelsummary)
m <- lm(dist~speed, data=cars)
msummary(m, 'markdown', stars=TRUE, statistic="p.value")


|            |Model 1   |
|:-----------|:---------|
|(Intercept) |-17.579** |
|            |(0.012)   |
|speed       |3.932***  |
|            |(0.000)   |
|Num.Obs.    |50        |
|R2          |0.651     |
|R2 Adj.     |0.644     |
|AIC         |419.2     |
|BIC         |424.9     |
|Log.Lik.    |-206.578  |

__Note:__
^^ * p < 0.1, ** p < 0.05, *** p < 0.01


msummary(m, 'markdown', stars=TRUE)


|            |Model 1   |
|:-----------|:---------|
|(Intercept) |-17.579** |
|            |(6.758)   |
|speed       |3.932***  |
|            |(0.416)   |
|Num.Obs.    |50        |
|R2          |0.651     |
|R2 Adj.     |0.644     |
|AIC         |419.2     |
|BIC         |424.9     |
|Log.Lik.    |-206.578  |

__Note:__
^^ * p < 0.1, ** p < 0.05, *** p < 0.01
```

**Comment by torfason** [comment]
This is working for me now using the development version.

Thanks for the quick fix, and for the package – I had been looking/waiting for exactly this kind of package (gt-aware tables for multiple models in the social science tradition) for a while when I found modelsummary :-).

**Comment by vincentarelbundock** [comment]
Excellent!

Be on the lookout for a new version soon with cool new features for data summaries, cross-tabs, "balance" tables (control vs treatment group characteristics), etc.
