### ISSUE TITLE
Stars in msummary() output do not match statistic = 'p.value'

### ISSUE THREAD

**Issue by ChrisWaloszek** [vincentarelbundock/modelsummary#99]
For some reason, the estimate for Literacy (-15.358) also receives a significance star in OLS2 despite its high p-value (0.745).

                    OLS 1	        Poisson 1	    OLS 2	        Poisson 2
    (Intercept)	10373.698*	9.402*	            20357.309*	        9.708*
                    (0.000)	        (0.000)	            (0.000)	        (0.000)
    Literacy	-64.465*	-0.009*	            -15.358*	        0.000*
                    (0.001)	        (0.000)	            (0.745)	        (0.000)
    Clergy		-0.002*		0.004*
                                    (0.000)		        (0.000)
    Num.Obs.	86	86	86	86
    R2	0.135		0.001	
    ** p < 0.01, * p < 0.001

### MWE

    library(modelsummary)
    library(kableExtra)
    
    url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
    dat <- read.csv(url)
    
    models <- list()
    models[['OLS 1']] <- lm(Crime_prop ~ Literacy, data = dat)
    models[['Poisson 1']] <- glm(Crime_prop ~ Literacy + Clergy, family = poisson, data = dat)
    models[['OLS 2']] <- lm(Crime_pers ~ Literacy, data = dat)
    models[['Poisson 2']] <- glm(Crime_pers ~ Literacy + Clergy, family = poisson, data = dat)
    
    msummary(models,
             statistic = 'p.value',
             # stars = c('**' = .01, '*' = .001)
    )

**Comment by vincentarelbundock** [comment]
@ChrisWaloszek could you re-install from Github and try again. I believe I have fixed this bug in a previous commit, and will release to CRAN soon.



``` r

library(remotes)
install_github('vincentarelbundock/modelsummary')

library(modelsummary)
library(kableExtra)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/HistData/Guerry.csv'
dat <- read.csv(url)

models <- list()
models[['OLS 1']] <- lm(Crime_prop ~ Literacy, data = dat)
models[['Poisson 1']] <- glm(Crime_prop ~ Literacy + Clergy, family = poisson, data = dat)
models[['OLS 2']] <- lm(Crime_pers ~ Literacy, data = dat)
models[['Poisson 2']] <- glm(Crime_pers ~ Literacy + Clergy, family = poisson, data = dat)

msummary(models,
         statistic = 'p.value',
         stars = c('**' = .01, '*' = .001)
)
```

<div id="dzirlntpss" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

OLS 1

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

Poisson 1

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

OLS 2

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

Poisson 2

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

(Intercept)

</td>

<td class="gt_row gt_left">

10373.698\*

</td>

<td class="gt_row gt_left">

9.402\*

</td>

<td class="gt_row gt_left">

20357.309\*

</td>

<td class="gt_row gt_left">

9.708\*

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(0.000)

</td>

<td class="gt_row gt_left">

(0.000)

</td>

<td class="gt_row gt_left">

(0.000)

</td>

<td class="gt_row gt_left">

(0.000)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Literacy

</td>

<td class="gt_row gt_left">

\-64.465\*

</td>

<td class="gt_row gt_left">

\-0.009\*

</td>

<td class="gt_row gt_left">

\-15.358

</td>

<td class="gt_row gt_left">

0.000\*

</td>

</tr>

<tr>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

(0.001)

</td>

<td class="gt_row gt_left">

(0.000)

</td>

<td class="gt_row gt_left">

(0.745)

</td>

<td class="gt_row gt_left">

(0.000)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Clergy

</td>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

\-0.002\*

</td>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

0.004\*

</td>

</tr>

<tr>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

(0.000)

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

</td>

<td class="gt_row gt_left" style="border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #000000;">

(0.000)

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Num.Obs.

</td>

<td class="gt_row gt_left">

86

</td>

<td class="gt_row gt_left">

86

</td>

<td class="gt_row gt_left">

86

</td>

<td class="gt_row gt_left">

86

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2

</td>

<td class="gt_row gt_left">

0.135

</td>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

0.001

</td>

<td class="gt_row gt_left">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

R2 Adj.

</td>

<td class="gt_row gt_left">

0.124

</td>

<td class="gt_row gt_left">

</td>

<td class="gt_row gt_left">

\-0.011

</td>

<td class="gt_row gt_left">

</td>

</tr>

<tr>

<td class="gt_row gt_left">

AIC

</td>

<td class="gt_row gt_left">

1616.6

</td>

<td class="gt_row gt_left">

79898.6

</td>

<td class="gt_row gt_left">

1783.7

</td>

<td class="gt_row gt_left">

242266.3

</td>

</tr>

<tr>

<td class="gt_row gt_left">

BIC

</td>

<td class="gt_row gt_left">

1624.0

</td>

<td class="gt_row gt_left">

79906.0

</td>

<td class="gt_row gt_left">

1791.1

</td>

<td class="gt_row gt_left">

242273.6

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Log.Lik.

</td>

<td class="gt_row gt_left">

\-805.318

</td>

<td class="gt_row gt_left">

\-39946.317

</td>

<td class="gt_row gt_left">

\-888.874

</td>

<td class="gt_row gt_left">

\-121130.130

</td>

</tr>

</tbody>

<tfoot class="gt_sourcenotes">

<tr>

<td class="gt_sourcenote" colspan="5">

\*\* p \< 0.01, \* p \< 0.001

</td>

</tr>

</tfoot>

</table>

</div>



<sup>Created on 2020-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ChrisWaloszek** [comment]
Works great now – thank you very much for fixing! By chance, would you also have any advice for [this modelsummary issue](https://stackoverflow.com/questions/62610249/modelsummary-kableextra-regression-table-with-models-of-the-same-name/62612900#62612900) posed at SO?

**Comment by vincentarelbundock** [comment]
Thanks, I responded on stackoverflow.

On 20/06/29 01:20AM, ChrisWaloszek wrote:
>Works great now – thank you very much for fixing! By chance, would you also have any advice for [this modelsummary issue](https://stackoverflow.com/questions/62610249/modelsummary-kableextra-regression-table-with-models-of-the-same-name/62612900#62612900) posed at SO?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/vincentarelbundock/modelsummary/issues/99#issuecomment-651008973

-- 

Vincent Arel-Bundock

Professeur agrégé / Associate professor
http://arelbundock.com
Université de Montréal, Science politique
3150 rue Jean-Brillant, Pav. Lionel-Groulx, C-4020
Montréal, Québec, Canada, H3T 1N8
